### PR TITLE
HPCC-27686 Create Expiration Date in DFUInfoResponse

### PR DESCRIPTION
**Pull request by kunalaswani**
Expiration Date field added to Logical File Details.

Signed-off-by: Kunal Aswani <kunal.aswani@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by kunalaswani** [comment]
I have made code corrections to both the current and new Eclwatch for this field, Kevin had to manipulate dali to test, I believe these fixes are correct, but i will need to test once the dali fix is made.

**Review by GordonSmith — APPROVED** [review]

**Review by GordonSmith — CHANGES_REQUESTED** [review]
Minor formatting error and build failing as client struct does not match server response (I will look further tomorrow)

**Comment by jeclrsg** [comment]
@kunalaswani Looks like that build failure is happening because the ExpirationDate property isn't available in the 2.77 version of comms that's included in package.json (https://github.com/kunalaswani/HPCC-Platform/blob/HPCC-27686/esp/src/package.json#L46). You can fix that by updating that to the latest (2.78.2), run npm install, and then push the changes to package.json & package-lock.json

**Comment by ghalliday** [comment]
@GordonSmith what do you want to do with this PR?

**Comment by GordonSmith** [comment]
@ghalliday I rebased and retargeted so should be good to pull once it passes its tests.

**Review by GordonSmith — APPROVED** [review]

**Pull request merged**
