### PR TITLE
HPCC-27164 Add support for USE_BOOST_REGEX to vcpkg

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [x] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Review by richardkchapman — APPROVED** [review]
Looks reasonable

**Comment by richardkchapman** [comment]
Looks like there may need to be some corresponding changes in the (non-GH) smoketest. @AttilaVamos FYI. I suspect just a question of changing the parameters to cmake to use the vcpkg-based options

**Comment by GordonSmith** [comment]
@richardkchapman @AttilaVamos Depending on what broke and what caused it, this should not be pulled to 8.6.x.  If the only fix is to enable vcpkgs then this change should be pushed to master?

**Comment by AttilaVamos** [comment]
@GordonSmith In CentOS 7 the default Boost is old, therefor we (on-fly) download the boost_1_71_0.tar.gz and build it. If I see well, you PR removes the FindBOOST_REGEX.cmake. Is this means the build uses the default Boost?

**Comment by richardkchapman** [comment]
Requiring that we enable vcpkgs for Attila's smoketest would be acceptable in 8.6.x

**Comment by GordonSmith** [comment]
@AttilaVamos Its removed as the one shipped with cmake is generally better.

**Comment by AttilaVamos** [comment]
@GordonSmith I am trying to find out what really went wrong in the building.

**Comment by AttilaVamos** [comment]
@GordonSmith now there is a conflict with vcpkg. I think this PR should rebase.

**Comment by GordonSmith** [comment]
@AttilaVamos, I suspect `Boost_REGEX_LIBRARY` is empty?

**Comment by AttilaVamos** [comment]
@GordonSmith yes, I found that.
```
message(STATUS "BOOST_REGEX_INCLUDE_DIR: ${BOOST_REGEX_INCLUDE_DIR}")
message(STATUS "Boost_INCLUDE_DIRS: ${Boost_INCLUDE_DIRS}")

include_directories (
         ./../../rtl/include
         ./../../rtl/nbcd
         ./../../rtl/eclrtl
         ./../../system/include
         ./../../system/jlib
         ./../../roxie/roxiemem
         ./../../testing/unittests
         ${BOOST_REGEX_INCLUDE_DIR}
         ${Boost_INCLUDE_DIRS}
    )
```
and then in build:
```
-- BOOST_REGEX_INCLUDE_DIR: /home/vamosax/smoketest/PR-15756/build/downloads/boost_1_71_0
-- Boost_INCLUDE_DIRS:
```

**Review by AttilaVamos — CHANGES_REQUESTED** [review]
@GordonSmith did you fixed that Boost_REGEX_LIBRARY is empty problem?
There are two conflicting files:  vcpkg.json and vcpkgSetup.cmake, So, I think you should rebase this PR.

**Comment by GordonSmith** [comment]
@AttilaVamos rebased and fixed - I don't think the regression failure is my doing?

**Comment by AttilaVamos** [comment]
@GordonSmith no, it isn't.

**Review by AttilaVamos — APPROVED** [review]
It seems good.

**Pull request merged**
