### PR TITLE
HPCC-12210 Change confusing label

### PR DESCRIPTION
**Pull request by miguelvazq**
Change "Name Prefix" to "Target Scope"

Signed-off by: Miguel Vazquez miguel.vazquez@lexisnexis.com

### CODE REVIEW

**Comment by miguelvazq** [comment]
@wangkx Please review string changes.

**Comment by wangkx** [comment]
@miguelvazq back to you.

**Comment by miguelvazq** [comment]
Refer to comments made https://track.hpccsystems.com/browse/HPCC-12210

**Comment by richardkchapman** [comment]
@wangkx Please confirm you are happy for me to merge this

**Comment by wangkx** [comment]
@richardkchapman please merge this.

**Pull request merged**
