### PR TITLE
HPCC-27212 Update spark-hadoop 2.4.3 for log4j and chainsaw vulnerabilities

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [x] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Review by rpastrana — APPROVED** [review]
@Michael-Gardner looks correct to me:
https://github.com/hpcc-systems/spark-hadoop/compare/3ee6812b740a24ae6304c4754fdf69511dab693e...678f94157a1fbac17598005c497f9eea788422b1

target commit: https://github.com/hpcc-systems/spark-hadoop/commit/678f94157a1fbac17598005c497f9eea788422b1

**Comment by rpastrana** [comment]
@AttilaVamos this change shouldn't be affecting any yaml, any idea why helm chart tests might have failed?

**Comment by rpastrana** [comment]
@richardkchapman this PR is complete, currently trying to determine why seemingly unrelated tests are failing

**Comment by rpastrana** [comment]
@AttilaVamos failed checks seem to be environmental issues, can we get confirmation?

----------------------------------------------------------------------------------------------------------------------------------------
Check compiles on Win32 
 Visual Studio 16 2019
 -- Configuring incomplete, errors occurred!
 See also "D:/a/HPCC-Platform/HPCC-Platform/build/CMakeFiles/CMakeOutput.log".

   could not find any instance of Visual Studio.

 CMake Error:
   Generator

     Visual Studio 16 2019

   could not find any instance of Visual Studio.

----------------------------------------------------------------------------------------------------------------------------------------
  
Check helm chart lint 
  
 Run ./run.sh
 version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}
 Testing unmodified values file
 Unmodified failed
 Error: 1 chart(s) linted, 1 chart(s) failed
 ==> Linting /home/runner/work/HPCC-Platform/HPCC-Platform/testing/helm/../../helm/hpcc
 Error:  templates/eclagent.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: apps/v1
 Error:  templates/esp.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: apps/v1
 Error:  templates/esp.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: apps/v1
 Error:  templates/esp.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: apps/v1
 Error:  templates/esp.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: apps/v1
 Error:  templates/roxie.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: apps/v1
 
 ----------------------------------------------------------------------------------------------------------------------------------------

**Comment by richardkchapman** [comment]
Merged and done the null upmerge. Can @Michael-Gardner  or @rpastrana confirm that the submodule versions for 7.12.x and 8.0.x both look correct now

**Comment by rpastrana** [comment]
They both seem to contain the expected submodule as far as I can tell:
8.0.x:
https://github.com/hpcc-systems/spark-hadoop/tree/3ee6812b740a24ae6304c4754fdf69511dab693e (spark-3.1.1-hadoop-2.7 + chainsaw patch)

7.12.x
https://github.com/hpcc-systems/spark-hadoop/tree/678f94157a1fbac17598005c497f9eea788422b1 (2.4.3 Spark-Hadoop + chainsaw patch)

**Pull request merged**
