### PR TITLE
HPCC-29855 Add the storage secret category to eclccserver

### PR DESCRIPTION
**Pull request by afishbeck**
Normally eclccserver doesn't need storage secrets, but sometimes the user 'instructs the compiler to fetch the source file's metadata for its record layout' in which case eclccserver may need to access remote (dfs) storage.

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by afishbeck** [comment]
@ghalliday

**Review by ghalliday — CHANGES_REQUESTED** [review]
I would have expected a different secret category to be used to get at the meta data for a (remote) file than to access a file on a storage plane.  Really this is a secret used to access a remote system.  @jakesmith?  It may be too late to change, but using "storage" for dafilesrv makes sense, for dfsclient it doesn't.

At least needs further discussion before merging.

**Comment by afishbeck** [comment]
> I would have expected a different secret category to be used to get at the meta data for a (remote) file than to access a file on a storage plane. Really this is a secret used to access a remote system. @jakesmith? It may be too late to change, but using "storage" for dafilesrv makes sense, for dfsclient it doesn't.
> 
> At least needs further discussion before merging.

@jakesmith can you comment on Gavin's question.  Even if we did want to change where the category for remote storage secret, would it be done before this PR, or as an improvement later?

**Comment by jakesmith** [comment]
> I would have expected a different secret category to be used to get at the meta data for a (remote) file than to access a file on a storage plane. Really this is a secret used to access a remote system. @jakesmith? It may be too late to change, but using "storage" for dafilesrv makes sense, for dfsclient it doesn't.
> 
> At least needs further discussion before merging.

There are 2 uses of "storage" secrets at the moment afacs:
1) to connect to a remote dfs service (which may or may not be backed by dafilesrv - if so it will use a signed opaque blob to connect to the dafilesrv's)
2) for direct azurefile connections (azurefile.cpp / getSASToken)


So yes, they are both/all categories under "storage" secrets, but I'm not sure that is a particularly bad/confusing thing.
Other than perhaps, the pods that need secrets would potentially be exposed to both, where they *could* be separated if under different categories, but I suspect if can access local, then they also need to be potentially be able to access any remote storage too (and/or we may need finer grained control than just category for these secrets).

We categorize the remote type under a new "remotestorage" category, but we'd probably have to support the old scheme for backward compatibility for a while at least.

I'm not sure it's worth it, but I may missing the crux of the concern.

**Review by ghalliday — APPROVED** [review]
Since the storage secrets for planes are almost never used I will merge as-is, and revisit later if it seems to be a problem.

**Pull request merged**
