### PR TITLE
HPCC-10248 Show JobName on Summary Tab for WU Details

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes HPCC-10248

Signed-off-by: Gordon Smith gordon.smith@lexisnexis.com

### CODE REVIEW

**Comment by GordonSmith** [comment]
@miguelvazq Please Review
@lorraineachapman Please Review (See screenshot)
image

**Comment by miguelvazq** [comment]
Implementation works but, could use some visual improvement.

**Comment by GordonSmith** [comment]
Which is why I am asking @lorraineachapman  to take a look...  

@lorraineachapman alternatively I could add the job name to the tab tooltip?

**Comment by lorraineachapman** [comment]
I think I would prefer it as a tooltip on the WUID tab. I'm worried that putting it on the tab extends the available space on the window too much which might annoy users with smaller screens or those who don't want to use it full screen.

**Comment by GordonSmith** [comment]
Changes made as per Lorrainnes suggestion - @miguelvazq Please Review.

**Comment by miguelvazq** [comment]
Looks good.

**Pull request merged**
