### PR TITLE
HPCC-12102 Add Logging to dynamicesdl configuration

### PR DESCRIPTION
**Pull request by garonsky**
Signed-off-by: Gleb Aronsky gleb.aronsky@lexisnexis.com

### CODE REVIEW

**Comment by garonsky** [comment]
@wangkx please review

**Comment by richardkchapman** [comment]
Needs rebasing

**Comment by garonsky** [comment]
@wangkx Rebased,  please review.

**Comment by garonsky** [comment]
@richardkchapman this is ready to be merged

**Comment by richardkchapman** [comment]
Has @wangkx reviewed it?

**Comment by wangkx** [comment]
Looks good.

**Pull request merged**
