### PR TITLE
HPCC-15846 Change prerm dafilesrv conditional to allow for non-generic dafilesrv component names

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner michael.gardner@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@rwagner42 @xwang2713 Currently the prerm script only checks for mydafilesrv pid's.  The component name is hard coded into the script, but isn't necessarily equivalent to what is in the environment.  I've gone ahead and instead repleaced the file check with a status call to dafilesrv, and then a dafilesrv stop.  Ming please review when you have time.

**Comment by richardkchapman** [comment]
Should this be in 6.0.2 / 6.0.4 ?

**Comment by Michael-Gardner** [comment]
I was expecting it to be in 6.2.0,  But I can re-target if you think it's small enough to go into 6.0.2/4

**Comment by richardkchapman** [comment]
Feels small to me...

**Comment by Michael-Gardner** [comment]
closing to retarget

**Pull request closed without merging**
