### PR TITLE
HPCC-18617 Refactor Dali unit tests

### PR DESCRIPTION
**Pull request by jakesmith**
Seperate different areas into different categorgies.
All used to fall under 'stress' and as such were not run by
e.g. the smoke test runs
Fix various bugs/leaks and ensure they all pass.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by jakesmith** [comment]
The vast majority of the changes here are code movement.
There were a few bugs in some of the tests discovered though which have been fixed.

One of the things refactored (in to own test) are the 2 DFS retry tests. These deliberately cause a lock and a transaction to pause and retry.
That means these 2 tests could take up to 2 minutes together.
So @AttilaVamos - if there's a 20 second timeout on unittests, I would expect the "CDaliDFSRetryTests" test to fail in the set of tests in this PR, since it's dependent on a retry timeout in Dali which the test can't change.

I'm not 100% sure whether to remove it or leave it in because of this.
If 2 mins is 'ok' for unittests then it's worth keeping the test, but if not we'll have to remove it.

@ghalliday - please review

**Comment by AttilaVamos** [comment]
@jakesmith The Smoketest completion time increased with ~ 1 minute ( I gave 180 sec timeout in the first tuning iteration), so I think it would be good to keep your tests.

**Comment by jakesmith** [comment]
Unfortunately the time is not consistent, because the Dali DFS (server-side) transaction pausing takes a random amount of time, up to a minute.
I will be re-categorizing this test as a "Slow" test, and as discussed it along with the other unit tests that smoketest does not run, can be run by OBT.

**Comment by jakesmith** [comment]
Have moved the DFSRetry test to "Slow" (filtered unless unitttest --all is used)
Have also added a couple of extra tests to test HPCC-18626 and HPCC-18627.
NB: Until those are merged CDaliSDSTests will fail in testSDSSubs2

@ghalliday - please review

**Comment by jakesmith** [comment]
```
Have also added a couple of extra tests to test HPCC-18626 and HPCC-18627.
NB: Until those are merged CDaliSDSTests will fail in testSDSSubs2
```

Now rebased to master, for smoketest rerun, now that the above changes are merged.

**Pull request merged**
