### PR TITLE
HPCC-25459 Fix problems dealing with sasha: null

### PR DESCRIPTION
**Pull request by jakesmith**
Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
@richardkchapman - please review

**Comment by jakesmith** [comment]
@richardkchapman - the indexcachebug.ecl mismatch in Roxie, isn't related to changes in this PR.
but does it look like a genuine issue? Here is the diff. report:
```
21-03-05T10:15:36.2015162Z     Error:
2021-03-05T10:15:36.2015944Z      24. Test: indexcachebug.ecl
2021-03-05T10:15:36.2017525Z     '--- indexcachebug.xml
2021-03-05T10:15:36.2018436Z     +++ indexcachebug.xml
2021-03-05T10:15:36.2019415Z     @@ -19,14 +19,14 @@
2021-03-05T10:15:36.2020094Z      <Dataset name=Result 5>
2021-03-05T10:15:36.2020795Z      </Dataset>
2021-03-05T10:15:36.2021513Z      <Dataset name=Result 6>
2021-03-05T10:15:36.2022810Z     - <Row><fname>1              </fname><lname>4280804635     </lname><age>999</age></Row>
2021-03-05T10:15:36.2024283Z     - <Row><fname>10             </fname><lname>4248528966     </lname><age>990</age></Row>
2021-03-05T10:15:36.2025838Z     - <Row><fname>2              </fname><lname>3497243773     </lname><age>998</age></Row>
2021-03-05T10:15:36.2027941Z     - <Row><fname>3              </fname><lname>3720055187     </lname><age>997</age></Row>
2021-03-05T10:15:36.2031062Z     - <Row><fname>4              </fname><lname>1626808383     </lname><age>996</age></Row>
2021-03-05T10:15:36.2032522Z     - <Row><fname>5              </fname><lname>2551174723     </lname><age>995</age></Row>
2021-03-05T10:15:36.2033972Z     - <Row><fname>6              </fname><lname>1985572737     </lname><age>994</age></Row>
2021-03-05T10:15:36.2035432Z     - <Row><fname>7              </fname><lname>647687799      </lname><age>993</age></Row>
2021-03-05T10:15:36.2036867Z     - <Row><fname>8              </fname><lname>2548245530     </lname><age>992</age></Row>
2021-03-05T10:15:36.2038520Z     - <Row><fname>9              </fname><lname>704836619      </lname><age>991</age></Row>
2021-03-05T10:15:36.2039672Z     + <Row><fname>Aaron          </fname><lname>Jones          </lname><age>100</age></Row>
2021-03-05T10:15:36.2041065Z     + <Row><fname>Adam           </fname><lname>Smith          </lname><age>90</age></Row>
2021-03-05T10:15:36.2042258Z     + <Row><fname>Bob            </fname><lname>Brown          </lname><age>80</age></Row>
2021-03-05T10:15:36.2043431Z     + <Row><fname>Brian          </fname><lname>Brown          </lname><age>70</age></Row>
2021-03-05T10:15:36.2044664Z     + <Row><fname>Charles        </fname><lname>Dance          </lname><age>60</age></Row>
2021-03-05T10:15:36.2045957Z     + <Row><fname>Christopher    </fname><lname>Gould          </lname><age>50</age></Row>
2021-03-05T10:15:36.2047296Z     + <Row><fname>David          </fname><lname>Brokenshire    </lname><age>40</age></Row>
2021-03-05T10:15:36.2048557Z     + <Row><fname>Edward         </fname><lname>Green          </lname><age>30</age></Row>
2021-03-05T10:15:36.2049823Z     + <Row><fname>Egbert         </fname><lname>Sillyname      </lname><age>20</age></Row>
2021-03-05T10:15:36.2051090Z     + <Row><fname>Freddy         </fname><lname>Peters         </lname><age>10</age></Row>
2021-03-05T10:15:36.2052040Z      </Dataset>
```

**Comment by richardkchapman** [comment]
It's been seen before related to running tests in parallel that overwrite a file in question - but it was supposed to be fixed.

If for some reason the file is not getting re-resolved correctly, we would see this. I don't recall a change in that area but maybe...

**Comment by richardkchapman** [comment]
@jakesmith I suggest you create a Jira for the indexcache issue

**Comment by jakesmith** [comment]
>I suggest you create a Jira for the indexcache issue

For reference: https://track.hpccsystems.com/browse/HPCC-25474

**Comment by jakesmith** [comment]
@ghalliday - do you know why the win32 github action failed?

**Review by richardkchapman — APPROVED** [review]

**Pull request merged**
