### PR TITLE
HPCC-16927 Global sort timeout not causing job to abort

### PR DESCRIPTION
**Pull request by mckellyln**
@jakesmith can you think of a better way to tear down the job ?

Signed-off-by: Mark Kelly <mark.kelly@lexisnexisrisk.com>

### CODE REVIEW

**Comment by jakesmith** [comment]
@mckellyln - That looks sensible to me, if you've confirmed a pseudo timeout exception is caught, aborts the job and reports the timeout error to the workunit correctly.

**Comment by mckellyln** [comment]
Yes, I have confirmed:
0000037B 2017-02-02 11:43:40.247 31803 32255 "ERROR: tsorts1.cpp(505) : **MultiMerge.2 : throwing example exception: timeout expired"
causes a job abort / restart of Thor.
The original error was:
00000F7E 2017-01-20 10:26:32.583 28215 30198 "ERROR: -6: /jenkins/workspace/LN-Candidate-withplugins-5.6.8-1/LN/centos-6.0-x86_64/HPCC-Platform/thorlcr/msort/tsorts1.cpp(505) : **MultiMerge.2 : timeout expired
So I know its catching at the same place.

**Comment by mckellyln** [comment]
@richardkchapman this can merged - should we retarget to 6.2.8 ?

**Comment by richardkchapman** [comment]
Rebased and merged at #9562

**Pull request closed without merging**
