### PR TITLE
 HPCC-22093 Add DataPatterns to STD / ECL Watch

### PR DESCRIPTION
**Pull request by GordonSmith**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [x] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by GordonSmith** [comment]
@miguelvazq @jbrundage Please Review (Note: is dependent on https://github.com/hpcc-systems/HPCC-Platform/pull/12554 being pulled)

**Comment by GordonSmith** [comment]
Docs JIRA:  https://track.hpccsystems.com/browse/HPCC-22095

**Comment by dcamper** [comment]
PR appeared in my to-do box because I'm the last person cited.

@miguelvazq should be in your queue for review

**Review by miguelvazq — APPROVED** [review]

**Comment by GordonSmith** [comment]
@AttilaVamos the error does not appear to be part of this PR?

**Comment by AttilaVamos** [comment]
@GordonSmith I had been rerun your PR on my other Smoketest system and it generates same error as above. 
It seems your libcouchbase-cxx submodule is different than we have on master. 
Is your master the latest and your branch is rebased, and all submodules are updated? 
(Recently a couchbase related fix merged into the master and I think there is some change in the submodule as well)

**Comment by GordonSmith** [comment]
@AttilaVamos apologies I had wrong;y assumed it was a master conflict / merge issue.

**Comment by AttilaVamos** [comment]
@GordonSmith  No problem.

**Review by kunalaswani — APPROVED** [review]

**Comment by GordonSmith** [comment]
@richardkchapman can you comment on the failing roxie test?

**Comment by richardkchapman** [comment]
00001362 2019-06-11 08:32:11.939 20076  5824 "[W20190611-083059-5] RoxieMemMgr: Memory leak: 603 records remain linked in active heaplet list - rowMgr=0x515d530"
00001363 2019-06-11 08:32:11.939 20076  5824 "[W20190611-083059-5] Block size 32 at 0x7f95991400e8 was allocated by activity 2966 and not freed (1)"
00001364 2019-06-11 08:32:11.939 20076  5824 "[W20190611-083059-5] Block size 32 at 0x7f9599140108 was allocated by activity 3000 and not freed (1)"
00001365 2019-06-11 08:32:11.939 20076  5824 "[W20190611-083059-5] Block size 32 at 0x7f9599140128 was allocated by activity 3034 and not freed (1)"
00001366 2019-06-11 08:32:11.939 20076  5824 "[W20190611-083059-5] Block size 32 at 0x7f9599140148 was allocated by activity 3068 and not freed (1)"

**Comment by richardkchapman** [comment]
Tha activity mentioned in the first two leak reports is an all join ecllibrary/std/DataPatterns/Profile.ecl(1265,9)

**Comment by richardkchapman** [comment]
(is it supposed to be an ALL join, I wonder? @dcamper )

**Comment by dcamper** [comment]
@richardkchapman That shouldn't need to be a JOIN(,ALL) call.  It has only one equality test in the condition.  There is an ONWARNING(4531, IGNORE) workflow attached, however, to suppress a warning about a folded JOIN.  There is actually not a JOIN(,ALL) anywhere in the code.

**Comment by richardkchapman** [comment]
So can we explain why it ended up generating an all-join activity in this test case? Is it something that we should be concerned about? Why did the test get folded?

(this is only indirectly directly related to the smoketest failure, which I think is highlighting that an alljoin may leak a row... we should fix that either way)

**Comment by richardkchapman** [comment]
See https://track.hpccsystems.com/browse/HPCC-22314

**Comment by dcamper** [comment]
I think the folding is a product of how the function macro works.  The inputs for that particular JOIN are derived solely from the record definition when dataset contents do not need to be considered, and the record definition is constant for the call.  So for those particular inputs, it makes sense to constant-fold the JOIN.

Gavin may be able to chime in on why it would also be converted to an all join.  Perhaps that would be faster when the number of records in both LHS and RHS are small (which they are, here).

**Comment by ghalliday** [comment]
A typical occasion when an ALL join is generated is when the join condition is constant folded to true.  That may happen if the sources are both single rows.  Adding NOFOLD() around the input datasets will normally prevent it.

**Comment by richardkchapman** [comment]
@GordonSmith Needs rebasing for a clean merge

**Comment by richardkchapman** [comment]
I don't mind that it has been folded to an all-join if it's a valid optimization and does not indicate any flaw in the underlying ECL logic. It's just that I was finding it hard to see how both of those would be true in this case (but single row might do it, as Gavin says)

**Comment by GordonSmith** [comment]
@richardkchapman rebased.

**Comment by richardkchapman** [comment]
I think my fix for the row leak has been merged, so if you rebase once more you should get a clean xmoketest

**Comment by richardkchapman** [comment]
@dcamper One small concern that the selftests seem to be very slow - which may discourage people from running the selftest at all when developing std library functions. May be worth splitting someof the code into a separate regression suite file. But I am happy to leave that as a future exercise and merge this as is

**Comment by dcamper** [comment]
Agreed that the tests are slow on thor.  On my dev box (4 channel-based slaves) they run in 98s on thor but in only 10s on hthor.

**Pull request merged**
