### PR TITLE
HPCC-14812 Fix ROWDIFF with nested records

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@jamienoss please review.
(Note the parameter order in the definition didn't match the header - hence the problem.)

**Comment by jamienoss** [comment]
@richardkchapman the change looks good to me however:
@ghalliday This looks like a good candidate for haven given incorrect results? Have you looked to see that the trigegred assertion (or others) completely contain the possible scanarioes that would prevent this from being true? Would be a good idea to add a runtime test.

**Comment by ghalliday** [comment]
@richardkchapman shall I move the rowdiff test to the runtime regression suite?

**Comment by richardkchapman** [comment]
ok

**Comment by richardkchapman** [comment]
@ghalliday back to you for now

**Comment by ghalliday** [comment]
@richardkchapman runtime test added

**Pull request merged**
