### PR TITLE
HPCC-13318 Add -fsaveCpp as a synonym for -fsaveCppTempFiles

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman please review

**Comment by richardkchapman** [comment]
No updates to help text needed?

**Comment by richardkchapman** [comment]
@ghalliday Back to you...

**Comment by ghalliday** [comment]
@richardkchapman I'm not sure it needed it, but added.  I also made the format slightly more consistent (and ensured 2 spaces between the option and the description otherwise it was hard to read).

**Pull request merged**
