### PR TITLE
HPCC-28937 Fix invalid target path for temp files in external.ecl

### PR DESCRIPTION
**Pull request by jakesmith**
external.ecl was relying on a bug side-effect fixed by HPCC-28891. The test should not expect an invalid LFN to be returned by ExternalLogicalFileName (with a trailing '::').

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Review by AttilaVamos — APPROVED** [review]
It is OK. Tested manually in local BM/VM (where 'dropzonePath' was a stored variable with trailing '/').

**Comment by AttilaVamos** [comment]
@jakesmith  only one thing: the usual copyright, etc header is missing.

**Comment by jakesmith** [comment]
> @jakesmith only one thing: the usual copyright, etc header is missing.

not new, and there are quite a lot of other regression suite queries that also have the copyright messasge missing.
Please open and fix in a separate JIRA.

**Review by ghalliday — APPROVED** [review]

**Comment by ghalliday** [comment]
@jakesmith the change is fine, but the commit message doesn't make sense if it is included in a changelog by itself.

**Review by ghalliday — CHANGES_REQUESTED** [review]
Improve commit message

**Comment by jakesmith** [comment]
@ghalliday - updated commit title/PR message.

**Review by ghalliday — APPROVED** [review]

**Comment by ghalliday** [comment]
@jakesmith would this be better for 8.12. (or 9.0) rather than 8.10?  It could break code, and isn't solving a critical problem.  what do you think?

**Comment by jakesmith** [comment]
> @jakesmith would this be better for 8.12. (or 9.0) rather than 8.10? It could break code, and isn't solving a critical problem. what do you think?

it could do, but my thinking was, it's harmless and it (the bug) will cause any 8.10.x PR's to show a failure in smoketest, so it might as well go in an earlier candidate branch.
Shall I retarget?

**Pull request merged**
