### PR TITLE
HPCC-13558 Uninitialized StTimeSoapcall stat causing roxie assert

### PR DESCRIPTION
**Pull request by afishbeck**
Signed-off-by: Anthony Fishbeck anthony.fishbeck@lexisnexis.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
I think this would mean that every roxie activitt had a soapcallStart statistic - you really want a separate list just for the soapcall activity (like the keyed joins do here)

@ghalliday may remember how this works more than I do

**Comment by afishbeck** [comment]
Ok I think I see.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by afishbeck** [comment]
Updated to be soapStat specific, but rebasing to 5.2.4.

**Pull request closed without merging**
