### PR TITLE
HPCC-14949 ConfigMgr - Fix registered trademark symbol

### PR DESCRIPTION
**Pull request by garonsky**
Signed-off-by: Gleb Aronsky gleb.aronsky@lexisnexis.com

### CODE REVIEW

**Comment by garonsky** [comment]
@miguelvazq please review

**Comment by miguelvazq** [comment]
This instance looks good.

**Comment by garonsky** [comment]
@miguelvazq please review again

**Comment by miguelvazq** [comment]
Looks good.

**Comment by garonsky** [comment]
@richardkchapman this is ready to merge

**Pull request merged**
