### PR TITLE
HPCC-14294 Correctly transform expressions hoisted inside keyed limits

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@jamienoss Please review

**Comment by jamienoss** [comment]
@richardkchapman this looks good to merge but I think jiras need to be opened to handle the two new comments so that they don't get lost. If there are already ones open and relating then adding the issue number to the comments would be good. Perhaps they should be opened and then added to the comment before merging.

**Comment by ghalliday** [comment]
Added HPCC-14408, and added a comment to HPCC-9313.

**Comment by jamienoss** [comment]
I meant, perhaps, add the jira issue to the actual c++ comment. This way when someone stumbles across it next they can see that it has already been acknowledged.

**Comment by jamienoss** [comment]
...and note the function that these comments are within, in the jira issues so that they can be prompted to be removed when the issue is resolved.

**Pull request merged**
