### PR TITLE
HPCC-13225 Convert units of expire to seconds

### PR DESCRIPTION
**Pull request by jamienoss**
Signed-off-by: James Noss james.noss@lexisnexis.com

### CODE REVIEW

**Comment by jamienoss** [comment]
@richardkchapman please review.

**Comment by jamienoss** [comment]
@richardkchapman hold on this I will change to unsigned rather than unsigned4.

**Comment by jamienoss** [comment]
@richardkchapman  ok done and rebased.

**Comment by richardkchapman** [comment]
Looks ok to me, but I'd like @ghalliday to sanity check

**Pull request merged**
