### PR TITLE
HPCC-16935 Do not complain about missing main when syntax checking a module

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman  change is simple, but just possible I may have messed something up - e.g., I need to check that LN still builds.
@shamser please review.

**Comment by ghalliday** [comment]
See https://github.com/hpcc-systems/LN/pull/824 for change to private repo

**Comment by richardkchapman** [comment]
@shamser This is waiting for you I think

**Review by shamser — COMMENTED** [review]
@ghalliday Just one comment regarding making the error message more user friendly.  Everything else looks ok

**Comment by ghalliday** [comment]
@shamser please open a jira if you think it is worth changing
@richardkchapman I remember why this was originally 6.2.x - I think it may be a regression in a 6.2.x caused by https://github.com/hpcc-systems/HPCC-Platform/pull/9427.  Which should it target?

**Comment by richardkchapman** [comment]
If you can confirm that it is a regression, I suppose it should target 6.2.8 (though we should also learn from this that the change in 6.2.2 should not have been made in a point release).

**Comment by shamser** [comment]
@richardkchapman Code reviewed ok.

**Comment by ghalliday** [comment]
I can confirm that was no warning in 6.2.0 but there is in 6.2.2.  I will retarget to 6.2.8 since a regression.

**Pull request merged**
