### PR TITLE
advice

### PR DESCRIPTION
**Pull request by jakesmith**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
We could release this and experiment with it further, but from local experimentations on HDD and SDD is actually performs worse.
My local test is with a 4 slave Thor that is reading a 10GB file.
Between each run I flush the disk cache (echo 3 > /proc/sys/vm/drop_caches).
10 runs of each test.

The HDD tests are consistently ~15% *slower* with the POSIX_FADV_SEQUENTIAL advice.
The SDD test speed different with or without the flag is too small to be significant.

**Comment by jakesmith** [comment]
@richardkchapman @mckellyln - any thoughts?

**Comment by richardkchapman** [comment]
I did a quick web search to see if it shed any light on when use of sequential might make things slower, and found this:

https://stackoverflow.com/questions/3755765/what-posix-fadvise-args-for-sequential-file-write/3755850

which I thought was interesting though not directly related. In particular the bit about good write performance!

**Comment by jakesmith** [comment]
I looked at whether we already perhaps using POSIX_FADV_NOREUSE (we're not), thinking it would be a sensible thing to use for large Thor writes.
However, the manual says:
```
In kernels before 2.6.18, POSIX_FADV_NOREUSE had the same semantics as POSIX_FADV_WILLNEED. This was probably a bug;
**since kernel 2.6.18, this flag is a no-op.**
```

sync_file_range sounds interesting. I wonder though if the reason POSIX_FADV_SEQUENTIAL is worse, is because the OS does a better job of anticipating readahead with overlapping requests that the test involved.
i.e. might be best to let the smarts be done by the kernel.

It would be good to avoid filling the cache unnecessarily though, and/or prioritizing what stays in the disk cache.
O_DIRECT looks to be one way potentially.
Or we could use POSIX_FADV_DONTNEED more aggressively (e.g. after every block read).

**Comment by mckellyln** [comment]
I think we do use sync_file_range() now, after writes() if the IFEnocache is set.
I've mentioned O_DIRECT before, sometimes with that comes having to use block boundaries and sometimes it might mean rolling our own async read-ahead where it helps.

**Comment by mckellyln** [comment]
io_uring is a new method to look into.  Not sure how it works with NAS though.

**Comment by mckellyln** [comment]
On a single / spindle disk extra read-ahead might hurt; SSD or multi-disk raid might show a small gain.
Read-ahead algo can be tricky and should take into consideration hardware etc.
I doubt the POSIX_FADV_SEQUENTIAL code does that.

**Comment by mckellyln** [comment]
@jakesmith PR looks good - just not sure if it should be enabled.
Perhaps also we should by default set IFEnocache flag on Thor reads ?

**Comment by jakesmith** [comment]
Closing for now.

**Pull request closed without merging**
