### PR TITLE
HPCC-23124 Take DST into account in Std.Date functions DatesForWeek, AdjustCalendar, and DatesForMonth

### PR DESCRIPTION
**Pull request by dcamper**
In the full time structure, dates are forced to midnight for these functions.  Changes in DST (specifically when "falling back" an hour) between the beginning and ending dates could cause a computed date to be one off.

Signed-off-by: Dan S. Camper <dan.camper@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Manual testing, unit tests

### CODE REVIEW

**Comment by dcamper** [comment]
@richardkchapman Please assign for review.

**Comment by richardkchapman** [comment]
@ghalliday Please review

Nervous about a change like this in a point release

**Comment by ghalliday** [comment]
@dcamper I'm also hesitant, although most of the changes look like they make the functionality consistent.   It feels a bit strange to be using dst (or local time) at all.
Do you have test cases for examples which are affected?

**Comment by dcamper** [comment]
I am unsure how to test this meaningfully.  I can add specific date tests as outlined in the Jira, but that only proves out that we're managing tm_isdst correctly.  If you want me to add those, just let me know.

I did verify the original report.  When constructing the fix, I realized that the underlying problem was related to the before/after date computation where DST changed, which is why I inserted the same fix before all calls to mktime() where it did not already exist.  This was a logical deduction rather than the result of testing.  The DST fix was already present in most cases due to an earlier Jira.

Altering dates with mktime() is really just adding/subtracting seconds.  mktime() takes DST into account during the calculation of seconds if tm_isdst is not -1.  DST changes the date-oriented results we are looking for only when changing from tm_isdst=1 to tm_isdst=0 and the hour portion of a date is 0 or 1 (2am is DST changeover, and all of our date-only calculations set tm_hour=0).

If tm_isdst changes from 1 to 0 instead, the date calculations are unaffected.  The end date will technically have an hour of 1 but we ignore that.

DatesForWeek calls mktime() three times:

1. Initial "fix up" of the date, after tm has been zeroed and date components stuck into it.
1. After adjusting the date to the beginning of the week; this becomes startOfWeek
1. After adjusting the date to the end of the week; this becomes endOfWeek

Prior to the fix, here are some relevant values from tm after calling mktime (given 20191103):

1. tm_isdst = -1: mday = 3, hour = 0, isdst = 1
1. tm_isdst = 1: mday = 3, hour = 0, isdst = 1
1. tm_isdst = 1: mday = 8, hour = 23, isdst = 0

After the fix:

1. tm_isdst = -1: mday = 3, hour = 0, isdst = 1
1. tm_isdst = -1: mday = 3, hour = 0, isdst = 1
1. tm_isdst = -1: mday = 9, hour = 0, isdst = 0

Prior to the fix, here are some relevant values from tm after calling mktime (given 20191104):

1. tm_isdst = -1: mday = 4, hour = 0, isdst = 0
1. tm_isdst = 0: mday = 3, hour = 1, isdst = 1 // notice the hour
1. tm_isdst = 1: mday = 9, hour = 0, isdst = 0

After the fix:

1. tm_isdst = -1: mday = 4, hour = 0, isdst = 0
1. tm_isdst = -1: mday = 3, hour = 0, isdst = 1
1. tm_isdst = -1: mday = 9, hour = 0, isdst = 0

**Comment by dcamper** [comment]
Manual testing of AdjustCalendar and DatesForMonth -- given a date with DST active and looking for a date where DST is inactive -- showed the problem as well.  I added tests for all three functions.

I rebased from the current 7.6.x branch as well.

@ghalliday Please re-review.

**Comment by ghalliday** [comment]
@dcamper is there user pressure to merge this into 7.6 rather than 7.8?  Trying to decide which is most appropriate/needed.

**Comment by dcamper** [comment]
@ghalliday There has been no pressure for a fix.  It can probably be postponed to 7.8.0 if you feel that would be a better target.

**Comment by ghalliday** [comment]
Merging into 7.8.  If there is a demand for this to be backported it should be easy to do.

**Pull request merged**
