### PR TITLE
HPCC-16533 Include time waiting for failed reads in stats

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

### CODE REVIEW

**Comment by ghalliday** [comment]
@mckellyln please review

**Comment by mckellyln** [comment]
@ghalliday looks fine.

**Comment by ghalliday** [comment]
@richardkchapman please merge

**Comment by richardkchapman** [comment]
@ghalliday Needs rebasing for a clean merge

**Comment by ghalliday** [comment]
@richardkchapman rebased

**Pull request merged**
