### PR TITLE
HPCC-26895 ecl-queries support for secure remote source locations

### PR DESCRIPTION
**Pull request by afishbeck**
Add support to ecl-queries-copy and ecl-queries-copyset so that these
services can copy queries from remote locations that require TLS secure
connections.

Signed-off-by: Anthony Fishbeck <anthony.fishbeck@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [x] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [x] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by afishbeck** [comment]
@richardkchapman @ghalliday this wasn't a regression, but was exposed by the recent changes in TLS configuration for our environments.  These service methods internally lacked a way of calling remotely using TLS.

**Review by richardkchapman — APPROVED** [review]

**Review by ghalliday — APPROVED** [review]
@afishbeck only question is whether the option should be --no-source-ssl for consistency  (or --source-ssl- which would be consistent with most eclcc options)

**Review by wangkx — APPROVED** [review]
@afishbeck looks good.

**Comment by afishbeck** [comment]
@ghalliday 

I considered --no-source-ssl but ended up thinking it was trivially grammatically confusing. "no source"-ssl vs  source-"no ssl".  But I could change it.
As to "--source-ssl-" I errored on the side of verbosity.  But could change it to that, the negative option probably won't be used that often anyway.

**Pull request merged**
