### PR TITLE
HPCC-20495 Change testing ICU version from 58 to 59 for char16_t support

### PR DESCRIPTION
**Pull request by xwang2713**
Signed-off-by: Xiaoming Wang <xiaoming.wang@lexisnexi.com> 

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.

- [x] The change has been fully tested:
 
## Testing:
http://10.240.32.243/job/CE-Clienttools-OSX-JIRA-HPCC-20495/

### CODE REVIEW

**Comment by richardkchapman** [comment]
I assume you are making this change because you have icu version 58 installed on an OSX build box?

**Comment by richardkchapman** [comment]
Not really sure how (/if) ICU support works on OSX client builds - there is no standard install of the ICU libraries, so do we include the libraries with our client tools? If so, then we should probably include the latest ones that can be installed via brew (which seems to be version 69 at present)

**Comment by xwang2713** [comment]
Yes, my MacOS has icu 58 from MacPorts.  I also download and build ICU 60.  ICU 62 can be installed with HomeBrew.  ICU 60 can work without any change. ICU 58 works after my change. But ICU 62 doesn't.. It does not have UnicodeString class definition

**Comment by xwang2713** [comment]
Yes, we ship with ICU libraries in lib2/

**Comment by richardkchapman** [comment]
Perhaps simplest fix is to put ICU 60 onto the build machine then?

**Comment by xwang2713** [comment]
Yes, nothing need to change. I already manually install ICU 60 on our new MacOS

**Pull request closed without merging**
