### PR TITLE
HPCC-16590 UDP stats reporting config option

### PR DESCRIPTION
**Pull request by mckellyln**
Signed-off-by: Mark Kelly <mark.kelly@lexisnexis.com>

### CODE REVIEW

**Comment by mckellyln** [comment]
Previous PR for 6.2.0 was https://github.com/hpcc-systems/HPCC-Platform/pull/9390

**Comment by mckellyln** [comment]
@jakesmith PR updated to be for 6.0.10.

**Comment by mckellyln** [comment]
NOTE this goes along with https://github.com/hpcc-systems/LN/pull/820

**Comment by jakesmith** [comment]
@ghalliday - ready to merge.

**Pull request merged**
