### PR TITLE
HPCC-19639 Update WUDetails regression with schema changes

### PR DESCRIPTION
**Pull request by shamser**
Signed-off-by: Shamser Ahmed <shamser.ahmed@lexisnexis.co.uk>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by shamser** [comment]
@ghalliday Please can you review.

**Comment by shamser** [comment]
I renamed AllAttributes to AllProperties as per @GordonSmith request in https://track.hpccsystems.com/browse/HPCC-19314. @ghalliday @ghalliday

**Comment by GordonSmith** [comment]
@ghalliday I requested the change, but may not have appreciated your conventions.  I was suggesting it as the response contained "property" tags.

**Comment by ghalliday** [comment]
@GordonSmith I don't think that change was correct.  It has made the service names inconsistent with the layer underneath, and means other things need to be renamed to be consistent.  

Can you clarify whatyou mean by the response containing "property" tags?

**Comment by GordonSmith** [comment]
@ghalliday @shamser Ok I would suggest just reverting this change and closing my issue.

**Comment by shamser** [comment]
@ghalliday I've updated the regression with the recent AllAttributes and AllProperties schema changes.  The regression has also picked up changes relating to workflow and activities.

**Comment by ghalliday** [comment]
@shamser you need to update some of the test cases.  E.g.  sort_thor_testcase4.json:

**Comment by ghalliday** [comment]
E.g.
 'Scope': 'graph1'
Needs to now be 
 'Scope': 'wf1:graph1'

**Comment by shamser** [comment]
@ghalliday

**Pull request merged**
