### PR TITLE
HPCC-15214 DOCS:Update Method for Configuring htpasswd

### PR DESCRIPTION
**Pull request by g-pan**
FIX HPCC-15214 DOCS:Update Method for Configuring htpasswd
Update Installing and Running the HPCC Platform doc
to reflect the appropriate way to configure htpasswd security
using the Security Manager Framework.

Signed-off-by: G Panagiotatos greg.panagiotatos@lexisnexis.com
@JamesDeFabia please review
@RussWhitehead please review

### CODE REVIEW

**Comment by JamesDeFabia** [comment]
Looks good from my perspective, let @RussWhitehead have the final say.

**Comment by RussWhitehead** [comment]
I don't see how to comment on graphics, but SECM_002.jpg is old and needs to be refreshed

**Comment by richardkchapman** [comment]
Needs rebasing for a clean merge

**Comment by g-pan** [comment]
did that work?

**Comment by richardkchapman** [comment]
Yes. @RussWhitehead You happy now?

**Comment by RussWhitehead** [comment]
@richardkchapman  Happy now :+1: , go ahead and merge

**Pull request merged**
