### PR TITLE
HPCC-17623 Fix _spawnvp windows build break

### PR DESCRIPTION
**Pull request by afishbeck**
Signed-off-by: Anthony Fishbeck <anthony.fishbeck@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by afishbeck** [comment]
@xwang2713 please test this windows build fix.

**Comment by afishbeck** [comment]
@richardkchapman assuming this fixes the windows build issue, please review.

**Comment by xwang2713** [comment]
Looks good. I will re-test LN+Clienttools on Windows

**Comment by xwang2713** [comment]
Build (LN afishbeck:spawnWinBuildBreak + Clienttools afishbeck:spawnWinBuildBreak ) fails with error: 14:26:10   CMake Error at D:/jenkins2/workspace/LN-Clienttools-win-32bit-6.4.0/LN/Windows_2k8_Servers/build/plugins/saltlib/cmake_install.cmake:46 (file):
14:26:10     file INSTALL cannot find
14:26:10     "D:/jenkins2/workspace/LN-Clienttools-win-32bit-6.4.0/LN/Windows_2k8_Servers/build/bin/Release/saltlib.dll".

Also missing metaphone3.dll,  datalib.dll, etc.

Log: http://10.240.32.243/job/LN-Clienttools-win-32bit-6.4.0/LN=Windows_2k8_Servers/6/consoleFull

**Comment by afishbeck** [comment]
@xwang2713 not sure who can help with those issues.

**Comment by xwang2713** [comment]
Let me try Linux LN + Clienttools build. I will investiage it and maybe ask @Michael-Gardner for help.

**Comment by xwang2713** [comment]
Sorry, it is my setup. I  should call deven.com to build all LN solution. Use cmake build only compile oss. Rebuilding now

**Comment by xwang2713** [comment]
The build run OK. 
log: http://10.240.32.243/job/LN-Clienttools-win-32bit-6.4.0/LN=Windows_2k8_Servers/7/console
image: http://10.240.32.243/job/LN-Clienttools-win-32bit-6.4.0/LN=Windows_2k8_Servers/lastSuccessfulBuild/artifact/build/hpccsystems-clienttools-internal_6.3.0-trunk0Windows-i386.exe

**Pull request merged**
