### PR TITLE
HPCC-25335 Sasha config issue causing startup failures

### PR DESCRIPTION
**Pull request by jakesmith**
1) Missing newline in yaml before vaults: causing config load error
and unhandled exception
2) Missing inDaliPod flag missing from services generated inside
Dali pod, used to toggle timing of sentinel creation, required
so to avoid dependency deadlock on dali/service needing each other
to be ready

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
NB: the changes to saserver.cpp are purely to move some of the init code (the loadConfiguration in particular) into the try/catch block, so it logs any unhandled exception in this area in the future

**Comment by stuartort** [comment]
I was able to start the system using the changes to _helpers.tpl and dali.yaml

**Comment by jakesmith** [comment]
The smoketest roxie regression failure is a bit of a mystery..
From the regression suite logging:
```
2021-02-10T17:43:24.7344085Z [Action] 184. Test: dfse2.ecl
...
2021-02-10T17:55:24.8685189Z [Failure] 184. Create Stack Trace for roxie (pid:9699) into '/home/runner/work/HPCC-Platform/HPCC-Platform/regress/log/W20210210-174325-roxie.trace'
2021-02-10T17:55:25.0037973Z [Failure] 184. Timeout occured for dfse2.ecl and no more attempt left. Force to abort... 
2021-02-10T17:55:25.1332628Z [Pass] 184. Pass dfse2.ecl - W20210210-174325 (720 sec)
2021-02-10T17:55:25.1333817Z [Pass] 184. Intentionally fails
2021-02-10T17:55:25.1334975Z [Pass] 184. URL http://127.0.0.1:8010/?Widget=WUDetailsWidget&Wuid=W20210210-174325
```

from eclccserver:
```
0000022E PRG 2021-02-10 17:43:25.024  9130 10515 "Compile request processing for workunit W20210210-174325"
..
0000022F USR 2021-02-10 17:43:25.028  9130 10515 "/home/runner/work/HPCC-Platform/HPCC-Platform/install/opt/HPCCSystems/bin/eclcc: Creating PIPE program process : '/home/runner/work/HPCC-Platform/HPCC-Platform/install/opt/HPCCSystems/bin/eclcc -shared - --timings --xml --nostdinc --metacache= --logfile=W20210210-174325.eclcc.log -dfs=10.1.0.4:7070 -scope=regress -cluster=roxie -wuid=W20210210-174325 -token=HPCC[u=,w=W20210210-174325]; -fmaxCompileThreads=2 -fpassDFSToEclcc=1 -oW20210210-174325 -platform=roxie --component=myeclccserver@10.1.0.4 -fcreated_for=regress -fallowvariableroxiefilenames=1 -fcreated_by=ws_workunits -ffailonleaks=1 -Dhpccbasedir='/home/runner/work/HPCC-Platform/HPCC-Platform/install/opt/HPCCSystems/' -fpickbestengine=false' - hasinput=1, hasoutput=0 stderrbufsize=0"
```

There's no evidence it ran on roxie though (nothing in logs).

Testing this manually locally the expected roxie logging would be e.g.:
```
000001C6 USR 2021-02-10 22:32:55.877 29823 29857 "roxie: Dequeued workunit request 'W20210210-223255'"
000001C7 PRG 2021-02-10 22:32:55.888 29823 30699 "Loading dll (libW20210210-223255.so) from location /home/jsmith/hpcc2Debug/var/lib/HPCCSystems/queries/myroxie/libW20210210-223255.so"
000001C8 PRG 2021-02-10 22:32:55.897 29823 30699 "[W20210210-223255:W20210210-223255@2] makeWrappedException - Could not resolve filename regress::single::DG_INDEX (in Index Read 2)"
000001C9 PRG 2021-02-10 22:32:55.897 29823 30699 "[W20210210-223255:W20210210-223255] Exception thrown in query - cleaning up: 1410: Could not resolve filename regress::single::DG_INDEX (in Index Read 2)"
000001CA PRG 2021-02-10 22:32:55.901 29823 30699 "[W20210210-223255:W20210210-223255] Done cleaning up"
000001CB OPR 2021-02-10 22:32:55.902 29823 30699 "[W20210210-223255] ERROR: 1410: Could not resolve filename regress::single::DG_INDEX (in Index Read 2) (in item 1)"
000001CC PRG 2021-02-10 22:32:55.905 29823 30699 "ERROR: 1410 - Could not resolve filename regress::single::DG_INDEX (in Index Read 2)"
000001CD PRG 2021-02-10 22:32:55.917 29823 30699 "[W20210210-223255] FAILED: W20210210-223255"
000001CE PRG 2021-02-10 22:32:55.917 29823 30699 "[W20210210-223255] EXCEPTION: Could not resolve filename regress::single::DG_INDEX (in Index Read 2)"
000001CF PRG 2021-02-10 22:32:55.917 29823 30700 "[W20210210-223255] Unload received for channel 1"
```

Normally stacks from roxie would be captured, but gdb was missing, although given there's no logging in roxie, it doesn't look like the query reached roxie.

It looks like it never got to esp, the 1st mention of the wuid is:
```
00001948 USR 2021-02-10 17:55:24.987  9493 30065 "Abort W20210210-174325"
00001949 USR 2021-02-10 17:55:24.989  9493 30065 "Abort W20210210-174325 done"
..
0000194D PRG 2021-02-10 17:55:24.995  9493 30066 "SOAP method <WUQuery> from regress@127.0.0.1."
0000194E PRG 2021-02-10 17:55:24.995  9493 30066 "Client version: 1.81"
0000194F USR 2021-02-10 17:55:24.999  9493 30066 "getWUInfo: W20210210-174325"
...
00001958 USR 2021-02-10 17:55:25.135  9493 24015 "WUDeploy generates: W20210210-174325"
00001959 USR 2021-02-10 17:55:25.135  9493 24015 "jsocket(7,2029) write err = 32 : A!:8010 -> 127.0.0.1:52016 (22)"
0000195A PRG 2021-02-10 17:55:25.135  9493 24015 "ERROR: In CHttpMessage::send(852) -- Exception(-4, connection is broken
Target: A!:8010 -> 127.0.0.1:52016 (22), Raised in: jsocket.cpp, line 2040) writing to socket(-1)."
0000195B PRG 2021-02-10 17:55:25.135  9493 24015 "TxSummary[activeReqs=2;auth=NA;contLen=20401;rcv=1ms;handleHttp=720130ms;user=regress@127.0.0.1;req=SOAP wsworkunits.WUDeployWorkunit v1.81;total=720130ms;]"
```

There should have been a "WUDeploy generates: W20210210-174325" @ approx. 17:43:24.

So it looks like there was a problem between - regression suite run -> ecl -> esp ..

How can we spot the culprit if this reoccurs?
I think we need to capture the state of the ecl process (assuming it was running) and esp possibly.

**Comment by richardkchapman** [comment]
That test is supposed to fail at compile time I think, having discovered that the requested field translation is not legal.

**Review by richardkchapman — APPROVED** [review]

**Comment by jakesmith** [comment]
It was either stuck in esp, or eclccserver, or dali:

eclccserver compile logging (which looks normal):
```
0000022E PRG 2021-02-10 17:43:25.024  9130 10515 "Compile request processing for workunit W20210210-174325"
0000022F USR 2021-02-10 17:43:25.028  9130 10515 "/home/runner/work/HPCC-Platform/HPCC-Platform/install/opt/HPCCSystems/bin/eclcc: Creating PIPE program process : '/home/runner/work/HPCC-Platform/HPCC-Platform/install/opt/HPCCSystems/bin/eclcc -shared - --timings --xml --nostdinc --metacache= --logfile=W20210210-174325.eclcc.log -dfs=10.1.0.4:7070 -scope=regress -cluster=roxie -wuid=W20210210-174325 -token=HPCC[u=,w=W20210210-174325]; -fmaxCompileThreads=2 -fpassDFSToEclcc=1 -oW20210210-174325 -platform=roxie --component=myeclccserver@10.1.0.4 -fcreated_for=regress -fallowvariableroxiefilenames=1 -fcreated_by=ws_workunits -ffailonleaks=1 -Dhpccbasedir='/home/runner/work/HPCC-Platform/HPCC-Platform/install/opt/HPCCSystems/' -fpickbestengine=false' - hasinput=1, hasoutput=0 stderrbufsize=0"
```

esp side:
```
0000126A PRG 2021-02-10 17:43:25.006  9493 24015 "HTTP First Line: POST /WsWorkunits?upload_ HTTP/1.1"
0000126B PRG 2021-02-10 17:43:25.007  9493 24015 "POST /WsWorkunits, from regress@127.0.0.1"
0000126C PRG 2021-02-10 17:43:25.007  9493 24015 "SOAP method <WUDeployWorkunit> from regress@127.0.0.1."
0000126D PRG 2021-02-10 17:43:25.007  9493 24015 "Client version: 1.81"
....
00001958 USR 2021-02-10 17:55:25.135  9493 24015 "WUDeploy generates: W20210210-174325"
00001959 USR 2021-02-10 17:55:25.135  9493 24015 "jsocket(7,2029) write err = 32 : A!:8010 -> 127.0.0.1:52016 (22)"
```

So esp received request, submitted workunit for compile. But then was waiting for the workunit until timeout, it was likely blocked here:
```
    WsWuHelpers::submitWsWorkunit(context, wuid.str(), req.getCluster(), nullptr, 0, 0, true, false, false, nullptr, nullptr, &req.getDebugValues(), nullptr);
    waitForWorkUnitToCompile(wuid.str(), req.getWait());
```

**Pull request merged**
