### PR TITLE
HPCC-24273 Improve speed of WUListQueries.

### PR DESCRIPTION
**Pull request by jakesmith**
The cost of validating whether a query was active, by scanning
Alias' for a match when there were 1000's of queries, was very
expensive.
Build a unordered_set 1st then use that to validate if queries
are active.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
Local testing with an environment with ~9000 deployed queries, this speeds up the scan from approx 30 seconds, to ~ 1.1 second.

@ghalliday - please review.

**Comment by richardkchapman** [comment]
Should this target 7.8.x ?

**Comment by ghalliday** [comment]
@jakesmith code looks good.  I think it could even be considered for 7.6.x given the impact v complexity.

**Comment by jakesmith** [comment]
could do, didn't target a point build because it's an old issue and there are other pending related issues that may not make it before 7.10, and the environment where this was seen may want to wait until then (which is not too far off).

OTH - this issue will slowdown at least Eclwatch in all environments where there's a decent number of deployed queries when using WUListQueries .. I don't know how comment it is to call from SOAPCALL ..

@richardkchapman - shall I target 7.6.x ?

**Comment by richardkchapman** [comment]
@jakesmith Yes

**Comment by jakesmith** [comment]
@ghalliday @richardkchapman - rebased to 7.6.x

**Pull request merged**
