### PR TITLE
HPCC-15739 Fix issue with IXmlWriterExt saving state for possible rewind

### PR DESCRIPTION
**Pull request by afishbeck**
Signed-off-by: Anthony Fishbeck anthony.fishbeck@lexisnexis.com

### CODE REVIEW

**Comment by afishbeck** [comment]
@richardkchapman @rpastrana This is an alternative solution for https://github.com/hpcc-systems/HPCC-Platform/pull/8786.

**Comment by afishbeck** [comment]
@gaojx not sure if you are tracking these changes this is my alternative for fixing the DynamicESDL invalid xml issue.

**Comment by rpastrana** [comment]
@afishbeck closed my old PR for this. Should we wait for me to review next week, or have it reviewed now by someone else?

**Comment by afishbeck** [comment]
@rpastrana Not sure.  I think the JV guys are doing their own builds.  I'm not sure if they currently have your previous fix or not.

@gaojx ?

**Comment by gaojx** [comment]
We took Rodrigo's fix and did a build so they can bypass the error. We need this to get to next build.

**Comment by richardkchapman** [comment]
@gaojx If you can confirm that you have reviewed and approved this pull request I will merge it...

**Comment by gaojx** [comment]
Code reviewed. Looks good.

**Comment by afishbeck** [comment]
@richardkchapman

**Pull request merged**
