### PR TITLE
HPCC-15985 Fix uninitialised variable in NSplitterSlaveActivity::getMetaInfo

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@mckellyln please review
Could this also be the root cause of HPCC-15945?
I will look at creating a similar fix for 5.6.6 once this is accepted.

**Comment by ghalliday** [comment]
jira: https://track.hpccsystems.com/browse/HPCC-15985

**Comment by ghalliday** [comment]
See also 5.6.6 fix in https://github.com/hpcc-systems/HPCC-Platform/pull/8962

**Comment by mckellyln** [comment]
Looks good.  Not sure of the fastThrough setting to true, but cannot disagree.

**Pull request merged**
