### PR TITLE
HPCC-21402 Populate BackEndRequest LogStructure using DESDL

### PR DESCRIPTION
**Pull request by roscoche**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [X] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [X] My code follows the code style of this project.
  - [X] My code does not create any new warnings from compiler, build system, or lint.
- [X] The commit message is properly formatted and free of typos.
  - [X] The commit message title makes sense in a changelog, by itself.
  - [X] The commit is signed.
- [] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [X] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [X] All new and existing tests passed.
  - [X] I have checked that this change does not introduce memory leaks.
  - [X] I have used Valgrind or similar tools to check for potential issues.
- [X] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [X] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

I've used the newly implemented log structure, according to this PR: https://github.com/hpcc-systems/HPCC-Platform/pull/12124. With that, I deployed an ESP instance and tested DESDL logging.

### CODE REVIEW

**Comment by richardkchapman** [comment]
@wangkx Is this dependent on another PR?

**Comment by wangkx** [comment]
Yes, this PR will not work without PR: https://github.com/hpcc-systems/HPCC-Platform/pull/12124. @afishbeck  please review.

**Comment by roscoche** [comment]
> Yes, this PR will not work without PR: #12124. @afishbeck please review.

@wangkx I've reviewed your PR, can you check that please?

**Review by afishbeck — APPROVED** [review]
@richardkchapman looks fine.

**Comment by richardkchapman** [comment]
I get a compile error:

/Users/rchapman/git/HPCC-Platform/esp/services/esdl_svc_engine/esdl_binding.cpp:704:16: error: no member named 'setBackEndReq' in 'IEspLogEntry'; did you mean 'setBackEndResp'?
        entry->setBackEndReq(rawreq);
               ^~~~~~~~~~~~~
               setBackEndResp
/Users/rchapman/git/HPCC-Platform/esp/logging/loggingmanager/loggingmanager.h:37:18: note: 'setBackEndResp' declared here
    virtual void setBackEndResp(const char* ptr) = 0;
                 ^
1 error generated.

@wangkx @afishbeck @roscoche

**Comment by wangkx** [comment]
@richardkchapman could the compile still use the old esp/logging/loggingmanager/loggingmanager.h? In the new loggingmanager.h (https://github.com/hpcc-systems/HPCC-Platform/blob/candidate-7.0.x/esp/logging/loggingmanager/loggingmanager.h), the setBackEndResp is in line 38.

**Comment by wangkx** [comment]
I just cherry-pick this PR on the top of the latest candidate-7.0.x. It is built OK.

**Comment by richardkchapman** [comment]
Ok, looks like I forgot the rebase - false alarm, sorry.

**Comment by roscoche** [comment]
@afishbeck @richardkchapman @wangkx Can you review my comment on this PR?(https://github.com/hpcc-systems/HPCC-Platform/pull/12124) It seems it was merged with an error.

**Comment by wangkx** [comment]
@roscoche Your code has been merged into hpcc-systems:candidate-7.0.x. I just built it without any problem. What kind of merge error do you have? When does it happen?

**Comment by roscoche** [comment]
@wangkx 

> @roscoche Your code has been merged into hpcc-systems:candidate-7.0.x. I just built it without any problem. What kind of merge error do you have? When does it happen?

The problem is in your PR, but it's not a compiling error, it's a runtime error. If you check your loggingagentbase.hpp there's a duplicate enum value for BackEndReq and BackEndResp. This will cause to have two BackEndReq's on the LoggingRequest.

**Comment by wangkx** [comment]
I will fix it in https://track.hpccsystems.com/browse/HPCC-21489.

**Pull request merged**
