### PR TITLE
HPCC-15769 Remove Deprecated features from Feature Permission List

### PR DESCRIPTION
**Pull request by RussWhitehead**
Remove references to unused SMC feature permissions
  FileDkcAccess Access to dkcing of key files
  ExecuteAccess Access to remote execution
  ConfigAccess Access to super computer environment

Signed-off-by: Russ Whitehead william.whitehead@lexisnexis.com

### CODE REVIEW

**Comment by RussWhitehead** [comment]
@wangkx Please review

**Comment by wangkx** [comment]
@RussWhitehead looks fine. You may need to change the environment.xml.in inside LN repo.

**Review by wangkx — APPROVED** [review]
@RussWhitehead looks fine.

**Comment by RussWhitehead** [comment]
@richardkchapman Please merge and close

**Pull request merged**
