### PR TITLE
HPCC-23297 Expose DFU "nocommon" option to esp/dfuplus

### PR DESCRIPTION
**Pull request by jakesmith**
Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Tested locally and on tested manually setting noCommon in a DFU workunit and resubmitting on the 160x.

### CODE REVIEW

**Comment by jakesmith** [comment]
@AttilaVamos - please review

**Comment by jakesmith** [comment]
NB: repushed because hadn't updated dfuplus CLI usage.

**Review by AttilaVamos — APPROVED** [review]
@jakesmith looks good.

**Comment by AttilaVamos** [comment]
@jakesmith Is it possible to test this change and or its effect in Regression Suite  (ECL) ?

**Comment by jakesmith** [comment]
>Is it possible to test this change and or its effect in Regression Suite (ECL) ?

@AttilaVamos - it could, but only if the environment that the regression suite runs on has multiple thor clusters of varying sizes.

**Comment by mckellyln** [comment]
I have thought before the regression suite could/should have multiple thors configured and running.

**Comment by jakesmith** [comment]
related, but not for this reason, I have suggested before that there should be N Thor's so the regression suite on Thor runs faster (quite possibly N times faster). i.e. if there were 4 thors, 4 queries would always be running parallel and since their all lightweight there isn't really any resource concerns.

**Comment by jakesmith** [comment]
NB: I've updated to Testing: section to reflect I have tested this both locally and on the 160x.

**Comment by jakesmith** [comment]
@ghalliday @richardkchapman - can we get this merged and into tomorrows 7.6 RC ?

**Pull request merged**
