### PR TITLE
HPCC-14323 Bad type definition on processPerSlave

### PR DESCRIPTION
**Pull request by jakesmith**
Signed-off-by: Jake Smith jake.smith@lexisnexis.com

### CODE REVIEW

**Comment by jakesmith** [comment]
@richardkchapman - please merge.

**Comment by mckellyln** [comment]
If the default for processPerSlave is true (and it is from above) then in several other places in the code:
./thorlcr/master/thmastermain.cpp:        bool processPerSlave = globals->getPropBool("@processPerSlave");
./thorlcr/slave/thslavemain.cpp:        bool processPerSlave = globals->getPropBool("@processPerSlave");
./thorlcr/slave/slavmain.cpp:        processPerSlave = globals->getPropBool("@processPerSlave");
./thorlcr/graph/thgraphmaster.cpp:        bool processPerSlave = globals->getPropBool("@processPerSlave");
should default to true as well so that for existing configs where the environment.xml exists and is not created processPerSlave is set to true.

**Comment by mckellyln** [comment]
processPerSlave="true"
Should also be added to another file:
testing/regress/environment.xml.in

**Comment by richardkchapman** [comment]
@jakesmith Back to you

**Comment by richardkchapman** [comment]
Also the commit message does not reference the Jira number in the title - please fix.

**Comment by jakesmith** [comment]
@mckellyln @richardkchapman - corrected default in code for processPerSlave and corrected commit message.

Will open a separate PR for LN change to environment.xml.in

**Comment by mckellyln** [comment]
Looks good.

**Comment by jakesmith** [comment]
I'll correct, squash and repush

**Comment by jakesmith** [comment]
@mckellyln @richardkchapman - corrected default on a getPropInt @slavesPerNode + added processPerSlave="true" default to testing/regress/environment.xml.in

**Comment by mckellyln** [comment]
Looks good to merge.

**Pull request merged**
