### PR TITLE
HPCC-17024 Spot scalar cses within inline table activities

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [x] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately

## Testing:
Run full regression suite.
Examples that show significant improvement are ups2, vlad12good, roxieassert

### CODE REVIEW

**Comment by ghalliday** [comment]
@shamser please review

**Comment by ghalliday** [comment]
Richard note this causes problems when upmerged to master, so upmerge it once it has been merged.

**Review by shamser — COMMENTED** [review]
@ghalliday You've checked "I have added tests to cover my changes."  There's no new test program in this PR.. does an existing PR testing this?

**Comment by ghalliday** [comment]
@shamser I don't see a check mark beside that.  I checked all new tests passed.

**Comment by shamser** [comment]
@richardkchapman Code reviewed ok.

**Pull request merged**
