### PR TITLE
HPCC-15664 Add gzip header to http/soapcall test result key files

### PR DESCRIPTION
**Pull request by wangkx**
Signed-off-by: wangkx kevin.wang@lexisnexis.com

### CODE REVIEW

**Comment by wangkx** [comment]
@afishbeck please review.

**Comment by afishbeck** [comment]
@wangkx looks good.

**Comment by wangkx** [comment]
@richardkchapman this PR is ready to be merged.

**Comment by richardkchapman** [comment]
@wangkx  Should this be targetting 6.0.2? Or was the gzip stuff added in 6.2?

**Comment by wangkx** [comment]
@richardkchapman the gzip stuff was added in 6.2 (not in 6.0.2).

**Pull request merged**
