### PR TITLE
HPCC-15316 Added permissions to file installation of libuv

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner Michael.Gardner@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 Please review

**Comment by xwang2713** [comment]
Looks good

**Comment by richardkchapman** [comment]
Do we need similar for the apple branch?

**Comment by Michael-Gardner** [comment]
I don't think we've ever had an issue with the apple branch in regards to .so permissions.  The reason this is an issue is because the package manager (yum) doesn't deem the .so as 'provided' unless it's executable, which means that it then will go out and try to get the package which provides libuv from the repo's it knows about.

**Pull request merged**
