### PR TITLE
HPCC-16124 GPG Signing changes

### PR DESCRIPTION
**Pull request by Michael-Gardner**
- GPG Signing on by default
- Check for ability to sign if SIGN_MODULES=ON
- Add public key to ecl/regress for developers to use in testing

Signed-off-by: Michael Gardner michael.gardner@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 These are the signing changes.  Biggest change is the fact that we default SIGN_MODULES to ON, and we have a check that will cause a build to fail if you don't have keys loaded into your gpg keychain.

@AttilaVamos This might cause issues with your smoketests and regression builds if you don't have keys on your test systems to sign the standard library.

@shamser a copy of the public key is under ecl/regress so that people running the regression suite have access to it.

I'm testing on OSX.  I've gone ahead and asked Ming to test on Windows for clienttools builds.

**Comment by xwang2713** [comment]
So for community user we should tell them to set SIGN_MODULES=OFF in cmake configuration right?

**Comment by Michael-Gardner** [comment]
Yes we should.  I'll add it to the build hpcc wiki page.

**Comment by Michael-Gardner** [comment]
We also shouldn't need it if we're doing a PLUGINS build.  I'll go ahead and modify the PR source to reflect that.

**Comment by richardkchapman** [comment]
I think that we should default SIGN_MODULES off in the code, but always set it to ON for the packages we build and ship...

**Comment by Michael-Gardner** [comment]
ok.  Ming you'll have to set SIGN_MODULES=ON to the cmake calls.  I'll go ahead and switch it around in the PR and modify the wiki page.

**Comment by xwang2713** [comment]
OK. I will set it on for our build

**Comment by Michael-Gardner** [comment]
Tested fine on OSX.

**Comment by Michael-Gardner** [comment]
@richardkchapman Ming gave me the heads up this morning that the keys are in place and the builds for 6.0.6 will have the standard ecllibrary signed.

**Comment by richardkchapman** [comment]
Looks ok to me, but I'd like @xwang2713 to review/sign-off before I merge

**Comment by xwang2713** [comment]
Looks good

**Pull request merged**
