### PR TITLE
HPCC-16018 Implement blocked heap allocators

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@mckellyln please review.  Based on another PR which needs merging first.

**Comment by ghalliday** [comment]
As an idea of the performance benefits trying running the following performance suite tests:

./ecl-test query --suiteDir ~/dev/ecl-bundles/PerformanceTesting/ "12ac*" -t=thor -fheapFlags=0

and

./ecl-test query --suiteDir ~/dev/ecl-bundles/PerformanceTesting/ "12ac*" -t=thor -fheapFlags=192

Some tests are 3x faster!

**Comment by mckellyln** [comment]
Awesome.  Will review today.

**Comment by ghalliday** [comment]
@mckellyln rebased.

**Pull request merged**
