### PR TITLE
HPCC-31696 Open ECL from docs into ECL Playground

### PR DESCRIPTION
**Pull request by GordonSmith**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [x] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by GordonSmith** [comment]
@g-pan @JamesDeFabia - Currently we swap out the ECL text with the ECL Editor control based on this selection:  
`"pre.programlisting:not([lang]),pre.programlisting[lang='ecl']"`

I have added a button to open the ECL in the ECL Playground - but I think we said this should only be enabled for "some" of the ECL samples?  So those samples need to be marked with another attribute so that I can optionally add the button as needed.

Note:  This is a very quick implementation for now.

**Comment by JamesDeFabia** [comment]
@GordonSmith  
We have already implemented an attribute for that purpose. 
We use the **lang** attribute to identify the language (ECL, CPP,  bash, etc.) the **role="runnable"** indicates it will run as is on play.hpccsysems.com. 
(IOW, no other attribute or file is needed). 
Example:
<programlisting lang="ECL" role="runnable">

**Comment by GordonSmith** [comment]
@JamesDeFabia can you point me to one of the files that has `role` set and I can use it for testing - thx.

**Comment by JamesDeFabia** [comment]
@GordonSmith Here are a few.
In the HPCC-Platform/docs/EN_US/ECLLanguageReference/ECLR_mods folder:
BltInFunc-AVE.xml
BltInFunc-ASIN.xml
Recrd-DICTIONARY.xml

**Review by jeclrsg — APPROVED** [review]

**Pull request merged**
