### PR TITLE
HPCC-15668 XSLT disable automatic encoding

### PR DESCRIPTION
**Pull request by rpastrana**
All xsl:text tags now contain disable-output-escaping="yes" attribute

Signed-off-by: rpastrana rodrigo.pastrana@lexisnexis.com

### CODE REVIEW

**Comment by rpastrana** [comment]
@wangkx please review.

**Comment by rpastrana** [comment]
@garonsky please review.

**Comment by garonsky** [comment]
Looks good.

**Comment by rpastrana** [comment]
@richardkchapman please merge.

**Pull request merged**
