### PR TITLE
HPCC-31864 Report error on re-entrant use of CBlockedFileIO

### PR DESCRIPTION
**Pull request by ghalliday**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [x] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
@jakesmith This is a bit tricky to reproduce.  I triggered it with this test by disabling the index cache (set to 0 size).  I also added a Sleep(100) before setting active to false, but that may not be needed.

**Comment by AttilaVamos** [comment]
@ghalliday there are 2 new warning when pullindex2.ecl executed:
```
    661. Test: pullindex2.ecl ( version: multiPart=true )
    '--- pullindex2.xml
    +++ pullindex2.xml
    @@ -1,3 +1,5 @@
    +<Warning><Code>4523</Code><Filename>pullindex2.ecl</Filename><Line>36</Line><Source>eclcc</Source><Message>Neither LIMIT() nor CHOOSEN() supplied for index read on  ~regress::multi::searchIndex</Message></Warning>
    +<Warning><Code>4523</Code><Filename>pullindex2.ecl</Filename><Line>36</Line><Source>eclcc</Source><Message>Neither LIMIT() nor CHOOSEN() supplied for index read on </Message></Warning>
     <Dataset name=Result 1>
      <Row><Result_1>true</Result_1></Row>
     </Dataset>
    '
    662. Test: pullindex2.ecl ( version: multiPart=false )
    '--- pullindex2.xml
    +++ pullindex2.xml
    @@ -1,3 +1,5 @@
    +<Warning><Code>4523</Code><Filename>pullindex2.ecl</Filename><Line>36</Line><Source>eclcc</Source><Message>Neither LIMIT() nor CHOOSEN() supplied for index read on  ~regress::single::searchIndex</Message></Warning>
    +<Warning><Code>4523</Code><Filename>pullindex2.ecl</Filename><Line>36</Line><Source>eclcc</Source><Message>Neither LIMIT() nor CHOOSEN() supplied for index read on </Message></Warning>
     <Dataset name=Result 1>
      <Row><Result_1>true</Result_1></Row>
     </Dataset>
    '
```
Are those related to this change?

**Review by jakesmith — APPROVED** [review]
@ghalliday - looks good, but the regression test won't expose it at the moment, as not run in k8s (so no default block size) , correct?

**Comment by ghalliday** [comment]
Note this needs to clear the flag if there is an exception

**Comment by ghalliday** [comment]
@jakesmith I have repushed and squashed to add a try block to reset the flag.
Interestingly I tried using COnScopeExit, and the generated code was much worse.  It is as if the code was not being inlined.  It may be worth investigating some more.

**Review by jakesmith — APPROVED** [review]
@ghalliday - looks good.

**Comment by jakesmith** [comment]
> @jakesmith I have repushed and squashed to add a try block to reset the flag. Interestingly I tried using COnScopeExit, and the generated code was much worse. It is as if the code was not being inlined. It may be worth investigating some more.

yes, I think I or we have seen how it's not great, and shouldn't be used in code that is expected to be hit frequently.

**Comment by ghalliday** [comment]
> Are those related to this change?

Yes, I will push a fix.

**Pull request merged**
