### PR TITLE
HPCC-8175 DOCS:Update ldap 

### PR DESCRIPTION
**Pull request by g-pan**
FIX HPCC-8175 DOCS:update the ldap documentation
Update the steps in in the documentation for 
setting up LDAP security through configuration manager.

@JamesDeFabia please review

### CODE REVIEW

**Comment by JamesDeFabia** [comment]
Looks good to merge

**Comment by richardkchapman** [comment]
Should this be targetting 5.2?

**Comment by g-pan** [comment]
This also applies to the 5.0.x. Therefore can be in 5.2 as well as earlier.

**Comment by richardkchapman** [comment]
Can you issue the pull request against candidate-5.2

**Comment by g-pan** [comment]
Closing. Will Rebase and reissue.

**Pull request closed without merging**
