### PR TITLE
HPCC-22002 Catch invalid DFU file type

### PR DESCRIPTION
**Pull request by jakesmith**
throw an exception if unknown dfu file type passed to
doCreateDFUFile. NB: was causing compile warning:
'serviceType' may be used uninitialized

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
@richardkchapman - please check/merge.

**Comment by richardkchapman** [comment]
@jakesmith Any reason not to target 72.x?

**Comment by jakesmith** [comment]
@richardkchapman - I've retargeted this to 7.2.x

**Comment by jakesmith** [comment]
@AttilaVamos - the 'Build log' doesn't seem to show the contents of the build log..
can you see what the issue is?

**Comment by AttilaVamos** [comment]
@jakesmith If I see well, your previous commit has a conflicting file: 'version.cmake'. 
If there is any conflicting file then there is no build. Smoketest add a short comment: 'Conflicting files, should skip build and test.'. It is unnecessary to Smoketest reports the files because GitHub already shows the conflicting file list.

**Comment by jakesmith** [comment]
>If I see well, your previous commit has a conflicting file: 'version.cmake'.

Where? I don't see it. I only see "wsdfuaccess.cpp" under Files changed.
@AttilaVamos

**Comment by AttilaVamos** [comment]
@jakesmith Here:
	git pull -ff --no-edit upstream pull/12480/head:u'hpcc-22002'-smoketest
		returncode: None
		stdout: Auto-merging version.cmake
		CONFLICT (content): Merge conflict in version.cmake
		Auto-merging thorlcr/slave/thslavemain.cpp
		Automatic merge failed; fix conflicts and then commit the result.
		stderr: From github.com:hpcc-systems/HPCC-Platform
		 * [new ref]         refs/pull/12480/head -> uhpcc-22002-smoketest

**Comment by jakesmith** [comment]
that's not the state now afaics, I think that must have betweeen here:
>@jakesmith jakesmith force-pushed the jakesmith:hpcc-22002  branch from d046641 to f761c6d an hour ago
> @jakesmith jakesmith changed the base branch from master  to candidate-7.2.x  an hour ago

In between would have been a few seconds when the branch was rebased onto 7.2.x (only wsdfuaccess.cpp file changed), but the PR was still targeting master.
A few seconds later, the PR base target was also changed to candidate-7.2.x.

I think the smoketest must have started running in the few secs. between those 2 events, leading to the conflict.

It says there are no conflicts now, and it hasn't been repushed since then.

**Comment by jakesmith** [comment]
@richardkchapman - please merge

**Pull request merged**
