### PR TITLE
HPCC-24632 Use archive before shared mysql client lib, if found

### PR DESCRIPTION
**Pull request by mckellyln**
Signed-off-by: Mark Kelly <mark.kelly@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [x] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by mckellyln** [comment]
Note: see https://github.com/xwang2713/cloud-image-build/pull/5
This PR should be merged before that one.

**Comment by mckellyln** [comment]
Some distros would link in the archive version of libmysqlclient.a and some linked in the shared lib.
In order to use a newer version of this lib and not have to include the package - as it may not be available from default reposiitories at HPCC installation time - we specify to look for the archive verison of the lib before the shared version.
Should we only look for the archive version ?

**Comment by mckellyln** [comment]
The reason for wanting a newer client lib version is to be able to use some newer options that are in the embed library, such as MYSQL_OPT_MAX_ALLOWED_PACKET.
@xwang2713 @richardkchapman for review/comment.

**Comment by xwang2713** [comment]
I will update cloud-image-build repo not only  CentOS 7 but also  Amazon 2 which is similar to CentOS 7 when this PR is merged. CentOS 8 should be OK since it has mysql-devel package which is MySQL 8.0

**Comment by mckellyln** [comment]
Thanks.
@richardkchapman your thoughts ?

**Comment by richardkchapman** [comment]
Is this change appropriate for a point release?

**Comment by mckellyln** [comment]
Good point, but then it would mean only in 7.12 and not available for current users.
But MySQL 8 is released, and this previous 5.7.30 is not the latest.
I will re-target.

**Comment by mckellyln** [comment]
We can delay the other repo (build) PR so that the mysql client version does not change until that is merged.
This PR ensures when/if the mysql client lib version changes (and no longer has a _r archive) the archive version is still used (if present) so that a newer mysql client package is not an install dependency.
But I do feel like the build repo should me more closely tied to platform releases, if that is possible.

**Comment by mckellyln** [comment]
I suppose we should not change these things in a point release, so I will also re-target.

**Comment by mckellyln** [comment]
rebased to master

**Comment by mckellyln** [comment]
Since the build PR (https://github.com/xwang2713/cloud-image-build/pull/5) is not hpcc version based I'm not sure any of this matters as we cannot use one version of the mysql client for 7.6 and a different one for 7.12 on the same el7 build platform.

**Pull request closed without merging**
