### PR TITLE
HPCC-20455 Make ws_config2 and ws_sql build without openssl

### PR DESCRIPTION
**Pull request by jakesmith**
Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by jakesmith** [comment]
@xwang2713 - please check

**Comment by xwang2713** [comment]
Test build fails :
collect2: error: ld returned 1 exit status
08:45:34 tools/dumpkey/CMakeFiles/dumpkey.dir/build.make:106: recipe for target 'Release/bin/dumpkey' failed
08:45:34 make[2]: *** [Release/bin/dumpkey] Error 1

**Comment by jakesmith** [comment]
@xwang2713 - retagging myself - otherwise I don't see it on my PR list 

@jakesmith

**Comment by jakesmith** [comment]
I've checked this and it compiles, but it requires USE_OPENSSL=Off _and_ USE_ZLIB=Off
At the time this was opened I opened a separate JIRA to address ZLIB issues (See HPCC-20456)

@xwang2713 - please confirm you can build with USE_OPENSSL=Off and USE_ZLIB=Off

**Comment by xwang2713** [comment]
Yes, I miss USE_ZLIB=OFF.  With it the build run successfully

**Comment by jakesmith** [comment]
@richardkchapman - please merge. The USE_OPENSSL=Off + USE_ZLIB=On issues are to be addressed by HPCC-20456.

**Pull request merged**
