### PR TITLE
HPCC-31504 Improve how ParquetWriter creates columns from ECL rows

### PR DESCRIPTION
**Pull request by jackdelv**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [x] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jackdelv** [comment]
After rebasing to 9.4.x it has conflicts with defines solved by JIRA HPCC-31301.

**Comment by ghalliday** [comment]
I'm waiting for @dcamper to do a first review.  Let me know if you would find it valuable for me to take a look first.

**Comment by jackdelv** [comment]
@ghalliday If you could take a look that would be great. Thank you!

**Review by dcamper — APPROVED** [review]
Nice to see RapidJSON removed!

**Review by ghalliday — APPROVED** [review]
I've scanned the changes and they look like a good improvement - anything that deletes 300 lines has got to be good!  I didn't spot any problems.

**Comment by ghalliday** [comment]
@jackdelv can you change this to a normal PR rather than a draft, and I will merge?  Draft normally means it isn't considered ready for merging, and it has been opened for initial discussion review.  Otherwise please open as non-draft.

**Comment by jackdelv** [comment]
@ghalliday Changed to normal PR. Thank you!

**Review by ghalliday — CHANGES_REQUESTED** [review]
@jackdelv this is not currently building on some of the systems.  
A short-term fix is to add
#undef BOOL
after the #includes

A better fix, which seems to work, is to delete the definition from platform.h (line 364).

**Comment by jackdelv** [comment]
@ghalliday Doesn't this PR, https://github.com/hpcc-systems/HPCC-Platform/pull/18310, already fix this, or is it easier to include the fix in this one?

**Pull request merged**
