### PR TITLE
HPCC-32771 Fix variable expansion in curl JSON object

### PR DESCRIPTION
**Pull request by xwang2713**
Expand variables in a string then pass it to curl JSON object:
 data="{\"ref\":\"main\", \"inputs\": { \"hpccVersion\":\"$hpcc_version\",\"hpccSrcBranch\":\"$community_tag\" }}"
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GAHT_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/xwang2713/github-action-hpcc-terraform/actions/workflows/$WF_YAML_FILE/dispatches \
          -d "${data}"

Assigned by xiaoming.wang@lexisnexisrisk.com

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

https://github.com/xwang2713/github-action-hpcc-terraform/actions/runs/11181690814
https://github.com/xwang2713/github-action-hpcc-terraform/actions/runs/11181693285

### CODE REVIEW

**Review by Michael-Gardner — APPROVED** [review]
Looks good. Ming was able to test this manually on his system to make sure it worked. The previous version wasn't passing the hpccVersion and hpccSrcBranch correctly. It was kicking off the bvt without targeting the correct branch.

**Review by ghalliday — CHANGES_REQUESTED** [review]
The commit message/title of the bug does not reference a jira ticket.

**Comment by xwang2713** [comment]
JIRA https://hpccsystems.atlassian.net/browse/HPCC-32771

**Comment by xwang2713** [comment]
Also updated committed message to include "HPCC-32771"

**Comment by xwang2713** [comment]
How can I reopen it? I doesn't mean to close it. But the "Reopen and commend" is grayout

**Comment by xwang2713** [comment]
Update the commit message. Reopen it

**Pull request closed without merging**
