### PR TITLE
HPCC-24548 Allow optional command at end of K8s job

### PR DESCRIPTION
**Pull request by jakesmith**
Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
Very similar to @xwang2713 's branch, which I only noticed after the fact.
This feature allows an arbitrary command to execute at the end of our ephemeral jobs.
Either when the main job's process ends, or when K8s detects the container is not ready and generated a PreStop event before terminating.

It might be useful for post-mortem collections reasons etc., but the main intention is to use it to signal sidecars to terminate, e.g. service sidecar containers from a service mech like Istio.

This is done by setting global.misc.postJobCommand.
E.g. for Istio, set to "curl -sf -XPOST http://127.0.0.1:15020/quitquitquit"
This will then execute at end of job container process, in this case causing the Istio sidecar to quit and therefore the pod to complete. Without it, the hpcc container is done, but the Istio runs indefinitely and the pod remains in a "NotReady" state indefinitely.

Tested under DD and AKS.

Eventually, K8s will implement something that will make this unnecessary, see: https://github.com/kubernetes/enhancements/issues/753 
However, those plans are 2 years old, and the KEP has was closed (Oct last year). It does not look likely a K8s solution will be available soon.

In the meantime, this offers a workaround to the injected sidecar termination problem.

@xwang2713 @richardkchapman - please review

**Comment by xwang2713** [comment]
Code looks good. 
Is it possible to move following to _helpers.tps as a function for better maintenance:
{{- if $postJobCommand }}
            lifecycle:
              preStop:
                exec:
                  command:
                  - >-
                      {{ $misc.postJobCommand }}
{{- end }}
            command: ["/bin/bash"]
            args:
            - -c
            - >-
                {{ $appCmd }}
{{- if $postJobCommand -}} ;
                {{ $misc.postJobCommand }}
{{- end }}

**Comment by jakesmith** [comment]
> Code looks good.
> Is it possible to move following to _helpers.tps as a function for easy maintenance:

I thought about it, but it would wrap several directives into one hidden place, and I think make it less clear what command: vs args: vs lifecycle would be when looking at each component yaml.
Think will leave as is for now.

**Comment by jakesmith** [comment]
@richardkchapman - please also review, thanks.

**Comment by xwang2713** [comment]
Looks good.

**Review by xwang2713 — APPROVED** [review]
Looks good

**Review by richardkchapman — APPROVED** [review]

**Pull request merged**
