### PR TITLE
HPCC-15043 Spurious teardown of slave connections err = 107

### PR DESCRIPTION
**Pull request by mckellyln**
Signed-off-by: Mark Kelly <mark.kelly@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately

### CODE REVIEW

**Comment by mckellyln** [comment]
@jakesmith please review.
I would like to test this on Boca dev after review / discussion

**Comment by AttilaVamos** [comment]
I don't think that wutoolTest(Cassandra) timeout is related to this change. I saw it in other PR as well. It seems sometime the Cassandra needs a bit more time to finish. I will check it on other PR again, probably doing some timeout tuning in unit tests environment and reschedule this.

**Comment by mckellyln** [comment]
I also added SOCK_CLOEXEC flag to socket() calls to ensure any exec[ve]() and close of dup'ed sockets would not cause epoll triggers.

**Comment by AttilaVamos** [comment]
@mckellyln Don't worry about the last smoketest result. It seems that was my fault and this PR re-scheduled.

**Comment by mckellyln** [comment]
This helped with finding errno msg ETIMEDOUT.  Closing for further investigation.

**Pull request closed without merging**
