### PR TITLE
HPCC-18772 Replace configurator with XSLT in docs build

### PR DESCRIPTION
**Pull request by xwang2713**
configurator was used to generate xml from xsd for docs build.
For better maintenance saxon with XSLT 2.0 script is used to replace configurator.
Other changes: move XML delcaration to the top in xsd files.

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:
Docs build: http://10.240.32.243/job/CE-Candidate-docs-xsd2xml-with-xslt/
Platform build: http://10.240.32.243/view/custom/job/CE-Candidate-JIRA-18772/

@Michael-Gardner please help review.

### CODE REVIEW

**Review by g-pan — APPROVED** [review]
Reviewed output resulting from build with these changes included. Output built as expected. however @Michael-Gardner should have final say.

**Comment by xwang2713** [comment]
@Michael-Gardner can you review the CMake configuration part? This PR is required for other docs build tickets such as multiple languages support, etc. Thanks

**Comment by Michael-Gardner** [comment]
Cmake sections look good.

**Comment by xwang2713** [comment]
@richardkchapman I rebased the PR with latest master. This PR is ready for merge.

**Comment by AttilaVamos** [comment]
This serializetypes error is not related to your PR. It comes from the master branch.

**Pull request merged**
