### PR TITLE
HPCC-12786 Ip address from scripts to match ifconfig

### PR DESCRIPTION
**Pull request by mckellyln**
@garonsky, @AttilaVamos please review minor changes to scripts.

I found get_ip_address did not always return what should be the default/correct interface, especially
when it was specified as '*' in the conf file.
util.py did not always work correctly on an IB cluster when Ethernet word is not present.

Signed-off-by: Mark Kelly mark.kelly@lexisnexis.com

### CODE REVIEW

**Comment by AttilaVamos** [comment]
The changes in Regression Engine util.py are fine for me. 
(A curious question: Which context/environment cause the ifconfig fail?)

**Comment by richardkchapman** [comment]
@garonsky Please review

**Comment by garonsky** [comment]
I do not believe that get_ip_address.sh.in is being used.  This appears deprecated.

**Comment by mckellyln** [comment]
Should we remove this file ?

**Comment by garonsky** [comment]
I can't see anything that uses it, so I would say it is safe to remove.  Be sure to remove any CMake references to it as well.

**Comment by mckellyln** [comment]
Updated PR to remove file and reference to it in other files.  Linked to issue 12798 which will remove auto-discovery option on Configmgr.

**Comment by richardkchapman** [comment]
I did a quick search of the sources to try to confirm that get_ip_address.sh was unused, and I discovered that there ARE references to a script file get_ip_address_wiz.sh (in configmgr.conf.in) that would appear to be used for a similar purpose, and yet there is no such file that I can see. I'm wondering if there is a typo here (and that we should remove the _wiz from config.conf.in and restore the get_ip_address.sh and the associated fixes)

**Comment by mckellyln** [comment]
This is related to 12798 - since the auto-discovery is being removed this script (or the _wiz reference) should no longer be needed.  After updating this I brought up this same issue and it was discussed and decided that all references to it and similar should be removed.

**Comment by mckellyln** [comment]
@AttilaVamos on a system with InfiniBand there may be no Ethernet NIC configured, so greping for Ethernet does not work and also ifconfig spits out a warning we should ignore.

**Comment by AttilaVamos** [comment]
@mckellyln Thanks Mark. Meanwhile I faced this warning in the new build and test system.

**Pull request merged**
