### PR TITLE
HPCC-15982 Default ws_ecl service name to 'ws_ecl'

### PR DESCRIPTION
**Pull request by wangkx**
Signed-off-by: wangkx kevin.wang@lexisnexis.com

### CODE REVIEW

**Comment by wangkx** [comment]
@GordonSmith @garonsky please review.

**Comment by garonsky** [comment]
Looks good.

**Comment by GordonSmith** [comment]
@wangkx Are these soft or hard values (can the user edit them later)?  Does this fix:  https://track.hpccsystems.com/browse/HPCC-15982 or does just fix it for the default?

**Comment by wangkx** [comment]
@GordonSmith this just fixes the default. A user can edit it using ConfigMgr.

**Comment by ghalliday** [comment]
@wangkx this needs to target 6.0.4.  6.0.x is only for documentation changes.

**Comment by ghalliday** [comment]
jira: https://track.hpccsystems.com/browse/HPCC-15982

**Comment by wangkx** [comment]
Ok, I will change it to 6.0.4. @GordonSmith do you need me to add the BuiltSet (see my comment on https://track.hpccsystems.com/browse/HPCC-15982)?

**Pull request closed without merging**
