### PR TITLE
HPCC-21471 Fix issues with swapnode and thor restart

### PR DESCRIPTION
**Pull request by jakesmith**
1) Groups with swapped nodes were rejected as mismatching
by Dali or by daliadmin requesting a group.
Consequently, following a swapnode, effected Thor's failed
to start.
Fix by noting swapnode activity and accepting groups that
mismatch environment that have previously been swapped.

2) Init scripts did not cope with restarting following a swapped
node, because the scripts treated a failure to contact an old
slave IP as fatal and quit Thor.
Fix by warning and retrying when Thor recycles (previous behaviour)

3) Swapnode validates nodes by writing a temporary file to the
thor slave and spare nodes. If that node had never been used
before, the data directory would not exist and the attempt to
create the tempoary file within it failed.
Fix by ensuring data directory exists before writing temp. file.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by jakesmith** [comment]
@cloLN - please test.

**Comment by cloLN** [comment]
basic test looks good.  However, pre-swap, it looks like the spare is listed as a slave on ECLWatch even though the xml shows otherwise.

**Comment by jakesmith** [comment]
@cloLN - you could you open a JIRA re. the eclwatch issues - which can be dealt with separately I think.

**Comment by jakesmith** [comment]
@Michael-Gardner - could you look over the changes please? Thanks.

**Comment by Michael-Gardner** [comment]
@jakesmith Looks good.  Tested startup/shutdown and looked at preflight output in eclwatch > cluster_processes

**Pull request merged**
