### PR TITLE
HPCC-24395 Add verbose option to ecl-test so that it logs what commands it's running

### PR DESCRIPTION
**Pull request by AttilaVamos**
Enable '--createEclRunArg' in Regression Test Engine for setup, run and query mode.

If it is enabled then the result log will be somethig similar to this
(each test log block has an extra '[Action] <nnn.> Cmd: ecl run ...' line ):

  [Action] Suite: hthor (setup)
  [Action] Queries: 11
  [Action]   1. Test: roxie_echo.ecl
  [Action]   1. Cmd: ecl run -fpickBestEngine=false --target=hthor --cluster=hthor --port=8010 --exception-level=warning --noroot --name="roxie_echo" -ffailOnLeaks -fdisableLocalOptimizations  -XdestClusterName=myhthor -XdropzonePath=/var/lib/HPCCSystems/mydropzone/ -XespFileSprayUrl=http://192.168.1.56:8010/FileSpray -XespIp=192.168.1.56 -XOriginalTextFilesIp=192.168.1.56 -XdropzoneIp=192.168.1.56 -XOriginalTextFilesEclPath=opt::^H^P^C^C^Systems::testing::regress::download -XOriginalTextFilesOsPath=/opt/HPCCSystems/testing/regress --server=192.168.1.56 --username=avamos --password=Tragya2018#Osz --port=8010  /home/ati/MyPython/RegressionSuite/ecl/setup/roxie_echo.ecl
  [Pass]   1. Pass roxie_echo.ecl - W20200713-163234 (2 sec)
  [Pass]   1. URL http://192.168.1.56:8010/?Widget=WUDetailsWidget&Wuid=W20200713-163234
  ...

Tested manually

Signed-off-by: AttilaVamos <attila.vamos@gmail.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by AttilaVamos** [comment]
@ghalliday Please check and merge.

**Comment by ghalliday** [comment]
@jakesmith please check this is what you were looking for

**Comment by jakesmith** [comment]
@AttilaVamos looks good, but check boxes need filling in.

**Comment by AttilaVamos** [comment]
@ghalliday Check boxes are filled, please merge.

**Pull request merged**
