### PR TITLE
HPCC-21508 Revise DESDL documentation

### PR DESCRIPTION
**Pull request by g-pan**
Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

@mayx please review  
Compiled PDF available http://10.240.32.243/view/Docs%207.0/job/DocDev70-1/38/CE=ubuntu-14.04-amd64-1/artifact/build-docs/Release/docs/EN_US/DynamicESDL_EN_US-7.2.0-closedown0.pdf 
to review changes in context
@JamesDeFabia please review
@rpastrana optionally review

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Successful Build tests http://10.240.32.243/view/Docs%207.0/job/DocDev70-1/

### CODE REVIEW

**Review by JamesDeFabia — CHANGES_REQUESTED** [review]
Comments inline

**Comment by mayx** [comment]
On the pdf, 

page 30, 
example
esdl unbind-service myesp myesp.8003.MathService
Should be:
esdl unbind-service myesp.8003.MathService

Page 31
example 
esdl bind-method myEsp myespbinding mySvc mySvc.1 myMthd1 --config myMethods.xml
Should be:
esdl bind-method myesp.8003.MathService AddThis --config myMethods.xml

**Comment by g-pan** [comment]
Revised and Rebased. New PDF available on http://10.240.32.243/job/DocDev70-1/CE=ubuntu-14.04-amd64-1/41/artifact/build-docs/Release/docs/EN_US/DynamicESDL_EN_US-7.2.0-closedown0.pdf
@mayx please review, also double check the example (esdl bind-service) on page 26 I think that is probably changed now as well. @JamesDeFabia please review as well.

**Review by mayx — APPROVED** [review]
@g-pan looks good.

**Comment by richardkchapman** [comment]
@AttilaVamos Are the smoketest reports genuine?

**Comment by AttilaVamos** [comment]
@richardkchapman yes, it seems an another on-fly download problem. Rescheduled.

**Comment by richardkchapman** [comment]
@JamesDeFabia Are you happy with this noe?

**Comment by JamesDeFabia** [comment]
@richardkchapman This is good to merge

**Pull request merged**
