### PR TITLE
HPCC-19804 Add public key alongside certificates

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.net>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@RussWhitehead Please take a look and test this out.  The private and public keys are located next to the certificate under /home/hpcc/certificate/

**Comment by RussWhitehead** [comment]
@Michael-Gardner Looks good  but you need to add a commit message

**Comment by Michael-Gardner** [comment]
@richardkchapman Ready for merge.

**Comment by RussWhitehead** [comment]
@Michael-Gardner @richardkchapman Not quite ready for merge. The private key file has to be RSA, as is the public key file. The first line
-----BEGIN ENCRYPTED PRIVATE KEY-----
should read
-----BEGIN RSA PRIVATE KEY-----

**Comment by xwang2713** [comment]
"-----BEGIN ENCRYPTED PRIVATE KEY-----" is "PKCS#8 encrypted private key".  "-----BEGIN RSA PRIVATE KEY-----" is  "PKCS#5 encrypted private key". It is from how we generate private key with openssl command

**Comment by richardkchapman** [comment]
@RussWhitehead @Michael-Gardner Please confirm if this needs additional changes

**Comment by RussWhitehead** [comment]
@richardkchapman  This is not ready to be merged yet

**Comment by richardkchapman** [comment]
@Michael-Gardner Then I guess this is back with you

**Comment by Michael-Gardner** [comment]
@RussWhitehead I modified it so that we use ssh-keygen to generate the rsa key first (has the header you want) and then use that key to generate the self signed cert.

Please check this out when you get a chance.

**Comment by RussWhitehead** [comment]
@Michael-Gardner Looks good

**Comment by Michael-Gardner** [comment]
@richardkchapman Ready for merge

**Pull request merged**
