### PR TITLE
HPCC-30208 Resolve KQL join issue

### PR DESCRIPTION
**Pull request by rpastrana**
- Uses alternate table join syntax
- Removes join on innerunique directive

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by rpastrana** [comment]
image

**Comment by rpastrana** [comment]
image

**Comment by rpastrana** [comment]
image

**Review by jakesmith — APPROVED** [review]
@rpastrana - looks ok, but it would benefit from a description of what was happening before the fix, how it fixed exactly 
Could you add some text to the JIRA and to the PR commit message ?

**Comment by rpastrana** [comment]
> @rpastrana - looks ok, but it would benefit from a description of what was happening before the fix, how it fixed exactly Could you add some text to the JIRA and to the PR commit message ?

@jakesmith thanks for the feedback - I thought I provided ample details (certainly more than I see in many PRs), but nonetheless I added a statement in the JIRA and will add one in PR as well referencing the contents of the screenshot provided.

**Comment by rpastrana** [comment]
Per visual inspection, it appears KQL join type=innerunique is causing projected column duplication.

Even though current join implementation is syntactically correct, it appears to cause unexpected join operation.

Per MS documentation, alternate join syntax should be utilized:
https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-log-query#pods-by-name-and-namespace

**Pull request merged**
