### PR TITLE
HPCC-16796 Fix configurator coredump

### PR DESCRIPTION
**Pull request by xwang2713**
@richardkchapman I accidentally rebased with master instead of candidate-6.4.0 in PR #9501. I re-create this branch and cherry-pick my changes f7708cb and fdb50ec. I will close PR #9501

Configurator used to be built separately before docs build. Now it Is included in HPCC-Platform/configuration.
This pull request (JIRA HPCC-16796) includes:

Fix two core dumps
Enable configurator and docs build integration
Change system/CMakeLists.txt to allow jlib only build for a component like configurator which depends on it.
The more detail information about configurator's fix will be documented in JIRA HPCC-16796

Signed-off-by: Xiaoming Wang xiaoming.wang@lexisnexi.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 Looks good.

**Comment by xwang2713** [comment]
Wait. The test build reports error when generating ftslave_linux.xml

**Comment by xwang2713** [comment]
Configurator broken for dropzone.xml is due to there are two "sequence" under element/complextype/. Rodrigo will change back to one "sequence".

**Comment by richardkchapman** [comment]
@xwang2713 Is this with you?

**Comment by xwang2713** [comment]
Yes.

**Comment by richardkchapman** [comment]
@xwang2713 This seems to have stalled

**Comment by xwang2713** [comment]
Summary of changes:
1) Fix coredump in configuration/configurator
2) Build configurator before docs  if "-DDOCS_AUTO=ON" set in cmake configuration
3) Add a flag JLIB_ONLY. if " -DJLIB_ONLY=ON" set in cmake configuration only Jlib not platform will be built. The projects  configurator, Ganglia-monitoring and Nagios-monitoring, etc only need jlib not whole platform.
4) Rebase with HPCC 6.4.0 on 04/06/2017 since some fixes are required to build documentation for HPCC 6.4.0.

## Type of change:
- [x ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x ] My code follows the code style of this project.
  - [x ] My code does not create any new warnings from compiler, build system, or lint.
- [x ] The commit message is properly formatted and free of typos.
  - [x ] The commit message title makes sense in a changelog, by itself.
  - [x ] The commit is signed.
- [ ] My change requires a change to the documentation.
- [x ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ x] I have raised JIRA issues to address them separately
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:
http://10.240.32.243/job/CE-Candidate-docs-JIRA-HPCC-16796/

@Michael-Gardner please reviewing commit bc4d87a (cmake configuration change)
@kenrowland please review commits 	00c7917 and 	e9e005b (configurator code change)

**Comment by g-pan** [comment]
Reviewed docs. All generated and rendered properly, even the more complex Using Configuration Manager book, this also appears to have composed correctly.

**Comment by Michael-Gardner** [comment]
@xwang2713 The cmake changes look good.

**Comment by richardkchapman** [comment]
@kenrowland Please review

**Comment by xwang2713** [comment]
@kenrowland there are some c++ code changes in e9e005b

**Review by kenrowland — APPROVED** [review]
Looks good

**Review by kenrowland — APPROVED** [review]
Looks good

**Pull request merged**
