### PR TITLE
HPCC-14289 add option to pull thorslave logs into ZAP reports

### PR DESCRIPTION
**Pull request by wangkx**
Also add a checkbox into legacy ECLWatch UI and default it to
unchecked. If it is checked, thorslave logs will be added
into ZAP report.

Signed-off-by: wangkx kevin.wang@lexisnexis.com

### CODE REVIEW

**Comment by wangkx** [comment]
@RussWhitehead please review.

**Comment by richardkchapman** [comment]
@wangkx Back to you...

**Comment by wangkx** [comment]
@RussWhitehead I made the changes based on your comments. Please review.

**Comment by RussWhitehead** [comment]
Looks good

**Comment by wangkx** [comment]
@richardkchapman this PR is ready to be merged.

**Pull request merged**
