### PR TITLE
HPCC-13616 Cache sessions and prepared queries in Cassandra driver

### PR DESCRIPTION
**Pull request by richardkchapman**

### CODE REVIEW

**Comment by richardkchapman** [comment]
@jamienoss Please review

I have separated this into 4 commits for ease of reviewing, and you may find it easiest to review them separately.

The first is a simple backport of changes already in master that move some class definitions into a separate .hpp file - this should have been done some time ago as without it all upmerges to master have been a real pain. There are no functional changes here of any significance.

The second moves some code around to combine the cluster and session into a single CassandraClusterSession object.

The third adds a cache of Prepared queries to the ClusterSession object (this is code backported from master where such a cache was used for workunit queries) and a cache of ClusterSession objects used when doing repeated Cassandra queries with the same options.

The fourth moves the rate-limiting semaphore to its proper place (per session rather than per-query) and cleans up a little code related to public members that should have been private. There are some new methods in the ClusterSession object that may appear to be unused - they are used in the master version and putting them in here will keep future  upmerges simple.

**Comment by jamienoss** [comment]
@richardkchapman commit fcea5aaa550f6f0ced0a6ed6cabbfee5d30b5b27 checks out as a backport of master.

**Comment by jamienoss** [comment]
@richardkchapman the 2nd commit (06289a4fe12b4a083bf8452bfd2f28b43723b12e) checks out also.

**Comment by jamienoss** [comment]
@richardkchapman small group of related comments regarding encapsulation in the 2nd commit ( 06289a4fe12b4a083bf8452bfd2f28b43723b12e)

In addition is heavy and nested overloading of the () operator considered good practice from a code/dev reuse perspective?

**Comment by jamienoss** [comment]
@richardkchapman done reviewing the 3rd commit (e40e582cf461ea3c5b3ff64ddd0bbc00a439c935) - see comments.

**Comment by jamienoss** [comment]
@richardkchapman Finished with the last commit.

**Comment by richardkchapman** [comment]
I don't think your concerns about missing const are valid - indeed, it would be impossible to make the code compile were I to add the consts you suggest.

Regarding the use of overload operators, maybe. Generally I don't like them, except in fairly specific cases where an object really is designed to look/act like a pointer/wrapper for another object. That WAS the case for CassandraCluster and CassandraSession as originally implemented before this change, but it's slightly less true now that I have combined them into a single object with something of a split personality. I put them in primarily to reduce the amount of code I would need to modify as a result of the change.

I will take a look at changing one or more of these three overloaded operators into queryXXX-style functions to see if it makes the code clearer or less clear.

**Comment by richardkchapman** [comment]
Pushed some changes following review.

**Comment by jamienoss** [comment]
@richardkchapman no further comments.

**Comment by richardkchapman** [comment]
Repushed to squash some commits

**Pull request merged**
