### PR TITLE
HPCC-15412 Use vcredist.exe to install vc runtimes

### PR DESCRIPTION
**Pull request by GordonSmith**
Removed inline runtime DLLs

Fixes HPCC-15412

Signed-off-by: Gordon Smith gordonjsmith@gmail.com

### CODE REVIEW

**Comment by GordonSmith** [comment]
@xwang2713 Please Review

**Comment by xwang2713** [comment]
Code looks good. Just a question: does this also work if build x86_64 version clienttools? We did build x86_64  version clienttools for internal build testing.

**Comment by GordonSmith** [comment]
No... it would need to include "vcredist_x64.exe"...

**Comment by GordonSmith** [comment]
(as well as vcredist_x32.exe for the IDE)

**Comment by xwang2713** [comment]
Right, we sometimes build IDE x86_64bit version as well.

**Pull request merged**
