### PR TITLE
HPCC-18081 Suppress initial ERROR: UDP inErrors msg

### PR DESCRIPTION
**Pull request by mckellyln**
Signed-off-by: Mark Kelly <mark.kelly@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Started Roxie and verfied first call logging does not occur.

### CODE REVIEW

**Comment by mckellyln** [comment]
@richardkchapman please review.

**Comment by mckellyln** [comment]
At first I was using a firstCall variable but just changed it to init prevErrors so that it does not print the first time.

**Comment by richardkchapman** [comment]
Change looks like it would work - but now we won't ever see the total number of UDP errors unless it goes up while a roxie is running. I wonder if we could still output the initial error count, but not as an error (hopefully operations will then not freak out when they see it, but I would still find it interesting)

**Comment by mckellyln** [comment]
Sure, good point.  I will make it print separately - an initial UDP error count and then any deltas ...

**Comment by mckellyln** [comment]
updated

**Comment by richardkchapman** [comment]
@mckellyln Looks good - can you squash

**Comment by mckellyln** [comment]
@richardkchapman - squashed

**Pull request merged**
