### PR TITLE
HPCC-14331 Means to import and export workunits from Dali and Cassandra

### PR DESCRIPTION
**Pull request by richardkchapman**
The existing wutest tool has been cleaned up, its commands rationalized,
and I have renamed it to wutool.

I think it should do all that is needed to get workunits out of dali to
XML and from XML to Cassandra (or vice versa should that be required).

Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@cloLN Please test

**Comment by richardkchapman** [comment]
Note - also fixes https://track.hpccsystems.com/browse/HPCC-15029

**Comment by richardkchapman** [comment]
Note - also fixes https://track.hpccsystems.com/browse/HPCC-15055 and https://track.hpccsystems.com/browse/HPCC-15029

**Comment by richardkchapman** [comment]
I rebased to latest 6.0.0 and changed the last commit to deploy the plugin to both old and new locations

**Comment by cloLN** [comment]
i had rebuilt this and installed successfully.  from a functionality standpoint, I was able to archive and restore from a traditional dali to a cassandra server and vice versa.  The wuid style of cassandra (W20160225-151330-5170) was also preserved when restoring to traditional dali.

**Comment by richardkchapman** [comment]
@ghalliday Please review/merge

**Pull request merged**
