### PR TITLE
HPCC-26971 Remove GVC graph code from legacy ECLWatch

### PR DESCRIPTION
**Pull request by wangkx**
Multiple code scanning alerts are reported in graphgvc.js by CodeQL.
In this fix, graphgvc.js related code is removed because it is only
used by legacy ECLWatch and legacy ECLWatch should be obsolete.
1. Remove the graphgvc.js.
2. Remove the following xslt files because the graphgvc.js is used by
those xslt files:
graph_gvc.xslt, GvcGraph.xslt, and RoxieGVCGraph.xslt.
3. Remove graph_gvc_common.xslt because it is only be used by:
graph_gvc.xslt, GvcGraph.xslt, and RoxieGVCGraph.xslt.
4. The roxieconfig should be obsolete. The following roxieconfig UI
code are removed because the GvcGraph.xslt are needed by the code:
ws_roxieconfig.html. Roxieconfig.xslt and ws_roxieconfig.js.
5. Remove RoxieGraph.xslt because it is not used.
6. Remove GVC graph code from other legacy ECLWatch code.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by wangkx** [comment]
Should this PR be targeting 8.4.x?

**Review by afishbeck — APPROVED** [review]

**Comment by wangkx** [comment]
@richardkchapman this PR is ready to be merged.

**Comment by richardkchapman** [comment]
@wangkx Why 8.4.x rather than 8.6.x ?

**Comment by wangkx** [comment]
@richardkchapman I target this PR to 8.4.x because it is security related. Please let me know if you want me to target it to 8.6.x.

**Comment by richardkchapman** [comment]
Is there a vulnerability/attack vector being removed? If so, we may need to target earlier. If not. 8.6 is fine.

**Comment by wangkx** [comment]
@richardkchapman this PR is re-targeted to 8.6.x.

**Pull request merged**
