### PR TITLE
HPCC-19720 Suppress build warnings for SQS on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by xwang2713**
Signed-off-by: Xiaoming Wang <xiaoming.wang@lexisnexi.com>
@Michael-Gardner please review.

## Type of change:
- [x] This change fixes warnings (the fix does not alter the functionality or the generated code)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.

## Testing:

.240.32.243/job/CE-Plugins-Ubuntu18.04/CE=ubuntu-18.04-amd64/

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 Looks good

**Comment by richardkchapman** [comment]
Smoketest is failing to build...

**Comment by xwang2713** [comment]
Updated. The setting should only be applied for GCC 7.0+.
Tested for CentOS 6,7 and Ubuntu 14.04 (i386, amd64), Ubuntu 16.04 and 18.04

@Michael-Gardner please review.

**Comment by Michael-Gardner** [comment]
Looks ok, should I be testing with the default gcc version? or is there anything special I need to do?

**Comment by xwang2713** [comment]
I did build for all distros.  Should cover GCC 7.0 and old ones.

**Pull request merged**
