### PR TITLE
IDE-404 Embedded ECL Watch Regression

### PR DESCRIPTION
**Pull request by GordonSmith**
Drop Down buttons stopped working in embedded ECL Watch
Rolled back dojo, dijit, dojox to 1.9.7

Fixes IDE-404

Signed-off-by: Gordon Smith gordon.smith@lexisnexis.com

### CODE REVIEW

**Comment by GordonSmith** [comment]
@miguelvazq Please Review

**Comment by miguelvazq** [comment]
This looks good. We have a current issue open that we may need to do this as well for.

**Comment by richardkchapman** [comment]
Why were they rolled forward - just as a general "try to be current" or was there a specific bug fix we wanted? IOW is there some other Jira we need to reopen if we rol them back?

**Comment by GordonSmith** [comment]
(From memory) there was a specific bug, which was part of dgrid - so I rolled them all forward to be current - this rolls the dojo ones back, but not dgrid.
I have opened a bug for the dojo team, but given how hard it is to reproduce/test I don't hold out any hope for it in the short term....

**Comment by richardkchapman** [comment]
Can we use git blame rather than memory to determine with more certainty?

**Comment by GordonSmith** [comment]
Looks like it was just a general "stay current" - HPCC-12820

**Pull request merged**
