### PR TITLE
HPCC-13648 Fix end-user specific code imported into esdl_svc_engine

### PR DESCRIPTION
**Pull request by shamser**
Remove CEsdlSvcEngineSoapBindingEx::handleSoapRequestException() from esdl_svc_engine.cpp as this is used to generate custom soap messages.  Removal will mean the default soap messages will be produced.

### CODE REVIEW

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by richardkchapman** [comment]
@rpastrana Please review

**Comment by rpastrana** [comment]
The change looks reasonable, I'm under the assumption this has been tested.

**Comment by richardkchapman** [comment]
@afishbeck Please review

**Comment by rpastrana** [comment]
@shamser please take a look at the two minor comments. Also, this change appears benign, but should be unit tested. Please let me know if I can help you set up for testing.

**Comment by shamser** [comment]
@rpastrana I've removed the unnecessary code as advised.  Please can you let me know how this can be unit tested. Thanks.

**Comment by rpastrana** [comment]
@shamser Let me know if you have any questions regarding the information sent to you via email.

**Comment by shamser** [comment]
Dynamic ESDL service checked to make sure it is starting correctly.

**Comment by richardkchapman** [comment]
@rpastrana Ok to merge?

**Comment by rpastrana** [comment]
loaded wsmath desdl service, performed several simple tests successfully.

**Comment by rpastrana** [comment]
@richardkchapman this should be ok to merge.

**Pull request merged**
