### PR TITLE
HPCC-18506 no longer remove .ssh on uninstall  for dev builds

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@jakesmith Please test this when you get a chance.  It will no longer attempt to lay down and overwrite if a user other than 'hpcc' is specified.  And subsequently shouldn't remove if the same case is met.

**Comment by jakesmith** [comment]
@Michael-Gardner - tested, the main problem persists. "make clean" is still deleting my ssh keys.

Would it not be better not to switch this behaviour via matching user = "hpcc", but instead, ensure that:
a) make install  // never creates or copies keys
b) make clean  // never deletes ssh keys

i.e. regardless of user, I don't think you want either of those make dependencies to alter ssh keys.

**Comment by Michael-Gardner** [comment]
I'll go ahead and remove that feature altogether then.

**Comment by Michael-Gardner** [comment]
@jakesmith I completely removed the targets and commands for generating ssh keys in the dev builds.  The .ssh directory shouldn't be touched at all anymore by the build.

**Comment by richardkchapman** [comment]
Is this safe for 6.4.4 ? Would 7.0.0 be more appropriate?

**Comment by Michael-Gardner** [comment]
@richardkchapman This code would have only run if you populated the DESTDIR option at build time.  It's contained to developer builds only and shouldn't be touching anything else.  @xwang2713 Can you look at this and confirm if it's safe for a point release?

**Comment by jakesmith** [comment]
@Michael-Gardner - retested - am not sure what happened last time (I can only think I can make clean in wrong directory). Anyway I can confirm works as expected.

**Pull request merged**
