### PR TITLE
HPCC-14819 Dispose of associations earlier in the code generation

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman is this worth taking?
It does reduce the peak memory consumption of a few queries - e.g., dabittan.eclxml, but most are not affected much, and it adds a minor runtime penalty.

**Comment by richardkchapman** [comment]
Why is there a runtime penalty?

**Comment by richardkchapman** [comment]
@ghalliday One question

**Comment by ghalliday** [comment]
@richardkchapman  I thought I had replied.  My comment was confusing.  It is a potential generate time penalty, not query run time penalty.

**Comment by richardkchapman** [comment]
@ghalliday Your call...

**Comment by ghalliday** [comment]
I will run time timings on some sample queries and see what +ve/-ve effect it has

**Comment by ghalliday** [comment]
From my sample of two nasty queries it seems to significantly slow the process down, so closing and will mark as won't fix.

**Comment by ghalliday** [comment]
(Significantly O(2%))

**Pull request closed without merging**
