### PR TITLE
HPCC-26111 CMake smoketest build issue with CC/CXX

### PR DESCRIPTION
**Pull request by mckellyln**
Signed-off-by: Mark Kelly <mark.kelly@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [x] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

smoketest

### CODE REVIEW

**Comment by mckellyln** [comment]
Removing the CMakeCache.txt appears to, so far, resolve this issue, at least with many PR updates.
Since the cmake command specifies many/most/all required options, deleting the CMakeCache.txt beforehand should not alter the created Makefiles.

**Review by jakesmith — COMMENTED** [review]
> Removing the CMakeCache.txt appears to, so far, resolve this issue, at least with many PR updates.
> Since the cmake command specifies many/most/all required options, deleting the CMakeCache.txt beforehand should not alter the created Makefiles.

it's hitting this problem (sometimes) because of a rerun from a previously build, because it's restored from a cache.

Deleting CMakeCache.txt will invalidate the build cache and cause a full rebuild I believe, that would defeat the point of the rerun/caching.

**Comment by richardkchapman** [comment]
I don't think removing CMakeCache.txt means that cpp recompiles happen (I just tried it). It does mean that CMake has to be run, but that's quick.

**Comment by jakesmith** [comment]
> I don't think removing CMakeCache.txt means that cpp recompiles happen (I just tried it). It does mean that CMake has to be run, but that's quick.

ok, maybe it's fine then. I thought it touched something in the process, perhaps that's before the build variables were moved from a changing header that was included everywhere, into 1 file (jutil.cpp) in jlib and picked up programmatically.
Does jutil.cpp recompile when CMakeCache.txt is removed/rebuilt?

**Comment by mckellyln** [comment]
cmake is already always run specifying needed values/arguments.
I do not think it causes any additional compiles or linking, but I will double check.
I think this is an issue within cmake, and to debug it fully would, I believe, require adding a debug cmake with much verbosity.  This PR is a quick attempt at a work-around.

**Comment by jakesmith** [comment]
> cmake is already always run specifying needed values/arguments.
> I do not think it causes any additional compiles or linking, but I will double check.
> I think this is an issue within cmake, and to debug it fully would, I believe, require adding a debug cmake with much verbosity. This PR is a quick attempt at a work-around.

as long as it doesn't cause a lot rebuild on a cache hit should be fine.

**Review by richardkchapman — APPROVED** [review]

**Comment by mckellyln** [comment]
Just did an amend with a title change to verify what gets rebuilt

**Review by jakesmith — APPROVED** [review]

**Pull request merged**
