### PR TITLE
HPCC-24408 Allow extern "C" OPTIMIZE to be generated

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
@mckellyln please review.  I haven't yet found a definitive answer to which version supports the attributes on member functions.

**Comment by mckellyln** [comment]
@ghalliday what is the symptom or error ?
I tried compiling a small test case with gcc/g++ 4.8.5 and it seems to honor the \_\_attribute\_\_ correctly.

**Comment by mckellyln** [comment]
@ghalliday I compiled a small program with the attribute on class member functions with g++ 4.8.5 and it did not complain.
What / where are the errors from this ?

**Comment by ghalliday** [comment]
There is a zip file associated with https://track.hpccsystems.com/browse/HPCC-24385  That has the c++ that failed within it.

**Comment by mckellyln** [comment]
I think we can just move these macros after any extern foo declarations and it should be ok.
Is that possible ?  So instead of:
orig:
```
NOOPTIMIZE extern "C" ECL_API size32_t tfB9UB1(ARowBuilder & crSelf, const byte * src) {
```
proposed:
```
extern "C" NOOPTIMIZE ECL_API size32_t tfB9UB1(ARowBuilder & crSelf, const byte * src) {
```

**Comment by mckellyln** [comment]
If that is not possible or reasonable then I am fine with this PR as it is.

**Comment by ghalliday** [comment]
I will see if I can make that change.  Since there is a work around I will not merge immediately, so fix will be in 7.8.32

**Comment by ghalliday** [comment]
@mckellyln, thanks for investigating the issue some more and coming up with a better fix.
I've taken a look at what would be required to do what you suggest, and it would be slightly tricky with the current code.  I suggest we merge this if you are happy with it, and I will improve the fix for 7.10.x

**Comment by mckellyln** [comment]
I tried g++ 7.3.1 and see the same error:
```
g++ (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
W20200708-114754.cpp:54659:19: error: expected unqualified-id before string constant
 NOOPTIMIZE extern "C" ECL_API size32_t tfB9UB1(ARowBuilder & crSelf, const byte * src) {
                   ^~~
W20200708-114754.cpp:82567:19: error: expected unqualified-id before string constant
 NOOPTIMIZE extern "C" ECL_API size32_t tf7G2F1(ARowBuilder & crSelf, const byte * src) {
                   ^~~
```
Did you use clang ?  I thik we need to change the version test.

**Comment by mckellyln** [comment]
@ghalliday but yes, I'm good with turning this off as you have - for the appropriate versions of g++.

**Comment by ghalliday** [comment]
It might be a problem for all versions of gcc - in which case I need to fix it properly asap.

**Comment by ghalliday** [comment]
Looks like it is a problem on 9.2.x as well.  I will go back and implement a better fix as you suggested.

**Comment by ghalliday** [comment]
@mckellyln I've reimplemented the code so it generates as you suggested.  Examples ecl/regress/(alien1/memleak4).ecl illustrate the problem.
Thanks for being thorough.

**Review by mckellyln — APPROVED** [review]

**Comment by mckellyln** [comment]
@ghalliday I am ok with this.  I dont really know this part of the code-base, but it seems ok.
Perhaps we can put alien1.ecl or memleak14.ecl into the smoke-test regression suite ?

**Comment by ghalliday** [comment]
@shamser please can you double check.

**Review by shamser — CHANGES_REQUESTED** [review]
@ghalliday reminder: title of PR needs updating to reflect change.

**Review by shamser — APPROVED** [review]
@richardkchapman Reviewed.

**Pull request merged**
