### PR TITLE
HPCC-24932 Send Roxie control command using Smart socket map

### PR DESCRIPTION
**Pull request by wangkx**
The existing ESP SMC/ECLWorkunits services use IP addresses defined in
environment xml to send requests to roxie. In this PR, the roxie name is used
to create the Smart socket map for roxie and send control commands to roxie.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by richardkchapman** [comment]
Should this target 8.0 ?

**Comment by wangkx** [comment]
@afishbeck please review. Should this target 8.0 ?

**Comment by afishbeck** [comment]
@wangkx yes this should probably target 8.0 at this point.

**Comment by afishbeck** [comment]
@richardkchapman this uses ISmartSocket to connect to the roxie service.  It's probably overkill since we use just the service name to connect.  So each SmartSocket contains one address.  Do you think keeping it this way future proofs us in any way?

It's done this way elsewhere but that was also for bare-metal where we could have multiple addresses.

**Comment by richardkchapman** [comment]
@afishbeck If SmartSocket helps us with the "we resolve names to IPs too early" issue - or at least gives us a place where we COULD fix that - then it's probably helpful.

**Comment by afishbeck** [comment]
Ok looks good then, but please rebase to 8.0.

**Review by afishbeck — DISMISSED** [review]
@wangkx looks good.  just needs to be 8.0.

**Comment by wangkx** [comment]
@afishbeck this PR has been rebased to master.

**Review by afishbeck — DISMISSED** [review]
@wangkx looks good.

**Comment by wangkx** [comment]
@richardkchapman this PR is ready to be merged.

**Comment by richardkchapman** [comment]
@wangkx Please rebase to resolve clash

**Comment by richardkchapman** [comment]
@wangkx Still needs rebasing

**Comment by wangkx** [comment]
@richardkchapman rebased

**Review by richardkchapman — APPROVED** [review]

**Pull request merged**
