### PR TITLE
HPCC-14750 Naming changes to redis/memcached/kafka plugins

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Add better mutual exclusion of plugins and reporting, also changes the names for redis/memcached/kafka plugins

Signed-off-by: Michael Gardner michael.gardner@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 a quick look please.  Changed the pluginname section in commonSetup.cmake to throw a FATAL_ERROR message if a user tries to build more than one plugin at once.  Also fixed the redis/memcached/kafka issue Richard talked about in the last PR.

**Comment by Michael-Gardner** [comment]
@richardkchapman looks good to merge.  In addition to the name changes, I added more verbose cmake messages to the mutual exclusion check for plugins declared at build time.  The logic achieves the same thing as before (can't declare more than one plugin at build time) but it throws a fatal error so the user knows they can't build more than one plugin at once.

**Comment by richardkchapman** [comment]
For development/testing purposes the ability to build a package with all the plugins, or to combine all plugins into a single package, would actually be quite handy...

**Comment by Michael-Gardner** [comment]
@richardkchapman I'll open up a ticket and get that done for development purposes

**Pull request merged**
