### PR TITLE
HPCC-29294 Use latest version of ZLIB helper files

### PR DESCRIPTION
**Pull request by RussWhitehead**
The ZLib package offering includes several source files that wrap complex ZLib functions into a more manageable interface. These files have been copied into the HPCC-Platform repo and used for many years, and have become outdated from the latest available. This PR replaces those files with the latest, more current ones from ZLib version 1.2.13.  The source file headers include a reference to the location of these files, for future updates.

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
I think this library is already available from vcpkg - and is already built as part of the system.  @GordonSmith can you comment?

**Comment by RussWhitehead** [comment]
@GordonSmith These source files would become part of an SO name minizip.so and miniunz.so.  

I don't think it would be in the zlib library, but to check I did a tty to the ECLWatch k8s pod running on DD, and tried the following

hpcc@eclwatch-d9c75847f-85xjk:/var/lib/HPCCSystems$ find / -iname zlib.so
/usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/Compress/Raw/Zlib/Zlib.so

hpcc@eclwatch-d9c75847f-85xjk:/var/lib/HPCCSystems$ nm -D /usr/lib/x86_64-linux-gnu/perl/5.30.0/auto/Compress/Raw/Zlib/Zlib.so | grep " T "
000000000000b530 T boot_Compress__Raw__Zlib
000000000000b130 T flushParams
00000000000029c0 T my_zcalloc
00000000000029d0 T my_zcfree


I searched for minizip.so and miniunz.so, and found nothing

hpcc@eclwatch-d9c75847f-85xjk:/var/lib/HPCCSystems$  find / -iname minizip.so
hpcc@eclwatch-d9c75847f-85xjk:/var/lib/HPCCSystems$ find / -iname miniunz.so
hpcc@eclwatch-d9c75847f-85xjk:/var/lib/HPCCSystems$

**Comment by GordonSmith** [comment]
The "minizip" library is not currently included as part of our build process (TBH I never spotted that it was third party code).  It is however available in vcpkg (is version 1.2.13 new enough?), so might be better to remove the minizip sources here and add the following to `vcpkg.json.in`

```json
{
    "name": "minizip",
    "platform": "@VCPKG_ZLIB@"
}
```

(Reusing the VCPKG_ZLIB flag in this case is sensible)

Then you need to add the following to your CMakeLists.txt where it is needed:

```cmake
find_package(minizip CONFIG REQUIRED)
target_link_libraries(main PRIVATE minizip::minizip)
```

**Comment by RussWhitehead** [comment]
Replacing this PR with https://github.com/hpcc-systems/HPCC-Platform/pull/17235

**Pull request closed without merging**
