### PR TITLE
HPCC-16866 New flag hasArchive set even when archive xml is removed query text

### PR DESCRIPTION
**Pull request by afishbeck**
Signed-off-by: Anthony Fishbeck <anthony.fishbeck@lexisnexis.com>

### CODE REVIEW

**Comment by afishbeck** [comment]
@wangkx can you test this before it is merged?
@ghalliday can you review?
@richardkchapman Targeting 6.2.2 because parent issue (https://track.hpccsystems.com/browse/HPCC-16822) is.  Please advise whether that is appropriate.

**Comment by richardkchapman** [comment]
Not convinced that we should be using isArchive flag - would a new flag (say "hasArchive") be more appropriate?

**Comment by richardkchapman** [comment]
Moved to 6.2.4

It's slightly debatable whether it should be 6.4.0

**Comment by richardkchapman** [comment]
@afishbeck One comment

**Comment by afishbeck** [comment]
@richardkchapman 
I debated another flag, and am easily convinced.

I thought maybe isArchive could be thought of as "workunit was generated from archive" rather than "the text below contains an archive".

But I'll change to a new "hasArchive" flag.

**Comment by richardkchapman** [comment]
@afishbeck this is waiting for an update from you

**Comment by afishbeck** [comment]
@richardkchapman updated
@wangkx EclWatch will have to check new hasArchive() flag.  Also, can you test?

**Comment by wangkx** [comment]
The code has been tested.

**Pull request merged**
