### PR TITLE
HPCC-31594 Update build_me.md for PCRE2 regex library changes

### PR DESCRIPTION
**Pull request by dcamper**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by dcamper** [comment]
@GordonSmith: This PR focuses on replacing Boost::regex references with PCRE2 but it appears that many more updates could be applied.  It needs to be brought up to date in general.  Or possibly removed and replaced with a reference to another more up-to-date document.

**Comment by GordonSmith** [comment]
@dcamper yes this doc is well out of date.  Also you don't need `libpcre2-dev` to be installed for the build process (same is true for a lot of libs mentioned in that old doc.)

**Comment by dcamper** [comment]
@GordonSmit: Should this documented be updated or removed?  Is there a more up to date version of this information somewhere?

**Comment by GordonSmith** [comment]
@dcamper I would open a new ticket to revisit the build docs (please add a reminder for Rocky)

**Comment by dcamper** [comment]
Closing in favor of better build documentation elsewhere.

**Pull request closed without merging**
