### PR TITLE
HPCC-29522 Add windows dafilesrv open retry mechanism

### PR DESCRIPTION
**Pull request by jakesmith**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
NB: tested by Orbit team who hit this issue.

**Review by mckellyln — APPROVED** [review]
Looks good.

**Review by ghalliday — APPROVED** [review]
I wonder if the code would be simpler to
(i) remove the _win32 dependency apart from the default value.  There might be situations where retrying on linux makes sense.
(ii) remove the if on line 3841.  Always execute the loop and test 
`if ((0 == retryOpenMs) | (ERROR_SHARING_VIOLATION != e->errorCode()))
`inside the catch.

**Comment by jakesmith** [comment]
> I wonder if the code would be simpler to (i) remove the _win32 dependency apart from the default value. There might be situations where retrying on linux makes sense. (ii) remove the if on line 3841. Always execute the loop and test `if ((0 == retryOpenMs) | (ERROR_SHARING_VIOLATION != e->errorCode())) `inside the catch.

not sure if there is an equivalent sharing violation on opening a file under  Linux. (at very least ERROR_SHARING_VIOLATION would need to be differentiated between linux/win.)

**Comment by jakesmith** [comment]
> @jakesmith do we really want to target 8.6.x though? That that moved out of active support - currently (8.8, 8.10, 8.12, 9.0).

I agree, but, they were experimenting with different builds, and for some yet unknown reasons, attempts to use 8.12 and 9.0.6 failed (silently, no output from windows console), so it might not help them in the short term if the fix went into those builds, I/they don't know about 8.8/8.10.

But, let's try 8.8 then, and they can try again with a newer build - and investigate further if need be.
I'll retarget.
They already have a custom 8.6 build now with these changes in it, that they can fall back on if all else fails in the short-term.

**Comment by jakesmith** [comment]
> > @jakesmith do we really want to target 8.6.x though? That that moved out of active support - currently (8.8, 8.10, 8.12, 9.0).
> 
> I agree, but, they were experimenting with different builds, and for some yet unknown reasons, attempts to use 8.12 and 9.0.6 failed (silently, no output from windows console), so it might not help them in the short term if the fix went into those builds, I/they don't know about 8.8/8.10.
> 
> But, let's try 8.8 then, and they can try again with a newer build - and investigate further if need be. I'll retarget. They already have a custom 8.6 build now with these changes in it, that they can fall back on if all else fails in the short-term.

I'm going to close this PR and reopen, because want to rename branch (remove -8.6)

**Pull request closed without merging**
