### PR TITLE
HPCC-15878 - Minor leaks reported from Valgrind

### PR DESCRIPTION
**Pull request by richardkchapman**
Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@afishbeck Please review

**Comment by ghalliday** [comment]
Should this target 6.0.4?

**Comment by afishbeck** [comment]
@richardkchapman looks good.

**Comment by richardkchapman** [comment]
@ghalliday I don't think it needs to target 6.0.4 - the leaks are one-off so won't actually cause a problem other than polluting the leak check reports - though I suppose that in itself might be a reason to target 6.0.4

I don't have strong feelings either way.

**Pull request merged**
