### PR TITLE
HPCC-16350 Add docs for some Date Functions

### PR DESCRIPTION
**Pull request by JamesDeFabia**
Signed-off-by: Jim DeFabia jamesdefabia@lexisnexis.com
@dcamper Please review (will send PDF for to ease readability)

### CODE REVIEW

**Comment by JamesDeFabia** [comment]
@g-pan Smoketest failed in an area where I made no changes. Can you investigate?

**Comment by dcamper** [comment]
Looks good, Jim.  Thanks!

**Comment by JamesDeFabia** [comment]
@g-pan Please review the second commit that fixed the Smoketest issue. Dan already approved the content

**Comment by g-pan** [comment]
Approved.

**Pull request merged**
