### PR TITLE
HPCC-15053 Changes to add_subdirectory dependencies for jlib

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner Michael.Gardner@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@mckellyln I think the lz4 is compression, which is your territory.  All this change does is make it so you can't fail to include the lz4 or lzma subdirectories, which are necessary for building jlib.

**Comment by Michael-Gardner** [comment]
@xwang2713 Ming can you review this please?  Makes lz4 and lzma subdirectories, which are used by jlib, requirements when a user tries to include jlib.

**Comment by xwang2713** [comment]
Looks good.

**Comment by mckellyln** [comment]
I agree, looks good.

**Pull request merged**
