### PR TITLE
HPCC-12516 Add generalized Esp caching mechanism

### PR DESCRIPTION
**Pull request by wangkx**
Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by wangkx** [comment]
@Michael-Gardner please review my changes in cmake files.
@afishbeck please review.

**Comment by wangkx** [comment]
@AttilaVamos could you please let me know why 'Configuring incomplete'? There is no error in my local VM build.

**Comment by AttilaVamos** [comment]
@wangkx It had  problem with memcached (download). I rescheduled.

**Comment by wangkx** [comment]
Thanks to @AttilaVamos . Please let me know if anything I need to do.

**Comment by AttilaVamos** [comment]
@wangkx So here is the thing: it build in smoketest running on on Ubuntu 16.04 (the latest result) but won't on CentOS 7 (previous result). I will check it morning. The schedule2 is a different issue, not related to this PR.

**Comment by AttilaVamos** [comment]
@wangkx The "Create makefiles" has a problem on CentOs :
-- Found LIBMEMCACHED: $<TARGET_FILE:libmemcached> (Required is at least version "1.0.10")

**Comment by wangkx** [comment]
@AttilaVamos I just did a CentOS build without a problem: http://10.240.32.243/job/CE-Kevin-Master/5/CE=centos-7.0-x86_64/

**Comment by AttilaVamos** [comment]
@wangkx I don't think my memcached is old, because:
- other master based PR built well
- it's version is: memcached 1.4.15
So, it seems the problem is in other place. I'm still checking.

**Comment by AttilaVamos** [comment]
@wangkx I find the problem on Smoketest machine. It was environment problem related to libmemcached-devel package. Reinstall fixed the configuration error at the beginning of the build. 

Perhaps it would be nice to add some checking into your code (FindLIBMEMCACHED.cmake) to handle situation where the libmemcached-devel doesn't exist.

**Comment by Michael-Gardner** [comment]
@wangkx Changes look good.

**Comment by mayx** [comment]
One thing I noticed is that in the ecm files there're places that uses cache_globel(1), and places that uses cache_global(1). The hidl uses cache_globel, which appears to be a mis-spell. Should we correct the spelling and make it cache_global for all the places?

**Comment by wangkx** [comment]
Yes, the cache_globel is a mistake. I will fix them

**Pull request merged**
