### PR TITLE
HPCC-14998 Spot Thor topology vs group mismatch during init

### PR DESCRIPTION
**Pull request by jakesmith**
Signed-off-by: Jake Smith jake.smith@lexisnexis.com

### CODE REVIEW

**Comment by jakesmith** [comment]
@Michael-Gardner - please review

**Comment by Michael-Gardner** [comment]
@jakesmith Works great

**Comment by richardkchapman** [comment]
Will the error message help users to realize that the mismatch may be caused by an IP change e.g. on a DHCP system?

**Comment by jakesmith** [comment]
It's an improvement.
It will now give an error (will be captured in init_thor log) saying that there's a mismatch between configuration and group, instead of starting up and hanging indefinitely and restarting in a loop.
Ideally there'd be a mechanism to issue startup errors back to the init system, so the user starting and seeing FAILED could see why directly.

We still need a proper solution to https://track.hpccsystems.com/browse/HPCC-12376

@richardkchapman

**Pull request merged**
