### PR TITLE
HPCC-23392 Solve CA problem for bare metal installations

### PR DESCRIPTION
**Pull request by mayx**
- If remote CA is provided, generate certificates from the CA.
- To generate a certificate remotely, construct a cfssl request,
  send the request to the CA server, extract the certificate from the
  response and save it to the certificate file.

Signed-off-by: Yanrui Ma <yanrui.ma@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [x] Performance
  - [x] Security
  - [x] Thread-safety
  - [x] Cloud-compatibility
  - [x] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by mayx** [comment]
@Michael-Gardner please review and test if it works with package install. I have tested with "make install" and it works.

To invoke the remote CA, specify the CAUrl on the command line. For example for "make install" I did:

caurl="http://10.173.160.101:8888" make install

I've set up a CA on 10.173.160.101, port 8888. It's for testing purposes only, let me know if it works. 

You'll be prompted for username password. I'll communicate them to you offline.

**Review by Michael-Gardner — CHANGES_REQUESTED** [review]
Adding jq into the runtime dependencies needs to be done.  I'll do that and submit the changes.

**Comment by richardkchapman** [comment]
@afishbeck How should this be moved forward?

**Comment by afishbeck** [comment]
@richardkchapman this is basically some enhancements to what is already there.  Michael is taking a look a the changes.  Post 8.0 we can take a look at lessons learned from using cert-manager and see if we can or can't make bare-metal more consistent with what I've done there.

**Comment by richardkchapman** [comment]
@Michael-Gardner Should this be closed? Is there a replacement in the works?

**Comment by stuartort** [comment]
@Michael-Gardner @afishbeck , what is the status of this?  can this PR and jira be closed?

**Comment by afishbeck** [comment]
I noticed the JIRA has the tag "cloud" but although Yanrui mentions running a CA in the cloud, this is really the bare metal solution for automating certificate generation.  The cert-manager integration features are the way forward for the cloud.

For our own releases I would say the cert-manager stuff rather than bare-metal would be the focus, so this would be low priority for our own use.

I'd defer to Michael's judgement on whether these changes are ready and useful for bare-metal though.

**Comment by stuartort** [comment]
@Michael-Gardner, please review and determine if this is needed.

**Pull request closed without merging**
