### PR TITLE
HPCC-24475 Move over to allowlist

### PR DESCRIPTION
**Pull request by jakesmith**
Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
@mckellyln - please review

**Comment by mckellyln** [comment]
@jakesmith looks fine, two ques:
1). We need a documentation update to match @JamesDeFabia 
2). Are hosts in allowlist _always_ IPs ?

**Comment by JamesDeFabia** [comment]
@jakesmith I understand all that needs changing in the docs, except for the roles that Dail understands. There are two that I think are changed or are changing. @mckellyln I am on it.

**Comment by jakesmith** [comment]
>1). We need a documentation update to match @JamesDeFabia
@mckellyln , yes there was a pre-existing JIRA under the parent issue for this.

**Comment by jakesmith** [comment]
>2). Are hosts in allowlist always IPs ?

by the time they are in the whitelist, they are bound IP's, their origin from the environment can be hostnames.
@mckellyln - Is this Q. related to this PR or just a general Q. ?

**Comment by jakesmith** [comment]
>I understand all that needs changing in the docs, except for the roles that Dail understands. There are two that I think are changed or are changing. 

@JamesDeFabia  -  the role names (ThorMaster and ThorSlave) will change later in a separate JIRA/PR that changes master/slave elsewhere. At that point the 'allowlist' docs. will need changing again, to change those role names.

**Comment by jakesmith** [comment]
Will leave PR tagged to @mckellyln, re. answers to questions.

**Comment by mckellyln** [comment]
@jakesmith it was more of a general question, just for my understanding.  But I think resolved IPs are ok as env.xml can have hostnames and IP is resovled at process start for its lifetime.  I was thinking what if one was an IP and the other was a hostname, etc.

**Comment by jakesmith** [comment]
@mckellyln - It's always an IP that's checked against the allowlist.
And the allowlist is populated with IPs only (but it's source can be hostnames.. that get bound to IPs)

**Comment by jakesmith** [comment]
@mckellyln - were you finished reviewing this?

**Comment by mckellyln** [comment]
@jakesmith yes - good to merge

**Comment by jakesmith** [comment]
@richardkchapman - please merge

**Pull request merged**
