### PR TITLE
HPCC-12507 Cli roxie-unused-files --delete improvements

### PR DESCRIPTION
**Pull request by afishbeck**
Unused-files will now support three forms of --delete.

--delete deletes unused files if they are not entries in a superfile.

--delete-subfiles will perform --delete, but after first removing the
file from any superfiles to which it belongs.

--delete-recursive will perform --delete-subfiles and also delete any
superfiles that are made empty (after removing those superfiles from
parent superfiles to which they belong, etc).

Signed-off-by: Anthony Fishbeck anthony.fishbeck@lexisnexis.com

### CODE REVIEW

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by richardkchapman** [comment]
@wangkx Please review

**Comment by afishbeck** [comment]
@wangkx updated

**Comment by wangkx** [comment]
@afishbeck looks good.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Pull request merged**
