### PR TITLE
HPCC-13336 SELF JOIN with limited ATMOST and SKIP is incorrect

### PR DESCRIPTION
**Pull request by shamser**
Signed-off-by: Shamser Ahmed shamser.ahmed@lexisnexis.co.uk

### CODE REVIEW

**Comment by shamser** [comment]
@ghalliday Please can you review.

**Comment by ghalliday** [comment]
@shamser the ecl/regress test isn't testing the error condition

**Comment by shamser** [comment]
@ghalliday Added regression program.  Please can you review.

**Comment by ghalliday** [comment]
@shamser looks good.  
Only comment are that the test case does not need to be duplicated in ecl/regress if it is present in testing/regress.  Also, there is a preference for files in testing/regress to be named according to what they are testing, rather than the original issue number.
I'm happy to merge as-is though.

**Comment by ghalliday** [comment]
@richardkchapman this should probably have gone into 6.0.0 rather than master.  I realised too late.

**Pull request merged**
