### PR TITLE
HPCC-25251 Increase default spray buffer size and remove explicit default

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
@jakesmith @mckellyln this is partly for discussion and possible merging.
I think the explicit default in the environment file is a mistake.  (Ideally it should depend on the target, and the explicit default prevents that being decided automatically.)  This could target master instead, I don't have a strong opinion.

However, what should be the size of the transfer size?  I suspect when reading/writing from a local disk a smaller size may reduce latency.  But sprays/copies will always involve at least one remote read or write, and a larger size will help there.  Will 1MB cause any issues e.g. in dafilesrv?  Increasing this is fairly essential for creating azure blobs - it would ideally be 4MB, but 1MB will do for now.

**Comment by jakesmith** [comment]
> I think the explicit default in the environment file is a mistake. (Ideally it should depend on the target, and the explicit default prevents that being decided automatically.)

I agree, removing default from the environment makes sense.

>This could target master instead, I don't have a strong opinion.

Not sure, it _should_ be safer enough for 7.12 - but it probably should not really go into a point build, and is more needed for cloud (8.0).

> However, what should be the size of the transfer size? I suspect when reading/writing from a local disk a smaller size may reduce latency. But sprays/copies will always involve at least one remote read or write, and a larger size will help there.

I suspect the upside of larger writes in general outweighs any benefit of small lower latency writes, which we don't tend to do.

>Will 1MB cause any issues e.g. in dafilesrv? Increasing this is fairly essential for creating azure blobs - it would ideally be 4MB, but 1MB will do for now.

I don't think so, most dafilesrv read sizes will I think already be 1MB, because they are via createRowStream, which in turn is ultimately via CSerialStreamBase I think - which uses DEFAULT_STREAM_BUFFER_SIZE (1MB).

There are likely other default/hard-wired sizes elsewhere in other situations that are used for both dafilesrv and IFile.
I think they can all safely default to 1MB.

**Review by jakesmith — COMMENTED** [review]
Looks sensible to me.

**Comment by mckellyln** [comment]
```
class CDFUengine: public CInterface, implements IDFUengine
{
    StringBuffer dfuServerName;
    size32_t defaultTransferBufferSize;

    void setDefaultTransferBufferSize(size32_t size)
    {
        defaultTransferBufferSize = size;
    }
```
Do we need to add a check for 0 here and if it is 0 then set it to DEFAULT_STD_BUFFER_SIZE ?

**Comment by ghalliday** [comment]
Yes, filecopy is the only place that it is used.

**Review by mckellyln — APPROVED** [review]
Looks fine.
Approved.

**Pull request merged**
