### PR TITLE
HPCC-22267 Authenticate /esp/files/stub.htm request

### PR DESCRIPTION
**Pull request by wangkx**
The existing code does not authenticate the requests if the
requests retrieve files from /esp/files/. But, the requests
for the stub.htm should be authenticated although the stub.htm
is in /esp/files/. This is because ECLWatch uses the stub.htm
to call ESP services.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by wangkx** [comment]
@GordonSmith could you please check if this is what you need?

**Comment by GordonSmith** [comment]
Code looks fine - going to build and test now.
@wangkx Will this code also work for URLs like this:  https://10.173.160.104:18010/?Wuid=W20190530-143553&Widget=WUDetailsWidget
Or is that the case that is already working?

**Comment by GordonSmith** [comment]
@wangkx should this target 7.2.x?

**Comment by wangkx** [comment]
The https://10.173.160.104:18010/?Wuid=W20190530-143553&Widget=WUDetailsWidget is already working. I am not sure whether it should be in 7.2.x or not. Please let me know.

**Comment by wangkx** [comment]
Just changed the base branch to 7.2.x.

**Review by GordonSmith — APPROVED** [review]
Good to pull.

**Comment by wangkx** [comment]
@richardkchapman this PR is ready to be merged to 7.2.x.

**Pull request merged**
