### PR TITLE
HPCC-12126 Add WsEcl support for Exception severity tags

### PR DESCRIPTION
**Pull request by afishbeck**
Also fix schema for result level "Exception" tag.

Signed-off-by: Anthony Fishbeck anthony.fishbeck@lexisnexis.com

### CODE REVIEW

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by richardkchapman** [comment]
@wangkx please review

**Comment by wangkx** [comment]
@afishbeck please see my comment.

**Comment by afishbeck** [comment]
@wangkx updated

**Comment by wangkx** [comment]
@afishbeck looks good.

**Pull request merged**
