### PR TITLE
HPCC-15482 Implement read/write locks in permission cache

### PR DESCRIPTION
**Pull request by RussWhitehead**
Currently the permissions cache uses a critical section to guard access to
the permission cache, including all updates and lookups. This serializes
lookups, even when no updates are taking place. This PR implement read/write locks
as appropriate to lock the cache during updates, and allow multiple concurrent
lookups

Signed-off-by: Russ Whitehead william.whitehead@lexisnexis.com

### CODE REVIEW

**Comment by RussWhitehead** [comment]
@richardkchapman The branch used for this PR was created from the one I used to check in the singleton cache (HPCC-15439). The commit for this PR is https://github.com/hpcc-systems/HPCC-Platform/commit/07e0903ef51ff5d1e97fd8192cbed23f1007a391
@rpastrana Please review the changes implemented in this PR https://github.com/hpcc-systems/HPCC-Platform/commit/07e0903ef51ff5d1e97fd8192cbed23f1007a391

**Comment by rpastrana** [comment]
@RussWhitehead reviewed left a few comments.

**Comment by rpastrana** [comment]
@RussWhitehead looks reasonable

**Comment by RussWhitehead** [comment]
@richardkchapman Please merge into 6.0.0 along with the branch parent https://github.com/hpcc-systems/HPCC-Platform/pull/8609/commits/7cd747169ec2df13e9d1ddab58fb691bfd6ceb45

**Comment by RussWhitehead** [comment]
Cancelling this PR and replacing with https://github.com/hpcc-systems/HPCC-Platform/pull/8610

**Pull request closed without merging**
