### PR TITLE
Revert "HPCC-25133 Decrease hard workunit result limit to 100MB"

### PR DESCRIPTION
**Pull request by ghalliday**
Reverts hpcc-systems/HPCC-Platform#14432

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman not sure if this should be a PR, or just remove the merge since it was the last merge.

**Review by richardkchapman — DISMISSED** [review]

**Comment by richardkchapman** [comment]
Rather than completely reverting, do we not want to give a warning that values over 100Mb are deprecated and will be disallowed in future versions?

**Comment by richardkchapman** [comment]
@ghalliday

**Comment by ghalliday** [comment]
Yes, that's probably better.  I will take a look at implementing something - unless @jakesmith wants to.

**Comment by jakesmith** [comment]
> Yes, that's probably better. I will take a look at implementing something - unless @jakesmith wants to.

@ghalliday - that's fine, you go ahead

**Pull request closed without merging**
