### PR TITLE
HPCC-13398 DropZone Folder Selector

### PR DESCRIPTION
**Pull request by GordonSmith**
Allow despray and file upload to select target folder.
Support nested folders.

Fixes HPCC-13398

Signed-off-by: Gordon Smith gordon.smith@lexisnexis.com

### CODE REVIEW

**Comment by GordonSmith** [comment]
@miguelvazq Please Review

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by richardkchapman** [comment]
@miguelvazq Please review

**Comment by miguelvazq** [comment]
I pulled in and tested. Looks good.

**Comment by miguelvazq** [comment]
We may consider a tree widget to display multiple folder within folder structure.

**Pull request merged**
