### PR TITLE
HPCC-17199 The python2 and python3 plugins should not be loaded together

### PR DESCRIPTION
**Pull request by richardkchapman**
Because the libpython exported symbols are the same in both libraries, loading
both at the same time can be problematical (it may work in some cases on some
distros, but not all).

However we want to include python support by default in the platform making it
hard to say "just install one".

Therefore I have introduced a mechanism whereby plugins can be
enabled/disabled via the environment.conf file. By default the python3 plugin
will be present but disabled, and the python2 plugin will be present and
enabled. But people wanting to use Python3 can modify their environment.conf
files accordingly.

Signed-off-by: Richard Chapman <rchapman@hpccsystems.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [x] I have created a JIRA ticket to update the documentation.
  - [x] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [x] Performance
  - [x] Security
  - [x] Thread-safety
  - [x] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:
Observed the tracing on startup of esp, roxie, and eclccserver is as expected.

### CODE REVIEW

**Comment by richardkchapman** [comment]
@ghalliday Please review. Note that there probably needs to be an LN PR too for the default environment.conf

**Comment by richardkchapman** [comment]
actually cancel that thought about the LN PR - seems there is no longer a different environment.conf for LN/EE builds

**Comment by richardkchapman** [comment]
You could argue that it's ok to load the ecllib (but not the dll) if syntax checking/archive building. Not sure how I would code that though.

**Comment by richardkchapman** [comment]
It's a little disconcerting that the python3 tests are listed as having passed here...

**Comment by richardkchapman** [comment]
These python3 errors are expected, unless/until the regression suite engine gets cleverer

**Comment by richardkchapman** [comment]
See also https://github.com/hpcc-systems/LN/pull/834

**Comment by AttilaVamos** [comment]
@richardkchapman Something is still suspicious. In my Smoketest development  environment I added a feature to include python tests if python2 enabled and they are all failed.

**Comment by richardkchapman** [comment]
What error did you get, and on which tests?

**Comment by AttilaVamos** [comment]
Error:
      1. Test: embedpy-catch.ecl
    Error (1001): Command return code non-zero. 
     retCode: 1, msg:'
    Deploying ECL Archive /home/ati/smoketest/PR-9697/HPCCSystems-regression/archives/archive_embedpy-catch.xml
    
    Deployed
       wuid: W20170316-151448
       state: failed
    
    eclcc: (0,0): Warning C0: (0,0): error C6003: C++ link error: cannot find -lpy2embed
    eclcc: W20170316-151448(0,0): Error C3000:  Compile/Link failed for W20170316-151448 (see '//192.168.1.58/var/lib/HPCCSystems/myeclccserver/eclcc.log' for details)
    eclcc: (0,0): Warning C0: 
    eclcc: (0,0): Warning C0: ---------- compiler output --------------
    eclcc: (0,0): Warning C0: /usr/bin/ld: cannot find -lpy2embed
    eclcc: (0,0): Warning C0: collect2: error: ld returned 1 exit status
    eclcc: (0,0): Warning C0: 
    eclcc: (0,0): Warning C0: --------- end compiler output -----------
    1 error(s), 7 warning(s)
    '

**Comment by AttilaVamos** [comment]
Neither libpyembed.so nor libpy2embed.so built.

**Comment by Michael-Gardner** [comment]
I'll try building this branch on one of my boxes also

**Comment by AttilaVamos** [comment]
I think there are problems in two files:
1.  In commonSetup.cmake:
   # Plugin options
    set(PLUGINS_LIST
    REMBED
    V8EMBED
    MEMCACHED
    PYEMBED    <- Should be PY2EMBED
    PY3EMBED

2.  in plugins/pyembed/CMakeList.txt:

      project(py2embed)
      if(PYEMBED)          <- should be PY2EMBED

and

       message("Python2 library is ${PYTHON2_LIBRARY}")
       if(MAKE_PYEMBED)   <- MAKE_PY2EMBED

**Comment by Michael-Gardner** [comment]
Yeah.  Since the ADD_PLUGIN call changed, MAKE_PYEMBED needs to change to MAKE_PY2EMBED

**Comment by richardkchapman** [comment]
Updated to change these symbols

**Comment by Michael-Gardner** [comment]
@richardkchapman Also in the top level CMakeLists.txt:
`153     HPCC_ADD_SUBDIRECTORY (plugins/pyembed "PY2EMBED")`

**Comment by richardkchapman** [comment]
@Michael-Gardner Yes, I did that one too

**Comment by AttilaVamos** [comment]
It seems there is only one issue left: The eclcc compiler doesn't find the py2embed library (which is exists in /opt/HPCCSystems/versioned/python2/ directory).

**Comment by richardkchapman** [comment]
Are you using a custom eclcc.ini, or otherwise overriding the plugins path when compiling?

Can you run eclcc -showpaths and tell me what you get

Also what does environment.conf look like?

**Comment by richardkchapman** [comment]
@AttilaVamos I found an issue with the plugin path and have pushed a fix

**Comment by AttilaVamos** [comment]
Smoketest uses files provided in base and PR branch only. So no custom ini file used except the regression test engine config (where the base path updated accordingly the test environment). 
```
eclcc -showpaths
CL_PATH=/usr
ECLCC_ECLBUNDLE_PATH=/home/ati/.HPCCSystems/bundles/
ECLCC_ECLINCLUDE_PATH=.
ECLCC_ECLLIBRARY_PATH=/opt/HPCCSystems/share/ecllibrary/
ECLCC_INCLUDE_PATH=/opt/HPCCSystems/componentfiles/cl/include
ECLCC_LIBRARY_PATH=/opt/HPCCSystems/lib:/opt/HPCCSystems/plugins
ECLCC_PLUGIN_PATH=/opt/HPCCSystems/plugins:/opt/HPCCSystems/versioned/python2
ECLCC_TPL_PATH=/opt/HPCCSystems/componentfiles
HPCC_FILEHOOKS_PATH=/opt/HPCCSystems/filehooks
```
and
```
cat /etc/HPCCSystems/environment.conf ## Default environment configuration file for OpenHPCC

[DEFAULT]
configs=/etc/HPCCSystems
path=/opt/HPCCSystems
classpath=/opt/HPCCSystems/classes
runtime=/var/lib/HPCCSystems
lock=/var/lock/HPCCSystems
# Supported logging fields: AUD,CLS,DET,MID,TIM,DAT,PID,TID,NOD,JOB,USE,SES,COD,MLT,MCT,NNT,COM,QUO,PFX,ALL,STD
logfields=TIM+DAT+MLT+MID+PID+TID+COD+QUO+PFX
pid=/var/run/HPCCSystems
log=/var/log/HPCCSystems
user=hpcc
group=hpcc
#umask=022
home=/home
environment=environment.xml
sourcedir=/etc/HPCCSystems/source
blockname=HPCCSystems
interface=*
# enable epoll method for notification events (true/false)
use_epoll=true
# allow kernel pagecache flushing where enabled (true/false)
allow_pgcache_flush=true
# report UDP network stats
udp_stats=true
mpStart=7101
mpEnd=7500
mpSoMaxConn=128
mpTraceLevel=0
#enable SSL for dafilesrv remote file access
#dfsUseSSL=false
#dfsSSLCertFile=/certfilepath/certfile
#dfsSSLPrivateKeyFile=/keyfilepath/keyfile
jvmoptions=-XX:-UsePerfData
#JNI_PATH=/absolute/path/to/alternative/libjvm.so

# Although HPCC platform includes plugins for both Python2 and Python3, only one may be safely enabled at a time
# as the Python libraries export the same symbols for both versions. Enabling both may lead to unpredicatable results
# including segfaults or undefined symbol errors.
#
# If you would prefer to use python 3 and disable python2, change the line below to read
#  additionalPlugins=python3
#
# Multiple paths can be specified (separate with :, or ; on Windows).
# Relative paths are assumed to be relative to /opt/HPCCSystems/versioned
additionalPlugins=python2
```
Finally from the end of eclcc.log file:
```
00000013 2017-03-17 09:18:13  7610  7610 Adding library: eclrtl
00000014 2017-03-17 09:18:13  7610  7610 Adding library: py2embed
00000015 2017-03-17 09:18:13  7610  7610 Adding source file: W20170317-091813.res.s
00000016 2017-03-17 09:18:13  7610  7610 addSourceFile W20170317-091813.cpp
00000017 2017-03-17 09:18:13  7610  7610 addSourceFile W20170317-091813_1.cpp
00000018 2017-03-17 09:18:13  7610  7610 addSourceFile W20170317-091813.res.s
00000019 2017-03-17 09:18:13  7610  7610 Compiling W20170317-091813
0000001A 2017-03-17 09:18:14  7610  7610 Remove temporaries
0000001B 2017-03-17 09:18:14  7610  7610 Remove W20170317-091813.res.s*
0000001C 2017-03-17 09:18:14  7610  7610 Failed to compile W20170317-091813
0000001D 2017-03-17 09:18:14  7610  7610 
---------- compiler output --------------
/usr/bin/ld: cannot find -lpy2embed
collect2: error: ld returned 1 exit status

--------- end compiler output -----------
```

**Comment by richardkchapman** [comment]
Those match what I would expect, and the latest version pushed should address that issue

**Comment by richardkchapman** [comment]
@ghalliday I think this is ready for you to review now

**Pull request merged**
