### PR TITLE
HPCC-15600 Use a consistent include directory for the regression tests

### PR DESCRIPTION
**Pull request by AttilaVamos**
Add dedicated variable to the include directory and set it to the ECL dir.

Signed-off-by: Attila Vamos attila.vamos@gmail.com

### CODE REVIEW

**Comment by AttilaVamos** [comment]
@richardkchapman please check and merge.

**Comment by richardkchapman** [comment]
@ghalliday I think this is something you wanted...

**Comment by ghalliday** [comment]
Thanks.  I'll check it - it is wanted to clean up the performance suite.

**Comment by ghalliday** [comment]
Looks good.  Old regression suite still works, and I can now code the required changes to the performance suite.

**Pull request merged**
