### PR TITLE
HPCC-23925 Enable regex timings by default

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
Full regression testing not yet complete - a couple of examples grow by a surprising amount.

**Comment by ghalliday** [comment]
@richardkchapman please review.

Note, I ended up implementing this is a different way because the previous implementation had problems
- It was generating a unique entry for each regex pattern, but some functions use > 1,000 so it would have overloaded the stats
- It was previously timing the regexfind and evaluating the arguments passed to regex find.
- it wasn't timing regexreplace.

Instead it is implemented by adding a new optional parameter to the time attribute on an external function which allows you to override the text associated with it in the stats.

**Comment by richardkchapman** [comment]
What's the overhead of these TIME attributes (I can't remember how it works)?

**Comment by richardkchapman** [comment]
@ghalliday One question

**Comment by ghalliday** [comment]
Overhead is
once:
i) time to register the timer.  Fairly low, but not indsignificant

Then for each timing 2 virtual calls, two calls to get_cycles_now(), an atomic increment or two.
I'm guessing <100 cycles

**Comment by ghalliday** [comment]
I could add an option to disable function timings.

**Comment by richardkchapman** [comment]
Should we also be timing the regex compile calls?

**Comment by ghalliday** [comment]
We could (it would be simple).  I didn't because I didn't want to add more overhead.  I was also wondering about moving static patterns to global constants - which would make them hard to time.  It would potentially be significant if they were used in roxie queries.

**Comment by richardkchapman** [comment]
The regex compiles SHOULD be less frequent than the regex calls - so the timing overhead would be less. And if they are not, that's information we would want to know?

Global constants for static patterns sounds like a reasonable idea but I don't think that should stop us timing them when they are not (and ideally not even when they are).

**Pull request merged**
