### PR TITLE
HPCC-16526 Add try/catch to failed LDAP unbind call

### PR DESCRIPTION
**Pull request by RussWhitehead**
Eclserver is restarting multiple times a day in both Alpha and Boca dev
thor environments, leaving any jobs that had been Submitted but not
Compiled as orphaned WUs. This PR wraps the failing call in try/catch and
adds additional logging to help debug

Signed-off-by: Russ Whitehead william.whitehead@lexisnexis.com

### CODE REVIEW

**Comment by RussWhitehead** [comment]
@wangkx Please review

**Comment by wangkx** [comment]
@RussWhitehead the code looks fine as a work around. Please make sure that original issue HPCC-16407 is  not  closed by this PR.

**Comment by RussWhitehead** [comment]
@richardkchapman Please merge

**Comment by RussWhitehead** [comment]
No need for this intermediate fix, closing

**Pull request closed without merging**
