### PR TITLE
HPCC-16829 Valgrind reporting invalid memory access in roxie

### PR DESCRIPTION
**Pull request by richardkchapman**
Signed-off-by: Richard Chapman <rchapman@hpccsystems.com>

### CODE REVIEW

**Comment by richardkchapman** [comment]
@ghalliday Please review

**Comment by ghalliday** [comment]
Is there a situation where the index could be non zero?  E.g., when the activity is the dependency of more than one activity?

**Comment by richardkchapman** [comment]
For some sinks, yes I believe that is the case (and the numOutputs should also be > 0 in such cases)

I'm not 100% sure I can remember how all this code works - but I think this change will make at least one case better.

**Comment by ghalliday** [comment]
It will fix the most common case.

In general I think you need to add _globalUsageCount - there are some examples like dbayliss31.eclxml where there are large numbers of dependencies to the same action activity.

**Comment by richardkchapman** [comment]
If you have a simple example where I can observe valgrind still failing after this change I will investigate

**Pull request merged**
