### PR TITLE
HPCC-13092 Return more variables in WsTopology.TpGroupQuery

### PR DESCRIPTION
**Pull request by wangkx**
1. return the 'kind' (Thor, Roxie, or HThor) for each Group;
2. return the '@replicateOutputs' of the thor cluster which
   uses the Group.

Signed-off-by: wangkx kevin.wang@lexisnexis.com

### CODE REVIEW

**Comment by wangkx** [comment]
@miguelvazq please review.

**Comment by wangkx** [comment]
@RussWhitehead could you please review also?

**Comment by miguelvazq** [comment]
Leaving to @RussWhitehead to make the call on approval. I basically need a Replicate: true flag if that group is capable of replicating.

**Comment by wangkx** [comment]
@RussWhitehead I made the changes based on your comments. Please check.

**Comment by RussWhitehead** [comment]
Looks good

**Comment by wangkx** [comment]
@richardkchapman this is ready to merge.

**Pull request merged**
