### PR TITLE
HPCC-31898 Remove ECLIPSE_HTML from Doc Builds

### PR DESCRIPTION
**Pull request by g-pan**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Complete unit testing :  https://github.com/michael-gardner/HPCC-Platform/releases/tag/community_H-31898-rc1

### CODE REVIEW

**Review by JamesDeFabia — APPROVED** [review]
Good from my POV. 
I made sure that the IDE built and installed correctly. I also checked to see if it had cromulent CHM files included.

**Review by Michael-Gardner — CHANGES_REQUESTED** [review]
So there's also a reference to EclipseHelp here on line 277.

https://github.com/hpcc-systems/HPCC-Platform/pull/18878/files#diff-1cb3dcabfd7d99ae883acdccc1e1729299d1245fb8607a102fccf3868aa05158R277

And I think this will just stop us from uploading that file. Perhaps we should turn it off in the build altogether?

Also do we want to just hide it after it's being built, or stop it altogether? Because it looks like we should remove:

docs/EN_US/CmakeLists.txt:71 (add_subdirectory(EclipseHelp)
docs/EN_US/EclipseHelp (entire directory)
docs/BuildTools/cmake_config/EclipseHelp.txt (entire file)

**Comment by g-pan** [comment]
> we should turn it off in the build altogether?

Yes, this is the actual intent of this of PR

**Comment by g-pan** [comment]
@Michael-Gardner all tests we reviewed all look good. Can you please approve this if you have no other concerns.

**Review by Michael-Gardner — APPROVED** [review]
Reviewed and tested

**Comment by g-pan** [comment]
@ghalliday this should be ready to merge now.

**Pull request merged**
