### PR TITLE
HPCC-18985 At startup, Dali doesn't write sudoersbasedn to daliconf.xml

### PR DESCRIPTION
**Pull request by RussWhitehead**
Dali.xsl currently only places the filesbasedn OU in daliconf.xml. All the OUs
need to be placed there, since at startup Dali tries to create them using
defaults if not specified. This PR adds groups, modules, sudoers,users and workunits
OUs to the configurations

Signed-off-by: Russ Whitehead <william.whitehead@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by RussWhitehead** [comment]
@kenrowland Please review

**Comment by richardkchapman** [comment]
@jakesmith Can you also check that this sounds sensible/sounds like it will address the issue.

**Comment by kenrowland** [comment]
@RussWhitehead  Changes look good. I am taking your word that the correct fields show up in the dali esp xml.

**Comment by RussWhitehead** [comment]
@kenrowland I rebuilt/deployed the platform, generate a new environment, bound LDAPServer component into it, and bound that to Dali.  Started Dali and confirmed the new OUs were now part of the daliconf.xml, and ensured the Dali startup (shared code with ESP startup) correctly used these setting to create the LDAP OU notes on the DC

**Comment by RussWhitehead** [comment]
@jakesmith Please review

**Comment by jakesmith** [comment]
As far as I can tell it looks fine.

**Comment by RussWhitehead** [comment]
@richardkchapman Please merge

**Pull request merged**
