### PR TITLE
HPCC-13146 Prevent Script Injection

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes HPCC-13146

Signed-off-by: Gordon Smith gordonjsmith@gmail.com

### CODE REVIEW

**Comment by GordonSmith** [comment]
@miguelvazq Please Review

**Comment by miguelvazq** [comment]
This will need to be revisited for perhaps https://github.com/hpcc-systems/HPCC-Platform/pull/8406/files I will mark this as something we need to fix.

**Comment by miguelvazq** [comment]
Looks good.

**Comment by richardkchapman** [comment]
@GordonSmith Needs rebasing for a clean merge

**Comment by GordonSmith** [comment]
@richardkchapman Rebased

**Pull request merged**
