### PR TITLE
HPCC-19106 Secure socket avail_read() fix for when peer closes socket

### PR DESCRIPTION
**Pull request by mckellyln**
Signed-off-by: Mark Kelly <mark.kelly@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

QA suite returned expected results

### CODE REVIEW

**Comment by mckellyln** [comment]
This is a fix for using avail_read()==0 to check for a closed SSL socket.
@mayx please review.
NOTE: there is a separate, larger code issue that our SSL wait_read() may return data is ready to read when an SSL_read() could still block and our SSL avail_read() may not return an accurate number of SSL bytes available - which should be addresses in a new issue we can open after discussion of this PR.

**Review by mayx — COMMENTED** [review]
(1) SSL_peek could return <0. Should we call SSL_get_error for this case and log the error? Of course we still return 0 for this case.
(2) Doesn't matter much, but is there any reason to use 2 bytes for reading 1 byte?

**Comment by mckellyln** [comment]
We should probably handle SSL_ERROR_WANT_READ properly.
The non-SSL avail_read() logs an error so I think yes we should do the same for SSL.  I will add these.
2 bytes is just old habit.

**Comment by mckellyln** [comment]
@mayx updated, please re-review.
I decided to not handle SSL_ERROR_WANT_READ/WRITE here at this time.
We can look into adding that here and in other places in a separate issue.

**Review by mayx — APPROVED** [review]
Looks good.

**Comment by mckellyln** [comment]
HOLD on this until more detail is learned about avail_read() and read() usage in sockfile.cpp

**Comment by mckellyln** [comment]
I did a test without SSL, but with avail_read returning only 1 byte if at least 1 byte was available.
I didn't like the inefficiency of avail_read() returning 1 byte when more might be present.
While this may not happen often in normal usage, I am going to close this and HPCC-19124 (#10889 and come up with an alternative.

**Pull request closed without merging**
