### PR TITLE
HPCC-12658 Enable c++11 support by default

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman replaces https://github.com/hpcc-systems/HPCC-Platform/pull/7847

**Comment by mckellyln** [comment]
Do we enforce a specific gcc/clang/vs version ?
Are there runtime issues on platforms that do not have matching dev toolset ?

**Comment by richardkchapman** [comment]
@AttilaVamos I think we may need a newer compiler installing on the smoketest machine

**Comment by AttilaVamos** [comment]
@richardkchapman I updated smoketest this morning and I will reschedule this PR. We can get result in ~10 minutes.

**Pull request merged**
