### PR TITLE
HPCC-32094 Bump vcpkg versions for 9.8.x

### PR DESCRIPTION
**Pull request by GordonSmith**
Switch vcpkg host triplet to match the target triplet (reduces the number of buils items)

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by GordonSmith** [comment]
@kenrowland @dcamper this is a draft PR for the vcpkg version bump can you take a look at my "fixes"?

**Review by dcamper — APPROVED** [review]
pcre2 changes look good.

**Review by dcamper — APPROVED** [review]
JWT and PCRE2 both changes look reasonable.

**Review by Michael-Gardner — COMMENTED** [review]
This looks good for most of the builds. Testing an issue with documentation builds now.  Set of test builds can be found here https://github.com/Michael-Gardner/HPCC-Platform/actions/runs/9585112175/job/26430268005

**Comment by ghalliday** [comment]
@GordonSmith this could do with a comment in the jira about why you needed to make the associated changes in our code.

**Comment by GordonSmith** [comment]
@rpastrana - this open telemetry version bump looks like it has broken the Jave support, any thoughts?

**Review by ghalliday — APPROVED** [review]

**Comment by rpastrana** [comment]
> @rpastrana - this open telemetry version bump looks like it has broken the Jave support, any thoughts?

@GordonSmith - I see the issues, but I don't think they're related to the cpp otel libraries, we'll investigate this either a github action env issue, or perhaps a dep packaging issue on the hpcc4j side...

**Pull request merged**
