### PR TITLE
HPCC-18303 Fix nway input stop issues.

### PR DESCRIPTION
**Pull request by jakesmith**
The NWay input activities were not correctly stopping all inputs,
which could cause problems with upstream splitters or if inside
a child query that was restarted.
The symptom reported was an activity that failed to re-start
because it's stop() had not been called.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Add a regression suite query that tests nway in this context.
Ran/passed full regression suite.

### CODE REVIEW

**Comment by jakesmith** [comment]
@ghalliday - please review

**Comment by jakesmith** [comment]
The roxie version is failing with:
```
<Exception><Code>1413</Code><Source>Roxie</Source><Message>STATE: activity 11 reset without stop (in Iterate 4)</Message></Exception>
``

@richardkchapman - do you know why that would happen? I tried running this test with ecl run --cluster=roxie, but it did not fail.

**Comment by jakesmith** [comment]
>I tried running this test with ecl run --cluster=roxie, but it did not fail.
ok, that's because query is going via hthor, can force it to go to target with pickBestEngine=0, then it fails with same error.

**Comment by richardkchapman** [comment]
That check is only reported as a failure when the option 'failOnLeaks' is selected. The regression suite includes that option on all roxie runs, but running via ecl run may not do so.

**Comment by richardkchapman** [comment]
I suspect your new test has revealed a lurking (minor) roxie bug. Roxie will work correctly under most circumstances, but the reset without stop implies there is a possibility for a row memory leak if used inside a child query I think.

In order to get your Thor fix merged, may be best to mark the new test as noroxie and open a separate Jira to address the roxie bug.

@jakesmith

**Pull request merged**
