### PR TITLE
HPCC-14669 ConfigMgr - Add security manager support

### PR DESCRIPTION
**Pull request by garonsky**
Signed-off-by: Gleb Aronsky gleb.aronsky@lexisnexis.com

### CODE REVIEW

**Comment by garonsky** [comment]
@rpastrana please review

**Comment by rpastrana** [comment]
Looks good, left a few comments/questions.

**Comment by richardkchapman** [comment]
@garonsky Back to you for now

**Comment by garonsky** [comment]
@rpastrana please review based feedback.

**Comment by rpastrana** [comment]
@garonsky the changes look good.

**Comment by garonsky** [comment]
@richardkchapman ready to merge

**Pull request merged**
