### PR TITLE
HPCC-16558 Fix problems comparing serialized nested child datasets

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

### CODE REVIEW

**Comment by ghalliday** [comment]
@shamser please review

**Review by shamser — APPROVED** [review]
@ghalliday Looks good.

**Comment by richardkchapman** [comment]
Is there/should there be a test case?

**Comment by ghalliday** [comment]
@richardkchapman test cased added.  Without the fix it reports:

    Dataset '.' does not contain expression 'ids'

**Pull request merged**
