### PR TITLE
HPCC-21047 Fix Examples in LOOP topic

### PR DESCRIPTION
**Pull request by JamesDeFabia**
Signed-off-by: Jim DeFabia <jamesdefabia@lexisnexis.com>
@ghalliday Please review

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by JamesDeFabia** [comment]
@ghalliday  a PDF built from this branch can be found here:
http://10.240.32.243/view/Docs%207.0/job/JimDocBuild7/CE=ubuntu-14.04-amd64-1/lastSuccessfulBuild/artifact/build-docs/Release/docs/EN_US/ECLLanguageReference_EN_US-7.0.0-documentation0.pdf#page=255

**Comment by ghalliday** [comment]
@JamesDeFabia form 4 and form 5 look the same to me, what is the difference?

**Comment by JamesDeFabia** [comment]
@ghalliday 
They're opposites of each other. 
Form 4's rowfilter is an expression that, when TRUE, indicates a record is done. 
Form 5's loopcondition is an expression that, when TRUE, indicates a record is still to be processed.

**Comment by ghalliday** [comment]
Format 4:  dataset, rowfilter, loopcondition, loopbody
Format 5: dataset, loopfilter,  loopcondition, loopbody

I can't see any difference between rowfilter and loopfilter - they are essentially the same thing.  Note this was alan's original confusion and reason for raising the issue.

The syntax is

LOOP(ds [, loop-counter] [, loop-filter] [,loopcondition], ...)

where at least one of those options must be supplied.

loop-counter specifies the (maximum) number of iterations.
loop-filter controls whether rows in the input are processed again by the loop - or fed into the output
loop-conditional terminates the loop if it is true.  (Can be used in combination with loop-counter specifying a maximum.)

It would probably be better to explain it in a single form than trying to enumate all the different combinations.

**Comment by ghalliday** [comment]
@JamesDeFabia

**Comment by JamesDeFabia** [comment]
@ghalliday I think this commit addresses all your feedback. Please review again and I will rebase when you tell me that it is ready

**Comment by JamesDeFabia** [comment]
@ghalliday I made the change as requested. Please have a look. If you want to see a PDF built from this branch, it is here: 

 10.240.32.243/view/Docs 7.0/job/JimDocBuild7/CE=ubuntu-14.04-amd64-1/lastSuccessfulBuild/artifact/build-docs/Release/docs/EN_US/ECLLanguageReference_EN_US-7.0.0-documentation0.pdf#page=255

**Comment by JamesDeFabia** [comment]
@ghalliday I made all the requested changes. Please have another look. 
PDF can be found here: http://10.240.32.243/view/Docs%207.0/job/JimDocBuild7/CE=ubuntu-14.04-amd64-1/lastSuccessfulBuild/artifact/build-docs/Release/docs/EN_US/ECLLanguageReference_EN_US-7.0.0-documentation0.pdf#page=255

**Comment by ghalliday** [comment]
@JamesDeFabia  pasted from the email review from Alan:

<<<
This is a great improvement, I just have a few comments:

•         The final result of the LOOP aggregates all result records from every iteration that have completed processing.’
o   Text in red is not grammatically correct English. Actually the whole sentence is not grammatically correct.
o    I’m a bit concerned about the use of the word ‘aggregates’ in this context. Your readers will have a perception of ‘aggregates’ meaning aggregations on data (CROSS-TAP,AGGREGATE etc.) ‘aggregates’ used here does not mean that. I would prefer only using the word ‘aggregate’ in the context its used throughout the rest of the Ref manual.
•         There is now a single definition of LOOP, great, but the examples still refer to ‘Form 1’, ‘Form 2’ etc.  These ‘Forms’ have now lost their meaning and, unfortunately, I think the examples will have to be re-worked.

But this is fantastic!

I would also say that:

PARALLEL
There is a restriction: ROWS(LEFT) cannot be directly used in a sub-query of the loopbody.

Could be expanded on. I don’t understand this sentence and I expect many others won’t as well.
>>>

I agree the PARALLEL documentation is not great, but it may be better to remove it rather than try and document it.  The original reason for adding it was superseded by GRAPH, (PARALLEL on LOOP doesn't give you what you need), the only reason for including it is because some of the regression tests contain it.

**Comment by JamesDeFabia** [comment]
@ghalliday Please have another look. Once you give the green light, I will squash. 
 I made all the changes suggested except for removal of the "form 1, Form 2. etc" from the examples. There are 7 forms and each is explained in the comments. Labeling them as Form# allows them to be easily referenced in conversation, email, forum posts, etc.
PDF is available at http://10.240.32.243/view/Docs%207.0/job/JimDocBuild7/CE=ubuntu-14.04-amd64-1/lastSuccessfulBuild/artifact/build-docs/Release/docs/EN_US/ECLLanguageReference_EN_US-7.0.0-documentation0.pdf#page=255

**Comment by ghalliday** [comment]
@JamesDeFabia looks much clearer.  Please squash and I will merge

**Comment by JamesDeFabia** [comment]
@ghalliday I have Squashed . Please merge

**Pull request merged**
