### PR TITLE
Remove JBASE64_Encode duplicate code

### PR DESCRIPTION
**Pull request by jakesmith**
Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [x] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
@ghalliday - for consideration.

I playing with this, because I wanted a version without padding, but didn't need it in the end.
But I templatized the 2 version that are there using a std::function, which avoids the code duplication.
I ran some tests and timing of before/after was the same.

**Comment by ghalliday** [comment]
@jakesmith I don't see any removal of duplication.  Am I missing something?

**Comment by jakesmith** [comment]
@ghalliday - I'd left 2 version in. Now removed.

**Comment by ghalliday** [comment]
@jakesmith the change looks fine - commit needs correct a better title etc.  This might be an example of a low risk-low value change that might not be worth doing, since unlikely to be modified in the future.  Probably worth merging since the work is done.

**Comment by jakesmith** [comment]
>This might be an example of a low risk-low value change that might not be worth doing

@ghalliday - agree - wouldn't have made the change, for the sake of the change alone.
it was whilst investigating a need elsewhere which involved a 3rd forms of encode base64, that turned out to be solved a different way.

I'm not fussed whether merged, can leave it as is, until/if ever revisited.

**Comment by ghalliday** [comment]
@jakesmith I think probably worth merging now you've done the change.

**Comment by richardkchapman** [comment]
That sounds like a "sunk cost" fallacy to me... I'd say let's not merge it!

**Pull request closed without merging**
