### PR TITLE
HPCC-20581 Add ganglia to Utility

### PR DESCRIPTION
**Pull request by miguelvazq**
Fixes HPCC-20581

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by miguelvazq** [comment]
@GordonSmith Please review. FYI @xwang2713

**Review by GordonSmith — APPROVED** [review]
Looks good - but appears to be smoke test issue?

There is no "GangliaWidget" in the eclwatch folder?

**Comment by miguelvazq** [comment]
I think this widget gets added at install time into a different folder outside of the eclwatch directory.

**Comment by richardkchapman** [comment]
@AttilaVamos Can you comment on the smoketest issue?

**Comment by AttilaVamos** [comment]
@miguelvazq on the [Build error:](https://gist.github.com/9c304c19701a4d035770bd1923fb6ce5) link there is a detailed error message.

**Comment by xwang2713** [comment]
Yes, GangliaWidget.js is installed with Ganglia-monitoring package.
Platform fails with error: 
13:36:05 CPack: Create package using DEB
13:36:05 CPack: Install projects
13:36:05 CPack: - Run preinstall target for: hpccsystems-platform
13:36:09 CPack: - Install project: hpccsystems-platform
13:36:10 -- ECL Watch:  Rebuilding Site
13:36:10 ---- Build Target: /var/lib/jenkins2/workspace/CE-JIRA-20581-ganglia/CE/ubuntu-16.04-amd64/build/esp/src/build
13:36:10 ---- Creating out of source build environment
13:36:10 ---- Installing third party libraries
13:36:29 ---- Copy resources
13:36:31 ---- Build website
13:36:40 ModuleNotFoundError: Module not found: Error: Can't resolve 'hpcc/GangliaWidget' in '/var/lib/jenkins2/workspace/CE-JIRA-20581-ganglia/CE/ubuntu-16.04-amd64/build/esp/src/tmp/lib/src'

**Comment by miguelvazq** [comment]
Confirmed with @xwang2713 this gets installed at files/Ganglia therefore causing this error.

**Comment by miguelvazq** [comment]
Closing due to fix that was discussed

**Pull request closed without merging**
