### PR TITLE
HPCC-20045 replace Eclipse_Html.xsl with PortalGen.xsl 

### PR DESCRIPTION
**Pull request by xwang2713**
Replace Eclipse_Html.xsl with ProtalGen.xsl  in portal HTML generation.
fix dockbool-xsl path in PortalGen.xsl

 Signed-off-by: Xiaoming Wang <xiaoming.wang@lexisnexi.com> 

@g-pan please review

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.

## Testing:

http://10.240.32.243/view/custom/job/CE-HPCC-20045-Docs-Portal_XSL/

### CODE REVIEW

**Review by g-pan — APPROVED** [review]
Looks good.

**Comment by richardkchapman** [comment]
Typo "ProtalGen" in the commit message @xwang2713

**Comment by xwang2713** [comment]
@g-pan I corrected typo and rebased. Can you double check the bottom of file EclipseHelp.txt.

**Review by g-pan — APPROVED** [review]
Looks good.

**Pull request merged**
