### PR TITLE
HPCC-17261 New feature #$ for location of currently expanding macro

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
Initial push to check smoketest etc.  Semantics may change - requesting feedback in the jira.

**Comment by ghalliday** [comment]
@shamser please review

**Review by shamser — APPROVED** [review]
@ghalliday Code reviewed. Documentation needs to be updated.

**Comment by ghalliday** [comment]
@dcamper please can you double check the semantics.  Essentially #$ inside a macro has the same meaning as $ at the same place if it was not in a macro.

**Comment by dcamper** [comment]
Gavin, I'm installing your branch to give this feature a test drive.

**Comment by dcamper** [comment]
@ghalliday Enclosing a directory of ECL code I used for initial testing.

- When the module is simple (does not have arguments), the syntax for using #$ is different depending on whether the module is file-based or directory-based.  See FileMod.AddValue() vs DirMod.AddValue(), kicked off via BWR_Test_[File|Dir]Mod.ecl.  That kind of makes sense, but not entirely.  Is it working as designed?
- When the module accepts arguments, I cannot get #$ to work at all.  I tried a number of techniques.  In the enclosed code, I tried re-instantiating the module with the arguments that should have been visible to the function macro, but that did not work.  BWR_Test_[File|Dir]Mod2.ecl contains what I tried.

I think the ideal usage would be that the symbol #$ is translated into the immediately enclosing module, whether that module is file- or directory-based, and whether it is simple or has arguments.  That would simplify the usage of the symbol (and probably complicate your work immensely).  Is that possible?

[FeatureTesting.zip](https://github.com/hpcc-systems/HPCC-Platform/files/3525407/FeatureTesting.zip)

**Comment by ghalliday** [comment]
@dcamper 
The idea was for the functionality to match $, and $ for a file currently means the directory containing the file, so #$ means the same for a macro.

If you want to pass anything into a macro I think you need to do it via a paramater e.g.
```
        factor := (string)NUM_CONSTANT;
        EXPORT AddMultipliedValue(inFile, fieldName, scale = factor) := FUNCTIONMACRO
```
Although I suspect that will only work for a small subset of the things you would like to use it for.

I can see why it be useful to have something to access the context of the macro, but I can't immediately see how it could be implemented - the information doesn't currently exist.

The aim of this change was to allow all imports to be relative - which I think this provides.  Does it solve that problem?

**Comment by richardkchapman** [comment]
@dcamper any comment?

**Comment by dcamper** [comment]
The requested functionality is something I asked for as a like-to-have, but others have concrete projects that depend on it.  I've requested feedback from that group.

**Comment by kev77log** [comment]
I am reasonably certain that this will provide the functionality that was originally requested in https://track.hpccsystems.com/browse/HPCC-22528.

**Comment by dcamper** [comment]
@ghalliday Kevin's project has the priority here.  If he says that this change will work for him, then we can move forward with this implementation.  Thanks!

**Comment by ghalliday** [comment]
@richardkchapman

**Pull request merged**
