### PR TITLE
HPCC-15091 Graph optionally hide spill write/reads

### PR DESCRIPTION
**Pull request by GordonSmith**
Added option to hide activities.
Set better defaults for legacy page.
Options persist no longer global.

Fixes HPCC-15091

Signed-off-by: Gordon Smith gordonjsmith@gmail.com

### CODE REVIEW

**Comment by GordonSmith** [comment]
@miguelvazq Please Review

**Comment by miguelvazq** [comment]
Looks fine. Although, G.H. is saying there is conflicts that must be resolved with the branch.

**Comment by richardkchapman** [comment]
@GordonSmith Please rebase for a clean merge

**Comment by GordonSmith** [comment]
@richardkchapman Rebased...

**Pull request merged**
