### PR TITLE
HPCC-13886 Use merge sort in preference to stable quick sort

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman @jakesmith please review.

**Comment by ghalliday** [comment]
Richard - I should default the spilling sort in roxie as well, but I'll need to rebase once my other change is merged to do that.  (Or have a separate commit.)

**Comment by richardkchapman** [comment]
I think you may have the wrong jira number on this?

**Comment by ghalliday** [comment]
Dyslexia or something...  I'll fix.

**Comment by ghalliday** [comment]
@AttilaVamos any ideas why smoketest failed like this?  (master builds for me)

**Comment by ghalliday** [comment]
Added some timing information to the jira

**Comment by ghalliday** [comment]
@richardkchapman back for you to review.

**Pull request merged**
