### PR TITLE
HPCC-26819 Ensure ISocket::close() aborts reads from the socket

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
@mckellyln please review/sanity check - I'm changing code I don't really understand....
Without this change the improved simulated udp tests sometimes waited for 5 seconds - which corresponded to the time in

`                        flow_socket->read(&f, readsize, readsize, res, 5);
`
With this change in place that delay never occurred.  I can't think of any downsides, but you will have a much better idea.  I imagine it may help in other situations as well.

**Comment by ghalliday** [comment]
The failures may be related to this PR - although not sure why.  Possibly items being added to the thor queue but not being noticed as removed?

**Review by mckellyln — COMMENTED** [review]
What is the specific case this is solving ?  Is it a wait_read() not terminating and then another thread calling shutdown() ?  Feels a bit like setting nolinger.
I am little apprehensive about adding RD in case there is any queued data still ?

**Comment by mckellyln** [comment]
I will test.  the close() should trigger the poll() in wait_read() and then the read's recv() should return 0 indicating a close.

**Comment by ghalliday** [comment]
> What is the specific case this is solving ? Is it a wait_read() not terminating and then another thread calling shutdown() ? Feels a bit like setting nolinger.

Yes that is exactly the case - the flow thread is waiting for another flow control message, but the object is being destroyed, so it calls close on the thread.  That *sometimes* takes the full timeout before aborting the read.

> I am little apprehensive about adding RD in case there is any queued data still ?
It seems to be causing an issue - although I'm not sure why it would.

**Comment by mckellyln** [comment]
I think close() in one thread does not do the same thing to the socket as close() in another process would and so the shutdown(RD) is needed to get the other thread to see an event in poll().

**Comment by mckellyln** [comment]
Can you call sock->shutdown(2) in your code when you know you are finished ?

**Comment by ghalliday** [comment]
Following marks' comments I don't think this is the correct fix - so will close and open a new PR later

**Pull request closed without merging**
