### PR TITLE
HPCC-15893 Script tmp.txt cleanup

### PR DESCRIPTION
**Pull request by mckellyln**
@Michael-Gardner please review.

Signed-off-by: Mark Kelly mark.kelly@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@mckellyln looks good.

**Comment by richardkchapman** [comment]
Why is this a 6.0.4 issue rather than 6.2.0 ?

**Comment by mckellyln** [comment]
Only because its a small and safe fix that could go into 6.0.4.

**Comment by richardkchapman** [comment]
It's an improvement rather than a bugfix though... and is there any such thing as a "safe fix" ?

**Comment by mckellyln** [comment]
Granted it is more of an improvement.  I will move to 6.2.

**Comment by mckellyln** [comment]
closing to re-target 6.2.0

**Pull request closed without merging**
