### PR TITLE
HPCC-16172 Fix some usability issues with daliadmin add.

### PR DESCRIPTION
**Pull request by jakesmith**
Used to silently reject xpath with a trailing '/'
Made value optional.
And allowed arbitrary xpaths to be provided, which will create
the intermediate missing nodes as well as the adding the tail.

Signed-off-by: Jake Smith jake.smith@lexisnexis.com

### CODE REVIEW

**Comment by jakesmith** [comment]
@AttilaVamos - please review

**Comment by AttilaVamos** [comment]
@jakesmith it seems good.

**Comment by jakesmith** [comment]
Probably, but this was a quick fix and I have to look at other issues with high priority.
I've created a separate JIRA for adding unittests (HPCC-16174), so this can get merged.

**Comment by jakesmith** [comment]
@richardkchapman - please merge.

**Pull request merged**
