### PR TITLE
HPCC-28922 PAT failing to clone LN repo

### PR DESCRIPTION
**Pull request by GordonSmith**
"Fine Grained" PATs require a "oauth2" user ID

Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by GordonSmith** [comment]
@ghalliday - the LN build and publish started failing when we issued the new PAT using "fine grained" control - I am not sure how far back this PR should go?

**Comment by ghalliday** [comment]
Adding @jakesmith and @richardkchapman to comment on what it should target. and potential effects.  I would be inclined to target 8.10 - I doubt anyone will do a 8.8 docker ln build.

**Comment by jakesmith** [comment]
@GordonSmith - how did this work before/when did it stop working?
Is it that the oauth2: url is needed now because the passed in/used secret changed to an oauth2 token?

8.10 sounds fine to me too.

**Comment by GordonSmith** [comment]
When we re-created the LNB_ACTOR / LNB_TOKEN we switched to use a "fined grained" token (as opposed to a "classic" token) - and apparently the "oauth2" user is needed when using the PAT to clone a repo...
The reason(s) we needed the new PAT:
1. Needed write access to uploaded build assets for each release as part of the new build mechanism
2. The old token was associated with RKCs account (I think)

**Review by richardkchapman — APPROVED** [review]

**Review by jakesmith — APPROVED** [review]
@GordonSmith - looks good.

**Review by ghalliday — APPROVED** [review]

**Comment by ghalliday** [comment]
Merging to 8.8, but not starting a build because of it.

**Pull request merged**
