### PR TITLE
HPCC-16879 Bundle tool catalog support

### PR DESCRIPTION
**Pull request by richardkchapman**

### CODE REVIEW

**Comment by richardkchapman** [comment]
@ghalliday Please review

**Comment by ghalliday** [comment]
One pre-existing problem.  ecl-bundle search --help displays the help twice (it does with all other commands as well)

I also ran it in a windows bash shell, and it didn't display any options.  Strange because ecl-bundle search --v showed identical tracing.

**Comment by ghalliday** [comment]
search also needs to be included in the list of commands ecl-bundle --help

**Comment by richardkchapman** [comment]
I'll raise a separate Jira re the repeated help - that's Tony's code and I'm not sure I follow it.

**Comment by richardkchapman** [comment]
@ghalliday Updated help texts

**Pull request merged**
