### PR TITLE
HPCC-21209 Ensure onCreate() is called before input is started

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [x] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman please review.
It would be worth checking that moving the onCreate early cannot possibly cause a big delay in calling the input->start()

**Comment by AttilaVamos** [comment]
@ghalliday  I think that was my fault, rescheduled.

**Comment by ghalliday** [comment]
@richardkchapman assign to correct person

**Comment by richardkchapman** [comment]
I think with this change all helper onCreate methods will be called before any starts happen, which is not ideal(though it’s not catastrophic.

An alternative fix would be to put a call to ensureCreate in CRoxieServerSkipCatchActivity::start’s catch block.

@ghalliday

**Comment by ghalliday** [comment]
@richardkchapman new much less intrusive version

**Comment by ghalliday** [comment]
@richardkchapman additional fix pushed.

**Comment by richardkchapman** [comment]
@AttilaVamos Do you know why the spray tests are failing?

**Comment by AttilaVamos** [comment]
@ghalliday @richardkchapman Based on the Smoketest uses "make install" and the platform installed into the user directory, it generates stored parameters for Regression Test Engine with the correct path of drop zone like this:
```
cmd: ./ecl-test query -t all -e=embedded,3rdparty,python3 --loglevel info --timeout 600 --pq 20 -X dropzonePath=/mnt/disk1/home/vamosax/smoketest/PR-12002/hpcc/var/lib/HPCCSystems/mydropzone/,localdir=mnt::disk1::home::vamosax::smoketest
::^p^r-12002::hpcc::var::lib::^h^p^c^c^systems::mydropzone *.ecl
```
From the DFU server log, the errors are:
```
000000CD 2018-12-14 15:07:02.227  5103  5149 "DFU Server running job: D20181214-150702-5"
000000CE 2018-12-14 15:07:02.230  5103  5149 "ERROR: 8112: dfurun.cpp(1730) : DFURUN Exception:  : No Drop Zone on '10.241.40.11' configured at '/var/lib/HPCCSystems/mydropzone/spray_input_terminated'."
000000CF 2018-12-14 15:07:02.232  5103  5149 "DFU Server finished job: D20181214-150702-5"
000000D0 2018-12-14 15:07:02.232  5103  5149 "DFU Server waiting on queue dfuserver_queue"
000000D1 2018-12-14 15:07:02.751  5103  5149 "DFU Server running job: D20181214-150702-4"
000000D2 2018-12-14 15:07:02.755  5103  5149 "ERROR: 8112: dfurun.cpp(1730) : DFURUN Exception:  : No Drop Zone on '10.241.40.11' configured at '/var/lib/HPCCSystems/mydropzone/spray_input_not_terminated'."
000000D3 2018-12-14 15:07:02.757  5103  5149 "DFU Server finished job: D20181214-150702-4"
000000D4 2018-12-14 15:07:02.757  5103  5149 "DFU Server waiting on queue dfuserver_queue"
000000D5 2018-12-14 15:07:03.229  5103  5149 "DFU Server running job: D20181214-150703-2"
000000D6 2018-12-14 15:07:03.234  5103  5149 "ERROR: 8112: dfurun.cpp(1730) : DFURUN Exception:  : No Drop Zone on '10.241.40.11' configured at '/var/lib/HPCCSystems/mydropzone/spray_input_fixed'."
000000D7 2018-12-14 15:07:03.236  5103  5149 "DFU Server finished job: D20181214-150703-2"
000000D8 2018-12-14 15:07:03.236  5103  5149 "DFU Server waiting on queue dfuserver_queue"
000000D9 2018-12-14 15:07:06.496  5103  5149 "DFU Server running job: D20181214-150706-1"
000000DA 2018-12-14 15:07:06.500  5103  5149 "ERROR: 8112: dfurun.cpp(1730) : DFURUN Exception:  : No Drop Zone on '10.241.40.11' configured at '/var/lib/HPCCSystems/mydropzone/spray_input_empty'."
000000DB 2018-12-14 15:07:06.501  5103  5149 "DFU Server finished job: D20181214-150706-1"
000000DC 2018-12-14 15:07:06.501  5103  5149 "DFU Server waiting on queue dfuserver_queue"
000000DD 2018-12-14 15:07:07.034  5103  5149 "DFU Server running job: D20181214-150707-4"
000000DE 2018-12-14 15:07:07.039  5103  5149 "ERROR: 8112: dfurun.cpp(1730) : DFURUN Exception:  : No Drop Zone on '10.241.40.11' configured at '/var/lib/HPCCSystems/mydropzone/spray_input'."
000000DF 2018-12-14 15:07:07.041  5103  5149 "DFU Server finished job: D20181214-150707-4"
```
It seems the Dropzone path from stored parameter is lost or doesn't exists on ECL code execution level. It is a really strange, because it seems ( and if I understand well) the changes introduced by this PR are not related to stored parameter handling.

**Comment by AttilaVamos** [comment]
I'm not sure the above is the real problem. I'm still investigating.

**Comment by AttilaVamos** [comment]
@richardkchapman I figured out what happened. All failures are related to  "make install" and already fixed in 7.0.0. This PR is based on 6.4.x that's why they are failed.

The persist_replicate,ecl:  [HPCC-19949 Persist_replicate.ecl failed on Roxie after "make install"](https://track.hpccsystems.com/browse/HPCC-19949) .  That was an mspec.defaultBaseDir handling error. 

All spray/despray tests: [HPCC-18822
Enable to pass drop zone path as a stored parameter to spray/despray test cases.](https://track.hpccsystems.com/browse/HPCC-18822)

**Pull request merged**
