### PR TITLE
HPCC-14811 Avoid duplicating annotations on expressions

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@jamienoss please review.
BTW I don't pretend to understand what this code is doing!

**Comment by jamienoss** [comment]
https://track.hpccsystems.com/browse/HPCC-14811

**Comment by jamienoss** [comment]
@ghalliday I'm unsure about this, I have the feeling that this may be covering up the issue.  I've looked into the generation side of things and I guess this is the easiest and possibly the actual correct fix but haven't looked in to the part where the clone with annotations is actually complaining.
1) Are you sure this is correct
2) Is it possible that other issues live with this one and this is our opportunity to find and fix those also?

**Comment by ghalliday** [comment]
1) Yes it fixes the problem
2) There are other issues in this area, and I don't have the inclination or the time to investigate them.

Do you have an alternative suggestion?

**Comment by ghalliday** [comment]
@jamienoss

**Comment by jamienoss** [comment]
No, I looked but couldn't find any but I didn't get round to looking at the actual section that was throwing the error. 

I guess we merge but it might be wise to doc this i.e. take a minute to link this with the other jiras that are the "other issues in this area", possibly opening another issue to continue looking into this one.
@richardkchapman good merge.

**Comment by richardkchapman** [comment]
Cherry-picked into 5.6.0

**Pull request merged**
