### PR TITLE
HPCC-14547 Add open ability to superfile tab

### PR DESCRIPTION
**Pull request by miguelvazq**
Within logical file details within the superfile tab there was no open ability into superfile details or number of superfiles in the tab.

Signed-off by: Miguel Vazquez miguel.vazquez@lexisnexis.com

### CODE REVIEW

**Comment by miguelvazq** [comment]
@GordonSmith Please review.

**Comment by GordonSmith** [comment]
Looks fine

**Comment by richardkchapman** [comment]
Worth targetting 5.6.0 ?

**Comment by miguelvazq** [comment]
Been missing for a while. But, safe enough sure.

**Comment by miguelvazq** [comment]
New PR based off of 5.6.0 https://github.com/hpcc-systems/HPCC-Platform/pull/8102

**Pull request closed without merging**
