### PR TITLE
HPCC-25300 Avoid permission issues with kafka build

### PR DESCRIPTION
**Pull request by jakesmith**
Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
@dcamper - Please review.

This is a solution we discussed, and avoids the build failure problems folks have been seeing.
But there may be a more elegant solution, one that avoids this step more thoroughly if nothing has changed or needs building (particularly an issue when deliberately running make install as root)

**Comment by dcamper** [comment]
@jakesmith The upshot of this change would be to rebuild librdkafka every time, even during make install, right?  That does not seem optimal.  Is there a way to test that the 'make install' is active?

**Comment by jakesmith** [comment]
>The upshot of this change would be to rebuild librdkafka every time, even during make install, right? That does not seem optimal. Is there a way to test that the 'make install' is active?

I don't think that's the upshot.
The code without the final delete md5file, i.e. as it was, does:

1) If [the source dir has been copied before] then unconditionally create an md5 file (*NB: before copying over with new*)
2) [unconditionally] copy sources (I think an rsync would work better and could tell if anything had changed using it)
3) Run configure if not run before (btw, might that be problematic if options have changed, and configure is needed? Should it instead run if there were new files..)
4) Use the md5 file created in step 1 (before the latest copy) to check if the files still match (i.e. whether any copied over are different).

So the md5 file is recreated/overwritten every time if the source dir has been copied before.
The old one from a previous step is not needed in this scheme, so it can be deleted..

@dcamper

**Review by richardkchapman — APPROVED** [review]

**Comment by richardkchapman** [comment]
@dcamper Given the chaos this is causing for developers I'm merging now to get into today's builds. Bit if you have suggestions for a better fix please do comment.

**Pull request merged**
