### PR TITLE
HPCC-12692 Additional Plugin Points

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes HPCC-12692

Signed-off-by: Gordon Smith gordon.smith@lexisnexis.com

### CODE REVIEW

**Comment by GordonSmith** [comment]
@miguelvazq @garonsky Please Review - this is just a single point and it can be accessed via "#stubplugin_32-32" and its 32px x 32px in dimensions.

**Comment by miguelvazq** [comment]
This could potentially add two new icons to the toolbar then?

**Comment by GordonSmith** [comment]
Its just a fixed size "DIV" whith a fixed ID of "#stubplugin_32-32" so the plugins can stuff whatever they want in there.

**Comment by miguelvazq** [comment]
Looks fine.

**Pull request merged**
