### PR TITLE
HPCC-14447 ConfigMgr incorrectly encodes passwords

### PR DESCRIPTION
**Pull request by garonsky**
- Escape passwords in response

Signed-off-by: Gleb Aronsky gleb.aronsky@lexisnexis.com

### CODE REVIEW

**Comment by garonsky** [comment]
@RussWhitehead please review.

**Comment by RussWhitehead** [comment]
@garonsky I tested and the behavior is still the same

**Comment by garonsky** [comment]
@RussWhitehead I have double checked and confirmed that this fix works.  Please be sure to refresh and browser and clear all cache when checking this fix.

**Comment by RussWhitehead** [comment]
Right you are @garonsky,  this is working correctly. Ready for merge

**Pull request merged**
