### PR TITLE
HPCC-16745 Include zlib.dll in platform and clienttools packages on Windows

### PR DESCRIPTION
**Pull request by xwang2713**
Signed-off-by: Xiaoming Wang <xiaoming.wang@lexisnexi.com> 

@Michael-Gardner please review

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 Looks good

**Comment by richardkchapman** [comment]
Is this a recent requirement? If not, should this change be targetting 6.0.10 ?

**Comment by xwang2713** [comment]
It is not new request. People reported this problem when run HPCC 6.0.x clienttools on Windows.

**Comment by xwang2713** [comment]
I checked HPCC 6.0.6, 6.0.8 and 6.2.0-rc3. It only happens on 6.2.0-rc3.

**Pull request merged**
