### PR TITLE
HPCC-20550 Remove target ESDL service name in ESDL.bat

### PR DESCRIPTION
**Pull request by dehilsterlexis**
HPCC-20550 remove target ESDL service name in ESDL.bat file.

Fixed IDE-20550

### CODE REVIEW

**Comment by dehilsterlexis** [comment]
@rpastrana for review

**Review by rpastrana — APPROVED** [review]
@dehilsterlexis looks reasonable

**Comment by richardkchapman** [comment]
@dehilsterlexis Should probably be rebased as I think the first listed commit is one that has already been merged separately.

Also the commit title is wrong (should be HPCC-xxxx not IDE-xxx)

**Comment by dehilsterlexis** [comment]
@richardkchapman rebased

**Comment by richardkchapman** [comment]
Commit message still wrong @dehilsterlexis

**Comment by richardkchapman** [comment]
Merged manually to correct commit message

**Pull request closed without merging**
