### PR TITLE
HPCC-15490 MADV_HUGEPAGE define missing from CentOS build

### PR DESCRIPTION
**Pull request by mckellyln**
@ghalliday, @xwang2713 please review

Signed-off-by: Mark Kelly mark.kelly@lexisnexis.com

### CODE REVIEW

**Comment by mckellyln** [comment]
I have seen THP help sort performance but also (rarely) cause excessive run times.
This fix allows users to avoid THP with the env.xml setting eapUseTransparentHugePages="false" instead of relying on OS / admin setting to disable.

**Comment by xwang2713** [comment]
Looks good

**Comment by richardkchapman** [comment]
@ghalliday Any concerns with this going into a point release?

**Comment by ghalliday** [comment]
@richardkchapman I can't see any problems.  Could possibly consider for 6.0 even.

**Comment by richardkchapman** [comment]
Merged manually to 6.0.0

**Pull request closed without merging**
