### PR TITLE
HPCC-16964 Corrects inaccurate dali related default conf values

### PR DESCRIPTION
**Pull request by rpastrana**
- Ensures optional entries with default vals are created with def val

Signed-off-by: Rodrigo Pastrana <rodrigo.pastrana@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [x] Performance
  - [x] Security
  - [x] Thread-safety
  - [x] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by rpastrana** [comment]
@wangkx please review

**Comment by wangkx** [comment]
@rpastrana looks fine.

**Comment by rpastrana** [comment]
@jakesmith can you verify this change does what you're expecting? Thanks.

**Comment by jakesmith** [comment]
Not what I expecting really, this change is burning-in the defaults that are already present in the xsd defined as "default="xxxx", into the xslt.

e.g, from dali.xsd:
```
    <xs:attribute name="backupSoftQueueLimit" type="xs:nonNegativeInteger" use="optional" **default="200"**>
      <xs:annotation>
        <xs:appinfo>
          <tooltip>Limit above which the backup queue will start introducing delays until the backup queue decreases below this limit</tooltip>
        </xs:appinfo>
      </xs:annotation>
    </xs:attribute>
```

The above default, is now duplicated into the xslt logic, i.e.:
```
       <xsl:attribute name="backupSoftQueueLimitDelay">
          <xsl:choose>
            <xsl:when test="string(@backupSoftQueueLimitDelay)!=''">
              <xsl:value-of select="@backupSoftQueueLimitDelay"/>
            </xsl:when>
            <xsl:otherwise>
              <xsl:value-of select="200"/>
            </xsl:otherwise>
          </xsl:choose>
        </xsl:attribute>
```

We don't want the defaults now in 2 places for each property.

@rpastrana  - Is it not possible to pick up the "default" attributes defined in the xsd in a generic fashion ? e.g. using a xslt function?

**Comment by rpastrana** [comment]
@jakesmith there's a layer of separation between the XSD and the XSL, the XSL transform template is not privy to the the XSD contents.  If we want to use the XSD defaults, then the behavior of ConfigMgr UI has to change and no longer make these items "optional".

**Comment by richardkchapman** [comment]
This is a general issue, I think. In most cases we end up with the default specified both in the XSD file and in the code that reads the generated XML. If configMgr has filled in the values with the default, then the XSL does not need to do anything special. If configmgr has not created the attribute at all, the XSL should not create it either...

**Comment by rpastrana** [comment]
Correct. The root issue here is pre-existing inconsistencies. It appears the ConfigMgr UI purposely ignores optional entries absent from the source config file.
However, the various component XSL templates sometimes override that behavior and forcefully insert those entries, and in the DALI case, they sometimes assign random value to those entries.

If we change the UI behavior to insert optional & absent entries, it'll affect all components and will likely cause unintended behavior changes.

@jakesmith I fully support your apprehension about the hard-coded default values in the XSL template, as we discussed before, if we don't forcefully insert those entries into the config file, your code will be responsible for assigning default values entries you don't find in the config file. Let me know your thoughts.

**Comment by jakesmith** [comment]
@rpastrana - Yes, we shouldn't add hard-coded defaults to a 3rd place (the xslt's).
So as the XSL cannot reference the default values defined in the XSD, the xslt's should not generate values that have not been set in configmgr, and therefore rely on the engines default values (which should match the ones present in the XSD's)

**Comment by rpastrana** [comment]
Ok, the xsl will only process existing entries provided by the UI...

**Comment by rpastrana** [comment]
@wangkx please review.

**Comment by wangkx** [comment]
@rpastrana looks fine.

**Comment by richardkchapman** [comment]
@jakesmith You happy now?

**Comment by jakesmith** [comment]
@rpastrana  - don't the other uses of outputBool have the same issue?

**Comment by rpastrana** [comment]
@jakesmith the outputBool template could generate unintended behavior ONLY IF the entry is optional and absent from the source environment file.

There are 4 references of that template, please take a look at the list below and confirm your code will handle the absence of those entries:

recoverFromIncErrors <-- not optional, should not be affected
enableSysLog <- optional (as declared in eclccserver.xsd, but defined in master.xml), confirm this entry should be copied, and no default value inserted at xls level
enableSNMP <- defined in master.xml), confirm this entry should be copied, and no default value inserted at xls level
snmpSendWarnings <- No declaration found, confirm this entry should be copied, and no default value inserted at xls level

**Comment by jakesmith** [comment]
All these have defaults in code and they should in general elsewhere and match any default that's specified in the xsd.

>the outputBool template could generate unintended behavior ONLY IF the entry is optional and absent from the source environment file.

They're not optional - so configmgr enforces that they're set, but If someone removes them from their environment.xml then the xsl will generate a spurious value that mismatches the default
e.g. if recoverFromIncs or enableSysLog is not present in environment.xml, it will generate "0" and not match the default behaviour defined the in engine.
I don't think the outputBool template defaulting to "0" was ever intended here.

Just as with the others (e.g. asyncBackup), if not set, the xslt shouldn't generate anything.


>no default value inserted at xls level

I don't think the XSLT's should ever have ever define the defaults.

Certainly with these Dali entries (and then the unused outputBool template), it would be best to remove them now.

**Comment by rpastrana** [comment]
@jakesmith

**Comment by jakesmith** [comment]
@rpastrana - changes look good.

Did you test what the resulting dali.xsd look like for the standard environment.xml , to see if any differences stood out?

**Comment by rpastrana** [comment]
@jakesmith of course this was tested, here is the diff based on the default env.xml after and before this change (I recommend you verify this change as well):

<   <SDS store="dalisds.xml" caseInsensitive="0" recoverFromIncErrors="true" lCIdlePeriod="" lCIdleRate="" lCMinTime="" lCQuietStartTime="" lCQuietEndTime="" environment="/etc/HPCCSystems/environment.xml"/>
---
>   <SDS store="dalisds.xml" caseInsensitive="0" enableSysLog="0" enableSNMP="0" snmpSendWarnings="0" recoverFromIncErrors="1" lCIdlePeriod="" lCIdleRate="" lCMinTime="" lCQuietStartTime="" lCQuietEndTime="" environment="/etc/HPCCSystems/environment.xml" asyncBackup="0" useNFSBackupMount="0"/>

**Comment by jakesmith** [comment]
@rpastrana - I asked re. testing because you left the 'The change has been fully tested:' section uncompleted and Testing: section empty.

**Comment by jakesmith** [comment]
> lCIdlePeriod="" lCIdleRate="" lCMinTime="" lCQuietStartTime="" lCQuietEndTime=""

These shouldn't be generated.

@rpastrana

**Comment by rpastrana** [comment]
Thanks @jakesmith. That was intentional, I have done as much unit testing as I can, but as I've mentioned a few times, I'd like you to verify the changes since you have intimate knowledge of this component.

**Comment by jakesmith** [comment]
@rpastrana - I know the defaults in the engine, but that's largely irrelevnat.

What I expect of the xslt/xsd in Dali (and other components too), is as we discussed before... that:
1) the xslt do not generate defaults (or spurious values) that mismatch the default present in the xsd.
2) if the value is not set in the environment, the xslt should not generate a value.

I think bar the newly discovered invalid lCIdlePeriod, lCIdleRate, lCMinTime and lCQuietStartTime properties that is now the case.

**Comment by jakesmith** [comment]
@rpastrana - looks good to me.

@richardkchapman - ready to merge.

**Comment by rpastrana** [comment]
Verified offline. 
@jakesmith please review.

**Comment by jakesmith** [comment]
@richardkchapman - ready to merge.

**Pull request merged**
