### PR TITLE
HPCC-14685 Incorrect info for PERSIST regarding SEQUENTIAL in the Lang-Ref-Man

### PR DESCRIPTION
**Pull request by jamienoss**
Signed-off-by: James Noss james.noss@lexisnexis.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@JamesDeFabia  @ghalliday Please review

**Comment by JamesDeFabia** [comment]
ok from my perspective, but  I defer to @ghalliday for final word

**Comment by JamesDeFabia** [comment]
the smoketest errors are unrelated to this PR and s/b resolved with https://github.com/hpcc-systems/HPCC-Platform/pull/8022

**Comment by jamienoss** [comment]
@richardkchapman don't merge yet.

**Comment by jamienoss** [comment]
@JamesDeFabia I missed a part in sequential, can you please review again, thanks.

**Comment by jamienoss** [comment]
...or @ghalliday, perhaps you can you review and merge please?

**Pull request merged**
