### PR TITLE
HPCC-25347 Ensure non-OPT KEYED fields after a wild match are keyed

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [x] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
The duplicate entry caused problems with the following code in jhtree.cpp:

```
    if (!filter->isWild())
    {
        lastReal = idx;
        if (option != FFopt || lastFull == idx-1)
            lastFull = idx;
    }

```
Because FFopt==FFkeyed the test inside that if was only true if the previous field is not wild.  Essentially all KEYED() filters acted as if they were KEYED(,OPT).

I do not know what version to target.  With the change included any queries that are already compiled will treat KEYED(,OPT) as KEYED() until they are recompiled and deployed.  That may be a more serious problem than the original issue.
@richardkchapman @mckellyln

**Comment by richardkchapman** [comment]
There's an alternative fix where FFkeyed = 0

That would leave existing queries behaving the same until recompiled, I think.

Can we spot queries that might be affected?

**Comment by ghalliday** [comment]
@jakesmith @AttilaVamos is this a known problem with 7.8.x github action?

**Comment by AttilaVamos** [comment]
@ghalliday by my best knowledge there is no Smoketest GitHub action for 7.8.x, and I have no idea how this executed.

**Comment by ghalliday** [comment]
Maybe it executed when it was targeting a more modern branch and wasn't removed.

**Comment by ghalliday** [comment]
@richardkchapman updated to add a global flag.  Not sure if the name is right or the default is best.  Will cleanly merge to 7.10.x, but has problems merging with 7.12.x.

**Comment by AttilaVamos** [comment]
The indexcachebug.ecl problem already fixed in 7.12.x. The workflow_contingency_8 is an open issue: HPCC-25248

**Review by richardkchapman — APPROVED** [review]

**Pull request merged**
