### PR TITLE
HPCC-12855 Add GetSprayTargets() to ESP FileSpray

### PR DESCRIPTION
**Pull request by wangkx**
The FileSpray.GetSprayTargets is added for new ECLWatch
to display the unique Groups of Thor/HThor as spray
targets. A sample return is:
<GetSprayTargetsResponse>
<Targets>
<Item>mythor</Item>
<Item>hthor__myeclagent</Item>
</Targets>
</GetSprayTargetsResponse>

Signed-off-by: wangkx kevin.wang@lexisnexis.com

### CODE REVIEW

**Comment by wangkx** [comment]
@GordonSmith please review.

**Comment by GordonSmith** [comment]
Should it return an array of ESPGroupNode?

**Comment by wangkx** [comment]
@GordonSmith For now, only one member 'Name' in the ESPGroupNode?

**Comment by wangkx** [comment]
@GordonSmith It returns an array of GroupNodes now. Each GroupNode contains a Name and a ClusterType.

**Comment by GordonSmith** [comment]
What I meant was:
Shouldn't this method return the same data structure as WsTopology.TpGroupQuery
(also should this method be in WsTopology?)

**Comment by wangkx** [comment]
@GordonSmith This method is only used for spray. So, I think it should be in ESP FileSpray. If you really want to use the same data structure of the WsTopology.TpGroupQuery. I can move it to WsTopology. Please let me know.

**Comment by GordonSmith** [comment]
Looks fine,

**Pull request merged**
