### PR TITLE
HPCC-14756 SOAP calls in child query need to reinit helper

### PR DESCRIPTION
**Pull request by jakesmith**
The SOAP helper object was not reinitialized per child query
execution, as a consequence if the SOAP call in the child query
had used parent row data, it would continue to use the 1st row
data it was initialized for all subsequent executions of the
SOAP call.

Fix by recreating the SOAP helper object per child query start()

Signed-off-by: Jake Smith jake.smith@lexisnexis.com

### CODE REVIEW

**Comment by jakesmith** [comment]
@ghalliday - please review.

NB: Made a point release change for now, as fix is simple and I can't see that anyone could have been relying on this bug before.

Can bump to 5.6 if necessary.

**Comment by jakesmith** [comment]
We decided this should target 5.6 ...

@richardkchapman - can you create a candidate-5.6 branch?

**Comment by richardkchapman** [comment]
5.6 branch created - @jakesmith please rebase and issue new PR

**Comment by jakesmith** [comment]
Closing to retarget 5.6

**Pull request closed without merging**
