### PR TITLE
HPCC-13101 Added option(WITH_PLUGINS) to allow for disabling all plugins

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner Michael.Gardner@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@cloLN Please review

**Comment by cloLN** [comment]
so it works fine for centos.

However, centos is the only distribution we want this flag for.  On ubuntu, we build with plugins by default so the name of the package doesn't reflect with or without plugins.  When you use this cmake flag on a ubuntu build, there's no way to tell from the package name whether or not the packages were built with it.  

Ideally, I'd just like this flag to be use by centos only.  Not sure if we want a ubuntu build without plugins (we already have a lot of ubuntu distros on the portal; providing both with and without plugins for all distros would make the portal page crazy)

**Comment by Michael-Gardner** [comment]
I can easily add a '-with-plugins' to the package file name for debian builds if we want to keep the naming scheme the same.  As we talked about though I really think the better route would be to have the plugins built separately and added as a separate package entirely for each distro.  So if you were to download from a repository, you would grab hpccsystems-platform and hpccsystems-plugins if you wanted both.

**Comment by Michael-Gardner** [comment]
@cloLN Have you tested this since I switched the logic on the WITH_PLUGINS option to make the default to build with plugins?

**Comment by cloLN** [comment]
I'll test again.

**Comment by cloLN** [comment]
On a fresh checkout, it looks like when I run cmake with DWITH_PLUGINS=OFF, I never get prompted to run git submodules

"Please run git submodule update --init --recursive"

**Comment by Michael-Gardner** [comment]
Thanks I'll check it out Chris!

**Comment by richardkchapman** [comment]
That's notmal behaviour on a fresh clean  checkout, isn't it?

**Comment by cloLN** [comment]
On a fresh checkout, it should prompt when I run cmake, but when I use the WITH_PLUGINS=OFF, it doesn't prompt for it at the terminal.

**Comment by Michael-Gardner** [comment]
Well the reason we throw that error there is because cassandra is reliant upon cpp-driver and libuv being populated in order to build.  We aren't building anything that needs cpp-driver/libuv if we aren't building cassandra and therefore not getting prompted.

I'm not sure what we want to do here.

**Comment by richardkchapman** [comment]
Sounds like it is working correctly then

**Comment by Michael-Gardner** [comment]
@richardkchapman talked to Chris this morning, we decided that this was the way it was intended.  Should be good to go for merge unless there's anything you'd like to add?

**Pull request merged**
