### PR TITLE
HPCC-21091 Fix smart join race condition causing crash

### PR DESCRIPTION
**Pull request by jakesmith**
1) Fix problems when row arrays spilt under memory pressure.
Code was thread unsafe – rows could be added and row array expanded
whilst saving, and subsequent flushes of any remaining rows was not using
spillable array correctly and could hit null rows and cause the crash
reported by this JIRA.

NB: this should resolve an old issue (HPCC_17331) that has some debugging
code (still left in for now).

2) Improve choice of row array to spill. Used to check if any had any rows
to process and spill in order, which meant if rows dripping in from
different sources and memory pressure was trying to flush, would spill lots
of small sets. Change to round robin through row arrays.

3) Move some of the code that cleans, compacts and prepares the row arrays
after oom event trying to prepare global lookup, to an earlier common point.
And before compacting ensure row array is force flushed to ensure relocated,
in the event it has spilt.

4) Add/change a few comments

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by jakesmith** [comment]
@ghalliday - please review

**Review by ghalliday — COMMENTED** [review]
@jakesmith code looks generally good - but found one problem

**Comment by jakesmith** [comment]
@ghalliday - please see fix for nextRhsToSpill issue.

**Comment by ghalliday** [comment]
@jakesmith looks good.  Please squash and fill in the checkboxes.

**Comment by jakesmith** [comment]
@ghalliday - squashed and filled checkboxes.

**Comment by ghalliday** [comment]
@richardkchapman should this be considered for 7.0.6?

**Comment by richardkchapman** [comment]
@ghalliday Yes I should think so, if we are confident in the fix

**Comment by jakesmith** [comment]
@ghalliday - retargeted to candidate-7.0.6

**Pull request merged**
