### PR TITLE
HPCC-14420 Dali should initialize cassandra data store

### PR DESCRIPTION
**Pull request by richardkchapman**
The previous code was broken when the environment.xml layout was changed.

Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@cloLN Please test/review

**Comment by cloLN** [comment]
works with the new environment.xml layout

**Comment by cloLN** [comment]
the fix looks good.

**Comment by richardkchapman** [comment]
@ghalliday Please review/merge

**Pull request merged**
