### PR TITLE
HPCC-23077 Pipe crash in run if pipethread exits (race condition)

### PR DESCRIPTION
**Pull request by mckellyln**
Signed-off-by: Mark Kelly <mark.kelly@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Smoke test and manual pipefail runs.

### CODE REVIEW

**Comment by mckellyln** [comment]
@jakesmith please review.

**Comment by jakesmith** [comment]
Looks good.
@richardkchapman - ready to merge.

**Comment by richardkchapman** [comment]
Not sure I see why it would crash before?

**Comment by jakesmith** [comment]
I thought I had, but now can't.
I had thought (as per Mark's comments in JIRA), the "forkthread.clear()", could destroy the running thread just before it called closeOutput().

But looking again, it should remain alive afaics, Thread start links itself and _threadmain will ultimately release/destroy it, if nobody else has a link.
So afaics, it should always be valid for the duration of Thread::run()

@mckellyln - can you elaborate on how the crash happens?

**Comment by mckellyln** [comment]
I thought closeOutput() was being called when forkthread was no longer valid.
I will try yo reproduce and report more info.

**Comment by jakesmith** [comment]
'forkthread' will be null/invalid after the clear, but the object it referenced should still be valid afaics.

**Comment by mckellyln** [comment]
It may not be from the forkthread.clear().  It sure seems CLinuxPipeProcess can go out of scope before closeOutput() is called.  Could the pipewriter end before this thread calls closeOutout() ?

**Comment by jakesmith** [comment]
>Could the pipewriter end before this thread calls closeOutput() ?

PipeWriterThread? I suspect it can, but don't see how related?

**Comment by mckellyln** [comment]
It is because of this -
```
    ~CPipeThroughSlaveActivity()
    {
        ::Release(pipeWriter);
    }
```
That the CLinuxPipeProcess goes out of scope - and thus the closeOutput() call causes the segv.

**Comment by ghalliday** [comment]
I think the fix is correct, but the reason is slightly different.  If retcode has been set but the thread is still running then forkthread will be cleared.  That will prevent the destructor of the pipe object from joining the thread.  When the thread finally wakes up the object will be destroyed leading to a crash.

I suspect only likely on systems with very few (1) cores.

**Comment by richardkchapman** [comment]
@mckellyln Should this target 7.6.x ?

**Comment by ghalliday** [comment]
I think it probably should.  Any "safe" fixes for crashes should target the next point release.

**Comment by mckellyln** [comment]
ok, I'll retarget 7.6.x

**Pull request merged**
