### PR TITLE
HPCC-13304 Assert failure in localSlave mode

### PR DESCRIPTION
**Pull request by richardkchapman**
If local packet discarder is deleted while packets are being discarded, can
end up with an assert failure (and/or memory corruption). This affects local
slave mode only.

Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
This should probably target 5.2.2 - @ghalliday what do you think?

**Comment by ghalliday** [comment]
It looks sensible to go in 5.2.2, and probably should.
Dynamic casts are surprisingly inefficient - we should probably go through the system seeing if we can remove some of them (e.g, by adding casting virtuals to the base classes)

**Comment by richardkchapman** [comment]
I suspect in this case a static cast would do (though I'd have to stare at the code for a while to be sure).

**Comment by richardkchapman** [comment]
Closing to target 5.2.2

**Pull request closed without merging**
