### PR TITLE
HPCC-10018 Initial documentation for Dynamic ESDL 

### PR DESCRIPTION
**Pull request by JamesDeFabia**
@rpastrana has reviewed the finished PDF and his edits have been incorporated
@g-pan Please review for build-readiness

### CODE REVIEW

**Comment by rpastrana** [comment]
final doc reviewed.

**Comment by g-pan** [comment]
This looks good to me. All files successfully build on the build box.

**Comment by richardkchapman** [comment]
Is it worth squashing to a single commit before I merge?

**Comment by JamesDeFabia** [comment]
I wanted to preserve the history of the incremental changes, if I could

**Pull request merged**
