### PR TITLE
HPCC-13510 Exclude childds4, 5, 6 and 7 tests from Hthor in Regression Suite

### PR DESCRIPTION
**Pull request by AttilaVamos**
Add //nohthor tag to avoid execute them on Hthor.

Signed-off-by: Attila Vamos attila.vamos@gmail.com

### CODE REVIEW

**Comment by AttilaVamos** [comment]
@richardkchapman @ghalliday please check but do not merge for a while. 
I'm improving the smoke test and this PR is a good candidate for it.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
setup                hthor      thor       roxie     
setup                Pass      Pass      Pass      
setup_fetch          Pass      Pass      Pass      
setupdict            Pass      Pass      Pass      
setupsearchindex     Pass      Pass      Pass      
setupsq              Pass      Pass      Pass      
setupwordindex       Pass      Pass      Pass      
setupxml             Pass      Pass      Pass      
 
test                 hthor      thor       roxie     
childds1             Pass      Pass      Pass      
childds1err          Pass      Pass      Pass      
childds2             Pass      Fail      Pass      
childds3             Pass      Pass      Pass      
childds4             Excl.     Pass      Pass      
childds5             Excl.     Pass      Pass      
childds6             Excl.     Pass      Pass      
childds7             Excl.     Pass      Pass      
childds7b            Pass      Pass      Pass      
 
HPCC Stop: OK

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| childds1 | Pass | Pass | Pass |
| childds1err | Pass | Pass | Pass |
| childds2 | Pass | Fail | Pass |
| childds3 | Pass | Pass | Pass |
| childds4 | Excl. | Pass | Pass |
| childds5 | Excl. | Pass | Pass |
| childds6 | Excl. | Pass | Pass |
| childds7 | Excl. | Pass | Pass |
| childds7b | Pass | Pass | Pass |
 
HPCC Stop: OK

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| childds1 | Pass | Pass | Pass |
| childds1err | Pass | Pass | Pass |
| childds2 | Pass | Fail | Pass |
| childds3 | Pass | Pass | Pass |
| childds4 | Excl. | Pass | Pass |
| childds5 | Excl. | Pass | Pass |
| childds6 | Excl. | Pass | Pass |
| childds7 | Excl. | Pass | Pass |
| childds7b | Pass | Pass | Pass |
 
HPCC Stop: OK

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| childds1 | Pass | Pass | Pass |
| childds1err | Pass | Pass | Pass |
| childds2 | Pass | Pass | Pass |
| childds3 | Pass | Pass | Pass |
| childds4 | Excl. | Pass | Pass |
| childds5 | Excl. | Pass | Pass |
| childds6 | Excl. | Pass | Pass |
| childds7 | Excl. | Pass | Pass |
| childds7b | Pass | Pass | Pass |
 
HPCC Stop: OK

**Comment by AttilaVamos** [comment]
@richardkchapman or @ghalliday please merge.

**Comment by ghalliday** [comment]
Probably would have been good to have commented why the tests were disabled on hthor, but since planning to deprecate hthor I'l merge anyway.

**Pull request merged**
