### PR TITLE
HPCC-22202 Set "local" attribute on hthor and roxie built indexes

### PR DESCRIPTION
**Pull request by jakesmith**
.. which are always 1 part and by definition local (not distributed)

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
@ghalliday - please check.

**Comment by richardkchapman** [comment]
You can argue that a 1-part index is distributed (1-way).

What is the benefit of marking them local?

**Comment by jakesmith** [comment]
It's more that that they're inconsistent between engines.
Could mark Thor's 1-way indexes as 'distributed' too.

Not sure (should check) what hthor does if asked to create , LOCAL index - which would be exactly the same as it's current default "distributed" 1-way indexes.

**Comment by richardkchapman** [comment]
Also what roxie/hthor do when they encounter an index that is marked both local and 1-way for reading.

**Comment by ghalliday** [comment]
@jakesmith I think waiting for some answers from you

**Comment by jakesmith** [comment]
>Also what roxie/hthor do when they encounter an index that is marked both local and 1-way for reading.

Afaics, after this change they'd be treated in exactly same way as if it was a 1-way without @local.

**Comment by jakesmith** [comment]
>Not sure (should check) what hthor does if asked to create , LOCAL index - which would be exactly the same as it's current default "distributed" 1-way indexes.

Neither hthor or Roxie (prior to this change) used to set the @local attribute under any circumstances, i.e. the only thing that does is Thor when ECL tell it to create a local key.

>You can argue that a 1-part index is distributed (1-way).

So that's the alternative, since hthor and roxie do not mark 1-way (i.e. all) index as local, we could instead change it so that 1-part (,FEW) indexes created by Thor don't either.

Still feels like 1-way's (without TLK) should be "local".. I think that is most logical/consistent.

@richardkchapman - what do you think?

**Comment by jakesmith** [comment]
@richardkchapman - apart from fixing the inconsistency issue (or because it does), it means you can mix hthor and thor 1 part index in a super.
Without this change you get an error when adding mixed subfiles (some "local", some not).

**Comment by jakesmith** [comment]
Closing to replace with: https://track.hpccsystems.com/browse/HPCC-22653

**Pull request closed without merging**
