### PR TITLE
HPCC-12527 Optimize count(a+b+..) to count(a)+count(b)+.. 

### PR DESCRIPTION
**Pull request by shamser**
Signed-off-by: Shamser Ahmed shamser.ahmed@lexisnexis.co.uk

### CODE REVIEW

**Comment by shamser** [comment]
Note: review comments from previous PR: https://github.com/hpcc-systems/HPCC-Platform/pull/9040

**Comment by shamser** [comment]
@ghalliday Made some changes as these changes did not optimize ecl/regress/jake18.ecl very well.

**Comment by ghalliday** [comment]
There are some examples in the private suite that look significantly different:

aaaslowvijay1
aaslowsbfe4
bug81212
dbayliss42
issue12876
issue16279
salini4
saltstep
srao2b
srao2

Also the code to restrict it to a count of a dataset affects the following examples:

vlad11
clad1
vlad24
vved2
rsantos3

@shamser

**Comment by ghalliday** [comment]
I've traced through the threadedConcat example with the original code.  The problem isn't that it is doing the optimization - the problem is that a spill is being created from the incorrect place.

That seems to be caused by code in hqlresource.cpp(~752) - which prevents code that can be executed inline from being hoisted, but does hoist no_dataset_from_transform.

So in this cause the cause for the poor code needs investigating in more detail.  That may well reveal a few other issues...

**Comment by ghalliday** [comment]
In this case a potential fix for that issue revealed another issue:

            //Generally this appears to be better to hoist since it involves calling a transform.
            IHqlExpression * root = queryRoot(ds);
            if (root && root->getOperator() == no_dataset_from_transform)
                return true;

that 

    case no_dataset_from_transform:

 was missing from void CHqlDataset::cacheParent()

**Comment by shamser** [comment]
@ghalliday Please can you review

**Comment by ghalliday** [comment]
@shamser all the changes in the public regression suite look good.  However some of the private ones still need more work:

aaaslowvijay1 - it is now creating a temporary dataset instead of counting the elements
bug81212/dbayliss42 - it looks like it is expanding something that is actually shared.
lbently10 - expanding something that is shared?

I suspect some/all of these are lurking issue that have been revealed by this change, but they need investigating.

**Comment by ghalliday** [comment]
(That was a sample of the largest changes I saw - others I didn't investigate are include saltstep, nospray)

**Comment by richardkchapman** [comment]
@ghalliday This seems to have stalled. What is the plan (or should we abandon it?)

**Comment by ghalliday** [comment]
Closing because there are too many issues with existing queries, and change isn't worth spending much more time working on it.

**Pull request closed without merging**
