### PR TITLE
HPCC-31397 Jirabot improvements / Cloud Jira support

### PR DESCRIPTION
**Pull request by jpmcmu**
- Externalized variables that differ between the Jira versions
- Externalized variables that change such as user mappings
- Added support for addtional workflow transitions
- Added support for Cloud Jira
- Changed PR attachment logic to post additional PRs in a Jira comment
- Changed comment code to use Jira API to post comments

Signed-off-by: James McMullan James.McMullan@lexisnexis.com

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [X] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [X] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [X] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [X] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [X] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [X] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jpmcmu** [comment]
@ghalliday @GordonSmith Please review. Note: we will need to create some new Github Action variables before this gets merged.

**Comment by jpmcmu** [comment]
@ghalliday Please review

**Comment by ghalliday** [comment]
Change looks reasonable.  Please can you add documentation to the jira - what variables are required, typical example of the format for those variables. etc.

**Comment by ghalliday** [comment]
@jpmcmu please can we get this merged - waiting on confirmation the symbols are defined, documented and version picked up by gordon is fixed.

**Comment by jpmcmu** [comment]
@ghalliday @GordonSmith Code review changes have been pushed up. Required Github Action Vars are on the Jira ticket.

 **Note:** In my testing against the live Jira today, there appears to be an issue either with Cloud Jira or python Jira libraries support of Cloud Jira where authentication of the service account will intermittently fail. I added some code to retry the authentication but this will likely need a better solution in the future as this isn't full proof in my testing.

**Comment by jpmcmu** [comment]
@ghalliday Gordon confirmed the Github vars have been added

**Comment by jpmcmu** [comment]
@ghalliday Any concerns or issues blocking this from being merged I can address? The Jira issue documents the required Github Action vars, Gordon added those vars to the Github repo config, python env script version has also been updated as per Gordon's code review.

**Review by ghalliday — APPROVED** [review]

**Pull request merged**
