### PR TITLE
HPCC-32670 Roxie should report k8s app label

### PR DESCRIPTION
**Pull request by rpastrana**
- Adds k8s label to roxie components

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by rpastrana** [comment]
@ghalliday  do you know of any reason why we wouldn't want to report the k8s label app=roxie?
Of note, we already report [app.kubernets.io/name](http://app.kubernets.io/name)=roxie which is the recommended label format per:
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

However most of our other components and likely many other applications report the "app" label as well.

**Comment by rpastrana** [comment]
Adding app label as seen from Kibana/Elk illustrate redundant information:
Untitled

**Review by ghalliday — CHANGES_REQUESTED** [review]
@rpastrana a couple of corrections - the roxie.yaml starts two different pods/components

**Comment by rpastrana** [comment]
> @rpastrana a couple of corrections - the roxie.yaml starts two different pods/components

Sounds good. Any benefit in reporting an app label for eclagent and eclccserver?

**Review by ghalliday — COMMENTED** [review]
@rpastrana change looks ok - please squash

Is this change needed at all since all the standard labels are filled in?

**Comment by rpastrana** [comment]
> @rpastrana change looks ok - please squash
> 
> Is this change needed at all since all the standard labels are filled in?

It's needed because the TF module used to forward logs to Loki relies on this label even though they should be using the standard label.
I recommend we accept this change if nothing else for consistency with most other components (except eclagent and eclcc) and a lot of external docker images.

**Pull request merged**
