### PR TITLE
HPCC-18096 Add Type System to Meta Generator

### PR DESCRIPTION
**Pull request by successar**
Signed-off-by: Sarthak Jain <successar@gmail.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by successar** [comment]
@ghalliday please review.

**Comment by ghalliday** [comment]
I will test by running the compiler regression suite.

My initial concern is that the same record may be generated multiple times if it does not retain information about the original record (relatively common).  That could cause a prohibitive amount of data to be generated.

**Comment by ghalliday** [comment]
@successar 
This crashes when you run it on some of the files in the regression suite.

E.g., testing/regress/ecl/dpat1.ecl

Probably something related to the PARSE patterns.

Please check it works on all of the ecl files in testing/regress/ecl and ecl/regress

**Comment by successar** [comment]
@ghalliday I have fixed the errors and ran it on both regression suites.

**Comment by ghalliday** [comment]
The change looks reasonable.  Running it on some of my private archived queries the generated meta size goes up from 74Mb to 237Mb.

I think that is because the same unnamed records being generated multiple times (and probably matching a named record).  I'm not sure how big a problem that is going to be.  It may just be the necessary cost.

**Comment by ghalliday** [comment]
@richardkchapman what are your thoughts?

**Comment by ghalliday** [comment]
@GordonSmith

**Comment by ghalliday** [comment]
I am merging this to 7.0, with the qualification that the format of the meta information is likely to change before 7.0 goes gold - and will be properly reviewed when work continues on the ecl indexer.

**Pull request merged**
