### PR TITLE
HPCC-15647 Not truncate Description in DFUQuery response

### PR DESCRIPTION
**Pull request by wangkx**
Signed-off-by: wangkx kevin.wang@lexisnexis.com

### CODE REVIEW

**Comment by wangkx** [comment]
@afishbeck please review

**Comment by richardkchapman** [comment]
@GordonSmith Please test. Is this going to cause any issues for the legacy eclwatch?

**Comment by wangkx** [comment]
With this fix, legacy ECLwatch will display full content of the description.

**Comment by GordonSmith** [comment]
Looks good.

**Pull request merged**
