### PR TITLE
HPCC-25065  Calling wrong returnSocket method causes esp to crash

### PR DESCRIPTION
**Pull request by mayx**
- Specify the class of the method to call the class's local version of the method, otherwise the overloaded method of the derived class will be called, which is not what was intended. The bug causes wrong/unintended execution path, and can cause serious consequences under certain conditions. For example, it causes esp to crash when esp is configured with a non-official tls certificate and the user chooses not to accept the certificate.

Signed-off-by: Yanrui Ma <yanrui.ma@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [x] Performance
  - [x] Security
  - [x] Thread-safety
  - [x] Cloud-compatibility
  - [x] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by mayx** [comment]
@afishbeck please review...

**Comment by mayx** [comment]
@wangkx please review...

**Review by wangkx — APPROVED** [review]
@mayx look fine.

**Comment by richardkchapman** [comment]
Picky, but the git commit title doesn't really tell the casual observer (or me) what the issue being fixed is...

"Code was wrong and needs fixing" ...

**Comment by mayx** [comment]
@richardkchapman good point, comment updated...

**Comment by richardkchapman** [comment]
@mayx I don't see a change - did you push it?

**Comment by mayx** [comment]
Sorry I only changed the comment in the PR, let me do it to the commit as well.

**Comment by mayx** [comment]
@richardkchapman commit pushed.

**Comment by richardkchapman** [comment]
What was the symptom? For someone reading the changelog, what will they understand when they read "Need to specify the exact returnSocket method to be called" and how will they know if they are likely to be affected/interested in this issue?

**Comment by mayx** [comment]
@richardkchapman added more details to the comment...

**Comment by richardkchapman** [comment]
@mayx The detail in the commit is fine - it's the title I am concerned about

(See the checkbox - The commit message title makes sense in a changelog, by itself)

As it stands, anyone reading the commit title (without any other information) really has no idea why they might be interested in this change.

**Comment by mayx** [comment]
@richardkchapman title corrected...

**Pull request merged**
