### PR TITLE
HPCC-16006 Remove sources link

### PR DESCRIPTION
**Pull request by miguelvazq**
Remove sources link from operations area. This link was added to the advanced menu area.

Signed-off by: Miguel Vazquez miguel.vazquez@lexisnexis.com

### CODE REVIEW

**Comment by miguelvazq** [comment]
@GordonSmith Please review.

**Comment by GordonSmith** [comment]
Looks good.

**Comment by miguelvazq** [comment]
@ghalliday Ready for merge.

**Comment by ghalliday** [comment]
jira: https://track.hpccsystems.com/browse/HPCC-16006

**Pull request merged**
