### PR TITLE
HPCC-18328 Set userID before calling onUpdatePassword()

### PR DESCRIPTION
**Pull request by wangkx**
The onUpdatePassword() verifies userID input by comparing it
with the userID stored inside HTTP cookie.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by wangkx** [comment]
@kunalaswani I did my unit test. As we discussed, you may do a full test. @RussWhitehead please review.

**Comment by RussWhitehead** [comment]
@wangkx Looks reasonable

**Comment by richardkchapman** [comment]
@kunalaswani Please let me know when your test is complete.

I'm not a security expert but shouldn't we be verifying userid using the currently logged in user, rather than relying on a value in a cookie. Cookies can be faked...

**Comment by wangkx** [comment]
Since the user's password is expired, ESP does not allow the user login before the password is changed. In this fix, the cookie is used to store the user's name in case the user types in a wrong username when submitting the new password. I may create another JIRA to address your security concern.

**Comment by kunalaswani** [comment]
Upon testing this code, a new issue has been encountered where the password fails to update.

**Comment by wangkx** [comment]
Tracing into the ldap lib, the password fails to update because missing old password inside the ISecUser. I have to set the password into the ISecUser and also pass the old password into the updateUserPassword(). @RussWhitehead we need more test accounts.

**Comment by kunalaswani** [comment]
With the new code fix, this has been built and tested. Users are able to update their expired pwds.

**Comment by wangkx** [comment]
@RussWhitehead please review my second change.

**Comment by RussWhitehead** [comment]
@wangkx Looks good
@richardkchapman Since user is not logged in they still has to enter their expired password, which we verify with LDAP.

**Comment by wangkx** [comment]
The changes have been rebased.

**Pull request merged**
