### PR TITLE
HPCC-12665 Use a list to maintain a list of heaplets that may have space

### PR DESCRIPTION
**Pull request by ghalliday**
- Add a lockless singly linked list of heaplets that may potentially
  have any spare space.  This avoids walking all the heaplets when checking
  if any existing blocks have space, and when checking for heaplets to
  return to the global memory pool.
- Convert the list of heaplets for a heap from singly to doubly linked to
  optimize removal of empty heaplets.

Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
Needs rebasing

**Comment by ghalliday** [comment]
rebased

**Comment by ghalliday** [comment]
Mark has found an issue running the unit tests which needs further investigtion:

"It does not fail often.  I had to rerun it many times to get it to fail again.  It could be something unrelated to your changes for sure.  But here is the traceback -
(gdb) where
#0  0x00002b8622d74cf9 in roxiemem::CChunkedHeap::inlineDoAllocate (this=0x1589910, allocatorId=4194304, maxSpillCost=4294967295)
    at /home/mkelly/lnrs/gavin/hpcc12665/HPCC-Platform/roxie/roxiemem/roxiemem.cpp:4211
#1  0x00002b8622d69fe9 in roxiemem::CFixedChunkedHeap::allocate (this=0x1589910, activityId=4194304)
    at /home/mkelly/lnrs/gavin/hpcc12665/HPCC-Platform/roxie/roxiemem/roxiemem.cpp:4273
#2  0x00002b8622d6972c in roxiemem::CRoxieDirectFixedRowHeap::allocate (this=0x158b830)
    at /home/mkelly/lnrs/gavin/hpcc12665/HPCC-Platform/roxie/roxiemem/roxiemem.cpp:3975
#3  0x00002b8622d8551f in roxiemem::RoxieMemTests::FixedCasAllocatorThread::allocate (this=0x158b870)
    at /home/mkelly/lnrs/gavin/hpcc12665/HPCC-Platform/roxie/roxiemem/roxiemem.cpp:5679
#4  0x00002b8622d84a1a in roxiemem::RoxieMemTests::CasAllocatorThread::run (this=0x158b870)
    at /home/mkelly/lnrs/gavin/hpcc12665/HPCC-Platform/roxie/roxiemem/roxiemem.cpp:5594
#5  0x00002b86208157d7 in Thread::begin (this=0x158b870) at /home/mkelly/lnrs/gavin/hpcc12665/HPCC-Platform/system/jlib/jthread.cpp:263
#6  0x00002b8620815266 in Thread::_threadmain (v=0x158b870) at /home/mkelly/lnrs/gavin/hpcc12665/HPCC-Platform/system/jlib/jthread.cpp:109
#7  0x00002b8621b46e9a in start_thread (arg=0x2b863af0b700) at pthread_create.c:308
#8  0x00002b8621e502ed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#9  0x0000000000000000 in ?? ()
(gdb) p chunk
$1 = 0x2b8628400080 ""

(gdb) p *donorHeaplet
$3 = {<roxiemem::Heaplet> = {<roxiemem::HeapletBase> = {_vptr.HeapletBase = 0x0, count = {counter = 2}}, next = 0x2b8628700000,
prev = 0x2b8628000000, allocatorCache = 0x0, heap = 0x0, chunkCapacity = 0, nextSpace = {counter = 184549404}}, r_blocks = {counter = 0}, 
freeBase = {counter = 0}, chunkSize = 0, sharedAllocatorId = 0}
"

**Comment by ghalliday** [comment]
@richardkchapman the problem mark spotted was actually a regression in the transparent huge page support - so if not taken for this pull request it will need to be taken separately.

@mckellyln please have another look - there was a race condition marking the memory as unused to the operating system - which meant it could be marked as unused after it was allocated for something else, leading to most of the fields being blanked out.

**Comment by ghalliday** [comment]
Commit has been separately split out - see https://github.com/hpcc-systems/HPCC-Platform/pull/6822

**Comment by mckellyln** [comment]
I have looked at this and think it is ok to merge.  @richardkchapman

**Pull request merged**
