### PR TITLE
HPCC-15131 Move generation of default environment.xml to hpcc-init/dafilesrv

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner michael.gardner@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 Please review when you have time.

**Comment by richardkchapman** [comment]
We should probably also generate it (if not found) in the configmgr script, so that people wanting to edit the setup before they run it don't start from a blank canvas.

Also need to make sure that people know how to auto-generate without starting a system (that may be a redbook or documentation item, though some sort of echo at the end of the installation might also be helpful)

**Comment by Michael-Gardner** [comment]
we now make sure that the /etc/HPCCSystems/source dir exists when creating a default environment.xml.  If it doesn't, we create it before trying to add the default environment.xml to ${CONFIG_DIR}/source/${ENV_XML_FILE}

This is logic is replicated in three places.  hpcc-init, dafilesrv, configmgr.

**Comment by richardkchapman** [comment]
Just a little bit hesitant about whether it wouldn't be better to generate at build time. Do we gain anything by waiting until first start? (I know I suggested first start...)

**Comment by richardkchapman** [comment]
@Michael-Gardner One question

**Comment by Michael-Gardner** [comment]
@richardkchapman We don't really gain anything.  It would be difficult to generate at build time, just because the program (envgen) is designed to run on a system with the package installed.  So there are a fair number of #defines and processed conf and xml files that I'd have to go through and alter just to get a special version of envgen to run properly at build time.

I am confident I 'could' make it work.  It just would be more work than I think I could handle before the closedown for 6.0.0 when I look at my remaining tickets.  If you want I can create a Jira for moving it to during the build, and try to target 6.2.0.

**Comment by richardkchapman** [comment]
We run programs that we built earlier as part of the build in several places (e.g. esdl, hidl). Why would envgen be different?

**Comment by richardkchapman** [comment]
@Michael-Gardner I don't mind waiting for 6.2 if I have to - but if so we should roll back (in 6.0) the change to use envgen rather than shipping a pre-canned environment.xml.

But take a quick look to see if it's as hard as you think. It might not be.

**Pull request closed without merging**
