### PR TITLE
HPCC-13417 Fix internal error using WILD(field) on PRELOAD DATASET

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@jamienoss please review

**Comment by jamienoss** [comment]
@ghalliday, @richardkchapman This looks good to me however, I think it requires an explicit test in ecl/regress that throws this error.

In the Jira Gavin mentions dlingle17.eclxml in LNtesting but I have commented that I could not find this example (assuming it covers that required anyhow).

**Comment by ghalliday** [comment]
Example is now included (together with dlingle17a which is a cut down version)

**Comment by jamienoss** [comment]
@richardkchapman (@ghalliday) I was still in the process of reviewing this e.g. the tests added to LNtesting.

I was going to say that, if possible, an explicit test should be added and not in the private suite. dlingle17a.eclxml is hardly a "cut down" version, it's only 600 lines diff, that's 0.34% of the total!

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success

**Pull request merged**
