### PR TITLE
HPCC-15609 Explicitly mark compare functions for optimization

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@mckellyln what do you think
@richardkchapman please review/think about it.
It is currently unconditional - it would be a pain to make it conditional without quite a bit more work.  My only concern would be a stupid compare function that then wouldn't compile.   The ECL really needs rewriting in that case anyway.

**Comment by ghalliday** [comment]
Jake questioned whether it is supported by all compilers   I'll check clang.

**Comment by ghalliday** [comment]
a.out.cpp:111:87: warning: unknown attribute 'optimize' ignored [-Wattributes]

If I explicitly compile it with clang.

**Comment by richardkchapman** [comment]
A more portable approach might be to generate separate source files for the different optimization levels?

**Comment by ghalliday** [comment]
That is likely to be nasty.  It is individual functions within classes that you want to configure.

Even though clang generates a warning, I would be inclined to take it.  (We suppress warnings on generated code + don't generally target clang anyway.)

**Comment by ghalliday** [comment]
I guess an alternative change would be to generate optimize_attribute, and have #defines for the different compilers.

**Comment by mckellyln** [comment]
I take it the default opt level is not already -O3 for these routines (when building Release or RelWithDebInfo) ?
I thought it was optimize("O3") - I assume its the same as optimize(3) ?
But otherwise fine, I like higher opt if its safe.
Could you make it be an empty pragma with clang to avoid warning ?

**Comment by richardkchapman** [comment]
I'd be happier taking this if it was configurable.

If you always output a macro, but conditionally output a different definition of that macro into the generated hpp file, would that help?

**Comment by ghalliday** [comment]
@richardkchapman see new implementation where it uses a macro which has a conditional definition.

**Comment by ghalliday** [comment]
Mark, we currently compile thor queries as -O0 because they can contain very large functions.  This is a short(ish) term fix.  A separate issue #15610 covers a fuller solution.

**Pull request merged**
