### PR TITLE
HPCC-20208 Need newer version of libcouchbase to work with OpenSSL1.1/ Ubuntu 18.04

### PR DESCRIPTION
**Pull request by richardkchapman**
Update to 2.9.3

Signed-off-by: Richard Chapman <rchapman@hpccsystems.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by richardkchapman** [comment]
@rpastrana Please review/test

**Comment by rpastrana** [comment]
@xwang2713 this change for embeddedcouchbase will apparently require OpenSSL1.1, do we have 1.1 available on the build machines?

**Comment by richardkchapman** [comment]
No it doesn't. It works with openssl1.1 on Ubuntu 18.04 (which is what 18.04 should be using) but should work with older openssl on other distros.

**Comment by hpccbuilds** [comment]
plugins/couchbase/CMakeLists.txt has " set(LIBCOUCHBASE_LIB_REAL ${CMAKE_CURRENT_BINARY_DIR}/libcouchbase-build/lib/libcouchbase.so.2.0.38)" but build create libcouchbase.so.2.0.59". This difference cause package fail

**Comment by richardkchapman** [comment]
Updated to 2.0.59 and repushed.

**Comment by xwang2713** [comment]
Verified all supported Linux distributions except Ubuntu 18.04 compile new libcouchbase with old openssl (1.0.2) OK.

**Comment by richardkchapman** [comment]
@wangkx Did you also confirm 18.04 building ok (using openssl1.1?) Seems to for me...

**Comment by xwang2713** [comment]
Yes, http://10.240.32.243/view/custom/job/CouchBasePlugin-RKC-Bionic/CE=ubuntu-18.04-amd64/

**Comment by richardkchapman** [comment]
Cool. @rpastrana Are you happy for this to be merged?

**Comment by rpastrana** [comment]
@richardkchapman I can run a quick test using the regression suite test cases for couchbase, setting up my couchbase server now

**Comment by xwang2713** [comment]
@richardkchapman I tried LN (master) with plugins (Platform private branch update-couchbase). The build run OK but couchbase was not build.  I am investigating.

**Comment by rpastrana** [comment]
@cloLN succesfully ran travel sample test on u14.04 -> Version: 4.5.1-2844 couchbase
I did as well on u16.04 -> Version: 4.5.1-2844 couchbase
@kunalaswani  did as well on u18.04 -> Version: 4.5.1-2844 couchbase

**Comment by xwang2713** [comment]
Sorry, it is my mistake. Forget provide plugin option in LN build.

**Comment by richardkchapman** [comment]
@ghalliday Please merge

**Pull request merged**
