### PR TITLE
HPCC-15293 Missing i18n String.

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes HPCC-15293

Signed-off-by: Gordon Smith gordonjsmith@gmail.com

### CODE REVIEW

**Comment by GordonSmith** [comment]
@miguelvazq Please Review

**Comment by miguelvazq** [comment]
looks good.

**Comment by GordonSmith** [comment]
@richardkchapman Don't pull yet there are more missing...

**Comment by GordonSmith** [comment]
@miguelvazq Please re-review

**Comment by miguelvazq** [comment]
Looks like you added the missing ones. Good to go.

**Pull request merged**
