### PR TITLE
HPCC-12965 Fix xsl:message handling

### PR DESCRIPTION
**Pull request by garonsky**
```
- Handle terminate yes/no properly
- Cleanup user error messages a bit
```

Signed-off-by: Gleb Aronsky gleb.aronsky@lexisnexis.com

### CODE REVIEW

**Comment by garonsky** [comment]
@wangkx please review

**Comment by garonsky** [comment]
Only files that terminate='yes' will have their configuration file deleted, otherwise it is just a warning and the configuration file will be retained.

**Comment by garonsky** [comment]
Line removed.

@wangkx please review.

**Comment by wangkx** [comment]
Ok now.

**Comment by garonsky** [comment]
@richardkchapman commits have been squashed and this is ready to pull.

**Comment by richardkchapman** [comment]
I'm hesitating before merging this because it's marked as targetting 5.4.0 in Jira, but if I merge to master now it will end up in 6.0. I may need to create the candidate-5.4.0 branch now and ask you to rebase and retarget.

**Comment by garonsky** [comment]
No problem.  Let me know what you decide and I will rebase appropriately.

**Comment by richardkchapman** [comment]
I have created the candidate-5.4.0 branch

**Pull request closed without merging**
