### PR TITLE
HPCC-13498 Ability to export list to CSV

### PR DESCRIPTION
**Pull request by miguelvazq**
Give user ability to export selected list to CSV for documentation purposes since copy and paste is not a usable option in dgrid.

Signed-off by: Miguel Vazquez miguel.vazquez@lexisnexis.com

### CODE REVIEW

**Comment by miguelvazq** [comment]
@GordonSmith Please review.

**Comment by miguelvazq** [comment]
@richardkchapman Should we target this towards 6.2 since it is a new feature?

**Comment by richardkchapman** [comment]
Yes, I think 6.2 is more appropriate

**Comment by miguelvazq** [comment]
Moved to 6.2.0 https://github.com/hpcc-systems/HPCC-Platform/pull/8683

**Pull request closed without merging**
