### PR TITLE
HPCC-13354 Usage % expensive in production

### PR DESCRIPTION
**Pull request by miguelvazq**
Will remove usage % to a report based call instead at a later time.

Signed-off by: Miguel Vazquez miguel.vazquez@lexisnexis.com

### CODE REVIEW

**Comment by miguelvazq** [comment]
@wangkx FYI @jakesmith

**Comment by miguelvazq** [comment]
Minor fix. Will make.

**Comment by miguelvazq** [comment]
@wangkx change made.

**Comment by wangkx** [comment]
Looks good.

**Comment by miguelvazq** [comment]
@wangkx  I removed reference to WsDFU since we do no longer use it anywhere else in this file.

**Comment by wangkx** [comment]
That should be fine.

**Pull request closed without merging**
