### PR TITLE
HPCC-18744 Improve WebPack out of box experience

### PR DESCRIPTION
**Pull request by GordonSmith**
Ensure package.json is in sync with package-lock.json
Add package-lock.json to git
Add lib and build to gitignore
Fix all build warnings
Check node exists and version is 8 (current LTS)

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by GordonSmith** [comment]
@richardkchapman please review

**Comment by mckellyln** [comment]
@GordonSmith this fixes build, but still affects one file:

modified:   esp/src/package-lock.json

**Comment by GordonSmith** [comment]
@mckellyln yes - I have had some additional conversation with @richardkchapman and am going to force an out of source build.

**Comment by GordonSmith** [comment]
@richardkchapman / @mckellyln - I have updated this with an out of source build.  You may want to do a ```git  clean -fxd``` to remove any previous in source build.

**Comment by mckellyln** [comment]
builds ok and there are no file changes in source dir.
But there are two npm WARNs -

CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: hpccsystems-platform
CPack: - Install project: hpccsystems-platform
-- ECL Watch:  Rebuilding Site
---- Build Target: /home/<usrname>/lnrs/wip/build/esp/src/build
---- Output log:   /home/<usrname>/lnrs/wip/build/esp/src/eclwatch_build.txt
---- Creating out of source build environment
---- Installing third party libraries
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-NgSLv/TntH4TZkQxbJlmnqWukfE= integrity checksum failed when using sha1: wanted sha1-NgSLv/TntH4TZkQxbJlmnqWukfE= but got sha512-L3hKV5R/p5o81R7O02IGnwpDmkp6E982XhtbuwSe3O4qOtMMMtodicASA1Cny2U+aCXcNpml+m4dPsvsJ3jatg==. (2872 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
---- Clean previous build
---- Copy resources
---- Build website
CPack: Create package
CPack: - package: /home/<usrname>/lnrs/wip/build/hpccsystems-platform-community_6.5.0-trunk0xenial_amd64.deb generated.

**Comment by GordonSmith** [comment]
FWIW those two npm warnings are known and safe to ignore, I haven't investigated if it will be possible to get rid of them yet.  If they are just noise I can move them to a log file like I was doing with the old build system, but for now its probably better to have all warnings and errors out in the open while we nail down the quirks.

**Comment by mckellyln** [comment]
@GordonSmith ok then I am ok with this PR

**Pull request merged**
