### PR TITLE
HPCC-19085 Check and fix syntax error in //skip tag in Regression Suite

### PR DESCRIPTION
**Pull request by AttilaVamos**
Fix them

Signed-off-by: Attila Vamos <attila.vamos@gmail.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by AttilaVamos** [comment]
This Smoketest  session executes Regression Suite only on hthor to get a quick result and it seem ok. Rescheduled with full test. Give it ~ 25 minutes to finish.

**Comment by jakesmith** [comment]
@AttilaVamos - looks like skip is not working correctly.

These tests have e.g. : 
```
//skip type==thorlcr TBD
```

so shouldn't have run in Thor.

**Comment by AttilaVamos** [comment]
@jakesmith All right. It seems I should go back to square one. What  is the difference between thor and thorlcr. If there is any why we have only hthor, thor and roxie engine and why we haven't thorlcr? How should I and test engines handle this?

**Comment by jakesmith** [comment]
@AttilaVamos - There used to be 2 different version of Thor for a while with thorlcr being the new one, but there's only been thorlcr for quite some time.

//nothor and //nothorlcr are treated equally.
I assume before this PR //skip type==thor and //skip type==thorlcr were treated equally, since the latter weren't running but are now.

**Comment by jakesmith** [comment]
Slightly separate issue - but could combine in this PR:
It would be sensible to standardize on just 'thor' everywhere.
i.e. change all tests so that they only reference //nothor or //skip type==thor
and remove notion of 'thorlcr' from regression suite.

**Comment by AttilaVamos** [comment]
@jakesmith OK, before there was a partial match checking in //skip and that was wrong because 'thor' partially matched to 'hthor'. Now it uses exact match. I will raise a JIRA and fix it now.

**Comment by AttilaVamos** [comment]
https://track.hpccsystems.com/browse/HPCC-19094 raised.

**Comment by AttilaVamos** [comment]
@jakesmith I think I will raise another JIRA for this thor and thorlcr cleanup in Regression Suite and Regression Test Engine. I don't want to make any more mistake with a quick fix and cause myself and the others more headache. Moreover there are a couple of PR waiting in the Smoketest queue.

**Comment by jakesmith** [comment]
@AttilaVamos - fair enough.

**Comment by AttilaVamos** [comment]
Regression test cases are fixed in PR-10875. 
A JIRA: 'HPCC-19095 Replace 'thorlcr' reference with 'thor' in regression testing.' opened to standardize on just 'thor' everywhere.

**Pull request closed without merging**
