### PR TITLE
HPCC-15425 Improve the reported position for invalid string characters

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@shamser please review.  
Richard I'm not concerned if this slips to 6.0.2

**Comment by richardkchapman** [comment]
It will, unless Shamser can review it now...

**Comment by shamser** [comment]
@ghalliday @richardkchapman I'm reviewing this now

**Comment by shamser** [comment]
@ghalliday Just one minor: is it worth commoning up the error handling code within 1710-1850 into a function call?  The changes looks good.

**Comment by ghalliday** [comment]
@shamser I've commoned up some of the code, I'm not sure it is worth doing any more.

**Comment by richardkchapman** [comment]
Should probably retarget for 6.0.2

**Comment by shamser** [comment]
@ghalliday Reviewed..looks good.

**Pull request merged**
