### PR TITLE
HPCC-16990 Include pyembed in clienttools package

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

Built clienttools package on ubuntu 16.04 and insured the libpyembed library was present in the final package.  I will also be insuring this works on OSX.  

Needs to be further tested on Windows.  Passing it off from here to @xwang2713 for Windows clienttools testing.

### CODE REVIEW

**Review by xwang2713 — COMMENTED** [review]
Look good.  I will build and test on one type of Linux and Windows

**Comment by xwang2713** [comment]
I will make a private build to build it on Windows (clienttools build failed on 6.4.0) and Mac OSX

**Comment by xwang2713** [comment]
@Michael-Gardner I run eclcc with python-simple.ecl on Mac.  The compile is OK. But the generated binary links with libpyembed.dylib under lib instead of plugins.

**Comment by Michael-Gardner** [comment]
@xwang2713 I think using the @rpath is probably the best way to go to make sure that runtime dependent shared objects get found.  It will allow for the dylib to be under lib or plugins without causing an issue.

**Comment by Michael-Gardner** [comment]
@richardkchapman This also fixes the CMP0042 errors that are emitted at the end of calling cmake on OSX.

**Comment by richardkchapman** [comment]
@Michael-Gardner We may need to discuss what to do about python2 vs python3 clashes.

**Comment by Michael-Gardner** [comment]
@richardkchapman Definitely.  Going to look into this a bit tonight and tomorrow.   From what I can tell the 2.7 and 3.5 lib on my system have some of the same signatures, so even though the 3.5 libpython is linked to py3embed.so, it gets confused if I also have pyembed.so loaded on my Esp.

**Comment by richardkchapman** [comment]
I've made a few changes here and there to try to minimize the impact of the overlapping symbols but I'm not sure there is any way to do a complete safe fix. We may need to set up some means of selectively disabling one or the other from the plugin load process.

**Comment by richardkchapman** [comment]
If my changes in https://github.com/hpcc-systems/HPCC-Platform/pull/9697 get accepted, then I think this change should be fine - unless we also want to include python3 in client tools (which we could - it would be safe so long as people didn't try to use both in the same standalone local program)

**Comment by richardkchapman** [comment]
@xwang2713 Have the concerns about building on Windows been addressed?

**Comment by xwang2713** [comment]
For HPCC 6.4.0 Clienttools Windows build it needs fix of  HPCC-17160 do not define micro _LARGEFILE64_SOURCE on Windows #9655

**Comment by richardkchapman** [comment]
I have merged that now.

**Comment by Michael-Gardner** [comment]
@richardkchapman Ok I'll retest.

**Comment by richardkchapman** [comment]
@Michael-Gardner I think this is back with you

**Comment by Michael-Gardner** [comment]
@richardkchapman Have we made a decision on whether we want py3embed by default in the clienttools package?  If so I'll add it quickly.

**Comment by Michael-Gardner** [comment]
@richardkchapman retested.  Seems to work well.  A quick question about the behavior of ESP now that we've moved to using versions/python.  Before I used to see python2 or python3 being loaded in the esp.log.  Now I don't.  With your most recent changes, is this the expected behavior?

**Comment by richardkchapman** [comment]
Yes, I think that's expected. There is no need for ESP to load these plugins (indeed it's better if it doesn't) so I didn;t worry about adding versioned support to ESP

**Pull request merged**
