### PR TITLE
HPCC-13261 Ensure streaming graph inputs are evaluated globally

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman please review.  It has no effect on the regression suites in the HPCC directory.

In the private regression suite if changes a few.
It slightly increases the size (but may improve speed) of a couple of examples - O(0.1%), and drastically reduces the size of a couple (10.2Mb->820K, 70Mb->2.4Mb).

Could merge into 5.2.2 instead, but unlikely to cause harm in 5.0.14.

**Comment by richardkchapman** [comment]
Does it impact the correctness of code or just its size?

**Comment by ghalliday** [comment]
I think just the size - it looks like the streaming results are later evaluated globally, but too late for generating good code.

**Comment by richardkchapman** [comment]
I think 5.2.2 is probably more appropriate - technically both 5.0.14 and 5.2.2 are point releases that should contain only safe bug fixes, but 5.0.x is a more mature build than 5.2.2 and as such I'm more nervous about breaking it.

**Comment by richardkchapman** [comment]
@ghalliday What do you think?

**Comment by ghalliday** [comment]
Closing to retarget 5.2.2

**Pull request closed without merging**
