### PR TITLE
HPCC-27300 WsLogAccess expose select column mode

### PR DESCRIPTION
**Pull request by rpastrana**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [x] I have tested my changes in multiple modern browsers
  - [x] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by rpastrana** [comment]
Dependent on https://github.com/hpcc-systems/HPCC-Platform/pull/15846 and https://github.com/hpcc-systems/HPCC-Platform/pull/15837


[3d32177](https://github.com/hpcc-systems/HPCC-Platform/pull/15862/commits/3d32177480811a8d649dcb41fff6d351bc4fefb4)

**Comment by rpastrana** [comment]
@wangkx please review [3d32177](https://github.com/hpcc-systems/HPCC-Platform/pull/15862/commits/3d32177480811a8d649dcb41fff6d351bc4fefb4)

**Review by wangkx — COMMENTED** [review]
@rpastrana https://github.com/hpcc-systems/HPCC-Platform/commit/3c9c483430989e0b8e171263bdcddf4e5bb5fab7 looks fine.

**Comment by rpastrana** [comment]
> @rpastrana [3c9c483](https://github.com/hpcc-systems/HPCC-Platform/commit/3c9c483430989e0b8e171263bdcddf4e5bb5fab7) looks fine.

Thanks @wangkx please approve review.

**Comment by rpastrana** [comment]
@GordonSmith see changes in 3c9c483430989e0b8e171263bdcddf4e5bb5fab7

**Review by wangkx — APPROVED** [review]
@rpastrana https://github.com/hpcc-systems/HPCC-Platform/commit/3c9c483430989e0b8e171263bdcddf4e5bb5fab7 looks fine.

**Comment by rpastrana** [comment]
thanks @wangkx 
@richardkchapman this is dependent on https://github.com/hpcc-systems/HPCC-Platform/pull/15837 and not ready to merge yet

**Comment by rpastrana** [comment]
@richardkchapman ready for merge.

**Comment by rpastrana** [comment]
@richardkchapman please merge.

**Pull request merged**
