### PR TITLE
HPCC-15791 Add ECLWatchVisible to ConfigMgr

### PR DESCRIPTION
**Pull request by wangkx**
Signed-off-by: wangkx kevin.wang@lexisnexis.com

### CODE REVIEW

**Comment by wangkx** [comment]
@mckellyln please review

**Comment by mckellyln** [comment]
I approve
@AttilaVamos fyi

**Comment by AttilaVamos** [comment]
@wangkx  OK, I got it, back to you.

**Comment by wangkx** [comment]
@richardkchapman this PR is ready to be merged.

**Pull request merged**
