### PR TITLE
HPCC-29160 Fix oversized compressed write

### PR DESCRIPTION
**Pull request by jakesmith**
The compressed writer can write files larger than necessary, due
to a bug in flush().

flush() ensures all content is committed to disk.
In the case of CCompressedFile it 1st ensures it's on a new block
boundary (1MB), before it flushes unwritten content to disk.
Prior to this change, it also did this when nothing
had been written since the last flush, meaning it would unnecessarily
ensure it was on the next block boundary by back filling the gap
behind it.

The net result on a typical write that called flush before
collecting stats, then again on close() was that it unnecessarily
rounded the last incomplete block (1MB) and committed to disk.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
@ghalliday @shamser - have left it as 3 commits for now. The 1st is the fix, the 2nd and 3rd are tidying up confusing lack of virtual declarations and moving flush() which looked like a non-virtual and private from where it was declared, and reordering others, so more clearly reflects interfaces they are implementing.

**Review by shamser — APPROVED** [review]

**Review by ghalliday — APPROVED** [review]
@jakesmith please squash.
Is this the correct target version?  Would 8.12.x be better?  Was it a recent change that caused an extra flush().

**Comment by jakesmith** [comment]
@ghalliday - not a new issue afaik, same pattern in 8.12.x.
Squashed.

**Comment by jakesmith** [comment]
@schero02 - I doubt related to this PR. Does it succeed if the # of records is e.g. 50% of the size) ?
Can you please open a new platform JIRA and attach a ZAP report that includes the worker logs? Thanks.

**Pull request merged**
