### PR TITLE
H22921 Test - smoketests cores

### PR DESCRIPTION
**Pull request by wangkx**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by AttilaVamos** [comment]
@wangkx It seems there is a bug in the (new/relocated) Smoketest, that's why it can't give core trace.
I think here is the main problem:
```
Program terminated with signal 11, Segmentation fault.
#0  Release<CUsageCacheReader> (ptr=0x5e2d2b0) at /home/vamosax/smoketest/PR-13295/HPCC-Platform/esp/services/ws_machine/./../../../system/jlib/jscm.hpp:46
46      template <class X> inline void Release(X * ptr) { if (ptr) ptr->Release(); }
```

**Comment by wangkx** [comment]
Attila, thank you very much for the help.

**Comment by AttilaVamos** [comment]
@wangkx 
The problem to generated core in this case has unfortunately much less info:
```
Core was generated by `esp snmpid=22364'.                                       
Program terminated with signal 11, Segmentation fault.                          
#0  0x0000000000000021 in ?? ()        
```
However it seems it is definitely in clean-up phase.

**Comment by wangkx** [comment]
Thanks. I am testing another change now.

**Comment by AttilaVamos** [comment]
@wangkx Same, I am afraid not to helpful trace:
```
Program terminated with signal 11, Segmentation fault.                          
#0  0x00007f36fbbae828 in ?? ()  
```

**Comment by AttilaVamos** [comment]
@wangkx Well done!

**Comment by wangkx** [comment]
Attila, thank you for your help!

**Comment by wangkx** [comment]
I am closing this PR since the test is finished.

**Pull request closed without merging**
