### PR TITLE
HPCC-17269 Improve the code for CASE with a dense range of integer values

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [x] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

Ran full regression test and looked at differences to check they were correct.

### CODE REVIEW

**Comment by ghalliday** [comment]
I also ran a sample of the queries in the regression suite that changed to ensure the generated code was valid.

@shamser please review.
Some of the queries in testing/regress//ecl and ecl/regress are affected by the changed, so you can examine these to see the difference.

A reasonable number of the regression tests in the private suite are also improved - see fallen1, xyan1 and others for some more extreme effects.

**Review by shamser — COMMENTED** [review]
@ghalliday My main two comments are (1) should this be configurable?  For some ecl code it's possible that this change could cause a lot more memory to be used - in some cases, enough to impact performance (2) if there is a small number of items (say less than 4 or 5 items), there may not be any benefit to an array map.  Switch-case may be easier to read and possibly perform  better

**Comment by ghalliday** [comment]
(1) I doubt there are many cases where it will use much more memory.  You will be trading code like the following for each possibility:

compare reg, value
bne next
mov mappedValue, result
jmp done

with some static constants - possibly 4 constants in the worse case.  I expect the memory is likely to be smaller, or the same - less code more data.  The evaluation will be much faster (since it will only ever do 2 comparisons), and compilation will be faster.

**Review by shamser — APPROVED** [review]
@richardkchapman Code reviewed ok

**Comment by ghalliday** [comment]
(2) yes a lower limit would probably make sense - although it it is probably more efficient to do this even for 3 items.

**Pull request merged**
