### PR TITLE
HPCC-13488 ps -ef will reveal passwords

### PR DESCRIPTION
**Pull request by AttilaVamos**
Add prompt for password if only the username presented in command line

Signed-off-by: Attila Vamos attila.vamos@gmail.com

### CODE REVIEW

**Comment by AttilaVamos** [comment]
@afishbeck please review.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by richardkchapman** [comment]
5.0.6 was closed a long time ago. This needs to target 5.2.4 or later

**Comment by AttilaVamos** [comment]
Close and re-target to 5.2.4

**Pull request closed without merging**
