### PR TITLE
HPCC-15475 Fix Regression in Clienttools package regarding ecllib files

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner Michael.Gardner@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 Can you run a quick windows build of clienttools using this branch for testing?  Lets pass it to Dan if it works so we make sure it's everything he needs also?

**Comment by xwang2713** [comment]
Building now

**Comment by xwang2713** [comment]
@dcamper  Don, could you try this clienttools on Windows to see if it fixes the problem : http://10.176.32.10/builds/custom/JIRA/15475/hpccsystems-clienttools-community_6.0.0-rc3Windows-i386.exe

@rpastrana

**Comment by dcamper** [comment]
@xwang2713 That seems to have done the trick. I can also verify the Mac OS X client tools, if you're inclined to build those for testing (I do some work in Eclipse, which needs the native client tools, so I'm interested in getting a prerelease).  Thanks!

**Comment by Michael-Gardner** [comment]
Good to hear!  Thanks for catching the issue Dan.

**Comment by Michael-Gardner** [comment]
@richardkchapman ready for you to look at.

**Pull request merged**
