### PR TITLE
HPCC-13390 Return persist/superowners in WsDfu.DFUQuery

### PR DESCRIPTION
**Pull request by wangkx**
Both persist and superowners are added into the file
information for ESP Browse Logical Files. ECLWatch
UI may need to display those two columns.

Signed-off-by: wangkx kevin.wang@lexisnexis.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@jakesmith Please review - in particular are there any efficiency concerns fetching this information (if so we may need to make it optional so only fetched if the UI is going to display it?)

Is there a separate JIRA or PR for the UI side of this?

**Comment by wangkx** [comment]
The 'https://track.hpccsystems.com/browse/HPCC-13259' is for UI.

**Comment by jakesmith** [comment]
Code looks fine, but I am also concerned about the bloat in serialized info when not needed.
This routine is expensive already when there are a lot of files and a request to iterate (and serialize) and lot of files is requested (as it often is in Prod systems).
So I think this additional meta info should be made optional, default off.

@wangkx

**Comment by wangkx** [comment]
@jakesmith the code has been modified to make the return of superowners optional. Please review.

**Comment by jakesmith** [comment]
Apart from trivial comment, looks good.

**Comment by wangkx** [comment]
@richardkchapman I just fixed the fixed brace formatting based on Jake's last comment. This PR is ready to be merged.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success

**Pull request merged**
