### PR TITLE
HPCC-22426 Define HAS_EFFICIENT_CAS for gcc 7.1+ and clang

### PR DESCRIPTION
**Pull request by mckellyln**
Signed-off-by: Mark Kelly <mark.kelly@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [x] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Smoke test - but this isn't enough as it will probably still use the previous inefficient cas.
Will try to use clang to build and then run regression

### CODE REVIEW

**Comment by mckellyln** [comment]
I tried building on linux with clang to test this with regression suite, but there is a build error.

**Comment by richardkchapman** [comment]
@ghalliday You happy to merge this?

**Comment by mckellyln** [comment]
With clang/clang++ build thor regression passes, except for one case:
```
    -------------------------------------------------
    Result:
    Passing: 767
    Failure: 1
    -------------------------------------------------
    Error:
    702. Test: teststdlibrary.ecl
    --- teststdlibrary.xml
    +++ teststdlibrary.xml
    @@ -1,3 +1,5 @@
    +<Exception><Code>100000</Code><Filename>TestDate.ecl</Filename><Line>196</Line><Source>user</Source><Message>Assert (675350301 = 19990301) failed [AdjustDate(20000229, -1, 0, 0) = 19990301]</Message></Exception>
    +<Exception><Code>100000</Code><Filename>TestDate.ecl</Filename><Line>196</Line><Source>user</Source><Message>Assert (675350301 = 19990301) failed [AdjustDate(20000229, -1, 0, 0) = 19990301]</Message></Exception>
     <Dataset name='Result 1'>
      <Row><day>1000001</day><gregorian><year>2738</year><month>11</month><day>29</day></gregorian><julian><year>2738</year><month>11</month><day>8</day></julian></Row>
     </Dataset>
```
which do not think is related to this change.

**Comment by mckellyln** [comment]
Just updated to align indentation.

**Pull request merged**
