### PR TITLE
HPCC-13453 Don't include hidden form field "itemcount" as query xml

### PR DESCRIPTION
**Pull request by afishbeck**
Signed-off-by: Anthony Fishbeck anthony.fishbeck@lexisnexis.com

### CODE REVIEW

**Comment by afishbeck** [comment]
Note that gen_form_wsecl.js is just a slightly modified copy of gen_form.js.  But it isolates this change, and it will be beneficial to keep it isolated as ws_ecl really doesn't behave quite the same as regular ESP forms.

**Comment by afishbeck** [comment]
This was a regression in 5.0 caused by the optimizations that avoid loading the query schemas from the workunit unless absolutely necessary.

**Comment by AttilaVamos** [comment]
Automated Smoketest Number of Error(s): 2Error(s): 2TERM environment variable not set.

**Comment by richardkchapman** [comment]
@wangkx Please review

**Comment by richardkchapman** [comment]
I'm more inclined to merge this to 5.2.2 than 5.0.14 (which is now ready to go gold)

**Comment by wangkx** [comment]
Apart from 2 comments, looks good.

**Comment by afishbeck** [comment]
closing and re-targeting 5.2.2

**Pull request closed without merging**
