### PR TITLE
HPCC-15358 Enable spray path field for despray

### PR DESCRIPTION
**Pull request by miguelvazq**
Enable the path field to allow a user to enter directories.

Signed-off by: Miguel Vazquez miguel.vazquez@lexisnexis.com

### CODE REVIEW

**Comment by miguelvazq** [comment]
@GordonSmith Please review.

**Comment by miguelvazq** [comment]
FYI @AttilaVamos

**Comment by AttilaVamos** [comment]
@miguelvazq Thanks!

**Comment by GordonSmith** [comment]
Looks Good.

**Pull request merged**
