### PR TITLE
HPCC-13713 daftformat.cpp Inverted Code For XML Splitter Header Length Calculation

### PR DESCRIPTION
**Pull request by AttilaVamos**
Remove dead code.

Signed-off-by: Attila Vamos attila.vamos@gmail.com

### CODE REVIEW

**Comment by AttilaVamos** [comment]
@richardkchapman please review and merge.

**Comment by richardkchapman** [comment]
I don't really understand this code.... I can see that this change won't have any affect on the behaviour (as it only removes dead code) but it would be good to understand the existing code enough to be sure that it is pertating correctly - and in particular that it should not have the return rather than the break.

@AttilaVamos did you analyse the behaviour? @ghalliday Do you understand this code?

**Comment by ghalliday** [comment]
Added to issue:
"I have checked back, and it looks like the change r16780 (12 years ago) inadvertently left that line in. (The return was unconditional, but became conditional).
Correct fix is to deleted it."

**Comment by ghalliday** [comment]
@AttilaVamos I think the commit message needs to be changed to 
HPCC-13712 Remove redundant code.
Otherwise the entry in the change log will be very confusing.

**Comment by richardkchapman** [comment]
Merged manually to correct the commit message

**Pull request closed without merging**
