### PR TITLE
HPCC-13072 Edit SOAPCALL examples in Prog Guide

### PR DESCRIPTION
**Pull request by JamesDeFabia**
Signed-off-by: Jim DeFabia jamesdefabia@lexisnexis.com
@lorraineachapman Please review

### CODE REVIEW

**Comment by richardkchapman** [comment]
@afishbeck Can you explain WHY the cluster type "roxie" is expected here and not the cluster's name? What happens if you have two clusters myroxie1 and myroxie2 each with a query called X on - how do you indicate which to hit?

**Comment by afishbeck** [comment]
It's not the cluster type, it's the target.  "myroxie" is typically used to indicate the process cluster.  "roxie" the target.  But perhaps something like "roxie1" would be a better example.

**Comment by JamesDeFabia** [comment]
A system created by a wizard (or the default environment.xml) creates a Target named roxie of a type = roxie running under the process myroxie.

**Comment by richardkchapman** [comment]
Ok, that makes sense (I think).

**Pull request merged**
