### PR TITLE
HPCC-12947 Support for new Metaphone 3

### PR DESCRIPTION
**Pull request by richardkchapman**
Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
Note that the source for metaphone3 is not redistributable - this is a binary-only plugin included in EE. See the corresponding PR in the LN repo.

**Comment by ghalliday** [comment]
@richardkchapman 
What should our policy be for test files/ecl library support for features not included in the main platform?

The tests/library code needs to be with the implementation code - otherwise running the standard library tests on the open system will fail because plugins are not available.

**Comment by richardkchapman** [comment]
At the moment the tests are not run automatically anyway so the question is moot.

Once we DO start running tests automatically, I think we should be doing so on an EE system. I think it's ok for tests to fail if the system they are run against do not support them (same as they do if you try to run the regression suite tests for embedded R support on a system that was built without it...)

**Comment by ghalliday** [comment]
I think teststdlibrary.ecl in the regression suite does currently run it...  The problem in this case is that it will stop all standard library tests, not just the metaphone test.

**Comment by richardkchapman** [comment]
I don't mind deleting the test...

Is there a way to check (at compile time, or indeed runtime) whether you are running EE ?

**Pull request merged**
