### PR TITLE
HPCC-15057  Use default CMAKE_<LANG>_COMPILER_VERSION 

### PR DESCRIPTION
**Pull request by xwang2713**
Use default CMAKE_C_COMPILER_VERSION and CMAKE_CXX_COMPILER_VERSION it they have correct version information. Otherwise run `<compiler> -dumpversion`.  
On Ubuntu both these variables return expected version format, i.e. <major>.<minor>.<point>.

Signed-off-by: Xiaoming Wang xiaoming.wang@lexisnexi.com 

@AttilaVamos please help to review it.

### CODE REVIEW

**Comment by AttilaVamos** [comment]
Unfortunately this changes pick up the default, more precisely the version of the  compiler installed at the first run. If the compiler updated between two runs (and the environment didn't swipe) then its pick up the version of the old compiler instead of the new one.

**Comment by xwang2713** [comment]
It requires re-run cmake if any environment change anyway. Even we use "gxx --version" it run at top level cmake configuration.

**Comment by AttilaVamos** [comment]
So, the cache (`<build_dir>/CMakeCache.txt`) doesn't contains any C/CXX compiler version related information:

> grep -i 'cxx' CMakeCache.txt 
> //Choose the type of build, options are: None(CMAKE_CXX_FLAGS or
> //CXX compiler.
> CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++
> CMAKE_CXX_FLAGS:STRING=
> CMAKE_CXX_FLAGS_DEBUG:STRING=-g
> CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG
> CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG
> CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
> //ADVANCED property for variable: CMAKE_CXX_FLAGS
> CMAKE_CXX_FLAGS-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_CXX_FLAGS_DEBUG
> CMAKE_CXX_FLAGS_DEBUG-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_CXX_FLAGS_MINSIZEREL
> CMAKE_CXX_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_CXX_FLAGS_RELEASE
> CMAKE_CXX_FLAGS_RELEASE-ADVANCED:INTERNAL=1
> //ADVANCED property for variable: CMAKE_CXX_FLAGS_RELWITHDEBINFO
> CMAKE_CXX_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1

All compilers relater information stored in `<build_dir>/CMakeFiles/<CMake_version>/` directory.
In CMakeCCompiler.cmake 
> set(CMAKE_C_COMPILER_VERSION "4.8.2")

and CMakeCXXCompiler.cmake file

> set(CMAKE_CXX_COMPILER_VERSION "4.8.2")

It seems to delete cache file doesn't force to rebuild those two compiler related files.

**Comment by stuartort** [comment]
@Michael-Gardner can you review this

**Comment by Michael-Gardner** [comment]
Works well.  Attila you're going to have to clean out the build directory and re-run the cmake command in order to get it to update the CMAKE_C_COMPILER_VERSION.  It's a cmake anti-pattern to run cmake twice in a row, and can lead to undefined behavior.

**Pull request merged**
