### PR TITLE
HPCC-17840 Normalize data for stats chart 

### PR DESCRIPTION
**Pull request by GordonSmith**
## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [x] I have tested my changes in multiple modern browsers
  - [x] The component(s) render as expected

### CODE REVIEW

**Comment by GordonSmith** [comment]
@miguelvazq please review (acutal commit:  https://github.com/hpcc-systems/HPCC-Platform/pull/11649/commits/9b987ba07346995b35374d9fbf3dbb881ffed8f2)

Will need rebase once https://github.com/hpcc-systems/HPCC-Platform/pull/11631 is pulled

**Comment by GordonSmith** [comment]
Resolved errors and rebased, still needs rebase once #11631 is pulled

**Comment by richardkchapman** [comment]
@GordonSmith Needs another rebase

**Comment by GordonSmith** [comment]
I will rebase once #11631 is pulled.

**Comment by richardkchapman** [comment]
@GordonSmith It has been pulled

**Comment by GordonSmith** [comment]
@richardkchapman rebased - can you leave the smoketest re-run before pulling?

**Review by miguelvazq — APPROVED** [review]

**Comment by GordonSmith** [comment]
@AttilaVamos Can we re-run the smoke test here?- thx.

**Comment by AttilaVamos** [comment]
@GordonSmith it is in the queue.

**Comment by AttilaVamos** [comment]
@GordonSmith The https://github.com/hpcc-systems/HPCC-Platform/pull/11621 generated huge amount of errors and stacked. Actually your PR is on its way, result is in <15 minutes.

**Pull request merged**
