### PR TITLE
HPCC-14461 Fix SEH in PARSE on empty computed string

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman please review (compare ignoring whitespace)

**Comment by richardkchapman** [comment]
I'm concerned about the regression test. It would be better to add a new case to the existing parse regression test rather than creating a new test that is named after the Jira issue, I think.

**Comment by richardkchapman** [comment]
@ghalliday One question

**Comment by ghalliday** [comment]
@richardkchapman There are multiple existing parse regression tests (30+), how do we select which one to add it to?  Should they all be combined into a single test?

In this case the test case came from a user, so keeping it separate might make sense.

I agree the issue name isn't a great name, but it isn't too bad as a regression test name.  I could rename this as parseboundary.ecl to indicate that it is testing some kind of boundary condition.

Open to any suggestions - we could discuss more generally how we would like the tests structured.

**Comment by richardkchapman** [comment]
Why are there 30+ regression tests for parse?

I don't think that the fact that the test came from a user is relevant - indeed, I'm not sure we should be preserving the original user's code in our test suite (it was not provided to us as a code contribution...)

A topic to discuss next meeting

**Pull request closed without merging**
