### PR TITLE
HPCC-15357 ConfigMgr - Topology Cluster should include alias attribute

### PR DESCRIPTION
**Pull request by garonsky**
Signed-off-by: Gleb Aronsky gleb.aronsky@lexisnexis.com

### CODE REVIEW

**Comment by garonsky** [comment]
@JamesDeFabia please review

**Comment by JamesDeFabia** [comment]
@garonsky Looks good to me (I reviewed an implementation of the code, not the code itself)

**Comment by richardkchapman** [comment]
Do we need a similar change in LN repo?

**Comment by garonsky** [comment]
Yes.  https://track.hpccsystems.com/browse/HPCC-15427

**Pull request merged**
