### PR TITLE
HPCC-13452 - New ECLWatch unable to display WU's

### PR DESCRIPTION
**Pull request by miguelvazq**
Moving trim and uppercase fix into html template.

Signed-off by: Miguel Vazquez miguel.vazquez@lexisnexis.com

### CODE REVIEW

**Comment by miguelvazq** [comment]
@GordonSmith The getFilter() call is being used to populate grid which caused an issue with the string transformation. I have moved the logic into the template (html) which is where we are doing most of trims already as well. Please review.

FYI @cloLN

**Comment by GordonSmith** [comment]
Looks good.

**Comment by richardkchapman** [comment]
There was a similar change in 5.0.14 (this was upmerged from it) - is that also causing problems, or is it just my hamfisted upmerge that is broken?

**Comment by GordonSmith** [comment]
Neither - the 5.0.14 was the quick fix, this one is slightly cleaner...

**Comment by richardkchapman** [comment]
"slightly cleaner" and "unable to display workunits" are not quite the same thing...

**Comment by GordonSmith** [comment]
Looked again - it was your upmerge that caused the issue - you had the casing wrong for the retVal. on the lhs.

**Comment by richardkchapman** [comment]
Ok, good (at least that means 5.0.14 should be ok).

**Pull request merged**
