### PR TITLE
HPCC-14168 Include who aborted a WU

### PR DESCRIPTION
**Pull request by miguelvazq**
Include who aborted a work unit on the work unit details page.

Signed-off by: Miguel Vazquez miguel.vazquez@lexisnexis.com

### CODE REVIEW

**Comment by miguelvazq** [comment]
@GordonSmith Please review.

**Comment by miguelvazq** [comment]
@g-pan Do you document this?

**Comment by richardkchapman** [comment]
Given that this requires new translations, I think it needs to target 6.2

@GordonSmith do you concur?

**Comment by GordonSmith** [comment]
6.2 - yes

**Comment by miguelvazq** [comment]
Will re-target

**Comment by miguelvazq** [comment]
Retargeted https://github.com/hpcc-systems/HPCC-Platform/pull/8734

**Pull request closed without merging**
