### PR TITLE
Document how to export data from bare metal to cloud systems

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman, what do you think of this?  I'm tempted to publish all blogs as documents in this directory - but if so they probably need a bit more organisation.

**Comment by richardkchapman** [comment]
The contents is fine - but is it really "dev docs" as opposed to end-user documentation? and to what extend does it overlap with what will eventually become chapters in the documentation? 

@JamesDeFabia What are your thoughts?

**Comment by ghalliday** [comment]
@jakesmith the smoketest failure is similar to some of the others we have seen.  It definitely isn't down to the contents of the PR!

**Comment by jakesmith** [comment]
> the smoketest failure is similar to some of the others we have seen. It definitely isn't down to the contents of the PR!

@ghalliday - looks like all tests pass now, not sure what the issue was now, or if I looked at it(?). There was an issue in the smoketest action relating to the cache that was fixed perhaps it was that, and there were some improvements to capture info. sfrom stalls (gracefully terminate regression suite, capture stacks and zaps).

**Comment by ghalliday** [comment]
@JamesDeFabia closing.  This has been published as a blog, and the information should probably be included in our documentation.  We are also likely to support directly reading from a bare metal system - which may prove simpler for some setups.

**Pull request closed without merging**
