### PR TITLE
HPCC-12456 Fix docs for Std.Date.ToGregorianYMD

### PR DESCRIPTION
**Pull request by JamesDeFabia**
Signed-off-by: Jim DeFabia jamesdefabia@lexisnexis.com
@dcamper Please review

### CODE REVIEW

**Comment by dcamper** [comment]
Recommend changing "It returns three separate values: Year, or Month, or Day." to "It returns a module with three exported values:  Year, Month, and Day."

Revised sample code to highlight the returned module:

```
IMPORT STD;
INTEGER2  MyYear  := 2012;
UNSIGNED1 MyMonth := 1;
UNSIGNED1 MyDay   := 1;

J := STD.Date.FromGregorianYMD(MyYear,MyMonth,MyDay);
    // J contains 734503

X := STD.Date.ToGregorianYMD(J);
    // X is a module with exported values

Y := X.Year;   //Y contains 2012
M := X.Month;  //M contains 1
D := X.Day;    //D contains 1
```

**Comment by richardkchapman** [comment]
@JamesDeFabia back to you

**Comment by JamesDeFabia** [comment]
@dcamper Edits made, have another look, please

**Comment by dcamper** [comment]
Looks great now, thanks.

**Pull request merged**
