### PR TITLE
HPCC-21403 Wrap Std.Date.FromStringToSeconds() in a compile-time version check

### PR DESCRIPTION
**Pull request by dcamper**
Trailing whitespace in a few other places has also been removed.

Signed-off-by: Dan S. Camper <dan.camper@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Manual tests with code supplied in the associated Jira and other code.

### CODE REVIEW

**Comment by richardkchapman** [comment]
Couple of general comments:

1. The PlatformVersionCheck function should probably live in a different Std module (not sure which - maybe Std.System.Util)
2. Feels like this may just swap one obscure error message for another. The #if will be compiled differently at syntax-check/archive creation time from workunit creation time, and is still going to come out as 'Unknown identifier' rather than 'Server version too old'. I don't know if it's possible to put in a #else that will give a more helpful message? 

@ghalliday Any thoughts?

**Comment by dcamper** [comment]
I like the idea of moving PlatformVersionCheck to Std.System.Util, and marking it as EXPORT.  There have been some similar recent problems that are causing our internal dev teams to explicitly reference a particular client tools version to work around the issue.  I suspect that using PlatformVersionCheck would solve that as well.  I will move the function.

I think the problem with "obscure message" is really just a documentation issue.  If Std.Date. FromStringToSeconds() is documented as first appearing in 7.2.0 -- which it is not as of this writing -- then the developer should be aware that both client tools and the cluster must both be at 7.2.0 or later.  With the documentation in place, the error that would appear ("FromStringToSeconds cannot be found in Std.Date" or whatever it is) will make sense at both syntax check and WU creation.

Without wrapping this function in a version check, the developer can get tripped up by this error when trying to use any Std.Date function in a mismatched client tools/cluster setup.  The error in that case is very confusing, as it references something that the developer wasn't even trying to use.  This scenario can occur easily:  The cluster is pre-7.2.0 and the developer upgrades their client tools.

Interested in hearing alternate points of view.

**Comment by richardkchapman** [comment]
Worth thinking about the different cases:

Adding a new function 
Adding a new parameter
Removing a function
Using new ECL functionality

Both for plugins and for the standard ECL library. Isn't there some rule saying we use the remove version of the plugin/std library ECL even though the local version has been embedded in the archive?

**Comment by ghalliday** [comment]
I have created a jira to document the new function in Std.Util

**Comment by ghalliday** [comment]
Yes - that means that code with old standard libraries will still work on new systems.  This is different - it allows new functions to work on old systems.  I think to work it would mean that any changes have to be wrapped in version checks.
I merged the change, but on reflection I'm not sure we want to support backward compatibility this way in general.

**Pull request merged**
