### PR TITLE
HPCC-13232 Correct recursive threadchain creation

### PR DESCRIPTION
**Pull request by richardkchapman**
Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by ghalliday** [comment]
Fix looks good.  @cloLN can you test?

**Comment by cloLN** [comment]
Sure.  I'll post back when I've gotten it built and tested.

**Comment by cloLN** [comment]
Ran the redissync test after building.  No roxie restarts or cores.  Looks good.

**Comment by jamienoss** [comment]
@cloLN Excellent! I'll add this to the memcached code also.
@ghalliday please merge.

**Pull request merged**
