### PR TITLE
HPCC-20849 Change a couple of edge case uses of /d$ to correct defaults

### PR DESCRIPTION
**Pull request by jakesmith**
1) In Thor slave startup, if useMirrorMounts was configured and
if "mirror" definition from <Directories> in environment was missing,
it was defaulting to d$ when should have defaulted to std. defaults.

2) In Roxie start startup, when getting primary/secondary disk space
stats. for logging, it was hardcoded to /c$ and /d$, change to use
std. default directories.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by jakesmith** [comment]
@richardkchapman - please review

**Comment by richardkchapman** [comment]
Should this target 7.0.2 ? 7.2.0 ?

**Comment by jakesmith** [comment]
I left it targeting master, so for 7.2, but not really sure with these kind of minor fixes.
It doesn't need to go in next point build, but could do.

**Comment by richardkchapman** [comment]
There is a 7.2.0 branch for targetting 7.2

**Comment by richardkchapman** [comment]
But in this instance I would have thought 7.0.2 was appropriate

**Comment by jakesmith** [comment]
@richardkchapman - retargeted to 7.0.2

**Pull request merged**
