### PR TITLE
HPCC-13297 Replace '-' with '~' for rc build on DEB systems

### PR DESCRIPTION
**Pull request by xwang2713**
This will help deb system to correctly compare the different versions. i.e.
final release version should be greater than rc builds.

@Michael-Gardner please help to review

Signed-off-by: Xiaoming Wang xiaoming.wang@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
Looks good @xwang2713

**Comment by richardkchapman** [comment]
There's a similar (or worse) issue in RPM - this feels like a bit of a hack to me fixing a symptom rather than the real cause (does dpkg really get the version info out of the filename rather than out of the variables in the deb file?)

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by xwang2713** [comment]
I am modifying the code to make it consistent: make "~" for all rc builds. I am testing the builds now.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by richardkchapman** [comment]
If the package version comparison is based on the CPACK variables, then you could leave the filename unchanged and just leave in the change that sets 

    SET(CPACK_PACKAGE_VERSION_PATCH ${point}${VER_SEPARATOR}${stagever})

correct?

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by xwang2713** [comment]
Right. I will make the change and do a brief test.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Pull request merged**
