### PR TITLE
HPCC-23730 Bump std.DataPatterns to v1.6.3

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by GordonSmith** [comment]
@dcamper please review

**Review by dcamper — APPROVED** [review]
Looks good.

**Comment by GordonSmith** [comment]
@dcamper the unit tests failed on hthor - is this expected (FWIW the same is true in the DataPatterns Bundle)

**Comment by dcamper** [comment]
Not expected, and I was unaware of that issue.  I will investigate.

**Comment by AttilaVamos** [comment]
@dcamper  This teststdlibrary contains a lots of different kind of subtests. I think it would be nice to split it into separated parts. I can see at least two advantages of it:
1. Its independent parts can be executed parallel and it will decrease the testing time
2. Part which can't run in a particular engine can exclude without excluding the whole collection.

**Comment by GordonSmith** [comment]
@dcamper FWIW @ghalliday is having a look as well...

**Comment by dcamper** [comment]
@GordonSmith @ghalliday I've been unable to determine the cause of the "System error: 99: Graph Result 1 accessed before it is created" error nor can I find an ECL-based workaround.  The code does succeed on both Thor and ROXIE however, which leads me to believe that hthor is handling EVALUATE(<module>) differently.  Gavin, do you want me to open a Jira for this issue?

**Comment by dcamper** [comment]
@AttilaVamos Could splitting up the testing be accomplished by just mirroring the contents of ecllibrary/teststd/ into the regression test code?  Basically, it appears to already be split up, but it is combined via a single call within the regression test code.

Also, I believe that most (if not all) Std library code should be able to be executed on all engines.  Maybe that is incorrect, but it sounds like a good idea anyway.

**Comment by ghalliday** [comment]
@dcamper - I have released a fix for the problem - https://github.com/hpcc-systems/HPCC-Platform/pull/13528

**Comment by dcamper** [comment]
Thanks, Gavin!

@GordonSmith Once #13528 is merged this PR should be triggered for another smoke test.  It should pass at that point and be good to go.

**Comment by GordonSmith** [comment]
@richardkchapman this can be pulled I think?

**Comment by GordonSmith** [comment]
(closed and reopened to trigger new build)

**Pull request merged**
