### PR TITLE
HPCC-29804 Fix for old helm version not liking lazy evaluation

### PR DESCRIPTION
**Pull request by jakesmith**
HPCC-29743 changes used lazy evalation expressions with hasKey. Older version of helm did not like this and produced errors. Fix by expanding the expressions into separate if statements.

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Review by rpastrana — APPROVED** [review]
Approved

**Review by ghalliday — COMMENTED** [review]
Looks reasonable, but there are a couple more places:

addPrometheusScrapeAnnotations in _helpers.tpl x2
network.yaml(~167)

**Comment by jakesmith** [comment]
> Looks reasonable, but there are a couple more places:
> 
> addPrometheusScrapeAnnotations in _helpers.tpl x2 network.yaml(~167)

Yes, talked to @rpastrana about this and left as is deliberately for now, because this PR change was a recent 9.0 regression, that affects many/vanilla installations, and I wasn't 100% sure the Prometheus one was in an issue in practice.
I think @rpastrana was going to check and open a separate JIRA to address if it was,
but I could go ahead and change at this juncture anyway.. (?)

**Comment by rpastrana** [comment]
@ghalliday the other instances @jakesmith pointed out aren't affecting us in practice, and we decided not to tackle in this issue in order to expedite this fix for the default values scenario (code changes are trivial, but proper testing coverage would take some time).

Went ahead and wrote up an issue to avoid compound conditionals in helm template logic:
https://track.hpccsystems.com/browse/HPCC-29820

**Review by ghalliday — APPROVED** [review]

**Pull request merged**
