### PR TITLE
HPCC-13635 Update Viz Framework to v1.0.2

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes HPCC-13635

Signed-off-by: Gordon Smith gordon.smith@lexisnexis.com

### CODE REVIEW

**Comment by GordonSmith** [comment]
@miguelvazq Please Review (and test).

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by miguelvazq** [comment]
Built OK and the graphs seem to load with no issues. I do however get a console.log('Invalid value for 'shape': rect) in the developer tools.

**Comment by GordonSmith** [comment]
I saw that and its ok to ignore.

**Comment by miguelvazq** [comment]
Looks good otherwise.

**Pull request merged**
