### PR TITLE
HPCC-25867 Add metrics tag to metrics log entries

### PR DESCRIPTION
**Pull request by kenrowland**
Added 'METRICS:' tag to metrics log entries

Signed-off-by: Ken Rowland <kenneth.rowland@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [x] Performance
  - [x] Security
  - [x] Thread-safety
  - [x] Cloud-compatibility
  - [x] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Review by ghalliday — APPROVED** [review]
I am fine with the change as long as @rpastrana is.

**Review by rpastrana — APPROVED** [review]
@kenrowland I'm ok with this change for the short-term. Eventually we'll want to utilize the "class" column (MSGCLS_metric) to distinguish metric log entries.

**Comment by richardkchapman** [comment]
Is there a reason the change Rodrigo suggests can't be made now?

**Comment by kenrowland** [comment]
If the desire is to use the class output option where MSGCLS_metric adds "cls=MET ", then this PR is not needed. I have seen somewhere, but cannot remember where, that ability to add the class output options. 

@rpastrana - if this is preferred, please indicate such and the PR can be abandoned.

**Comment by rpastrana** [comment]
@ghalliday I think this change is fine.
Yes, the alternative is to add the class field by default in containerized mode (we would presumably no longer need the prefix embedded in the message), but as you point out, that would potentially break pre-existing  bare-metal processes.

**Comment by richardkchapman** [comment]
@rpastrana It would not break existing bare-metal processes if the change was in containerized mode only?

I guess my question is, if now is not the right time to make that change, when will be?

**Comment by ghalliday** [comment]
@richardkchapman this may also tie in with a discussion of costs that I was having with Jake and Shamser.  It might be better to hold off on this change and add the class to the container (and non container) logging for 8.2.

**Comment by rpastrana** [comment]
Agreed, this is a good time to make the change.
We can add MSGFIELD_class and remove MSGFIELD_prefix from the MSGFIELD_STANDARD  definition in code:
https://github.com/hpcc-systems/HPCC-Platform/blob/7c6452e741a6e758a2ea5c16b2ddf08dd4f86aae/system/jlib/jlog.hpp#L313

Users can always override those defaults via config: --set global.logging.fields="STD+CLS"

**Pull request closed without merging**
