### PR TITLE
Cmake required version updated to 3.3.2

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner michael.gardner@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 please review
@richardkchapman modifies the cmake required version so the issue Attila had this morning won't happen again.

**Comment by xwang2713** [comment]
Looks good. All our build systems are in 3.4.x or 3.5.x

**Comment by richardkchapman** [comment]
My cmake is 3.2.2 on osx... 

Is 3.3.2 really the minimum version required?

**Comment by richardkchapman** [comment]
(and on my Ubuntu 14.04 box it's 2.8.12 ...)

**Comment by Michael-Gardner** [comment]
3.3.2 is the version I've found as a minimum to work on all platforms we support.  If you use anything lower than 3.3 for centos you should run into more packaging issues with the @ symbol in the systemd service files.  You certainly can get away with a lower version on ubuntu and osx though.

**Comment by richardkchapman** [comment]
Not if I merge this change I can't ...

**Comment by Michael-Gardner** [comment]
I'll see about making it conditional on the platform we're running on so you won't have to update for osx.

**Comment by richardkchapman** [comment]
I have updated osx - not a big deal there. It's old LTS Ubuntu systems that concern me more...

**Comment by Michael-Gardner** [comment]
Older LTS like 12.04 have been required to use a version of cmake that isn't provided by the package manager for some time now.  14.04 does come with 2.8.12 in the package manager, and it does look like we can build with that just fine (tested on a 14.04 VM.)

I modified the code to conditionally require different min versions depending on the OS we're building on. @xwang2713 please take another quick look.

**Comment by xwang2713** [comment]
For old Ubuntu and CentOS users need download cmake and run config(libcurl support)/make/make install.  The default cmake on these systems will not work.

**Comment by richardkchapman** [comment]
@Michael-Gardner The modification you mention does not appear to have been pushed...

**Comment by richardkchapman** [comment]
@Michael-Gardner Was there a JIRA ticket for this change?

**Comment by Michael-Gardner** [comment]
@richardkchapman negative, was raised on flowdock by Attila and I took the opportunity to fix it so no one else would have the same problem.  Want me to create a Jira and tie it to this PR?

**Comment by richardkchapman** [comment]
Yes please

**Comment by richardkchapman** [comment]
(or use the oneI just raised against LN repo not having this change...)

**Pull request merged**
