### PR TITLE
HPCC-13622 Add //class=embedded tag to all embedded/plug-in test cases to easy exclusion

### PR DESCRIPTION
**Pull request by AttilaVamos**
Add tag (and banner if missing)

Signed-off-by: Attila Vamos attila.vamos@gmail.com

### CODE REVIEW

**Comment by AttilaVamos** [comment]
@richardkchapman please check the list of changed test cases is correct. 
The
 - cassandra-simple.ecl
 - embedR.ecl
 - mysqlembed.ecl
already has a tag.
My aim is to reach clean regression test result when no 3rd party module installed. It is possible some test should run in an out of box system, and then I will remove tag from that.

**Comment by richardkchapman** [comment]
$ grep -i -c EMBED testing/regress/ecl/*.ecl | grep -v :0
testing/regress/ecl/cassandra-simple.ecl:48
testing/regress/ecl/embedR.ecl:35
testing/regress/ecl/embedjs-catch.ecl:1
testing/regress/ecl/embedjs.ecl:26
testing/regress/ecl/embedjs2.ecl:2
testing/regress/ecl/embedp2.ecl:2
testing/regress/ecl/embedpy-catch.ecl:2
testing/regress/ecl/embedpy.ecl:34
testing/regress/ecl/mysqlembed.ecl:37
testing/regress/ecl/pyimport.ecl:1
testing/regress/ecl/sqlite.ecl:32
testing/regress/ecl/streame.ecl:10
testing/regress/ecl/streame2.ecl:14
testing/regress/ecl/streame3.ecl:5

Suggests (at least) 14 files need the embedded tag - you have 9 here and 3 already had it, so you must be missing 2.

In addition. redis and memcached tests require 3rd party modules but do not go via the embed mechanism, so you may want to add

testing/regress/ecl/redislockingtest.ecl:87
testing/regress/ecl/redissynctest.ecl:75
testing/regress/ecl/memcachedtest.ecl:37

**Comment by AttilaVamos** [comment]
I think I should refine my aim because the //class=embedded tag doesn't match to my original plan. 
If I tag all files above with //class=embedded and I use this class for exclusion then I exclude some tests (e.g.: embedded C++) which should run on the out of box system (without any 3rd party modules).

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
 
HPCC Stop: OK

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| testing/regress/ecl/embedjava-catch.ecl | Excl. | Excl. | Excl. |
| testing/regress/ecl/embedjava.ecl | Excl. | Excl. | Excl. |
| testing/regress/ecl/embedjs-catch.ecl | Excl. | Excl. | Excl. |
| testing/regress/ecl/embedjs.ecl | Excl. | Excl. | Excl. |
| testing/regress/ecl/embedjs2.ecl | Excl. | Excl. | Excl. |
| testing/regress/ecl/javaimport.ecl | Excl. | Excl. | Excl. |
| testing/regress/ecl/memcachedtest.ecl | Excl. | Excl. | Excl. |
| testing/regress/ecl/redislockingtest.ecl | Excl. | Excl. | Excl. |
| testing/regress/ecl/redissynctest.ecl | Excl. | Excl. | Excl. |
 
HPCC Stop: OK

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| embedjava-catch.ecl | Excl. | Excl. | Excl. |
| embedjava.ecl | Excl. | Excl. | Excl. |
| embedjs-catch.ecl | Excl. | Excl. | Excl. |
| embedjs.ecl | Excl. | Excl. | Excl. |
| embedjs2.ecl | Excl. | Excl. | Excl. |
| javaimport.ecl | Excl. | Excl. | Excl. |
| memcachedtest.ecl | Excl. | Excl. | Excl. |
| redislockingtest.ecl | Excl. | Excl. | Excl. |
| redissynctest.ecl | Excl. | Excl. | Excl. |
 
HPCC Stop: OK

**Comment by richardkchapman** [comment]
If the intention is to identify all tests that require additional components to be installed before they can run, then I suppose you need to include 

testing/regress/ecl/cassandra-simple.ecl:48
testing/regress/ecl/embedR.ecl:35
testing/regress/ecl/embedjs-catch.ecl:1
testing/regress/ecl/embedjs.ecl:26
testing/regress/ecl/embedjs2.ecl:2
testing/regress/ecl/mysqlembed.ecl:37
testing/regress/ecl/sqlite.ecl:32
testing/regress/ecl/redislockingtest.ecl:87
testing/regress/ecl/redissynctest.ecl:75
testing/regress/ecl/memcachedtest.ecl:37

i.e. python tests are ok (since we have a dependency on python for other reasons). You should probably use something other than embedded for the class name though, to avoid confusion.

**Comment by AttilaVamos** [comment]
@richardkchapman Thank you. I think I put the '//class=embedded' for all test cases contain EMBED keyword (on your first list). Possible it will be useful later and add another tag for test cases on your second list something like '//class=external' or '//class=3rdparty'.

**Comment by AttilaVamos** [comment]
@richardkchapman please check.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| cassandra-simple | Excl. | Excl. | Excl. |
| embed | Pass | Pass | Pass |
| embedjava | Excl. | Excl. | Excl. |
| embedjava-catch | Excl. | Excl. | Excl. |
| embedjs | Excl. | Excl. | Excl. |
| embedjs-catch | Excl. | Excl. | Excl. |
| embedjs2 | Excl. | Excl. | Excl. |
| embedp2 | Excl. | Excl. | Excl. |
| embedpy | Excl. | Excl. | Excl. |
| embedpy-catch | Excl. | Excl. | Excl. |
| embedR | Excl. | Excl. | Excl. |
| javaimport | Excl. | Excl. | Excl. |
| macro | Pass | Pass | Pass |
| manylookup | Pass | Pass | Pass |
| map | Pass | Pass | Pass |
| memcachedtest | Excl. | Excl. | Excl. |
| merge | Pass | Pass | Pass |
| mergechild | Pass | Pass | Pass |
| mergededup | Pass | Pass | Pass |
| mergenway | Pass | Excl. | Pass |
| metaphone | Pass | Pass | Pass |
| multilfn | Pass | Pass | Pass |
| mysqlembed | Excl. | Excl. | Excl. |
| pyimport | Excl. | Excl. | Excl. |
| redislockingtest | Excl. | Excl. | Excl. |
| redissynctest | Excl. | Excl. | Excl. |
| sample | Pass | Pass | Pass |
| sample2 | Pass | Pass | Pass |
| scalar | Pass | Pass | Pass |
| schedule1 | Pass | Excl. | Excl. |
| selfjoin | Pass | Pass | Pass |
| selfjoin2 | Pass | Pass | Pass |
| selfjoinlw | Pass | Pass | Pass |
| sendlimit | Excl. | Excl. | Pass |
| serial3a | Pass | Pass | Pass |
| serial3b | Pass | Pass | Pass |
| serial3c | Pass | Pass | Pass |
| serial3d | Pass | Pass | Pass |
| serial4a | Pass | Pass | Pass |
| serial4b | Pass | Pass | Pass |
| serial5a | Pass | Pass | Pass |
| serial5b | Pass | Pass | Pass |
| serial5c | Pass | Pass | Pass |
| serial6a | Pass | Pass | Pass |
| serial6b | Pass | Pass | Pass |
| serial6d | Pass | Pass | Pass |
| serial7a | Pass | Pass | Pass |
| serial7b | Pass | Pass | Pass |
| serial7c | Pass | Pass | Pass |
| serial7d | Pass | Pass | Pass |
| serial8a | Pass | Pass | Pass |
| serial8b | Pass | Pass | Pass |
| serial9a | Pass | Pass | Pass |
| serial9b | Pass | Pass | Pass |
| serial9c | Pass | Pass | Pass |
| serial9d | Pass | Pass | Pass |
| setrange | Pass | Pass | Pass |
| setresult | Pass | Pass | Pass |
| sets | Pass | Pass | Pass |
| sets2 | Pass | Pass | Pass |
| sets3 | Pass | Pass | Pass |
| sets4 | Pass | Pass | Pass |
| shift | Pass | Pass | Pass |
| simplestored | Pass | Pass | Pass |
| sizeof | Pass | Pass | Pass |
| smartjoin | Pass | Pass | Pass |
| soapcall_multihttpheader | Pass | Pass | Pass |
| sort | Pass | Pass | Pass |
| sort2 | Pass | Pass | Pass |
| sort3 | Pass | Pass | Pass |
| spill | Pass | Pass | Pass |
| spillsort | Pass | Excl. | Excl. |
| spray_test | Pass | Excl. | Excl. |
| spray_test2 | Pass | Excl. | Excl. |
| sqagg | Pass | Pass | Pass |
| sqagg2 | Pass | Pass | Pass |
| sqaggds | Pass | Pass | Pass |
| sqaggds3 | Pass | Pass | Pass |
| sqaggds4 | Pass | Pass | Pass |
| sqaggds_an | Pass | Excl. | Pass |
| sqaggseq | Pass | Pass | Pass |
| sqcntds | Pass | Pass | Pass |
| sqcntidx | Pass | Pass | Pass |
| sqcond | Pass | Pass | Pass |
| sqcond3 | Pass | Pass | Pass |
| sqdistr | Pass | Pass | Pass |
| sqfilt | Pass | Pass | Pass |
| sqfilt2 | Pass | Pass | Pass |
| sqfilt3 | Pass | Pass | Pass |
| sqfilt4 | Pass | Pass | Pass |
| sqfilt_an | Pass | Excl. | Pass |
| sqgragg | Pass | Pass | Pass |
| sqgroup | Pass | Pass | Pass |
| sqidxlimit | Pass | Excl. | Pass |
| sqidxlimit2 | Pass | Pass | Pass |
| sqif | Pass | Pass | Pass |
| sqlite | Excl. | Excl. | Excl. |
| sqnormds1 | Pass | Pass | Pass |
| sqnormds1_an | Pass | Excl. | Pass |
| sqnormds2 | Pass | Pass | Pass |
| sqnormidx1 | Pass | Pass | Pass |
| sqnormidx2 | Pass | Pass | Pass |
| sqregress | Pass | Pass | Pass |
| sqshare | Pass | Pass | Pass |
| sqshare2 | Pass | Pass | Pass |
| sqsimple | Pass | Pass | Pass |
| sqsimple2 | Pass | Pass | Pass |
| stablesort | Pass | Pass | Pass |
| stablesort_nothor | Pass | Excl. | Pass |
| stats | Pass | Pass | Pass |
| stepjoin1 | Pass | Excl. | Pass |
| stepjoin2 | Pass | Excl. | Pass |
| stepjoin3 | Pass | Excl. | Pass |
| stepjoin4 | Pass | Excl. | Pass |
| steplimit1 | Pass | Pass | Pass |
| steplimit2 | Pass | Pass | Pass |
| steplimit3 | Pass | Excl. | Pass |
| stepping | Pass | Excl. | Pass |
| stepping2 | Pass | Pass | Pass |
| stepping3 | Pass | Excl. | Pass |
| stepping4 | Pass | Excl. | Pass |
| stepping7 | Pass | Excl. | Pass |
| stepping7a | Pass | Excl. | Pass |
| stepping7b | Pass | Excl. | Pass |
| stepping7c | Pass | Excl. | Pass |
| stepping7d | Pass | Excl. | Pass |
| stepping7e | Pass | Excl. | Pass |
| stepping7f | Pass | Excl. | Pass |
| stepping7g | Pass | Pass | Pass |
| stepping7h | Pass | Pass | Pass |
| stepping8 | Pass | Excl. | Pass |
| stepping8a | Pass | Excl. | Pass |
| stepping8b | Pass | Excl. | Pass |
| stepping9a | Pass | Excl. | Pass |
| stepping9b | Pass | Excl. | Pass |
| stepskip | Pass | Excl. | Pass |
| stored | Pass | Pass | Pass |
| storeset1 | Pass | Pass | Pass |
| streame | Excl. | Excl. | Excl. |
| streame2 | Excl. | Excl. | Excl. |
| streame3 | Excl. | Excl. | Excl. |
| streamread | Excl. | Excl. | Excl. |
| stringlib | Pass | Pass | Pass |
| stringlib1 | Pass | Pass | Pass |
| stringlib3 | Pass | Pass | Pass |
| subagg6 | Pass | Pass | Pass |
| subassign | Pass | Excl. | Pass |
| subsort | Pass | Pass | Pass |
| superfile1 | Pass | Pass | Pass |
| superfile10 | Pass | Pass | Pass |
| superfile2 | Pass | Pass | Pass |
| superfile5 | Pass | Pass | Pass |
| superfile6 | Pass | Pass | Pass |
| superfile7 | Pass | Pass | Pass |
| superfile8 | Pass | Pass | Pass |
| superfile9 | Pass | Pass | Pass |
| superkey1 | Pass | Pass | Pass |
 
HPCC Stop: OK

**Comment by richardkchapman** [comment]
Why have you not tagged the Java ones as 3rdparty? There's no guarantee that java is installed on a clean system, AFAIK, nor do we have an existing dependency on it.

**Comment by AttilaVamos** [comment]
@richardkchapman updated, please recheck.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| cassandra-simple | Excl. | Excl. | Excl. |
| embed | Pass | Pass | Pass |
| embedjava | Excl. | Excl. | Excl. |
| embedjava-catch | Excl. | Excl. | Excl. |
| embedjs | Excl. | Excl. | Excl. |
| embedjs-catch | Excl. | Excl. | Excl. |
| embedjs2 | Excl. | Excl. | Excl. |
| embedp2 | Pass | Pass | Pass |
| embedpy | Pass | Excl. | Pass |
| embedpy-catch | Pass | Excl. | Pass |
| embedR | Excl. | Excl. | Excl. |
| javaimport | Excl. | Excl. | Excl. |
| memcachedtest | Excl. | Excl. | Excl. |
| mysqlembed | Excl. | Excl. | Excl. |
| pyimport | Pass | Pass | Pass |
| redislockingtest | Excl. | Excl. | Excl. |
| redissynctest | Excl. | Excl. | Excl. |
| sqlite | Excl. | Excl. | Excl. |
| streame | Pass | Pass | Pass |
| streame2 | Pass | Pass | Pass |
| streame3 | Pass | Pass | Pass |
| streamread | Pass | Pass | Pass |
 
HPCC Stop: OK

**Pull request merged**
