### PR TITLE
HPCC-30298 Allow tracing detail level to be controlled by tracing flags

### PR DESCRIPTION
**Pull request by ghalliday**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Review by mckellyln — COMMENTED** [review]
I am not sure this will change threadTraceFlags properly ?
We want:
```
    doTrace(TraceFlags::Always, TraceFlags::Detailed));
```
to return true when traceLevel>="2", something I initially thought like:
```
    TraceFlags traceLevelFlag = (traceLevel > 1) ? TraceFlags::Detailed : ((traceLevel == 1) ? TraceFlags::Standard : TraceFlags::None);
```
??
This PR should be against candidate-8.12.x as that is what is in production now that is not logging enough info about missing files.

**Comment by ghalliday** [comment]
The changes happened in 8.12.x.
@richardkchapman what do you think about the second commit?  Should that go into 8.12.x and the 1st commit into a later version?

**Review by mckellyln — APPROVED** [review]
Approved, thanks.
In future versions we could remove check for config traceLevel altogether, if desired.

**Comment by richardkchapman** [comment]
I'm not sure the second commit is a good idea. It makes over-tracing a bit too easy (and might as a result cause issues for existing installations if they have traceLevel set to 2)

First looks fine.

**Comment by mckellyln** [comment]
ok, but without second commit, how can we get:
```
      if (doTrace(TraceFlags::Always, TraceFlags::Detailed))
```
to be true in 8.12.x ?
Current installs set traceLevel=2 and want to preserve messages output from this.
After this change goes into prod would we request:
```
traceDetailed="true"
```
to env.xml ?
But then how is it different ?

**Comment by richardkchapman** [comment]
If there are bits of tracing at level 2 that ops want to continue seeing, perhaps they should be changed to come out at standard detail level?

**Comment by mckellyln** [comment]
ok, that would work.  This is the tracing they find helpful and now missing -
```
                    if (doTrace(TraceFlags::Always, TraceFlags::Detailed))
                    {
                        DBGLOG("Failed to open file at any of the following %d local locations:", localLocations.length());
                        ForEachItemIn(local_idx, localLocations)
                        {
                            DBGLOG("%d: %s", local_idx+1, localLocations.item(local_idx));
                        }
                        DBGLOG("Or at any of the following %d remote locations:", remoteLocationInfo.length());
```

**Review by mckellyln — APPROVED** [review]
Approved.

**Pull request merged**
