### PR TITLE
HPCC-20365 Avoid row collector/roxiemem callback deadlock

### PR DESCRIPTION
**Pull request by jakesmith**
Avoid deadlock where shared stream is being initiated, at same
time as Roxiemem's background callback is calling the same
row collector.

Also removed a unusued member (clearCB in CSpillable) and the
associated code, which looked like it might be involved in
a similar problem, but was never used.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by mckellyln** [comment]
activateSpillingCallback() is also called from CSpillableStream ctor.  Could this same issue happen there ?

**Comment by mckellyln** [comment]
I think the CSpillableStream ctor is ok as is, as it is called outside of the CThorArrayLockBlock block(spillableRows) scope.

**Review by mckellyln — APPROVED** [review]

**Review by mckellyln — COMMENTED** [review]
@jakesmith What about deactivateSpillingCallback() in getStream() ?
Doesn't this call perhaps call removeRowBuffer() which tries to get callbackCrit ??

**Comment by jakesmith** [comment]
>What about deactivateSpillingCallback() in getStream() ?
Doesn't this call perhaps call removeRowBuffer() which tries to get callbackCrit ??

deactivateSpillingCallback() will never call ensureSpillingCallbackRemoved and hence not call removeRowBuffer() because clearCB is never set in this context.
It (deactivateSpillingCallback) also has to be called in getStream() within the spillableRows stream, to ensure that when it is re-entered by other threads, particularly freeBufferedRows which checks if still enabled and bails out if not.

In fact this clearCB (CSpillable::clearCB) is not set or used at all, so I'm going to remove it in this PR also.

**Comment by jakesmith** [comment]
@mckellyln - see replies. I've removed clearCB and associated code, and squashed that change in as both commits were small.

**Review by mckellyln — APPROVED** [review]

**Comment by mckellyln** [comment]
@jakesmith changes look good for merge.

**Comment by mckellyln** [comment]
@jakesmith why not merge into 6.4.26 ?

**Comment by jakesmith** [comment]
Actually the branch was based off candidate 6.4.26 , but just updated it to latest upstream.
The PR base hadn't been changed though, just changed it.

**Comment by jakesmith** [comment]
@richardkchapman - please merge (perhaps wait til smoketest reruns JIC)

**Comment by jakesmith** [comment]
@richardkchapman - please merge.

**Pull request merged**
