### PR TITLE
HPCC-12669 Rename platform.h and all references to it

### PR DESCRIPTION
**Pull request by RussWhitehead**
The file named system/include/platform.h is somewhat of a common name among
the many SDKs out there, and causes build errors when trying to coexist
with one or more of these SDKs. A better solution would be to rename it to
something less ambiguous like hpcc_platform.h or hpccplatform.h. This PR
renames that file and updates all references to it

Signed-off-by: William Whitehead william.whitehead@lexisnexis.com

### CODE REVIEW

**Comment by RussWhitehead** [comment]
@ghalliday Implemented all your (3) suggestions, ready for re-review

**Comment by ghalliday** [comment]
@richardkchapman any reason not to merge? There are still some #oinclude <hpcc...> but they're no worse than they were.

**Comment by richardkchapman** [comment]
Only that I am hoping we will discover a better way. I really dislike this fix.

**Comment by richardkchapman** [comment]
@RussWhitehead Can you take a look

**Comment by RussWhitehead** [comment]
It should be noted that I don't include either version of platform.h; they are being included by HPCC headers and Progress Software headers. That being said, I am not sure what the best fix is. I am not a fan of hard coding absolute or relative paths to header files in source code for obvious reasons.  This becomes even more ugly when those files do not belong to the same source tree as is the case here (Progress SDK is its own product, and HPCC is in a different repository).

However, as you suggested, I was able to get it to build by always including the HPCC platform.h file using a hardcoded path, so lets close this issue for now.

**Comment by richardkchapman** [comment]
Absolute paths should never be hardcoded, but relative ones are ok (and indeed using relative paths in include definitions is a good way to cut down on namespace pollution)

**Pull request closed without merging**
