### PR TITLE
HPCC-28896 Fix regression for listing log files using FileList

### PR DESCRIPTION
**Pull request by wangkx**
Before the dropzone scope check is added to the ESP FileSpray.FileList, the FileList can also be used to retrieve a list of log files. In this PR, the function of retrieving a list of log files is added back to the FileList.
1. Rename the addDropZoneFile() to addPhysicalFile(). Rename/modify the getDropZoneFiles() to getPhysicalFiles(). Both functions can be used for both dropzone files and log files.
2. If a user does not specify a dropzone name and the specified path is a valid log path, the FileList calls the getPhysicalFiles() to retrieve a list of log files.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by wangkx** [comment]
The PR is based on https://github.com/hpcc-systems/HPCC-Platform/pull/16710.

**Review by jakesmith — APPROVED** [review]
@wangkx - looks ok.

**Comment by jakesmith** [comment]
@ghalliday - this could be merged as an alternative to rolling back HPCC-28553 changes in 8.12.0

**Review by ghalliday — APPROVED** [review]
@wangkx looks good.  Please rebase (onto master) to avoid the clash between commits

**Comment by wangkx** [comment]
@ghalliday This PR is a fix for https://github.com/hpcc-systems/HPCC-Platform/pull/16710. The clash is because that PR has been reverted (https://github.com/hpcc-systems/HPCC-Platform/pull/16916). Should I re-open https://github.com/hpcc-systems/HPCC-Platform/pull/16710 and add this fix to that PR? Or keep them as separated PRs? Should I re-target all of those Dropzone security PRs to master?

**Comment by jakesmith** [comment]
> @ghalliday This PR is a fix for #16710. The clash is because that PR has been reverted (#16916). Should I re-open #16710 and add this fix to that PR? Or keep them as separated PRs? Should I re-target all of those Dropzone security PRs to master?

I think yes. Can you please open a new JIRA though for HPCC-28553, and reference it, the rollback JIRA (HPCC-28882), this JIRA and HPCC-28892, and also incorporate that fix.

**Comment by jakesmith** [comment]
@wangkx - also as discussed offline with @ghalliday - for now when the new PR is issued, it should contnue to adhere to isDropZoneRestrictionEnabled for now. In the hopefully near future we'll deprecate that feature.

**Comment by wangkx** [comment]
I am closing this PR because the fix will be in https://github.com/hpcc-systems/HPCC-Platform/pull/16969.

**Pull request closed without merging**
