### PR TITLE
HPCC-24541 Fix crash in thormaster in container mode, relating to log…

### PR DESCRIPTION
**Pull request by jakesmith**
… file

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
@richardkchapman - please review

**Comment by richardkchapman** [comment]
@rpastrana Can you comment on this?

**Comment by rpastrana** [comment]
@jakesmith change seems reasonable if we're willing to sacrifice persisting WU log info to local file.
Do any other components assume these log files will be available?

**Comment by rpastrana** [comment]
@jakesmith also out of curiosity, what is the actual cause of the crash in updateWorkUnitLog?

**Comment by jakesmith** [comment]
@rpastrana , it's because "log" is empty (because logHandler is stdrer handler), and that means:
```
    const char *ptr = strstr(log, THORMASTERLOGSEARCHSTR);
    dbgassertex(ptr);
```

ptr is null here.

**Comment by rpastrana** [comment]
Outside the scope of this issue, there might be other components relying on the existence of a filelog handler:
https://track.hpccsystems.com/browse/HPCC-24547

**Comment by jakesmith** [comment]
@rpastrana - were you happy with this fix?

**Review by rpastrana — APPROVED** [review]
@jakesmith seems reasonable.
I just wanted confirmation nothing downstream breaks because of the absence of the WU specific log file

**Comment by jakesmith** [comment]
>I just wanted confirmation nothing downstream breaks because of the absence of the WU specific log file

right, there are known issues in this area that we need to tackle, i.e. getting to logs for the workunit, no longer work from Helpers tab of workunit.
But given that before this change it was publishing a blank entry, with no filename (as there is none),
any functionality which relied on loading/looking for a log would have failed, including the workunit helpers tab. In fact before this change it had an entry, that didn't work, whereas now, there is no entry (as no way to support it at the moment).

**Comment by rpastrana** [comment]
@jakesmith we'll discuss other mechanism to persist these logs during Thursday meeting.

**Comment by jakesmith** [comment]
@richardkchapman - please merge.

**Comment by jakesmith** [comment]
@richardkchapman - this was a 7.10.10 regression (introduced by : https://track.hpccsystems.com/browse/HPCC-24157)
And, it will crash in release mode in containerized mode.

**Comment by jakesmith** [comment]
@richardkchapman - retargeted to candidate-7.10.10

**Pull request merged**
