### PR TITLE
HPCC-16071 Default Thor and roxie to using the new scanning allocator

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman please review

**Comment by richardkchapman** [comment]
Do you need to default the fragment flag differently on some thor activities?

**Comment by richardkchapman** [comment]
@ghalliday One question

**Comment by ghalliday** [comment]
@jakesmith what is your opinion?  There definitely are pathological possibilities, but I don't think they are very likely.  I should really rename the flag since it is ok with some fragmentation.

**Comment by jakesmith** [comment]
An activity that feeds into a distribute is such a case isn't it?
Or into a dedup?

@ghalliday

**Comment by ghalliday** [comment]
I think the only significant problem will be with activities that remove a quantity of rows just as the block becomes full (possibly dedup), and then only if it continues to throw away large numbers of rows.

Something like

myDataset(count < threshold)

where myDataset is very large and myThreshold is just below the number of rows that can fit in a page.

I don't expect any in real life.  How do we check?  Run the performance suite with and without, but doesn't really test real world issues.

@jakesmith any suggestions other than enabling it and waiting to see if there are any problems?

**Comment by jakesmith** [comment]
>I think the only significant problem will be with activities that remove a quantity of rows just as the block becomes full (possibly dedup), and then only if it continues to throw away large numbers of rows.

Won't that be the normal pattern of distribute fed by e.g. diskread?

If not - then I don't know how else you would automagically spot.
@ghalliday

**Comment by richardkchapman** [comment]
After discussion it was determined that it was ok to merge this, but a Jira was opened to generate stats on scan lengths that would help identify if any pathogenic cases were encountered.

**Pull request merged**
