### PR TITLE
HPCC-18596 Avoid patching workunit XML patching

### PR DESCRIPTION
**Pull request by jakesmith**
Exporting a workunit to XML invovled serializing it to XML
and spotting parts which were sensitive and removing them on
the fly. Followed by a later stage which inserted another piece
of XML into the XML text block.

Instead get a copy of the workunit tree, prune the unwanted into,
add the extra info (in the form of their original trees) and
serialize the whole cleaned workunit in one go.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by jakesmith** [comment]
@richardkchapman - please review

**Comment by richardkchapman** [comment]
Not sure I see why this is an improvement - it requires an entire extra copy of the tree.

**Comment by jakesmith** [comment]
Yes it requires a local copy of the tree to prune it.
It removes a lot of custom code that was walking/filtering/merging and formatting the IPT, instead of using the standard functions in the process though.
The code is a cleaner, I didn't consider the extra tmp copy to do so prohibitive.

**Comment by richardkchapman** [comment]
Workunits are big...

Is it really cleaner? The functionality we actually want is to suppress output, not modify a tree - so coding it by suppressing output seams reasonable to me

Side question - should sasha archives actually be suppressing this information - I would not have thought so.

**Comment by jakesmith** [comment]
>so coding it by suppressing output seams reasonable to me

If there was clean way to do it and to merge output to a single XML block as required, I agree would be better to stream and filter and merge. But it was degrees of kludgy code before.

Is it that time critical to worry? By the time the client (sasha etc.) has the workunit locally, i.e. fetched from the server (dali/cassandra) a local copy should be relatively quick.

Can keep existing code if you want, but it's not v. nice IMO.

**Comment by jakesmith** [comment]
>Side question - should sasha archives actually be suppressing this information - I would not have thought so.

Not sure, it's suppressed because sensitive, but Sasha archive should also be secure, so I think you're right, no reason to suppress in that case (It was designed to be suppressed when viewing workunit XML in Eclwatch only I think)

**Comment by richardkchapman** [comment]
Both the "filter as output" and the "patch the string" were deliberately coded in their slightly obscure ways precisely to avoid an extra copy. I'm inclined to leave them as-is.

**Pull request closed without merging**
