### PR TITLE
HPCC-22542 Activity Widget sending hundreds of requests to WUInfo

### PR DESCRIPTION
**Pull request by miguelvazq**
During a change to correct the progress graphic that was out of sync in the WUDetailsWidget a hasCompleted event fired in multiple places. This caused monitoring(timer) to start on the Activity widget needlessly. The Activity widget has its own timer that can monitor its un-completed workunits. I have added an indentifier that destinguishes it from the WUDetailsWidget.

Related to: https://github.com/hpcc-systems/HPCC-Platform/commit/febaf310a0440398cdbf90a50f570419dfe0ca1d#diff-b357ce8bbd5b62aea547413e4862f360

Signed-off: Miguel Vazquez <miguel.vazquez@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by miguelvazq** [comment]
@kunalaswani Please review. @cloLN @gfortil probably worth a test via cherry-pick.

**Comment by jakesmith** [comment]
> This caused monitoring(timer) to start on the Activity widget needlessly. The Activity widget has its own timer that can monitor its un-completed workunits. 

Did it cause multiple independent Activity widgets to run ?
I'm still wondering how causing the monitoring(timer) to start, caused the quite as much traffic/connections as we witnessed ?

**Review by kunalaswani — APPROVED** [review]

**Comment by kunalaswani** [comment]
Reviewed changes, looks good

**Comment by cloLN** [comment]
so.  It looks like the 15 WUInfo calls are coming from opening the Workunit Details in eclwatch.
As soon as I close the details and have just the activity page open, the WUInfo calls go back to 0 from what I can see

**Pull request merged**
