### PR TITLE
HPCC-18533 Add jptree unit tests

### PR DESCRIPTION
**Pull request by jakesmith**
Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

NB: These unit tests will fail until HPCC-18523, HPCC-18531 and HPCC-18534 are merged.

### CODE REVIEW

**Comment by jakesmith** [comment]
@mckellyln - please review

NB: These unit tests will fail until HPCC-18523, HPCC-18531 and HPCC-18534 are merged.

**Comment by jakesmith** [comment]
@AttilaVamos - I see it failed the smoketest (as expected), but I do not see the unit tests that failed listed ?

**Comment by AttilaVamos** [comment]
@jakesmith  The problem is:
2017-10-17 09:13:00: JlibIPTTest
2017-10-17 09:13:00: .E !!!FAILURES!!! Test Results: Run: 1 Failures: 0 Errors: 1 1) test: JlibIPTTest::test (E) uncaught exception of unknown type

**Comment by jakesmith** [comment]
@AttilaVamos - yes that was expected (it hit a CPPUNIT_ASSERT), but why was it not reported in the smoke test report above?

**Comment by AttilaVamos** [comment]
@jakesmith  Because the unittest subpart of smoketest doesn't handle this situation well. I'm working on the fix.

**Comment by jakesmith** [comment]
@AttilaVamos ok, thanks.

**Comment by jakesmith** [comment]
@mckellyln - please review

**Review by mckellyln — APPROVED** [review]

**Comment by mckellyln** [comment]
@jakesmith @richardkchapman ok to merge

**Comment by jakesmith** [comment]
@richardkchapman - please merge.

**Comment by jakesmith** [comment]
NB: unit test expected to fail until HPCC-18531 is merged (and this is rebased)

**Comment by richardkchapman** [comment]
@jakesmith Can you rebase now that HPCC-18531 is merged

**Comment by jakesmith** [comment]
@richardkchapman - rebased.

**Pull request merged**
