### PR TITLE
HPCC-16146 Allow multiple DESDL ESP services share common binding

### PR DESCRIPTION
**Pull request by rpastrana**
- Allows services of the same type share binding if DynamicESDL

Signed-off-by: Rodrigo Pastrana <rodrigo.pastrana@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [x] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [x] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [x] Performance
  - [x] Security
  - [ ] Thread-safety
  - [x] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by rpastrana** [comment]
@Michael-Gardner please review

**Comment by Michael-Gardner** [comment]
@rpastrana looks good.

**Comment by rpastrana** [comment]
@richardkchapman please merge

**Comment by afishbeck** [comment]
@rpastrana I don't think this solves the issue though.  This affects the configuration of ESP bindings that happen to be DESDL, but we need to be able to load more than one service inside a DESDL binding.  This also doesn't benefit from some of the things that SCAPPS would like such as commoning up the processing of shared structures.

**Comment by rpastrana** [comment]
@afishbeck this change allows multiple DESDL services per ESP binding... the original issue was described as such: "Dynamic ESDL: allow more than one Service on the same port in the same ESP". 
I think the issue you're describing is different, as you mention "load more than one service inside a DESDL binding" prob warrants a new jira.

**Comment by afishbeck** [comment]
@rpastrana I'm pretty sure Jiafu's intention was what I described.

Did you verify that the change you made works?  By works I mean you can load stuff and run stuff from each of the muliple static DESDL ESP bindings on the same port?  Don't we route actions taken based on the port?  How does an action get routed to one binding vs. the other?

**Comment by afishbeck** [comment]
By "Dynamic ESDL: allow more than one Service on the same port in the same ESP".  He means a DESDL service, not an ESP service.

**Comment by rpastrana** [comment]
@afishbeck testing this change took a lot longer than the code change. I talked to Jaifu recently and this seemed to be the fix he was looking for. The routing is based on ESP bindings (protocol, port) + Service name + Method name. I can show you an example on my local environment if you're so inclined.

**Comment by afishbeck** [comment]
Jiafu only cares about the end result but doesn't realize what he's loosing.  Perhaps you should show me how the bind and publish work for multiple static bindings on the same port.  But I don't want to take the dynamic out of dynamic ESDL,  ConfigMgr or environment.xml shouldn't bee needed for this.

And by routing I didn't mean a user request, I meant the publish and bind.  I thought the command line only required the process and port to know where to DESDL (virtual) bind to.  Having the static bindings on the same port seem like it complicates any future changes quite a bit.

**Comment by afishbeck** [comment]
@rpastrana I'd rather reverse this change and make it a 7.0 feature.  Otherwise we're going to have to support doing it this way forever.  I'd rather focus on doing it the truly dynamic way.

**Comment by rpastrana** [comment]
@afishbeck opened new Jira: https://track.hpccsystems.com/browse/HPCC-17379 
It might be helpful if you share your thoughts and expectations there.

**Comment by rpastrana** [comment]
@afishbeck thinking about this change, I don't think we should restrict users from setting up their environment this way, unless of course you think it would be misused as a way around the purely Dynamic approach.

**Comment by afishbeck** [comment]
@rpastrana I must be missing something.  I find this complex to work out
and am afraid future features will be even worse.

If I have 2 or more ESP Bindings of DESDL on port 8888... and I:

esdl bind-service myesp 8888 my_esdl_def my_service

which ESP binding is that going to configure?

I really want to make sure it stays completely deterministic by port.

**Comment by rpastrana** [comment]
Great point! Although "esdl bind-service" could be done by esp service name rather than port, but we prob do want to make the mapping as direct as possible.

**Comment by afishbeck** [comment]
service names get very complicated.  We supported port (in my opinion as
the primary way) because it is far more user friendly.

**Comment by afishbeck** [comment]
@rpastrana I always picture two conversations with a user:

Conversation 1:
Me: Specify the ESP process and the ESP service on the command line.
User: Like this?
Me: No that's the ESDL service, specify the ESP service.
User: Huh?

Conversation 2:
Me: Specify the ESP process and port on the command line.
User: OK

**Pull request merged**
