### PR TITLE
HPCC-14827 Update cassandra cpp driver to latest version 2.2.2

### PR DESCRIPTION
**Pull request by richardkchapman**
Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@rpastrana Please review

**Comment by rpastrana** [comment]
commit number seems correct: https://github.com/datastax/cpp-driver/commit/b4bb435129bab533612fa2caf194555fa943f925

**Comment by richardkchapman** [comment]
Do you have a cass3 installation you can test against?

**Comment by rpastrana** [comment]
I do, I'll run Easy cassandra against it

**Comment by rpastrana** [comment]
most of easycassandra works, but datatypes represented as "set of" generated errors:

Error: System error: 0: cassandra: While binding parameter list1: Invalid value type (processing query 
  INSERT INTO tbl1 (name, value, boolval, r8, r4,d,ddd,u1,u2,a,set1,list1,map1) values (?,?,?,?,?,?,?,?,?,?,?,?,?);)

also:
testCassandraSet : Error:    Error: 0: cassandra: type mismatch - scalar expected (0, 0), 0, 
testCassandraList: Error:    Error: 0: cassandra: type mismatch - scalar expected (0, 0), 0, 
testCassandraMap: Error:    System error: 0: Graph[1], cassandra: type mismatch - row expected (0, 0), 0, 
and I could not recreate, but I did get a seg fault in one case:
Error:    SIG: Segmentation fault(11), accessing 0000000000000000, IP=00007F8CAB0F70CE (0, 0), 1000,

**Comment by richardkchapman** [comment]
It's quite likely there is a very similar bug to the one I just fixed in Python in the Cassandra driver.

If you can come with some test ECL illustrating it please open a new Jira

**Comment by richardkchapman** [comment]
@rpastrana Please retest

**Comment by rpastrana** [comment]
@richardkchapman 
confirmed the following data types were mapped successfully:
SET OF STRING set1,
SET OF INTEGER4 list1,
LINKCOUNTED DICTIONARY(maprec) map1{linkcounted};

where maprec := RECORD
   string fromVal => string toVal
 END;

**Comment by richardkchapman** [comment]
@ghalliday Please review/merge

**Pull request merged**
