### PR TITLE
HPCC-19124 SSL Blocking read min_size not correct

### PR DESCRIPTION
**Pull request by mckellyln**
Signed-off-by: Mark Kelly <mark.kelly@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Full QA suite gives expected results and SSL queries to Roxie work as expected.

### CODE REVIEW

**Comment by mckellyln** [comment]
@afishbeck please review.

**Review by afishbeck — APPROVED** [review]
@mckellyln looks good

**Comment by mckellyln** [comment]
@richardkchapman or @ghalliday for merge into 6.4.12 or next version.

**Comment by mckellyln** [comment]
ok, because of usage like this in sockfile.cpp:
```
       socket->read(msg.reserve(toread), toread);
```
We must try to read the full amount or fail, so I am confident this change to provide min_size == max_size is correct.

**Comment by richardkchapman** [comment]
Can you provide any information about what symptoms users might observe as a result of this issue?

**Comment by mckellyln** [comment]
I think this and https://track.hpccsystems.com/browse/HPCC-19106 should be put together as one.
As code is currently, avail_read() function for SSL socket might return more than is possible to read without blocking (until HPCC-19106 is merged).

Code now for SSL sockets:
-avail_read() might return more bytes than can be SSL_read(), and may not detect close correctly.
-but read() will return without blocking because min_size is 0.
-coding error is that read() could return reading less than amount specified and the lessor amount is not returned.

New change (both HPCC-19124 and HPCC-19106) for SSL sockets:
-avail_read() returns 0 correclty if socket closed, but may also return only 1 when there could be more bytes available.
-read() will block for specified amount (which may be 1 byte) which is correct, but could lead to some inefficiences.

**Comment by mckellyln** [comment]
My idea would be to change avail_read() to become a check for if socket is closed (by comparing result==0 as it is used in many places) and to not use it for determining a minimum amount to blocking read.

**Comment by mckellyln** [comment]
I did a test without SSL, but with avail_read returning only 1 byte if at least 1 byte was available.
I didn't like the inefficiency of avail_read() returning 1 byte when more might be present.
While this may not happen often in normal usage, I am going to close this and HPCC-19106 (https://github.com/hpcc-systems/HPCC-Platform/pull/10883) and come up with an alternative.

**Pull request closed without merging**
