### PR TITLE
HPCC-25491  Support Azure LDAP Helm configuration for DALI

### PR DESCRIPTION
**Pull request by RussWhitehead**
Added yaml files for bare metal and azure based configuration

Signed-off-by: Russ Whitehead <william.whitehead@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [x] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by RussWhitehead** [comment]
@afishbeck @jakesmith Please review

**Comment by AttilaVamos** [comment]
I am sure the indexcachebug failure is not related to this PR.

**Comment by afishbeck** [comment]
@RussWhitehead not sure how this works.  ESP uses a scheme like this but it has a mechanism for building a very flexible configuration of services from it's various YAML files.

**Comment by RussWhitehead** [comment]
@afishbeck I followed the ESP pattern, with the expectation that we could vet it out when we have the SDS Migration to Azure complete. Until then, perhaps @jakesmith can clue us in on how the Dali side of Helm configuration works

**Comment by jakesmith** [comment]
@afishbeck @RussWhitehead -  A meta question 1st - shouldn't this be a JIRA/PR about how to configure LDAP in general, with Azure just being a specific example? (and as an example, placed in e.g. helm/examples/ ...)

Secondly, is this essentially attempting to move the legacy configuration out of Dali, into a separate configurable yaml file?

As far as how dali config in cloud mode configuration works - it follows same default pattern that all component configurations follow. There's a defaultYaml in the code, the component calls loadConfiguration and it picks up the component yaml that has been generated based on the component name section from the helm values file/settings/overrides. 

At some point we're going to want to move the whole file service to an esp service, at that point it will be only esp that does any LDAP validation and the Dali calls will be removed.
Therefore we should probably try to avoid tying this to Dali now/with future changes, but we can still generate these LDAP settings so Dali can see them, and later simply move which component/serivce they're generated into.

So I suspect the ldap configuration should be in a separate section in helm values (under the security: section would make sense).

The dali configution (for now, later moved to esp service) can generate this section into its configuration (i.e. see helm/hpcc/templates/dali.yaml configMap generation)

**Review by jakesmith — COMMENTED** [review]
see comments/questions

**Comment by afishbeck** [comment]
@jakesmith I'm not sure that this current change does anything.  This is essentially a copy of what becomes the ESP defaultYaml for ldap.  Because ESP is a bunch of pluggable components tied together via configuration it's defaultYaml is buit more dynamically.

ESP currently supports helm configuration of it's LDAP security within the "esp:" section, but allowing the LDAP information to be defined in the security section and used globally does make sense.  I think at least for now I'd still allow it to be overridden for a specific ESP just in case.

**Comment by jakesmith** [comment]
@afishbeck - so this is a placeholder?

I think the questions re. whether Azure LDAP is an example, and re. this not specifically being helm config. for Dali  - still hold.

**Comment by afishbeck** [comment]
@jakesmith @RussWhitehead This PR can be closed for now until the real solution reaches PR status.

Hopefully Azure LDAP will be available from the ops team soon so we can test that.  @RussWhitehead are you able to test against your existing LDAP server for that configuration flavor?  There still may be scenarios where we need that even in k8s.

**Comment by richardkchapman** [comment]
Closing as per comments

**Pull request closed without merging**
