### PR TITLE
HPCC-14822 Support dropzone umask in FileSpray web service

### PR DESCRIPTION
**Pull request by wangkx**
In FileSpray.Despray, read the umask from environment.xml
and forward it to dfuserver.

Signed-off-by: wangkx kevin.wang@lexisnexis.com

### CODE REVIEW

**Comment by wangkx** [comment]
@mckellyln please review.

**Comment by mckellyln** [comment]
Looks good to merge.  @AttilaVamos fyi

**Comment by wangkx** [comment]
@richardkchapman this PR is ready to merge.

**Comment by richardkchapman** [comment]
This seems related to HPCC-14832 but that is targetting 6.0. Which should it be (I think probably 6.0)

**Comment by mckellyln** [comment]
This is a sub-task of 14610 and needed together with 14610 to achieve the goal of supporting a dropzone umask parameter.

**Pull request merged**
