### PR TITLE
HPCC-17931 Add an INLINE operator to force function expansion with --fastsyntax

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [x] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [x] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by ghalliday** [comment]
@shamser please review.

The new example fails with --fastsyntax without the inline keyword.
This also includes a couple of fixes for cores when using the --fastsyntax options (issue14712 and issue16354 in the private regression suite).

**Comment by ghalliday** [comment]
The change affected 1 test in ecl/regress (issue14052.ecl) but no examples from the private regression suite.

**Review by shamser — COMMENTED** [review]
@ghalliday Should nested inline work also?  If so, maybe the test ecl can be extended to include a test for nested inline.

**Comment by ghalliday** [comment]
@shamser I'm not sure what you mean by nested inline.  Can you give an example?  Nested functions aren't treated any differently from other functions....

**Comment by shamser** [comment]
@ghalliday I mean would something like this work:

```
w(unsigned i) := INLINE MODULE
   export v := i * 10;
END;

x(unsigned i) := INLINE MODULE
    export y := w(i).v * 2 ;
END;

r := record,maxlength(x(10).y)
    unsigned i;
end;
```

**Comment by ghalliday** [comment]
I have extended the example to include an extra level.  It will not make any difference as far as the implementation goes....

**Review by shamser — APPROVED** [review]
@richardkchapman Code reviewed. Looks good.

**Pull request merged**
