### PR TITLE
HPCC-23551 Build eclwatch out of HPCC-Platform source

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@GordonSmith so somewhere back between 7.6.x - 7.8.x there were some build changes to how eclwatch was generated which really helped speed up the entire process.  There was a downside though, in that the build was actually being done 'in source' instead of in the build directories, and this created problems with git because now there were new generated files in the source directories.  There was a simple fix to this which was to just add the output to .gitignore, but then this creates an issue if you are swapping between minor/major branches of the platform during your workday.  Because all the sudden there's files in the esp/src directory that can cause issues with earlier versions of the platforms eclwatch builds.

To fix this I've created a quick copy of all the esp/src files necessary for the npm build, to be replicated in {CMAKE_CURRENT_BINARY_DIR} (the build tree).  And then I've modified all the build targets to use that as the working directory.  Seems to be building fine for me and there's no more generated output to the HPCC-Platform source tree.

Not sure if I should target 7.8.x or 7.10.x for this.  If you're ok with the change I can move it to wherever it's needed.

**Comment by GordonSmith** [comment]
FYI when switching between 7.6.x and 7.8.x you can run `git -f -fd ./esp/src` and you should be good to go.

**Comment by GordonSmith** [comment]
FYI when switching between 7.6.x and 7.8.x you can run `git -f -fd ./esp/src` and you should be good to go - but an out of source build is probably preferable.

**Comment by GordonSmith** [comment]
Visually looks good - would like to test (in the morning) also.

**Review by GordonSmith — APPROVED** [review]
Looks good

**Comment by Michael-Gardner** [comment]
@richardkchapman ready for merge.

**Pull request merged**
