### PR TITLE
HPCC-15458 Add option to eclcc to include archive in generated workunit

### PR DESCRIPTION
**Pull request by richardkchapman**
Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@ghalliday Please review

**Comment by richardkchapman** [comment]
Also fixes https://track.hpccsystems.com/browse/HPCC-15457

**Comment by ghalliday** [comment]
@richardkchapman can you upmerge 6.0.0 to master - I think it may cause merge conflicts with this branch.

**Comment by richardkchapman** [comment]
@ghalliday Upmerged and rebased

**Comment by ghalliday** [comment]
@richardkchapman before merging I wanted to double check this wasn't something we wanted in 6.0.0 (to make our lives easier).

**Comment by richardkchapman** [comment]
@ghalliday I'm happy to retarget to 6.0.0 if you think it's safe enough

**Comment by ghalliday** [comment]
merged to 6.0.0 instead, to simplify life internally when gitlab comes on line.
https://github.com/hpcc-systems/HPCC-Platform/pull/8597

**Pull request closed without merging**
