### PR TITLE
HPCC-26249 Removed xterm dependencies in the platform

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
tested on 20.04 and found no runtime issues after removing the xterm dependency

**Comment by richardkchapman** [comment]
Why is this functionality not needed on newer Ubuntu systems?

**Comment by richardkchapman** [comment]
@Michael-Gardner One question. Also at this point 8.4.x seems a more appropriate target

**Comment by Michael-Gardner** [comment]
@richardkchapman The information returned by hpcc-run.sh running hpcc-init on older ubuntu distro's and systemd on newer distros has changed, so the output differs depending on what the underlying init system is.  It doesn't really 'display' the output of starting the platform on the newer distributions. The reason behind using xterm was so we could launch and display the old hpcc-init output to the end user so they knew something was being done.  If this tool is still relevant to people we could keep it around and I could rewrite it to output something for when we're using systemd.

We already have it conditionally being excluded for Containerized builds, so there's no extra bloat there.

**Comment by richardkchapman** [comment]
@Michael-Gardner Please retarget to master/8.4.x

**Review by richardkchapman — APPROVED** [review]

**Comment by richardkchapman** [comment]
@Michael-Gardner Looks ok (though it will need to target master now since it has been stalled for so long), but wasn't the point of this change to remove the dependency on xterm? And if so should there be some change to a dependency list and/or a change to what is installed into containers?

**Comment by richardkchapman** [comment]
Actually I see that one of the deleted files was responsible for adding the xterm dependency (and this code is not enabled in containerized). So ignore my question above.

**Pull request merged**
