### PR TITLE
HPCC-14764 Roxie protocol encapsulation

### PR DESCRIPTION
**Pull request by afishbeck**
Encapsulate roxie protocol handling behind generic interfaces.  Remove
all references to internal ccd code from roxie protocol component.

This is a major step toward allowing pluggable protocols, although more
work and testing will be needed to load additional protocol
implementations.

Signed-off-by: Anthony Fishbeck anthony.fishbeck@lexisnexis.com

### CODE REVIEW

**Comment by afishbeck** [comment]
@richardkchapman  There are still a few things I need to test... like the ECL debugger, but I think the code review can begin.

**Comment by richardkchapman** [comment]
@afishbeck Looks sensible to me. @stuartort Please check too

**Comment by stuartort** [comment]
@afishbeck - looks reasonable to me.  We can test on the 190 cluster next week

**Comment by richardkchapman** [comment]
You wnt me to merge this as is or is there more to do first?

**Comment by afishbeck** [comment]
Generally I would say the sooner the better for something like this so we can find and deal with anything that breaks, and I have other issues that depend on this... but I will be away next week, so...

**Comment by stuartort** [comment]
The code looks fine.  You can merge and new issues can be logged independently

**Pull request merged**
