### PR TITLE
HPCC-23146 Issues with variable filenames in CQ's with index and fetch

### PR DESCRIPTION
**Pull request by jakesmith**
Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
@ghalliday - please review.

NB: I'm targeting 7.4 here. I wasn't sure if should target 7.2 (it was hit there also), but there is a workaround.

**Comment by ghalliday** [comment]
@jakesmith the change looks good, but could do with a test case.  Do you have one (or is the example in https://github.com/hpcc-systems/HPCC-Platform/commit/0cb2d8755e21bf17370bf50f26aeb96aa19589dc sufficient to reproduce it?)

**Comment by jakesmith** [comment]
@ghalliday - your childindex.ecl test is enough to expose/test this.

**Comment by ghalliday** [comment]
@jakesmith can you take my modification to childindex and add it to your PR - I think that makes more sense.

**Comment by jakesmith** [comment]
@ghalliday - childindex.ecl change taken.

**Comment by jakesmith** [comment]
@ghalliday - looks like I forgot to take childindex.xml .. I'll do that now.

**Comment by jakesmith** [comment]
@ghalliday - no it's the crash you saw in your PR, so not directly related to this PR, except it now has your childindex.ecl change that exposes the hthor issue.

So we may want to force the smoketest to rerun after that is resolved.

**Comment by ghalliday** [comment]
Hmm, strange.  I couldn't reproduce that crash.  Looks like I'll need to do some more debugging on that issue.

**Comment by ghalliday** [comment]
I think I may need to create a separate PR that adds that test case and fixes the problem in hthor, independent of your change and mine.

**Comment by ghalliday** [comment]
@jakesmith the fix for hthor was merged into master (7.8) which is why this is still failing.  So the simplest fix is probably to remove the test case, and merge this.  However master isn't currently failing - so I'm not convinced that this example triggers the thor issue anyway.

**Comment by jakesmith** [comment]
@ghalliday - a little confused here

You said:
>However master isn't currently failing - so I'm not convinced that this example triggers the thor issue anyway.

but the new ECL test case in childindex.ecl, is only in this PR ( it was merged into this PR following comment: https://github.com/hpcc-systems/HPCC-Platform/pull/13175#issuecomment-558059556 )

**Comment by ghalliday** [comment]
It was also merge as part of PR https://github.com/hpcc-systems/HPCC-Platform/pull/13188, and master doesn't show any problems in thor.

**Comment by ghalliday** [comment]
@jakesmith see reply

**Comment by jakesmith** [comment]
Have re-pushed to retest PR.

>and master doesn't show any problems in thor.
@ghalliday - I can reproduce the crash on master.
OBT isn't hitting it because only occurs when handling a 1-way index in a CQ, and OBT is 4/4.

**Comment by ghalliday** [comment]
@richardkchapman what is the best solution?  To merge this, but with the test disabled on hthor (and restore in 7.8).

**Comment by richardkchapman** [comment]
@ghalliday Either that or backport the hthor fix to 7.4.x

**Comment by ghalliday** [comment]
@jakesmith can you add a //nohthor to the test case, and then we'll remove it in 7.6.x.

**Comment by jakesmith** [comment]
@ghalliday - amended regression test with //nohthor

**Pull request merged**
