### PR TITLE
HPCC-14758 Various enhancements to wsesdlconfig

### PR DESCRIPTION
**Pull request by rpastrana**
- Prevents core in pubishESDLBinding
- Enhances several error messages

Signed-off-by: rpastrana rodrigo.pastrana@lexisnexis.com

### CODE REVIEW

**Comment by rpastrana** [comment]
@wangkx please review.

**Comment by wangkx** [comment]
@rpastrana two questions.

**Comment by rpastrana** [comment]
@wangkx please review changes based on code review.

**Comment by wangkx** [comment]
@rpastrana looks good now.

**Comment by rpastrana** [comment]
@richardkchapman this PR is ready to be merged.

**Pull request merged**
