### PR TITLE
HPCC-32722 Spurious errors from helm lint with certificates enabled

### PR DESCRIPTION
**Pull request by richardkchapman**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [x] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Using helm lint

### CODE REVIEW

**Review by ghalliday — COMMENTED** [review]
Please can you check in a test file to testing/helm/tests that would provoke the problem.

**Review by ghalliday — APPROVED** [review]
Please squash.
I wonder if this should traget 9.6.x though.  Asking @jakesmith for a second opinion.

**Comment by richardkchapman** [comment]
Squashed

**Comment by jakesmith** [comment]
Looks correct - but am unsure why it hasn't caused problems in practice. Is the issue helm version dependent?
On latest master:
```
helm lint hpcc hpcc/hpcc --set global.image.version=latest --set certificates.enabled=true 
```
is not reproducing the issue for me.

Regardless, looks sensible and safe to me, and could target 9.6

**Comment by ghalliday** [comment]
@jakesmith I wonder if it means that the second configuration file (that follows the invalid separator) is actually being ignored.  If so it would be more of a serious issue.

**Comment by jakesmith** [comment]
@ghalliday - not sure what happened when I previously ran. I just reran and now do see the linting issues :confused:

```
$ helm lint hpcc hpcc/hpcc --set global.image.version=latest --set certificates.enabled=true
==> Linting hpcc
[ERROR] templates/esp.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: apps/v1
[ERROR] templates/esp.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: apps/v1
[ERROR] templates/esp.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: apps/v1
[ERROR] templates/esp.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: apps/v1
[ERROR] templates/esp.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: apps/v1
[WARNING] templates/issuers.yaml: object name does not conform to Kubernetes naming requirements: "": metadata.name: Invalid value: "": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
[WARNING] templates/issuers.yaml: object name does not conform to Kubernetes naming requirements: "": metadata.name: Invalid value: "": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

==> Linting hpcc/hpcc
Error unable to check Chart.yaml file in chart: stat hpcc/hpcc/Chart.yaml: no such file or directory

Error: 2 chart(s) linted, 2 chart(s) failed
```

**Review by ghalliday — APPROVED** [review]

**Pull request merged**
