### PR TITLE
HPCC-15593 Adding HU, and ZH translations.

### PR DESCRIPTION
**Pull request by kunalaswani**
Adding HU, and ZH translations.

Signed-off by: Kunal Aswani kunal.aswani@lexisnexis.com

### CODE REVIEW

**Comment by kunalaswani** [comment]
@miguelvazq Please review

**Comment by miguelvazq** [comment]
Looks good.

**Comment by miguelvazq** [comment]
FYI @GordonSmith

**Comment by GordonSmith** [comment]
Looks good.

**Pull request merged**
