### PR TITLE
HPCC-13833 Add description and owner to groups

### PR DESCRIPTION
**Pull request by miguelvazq**
Add ability to add description and owner/managed by required fields to creation of groups in LDAP. Also, display them in the grid for users to see this information.

Signed-off by: Miguel Vazquez miguel.vazquez@lexisnexis.com

### CODE REVIEW

**Comment by miguelvazq** [comment]
@GordonSmith Please review

**Comment by GordonSmith** [comment]
Looks fine

**Comment by miguelvazq** [comment]
Added a placeholder to the managed by field for users. This will be documented by @g-pan

**Comment by GordonSmith** [comment]
Looks fine

**Pull request merged**
