### PR TITLE
HPCC-16434 Coverity: Resource leak

### PR DESCRIPTION
**Pull request by richardkchapman**
Fixed memory leak pointed out by coverity.

Signed-off-by: Richard Chapman <rchapman@hpccsystems.com>

### CODE REVIEW

**Comment by richardkchapman** [comment]
@mckellyln Please review

**Comment by mckellyln** [comment]
@richardkchapman good find.  I approve change.

**Comment by richardkchapman** [comment]
@ghalliday Please review/merge (into 6.2.0 if you think suitable...)

**Comment by ghalliday** [comment]
@richardkchapman it probably should go into 6.2 - I think it will cause a leak every minute of inactivity if dafilesrv is running in ssl mode.

**Comment by richardkchapman** [comment]
@ghalliday Retargetted to 6.2.0

**Pull request merged**
