### PR TITLE
HPCC-13749 Add missing dependencies between definitions

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@jamienoss please review

**Comment by jamienoss** [comment]
@ghalliday did you run the reg suite over this for sanity?

**Comment by ghalliday** [comment]
@jamienoss Yes, and it showed lots of missing items.  (I always run the private regression suite with this option enabled by default.)

**Comment by jamienoss** [comment]
@richardkchapman this is good to merge.

**Pull request merged**
