### PR TITLE
HPCC-28802 Install vcpkg third party headers

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Review by dcamper — APPROVED** [review]
Looks good.

**Comment by richardkchapman** [comment]
Will this install only the "outward facing" headers for these libraries, or are we going to have every header used in any third-party library when it is built from source?

The former is probably ok, the latter feels like it would be a nightmare (both from a namespace pollution and a size perspective).

**Comment by dcamper** [comment]
@richardkchapman The headers need to be complete at compile time, so I would think that all headers for a library would need to be available because the "public" header may include "private" headers from the same build.

This is really a nasty problem, especially when you consider conditional library inclusion -- different platform builds get different subsets of the 3rd party libraries we're building -- and cross-library dependencies.  For instance, libicu may require libfoo.so, but libfoo.so is used on only some of our platform builds for whatever reason, and libfoo.so is provided by the OS everywhere.  Because libfoo is needed by some of our builds, we build it separately so the headers are present, but then we only conditionally install it.  That scenario may not exist in the real world, but it is a logical possibility.

Installing all 3rd party headers actually inverts the problem the Jira defined:  Instead of old (OS-provided) headers and new libraries supplied by us, we will now have a scenario where new headers (provided by us) are used with old (OS-provided) libraries.

I don't have a good solution here.  I just wanted to get some thoughts recorded.

**Comment by GordonSmith** [comment]
> Will this install only the "outward facing" headers for these libraries, or are we going to have every header used in any third-party library when it is built from source?
> 
> The former is probably ok, the latter feels like it would be a nightmare (both from a namespace pollution and a size perspective).

This is the current behaviour (which is sub optimal, but will get better):
1. We list all the third-party dependencies directly referenced by HPCC in vcpkg.json
2. Prior to building HPCC, these dependencies are expanded to include their dependencies (recursively) 
3. This longer list is then downloaded, built and installed to the build folder
4. Then HPCC-Platform is built
5. When creating the install scripts and/or install packages, library dependencies are checked against the vcpkg install and when matched they get added to install package (this is done via LDD or similar).
6. We add ALL the vcpkg installed headers to the package (I had started to see if I could filter this list to match the potentially smaller list of installed third party libs - but ran out of time).

Note:  These headers and libraries only come into play when ECL Workunits are compiled that have embedded c++ that `#include` a library from the vcpkg list.

**Review by ghalliday — APPROVED** [review]
@GordonSmith Approving, but created another jira to see if we can reduce the size.

**Pull request merged**
