### PR TITLE
HPCC-18738 Pass current user creds, if no foreign creds available

### PR DESCRIPTION
**Pull request by jakesmith**
## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Tested in Eclwatch and using a ECL query that performed a remote copy fie File.Std.Copy, against a system with LDAP authentication on that denied the default user.
Without this fix, a 'Lookup access denied for' error is thrown.

### CODE REVIEW

**Comment by jakesmith** [comment]
@richardkchapman - please review

**Comment by richardkchapman** [comment]
@RussWhitehead Please review

**Review by RussWhitehead — COMMENTED** [review]
These look good, but there is another suspicious one in dfuwu.cpp, getFileDescriptor

**Comment by richardkchapman** [comment]
@AttilaVamos Any idea why smoketest failed?

**Comment by richardkchapman** [comment]
@jakesmith Can you respond to Russ's comment

**Comment by jakesmith** [comment]
>These look good, but there is another suspicious one in dfuwu.cpp, getFileDescriptor

@RussWhitehead  - did you mean this code in getFileDescriptor ? : 
```
                StringBuffer username;
                StringBuffer password;
                if (!isforeign||!getForeignUser(username,password)) {
                    parent->getUser(username);
                    parent->getPassword(password);
                }
                userdesc->set(username.str(),password.str());
                Owned<IDistributedFile> file = queryDistributedFileDirectory().lookup(lfn,userdesc);
```

If so, I don't see a similar problem there, it is already passing the wuid creds if no foreign creds supplied.

**Comment by jakesmith** [comment]
Re. the smoketest failure, this is in the gist zap report logs:
```
00023ACD 2017-11-15 15:24:24.284 10208 10215 "jsocket(9,2453) shutdown err = 107 : C!:56594 -> 10.241.40.11:20100 (11)"
00023ACE 2017-11-15 15:24:24.284 10208 10215 "WARNING: closeSocket() : Ignoring shutdown error"
00023ACF 2017-11-15 15:24:24.285 10208 10208 "ERROR: 4: MP link closed (10.241.40.11:20100)"
00023AD0 2017-11-15 15:24:24.285 10208 10208 "Posting exception: MP link closed (10.241.40.11:20100) to agent 10.241.40.11 for workunit(W20171115-152420)"
```

Unfortunately the ZAP report doesn't have the slave log.
@AttilaVamos - is it available somewhere ?
And can we change the ZAP report to include slave logs for capture of future smoketest failures?

**Comment by AttilaVamos** [comment]
@jakesmith logs are emailed to you. Theoretically the include slave logs is default for Regression Test Engine. I will check why it is missing.

**Comment by RussWhitehead** [comment]
@jakesmith You are correct it is passing the creds. This PR looks good to me

**Comment by jakesmith** [comment]
This is the stack trace from the slave log:
```
0003E84B 2017-11-15 15:24:22.919 10203  6716 "================================================"
0003E84C 2017-11-15 15:24:22.919 10203  6716 "Program:   10.241.40.11:/opt/HPCCSystems/bin/thorslave_lcr"
0003E84D 2017-11-15 15:24:22.919 10203  6716 "Signal:    11 Segmentation fault"
0003E84E 2017-11-15 15:24:22.919 10203  6716 "Fault IP:  00007F744E227DF7"
0003E84F 2017-11-15 15:24:22.919 10203  6716 "Accessing: 00007F6481C3BA08"
0003E850 2017-11-15 15:24:22.919 10203  6716 "Backtrace:"
0003E851 2017-11-15 15:24:22.919 10203  6716 "  /lib64/libpthread.so.0(pthread_detach+0x17) [0x7f744e227df7]"
0003E852 2017-11-15 15:24:22.919 10203  6716 "  /opt/HPCCSystems/lib/libtbb.so.2(_ZN3rml8internal14thread_monitor13detach_threadEm+0x9) [0x7f744ec75209]"
0003E853 2017-11-15 15:24:22.919 10203  6716 "  /opt/HPCCSystems/lib/libtbb.so.2(+0x1aa7c) [0x7f744ec75a7c]"
0003E854 2017-11-15 15:24:22.919 10203  6716 "  /lib64/libpthread.so.0(+0x7bc2) [0x7f744e226bc2]"
0003E855 2017-11-15 15:24:22.919 10203  6716 "  /lib64/libpthread.so.0(+0x7dd3) [0x7f744e226dd3]"
0003E856 2017-11-15 15:24:22.919 10203  6716 "  /lib64/libc.so.6(clone+0x6d) [0x7f744df53ced]"
0003E857 2017-11-15 15:24:22.919 10203  6716 "Registers:"
0003E858 2017-11-15 15:24:22.919 10203  6716 "EAX:0000000000000000  EBX:000000000000007E  ECX:00007F744DF4E469  EDX:0000000000000003  ESI:0000000000000000  EDI:00007F6481C3B700"
0003E859 2017-11-15 15:24:22.919 10203  6716 "R8 :0000000000000000  R9 :0000000000000000  R10:0000000000000000  R11:0000000000000246"
0003E85A 2017-11-15 15:24:22.919 10203  6716 "R12:0000000000000000  R13:00007F744E4362E8  R14:0000000000000004  R15:000000000000001E"
0003E85B 2017-11-15 15:24:22.919 10203  6716 "CS:EIP:0033:00007F744E227DF7"
0003E85C 2017-11-15 15:24:22.919 10203  6716 "   ESP:00007F648017C4E8  EBP:00007F6480576580"
0003E85D 2017-11-15 15:24:22.919 10203  6716 "Stack[00007F648017C4E8]: 00007F744EC75209 8057658000007F74 00007F6480576580 4EC75A7C00007F64 00007F744EC75A7C 0000000000007F74 0000000000000000 8017DA3800000000"
0003E85E 2017-11-15 15:24:22.919 10203  6716 "Stack[00007F648017C508]: 00007F648017DA38 4E43630800007F64 00007F744E436308 4E226BC200007F74 00007F744E226BC2 4C5AFB2800007F74 00007F744C5AFB28 0000000000007F74"
0003E85F 2017-11-15 15:24:22.919 10203  6716 "Stack[00007F648017C528]: 0000000000000000 0000000000000000 0000000000000000 0000000000000000 0000000000000000 8017D9C000000000 00007F648017D9C0 8017D70000007F64"
0003E860 2017-11-15 15:24:22.919 10203  6716 "Stack[00007F648017C548]: 00007F648017D700 4C5AFB3000007F64 00007F744C5AFB30 4E226DD300007F74 00007F744E226DD3 0000000000007F74 0000000000000000 8017D70000000000"
0003E861 2017-11-15 15:24:22.919 10203  6716 "Stack[00007F648017C568]: 00007F648017D700 8017D70000007F64 00007F648017D700 D65436BA00007F64 A0FD04A3D65436BA 00000000A0FD04A3 0000000000000000 8017D9C000000000"
0003E862 2017-11-15 15:24:22.919 10203  6716 "Stack[00007F648017C588]: 00007F648017D9C0 8017D70000007F64 00007F648017D700 4C5AFB3000007F64 00007F744C5AFB30 5C9436BA00007F74 5E34048C5C9436BA 0D4E36BA5E34048C"
0003E863 2017-11-15 15:24:22.919 10203  6716 "Stack[00007F648017C5A8]: 5E1598E70D4E36BA 000000005E1598E7 0000000000000000 0000000000000000 0000000000000000 0000000000000000 0000000000000000 0000000000000000"
0003E864 2017-11-15 15:24:22.919 10203  6716 "Stack[00007F648017C5C8]: 0000000000000000 0000000000000000 0000000000000000 0000000000000000 0000000000000000 0000000000000000 0000000000000000 0000000000000000"
0003E865 2017-11-15 15:24:22.919 10203  6716 "ThreadList:
7F744C41A700 140137472304896 10211: CMPNotifyClosedThread
7F7449C19700 140137430357760 10212: CSocketBaseThread
7F7447418700 140137388410624 10213: MP Connection Thread
7F7444C17700 140137346463488 10226: CMemoryUsageReporter
7F648A995700 140069798762240 10230: CGraphProgressHandler
"
```

**Comment by AttilaVamos** [comment]
@jakesmith the Regression Test Engine zapgen include Thor slaves feature merged into 7.0.0. Your PR is 6.4.6 that's why slave log is not in ZAP file.

**Comment by jakesmith** [comment]
>Thor slaves feature merged into 7.0.0. Your PR is 6.4.6 that's why slave log is not in ZAP file.

@AttilaVamos - ok thanks.

**Pull request merged**
