### PR TITLE
HPCC-17137 Improve efficiency of registerTimer

### PR DESCRIPTION
**Pull request by richardkchapman**
No need to look up the activity - it is always the current one.

Signed-off-by: Richard Chapman <rchapman@hpccsystems.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [x] Performance
  - [x] Security
  - [x] Thread-safety
  - [x] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:
Ran full roxie regression suite. Stepped through one case to ensure correct code path was taken.

### CODE REVIEW

**Comment by richardkchapman** [comment]
Seeing some cores from regression suite at the moment - investigating

**Comment by richardkchapman** [comment]
Yuk - indirect code context didn't intercept everything... that was a nasty one!

**Comment by richardkchapman** [comment]
@AttilaVamos What happened on smoketest?

**Comment by AttilaVamos** [comment]
It was a network error, not related to this PR. 
At the beginning of build thes happened:
```
-- LIBMEMCACHED_LIBRARIES (missing:  LIBMEMCACHED_INCLUDE_DIR LIBMEMCACHED_VERSION_OK) 
CMake Error at cmake_modules/FindLIBMEMCACHED.cmake:94 (message):
  Fatal Error: download of
  https://launchpad.net/libmemcached/1.0/1.0.10/+download/libmemcached-1.0.10.tar.gz
  failed

                  status_code: 28
                  status_msg: "Timeout was reached"
                  log:   Trying 91.189.89.223...

  Connected to launchpad.net (91.189.89.223) port 443 (#0)
```
Test rescheduled.

**Comment by richardkchapman** [comment]
@ghalliday Please review/merge

**Pull request merged**
