### PR TITLE
HPCC-15003 Secmanager should remove superflous artifacts

### PR DESCRIPTION
**Pull request by RussWhitehead**
There are several security manager artifacts that were "work in progress" at
some point in the past. They are not used and there is no reason to keep them
around, so this PR removes all references to them

Signed-off-by: Russ Whitehead william.whitehead@lexisnexis.com

### CODE REVIEW

**Comment by RussWhitehead** [comment]
@rpastrana Please review

**Comment by rpastrana** [comment]
@RussWhitehead just one minor comment. Also, I noticed the base secmanager implementation contains many superfluous member vars, perhaps it would be worth cleaning up that class as well?

**Comment by RussWhitehead** [comment]
@rpastrana Please rereview

**Comment by rpastrana** [comment]
@RussWhitehead reviewed.

**Comment by RussWhitehead** [comment]
@rpastrana Please rereview

**Comment by rpastrana** [comment]
@RussWhitehead reviewed, no issue with latest commit.

**Comment by RussWhitehead** [comment]
@richardkchapman Please merge and close

**Pull request merged**
