### PR TITLE
HPCC-16041 Indicate if inline tables can be filtered

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@jakesmith please check Thor change,  @shamser please review the code gen

**Comment by shamser** [comment]
@ghalliday dataset_transform.xml no longer reflect the results from dataset_transform.ecl.

**Comment by ghalliday** [comment]
Thanks,  I'll investigate

**Comment by ghalliday** [comment]
Thanks - I thought I had modified a non runtime test.  I'll release a fix.

**Comment by ghalliday** [comment]
@shamser try again!

**Comment by shamser** [comment]
@ghalliday @richardkchapman All good now.

**Comment by richardkchapman** [comment]
@jakesmith Over to you for the thor changes

**Comment by jakesmith** [comment]
Thor change is good.

@richardkchapman - ready to merge.

**Pull request merged**
