### PR TITLE
HPCC-16354 Fix internal error triggered by SORT(ds, x, -x)

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

### CODE REVIEW

**Comment by ghalliday** [comment]
@shamser please review.
Note: This is depenendent on https://github.com/hpcc-systems/HPCC-Platform/pull/9294 (which is targeted for 6.2)

**Comment by shamser** [comment]
@ghalliday Why would DS be sorted by (field,-field) order?

**Comment by ghalliday** [comment]
It is if you have a dataset sort sorted by

 x, -score, record

which will be expanded out to

x, -score, y, score, z,

**Comment by ghalliday** [comment]
See issue16354.eclxml in the private regression suite.

**Comment by ghalliday** [comment]
@richardkchapman

**Pull request merged**
