### PR TITLE
HPCC-24998 Ensure librdkafka is rebuilt if underlying code changes

### PR DESCRIPTION
**Pull request by dcamper**
Also fix minor formatting errors

Signed-off-by: Dan S. Camper <dan.camper@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Manual testing

### CODE REVIEW

**Comment by dcamper** [comment]
@richardkchapman Please review.  Thanks!

**Comment by richardkchapman** [comment]
@Michael-Gardner Can you review this

**Comment by Michael-Gardner** [comment]
@dcamper Tested and it seems to work well. I like the idea about keeping the file timestamps when we copy it over.  Something I'll have to look into for other submodules that want to be built 'in-source' that we copy into /build.  From this point forward (7.12.x) it looks like a worthwhile change. Only comment I have is if we perhaps want to put it back towards 7.8.x and then merge it forward? I think there's still active bug fixes going on there looking at our builds. Might not be worth it, up to you.

**Comment by dcamper** [comment]
I'm not sure what prompted this Jira, but I don't think the underlying cause -- librdkafka source changing without anyone noticing -- is common outside of a developer's environment.  I don't think it is worth back-porting to 7.8.x.

@richardkchapman Please merge, unless you _do_ think that it should be back-ported.

**Comment by richardkchapman** [comment]
It was prompted by me getting build errors when switching between branches, because there was code introduced in the plugin (in commit https://github.com/hpcc-systems/HPCC-Platform/commit/9f0e3d8b70d3a6e1d480ec1c8e47ef3d8e35d9ad ) that relied on the latest version of the kafka library...

It looks like the last time the submodule was updated was between 7.6.x and 7.8.x

Given that fixes are still being made in 7.8.x, it probably makes sense for the change to target that version - then we should be good going forwards.

**Comment by dcamper** [comment]
@richardkchapman Retargeted to 7.8.x.

**Comment by AttilaVamos** [comment]
@dcamperSomething strange is happening with this PR. After the platform package build and installed, the PR work directory's owner and group suddenly changed from centos:centos to root:root and then the Smoketest is losing the right to do anything inside it. 
Did you build and install a package in your environment? If not please do me a favour and do it to see this problem is reproducible outside the Smoketest.

Perhaps it is not related, but during the package generation I see this kind of warnings:
```
CPack: Create package
CMake Warning (dev) at /usr/local/share/cmake-3.13/Modules/Internal/CPack/CPackRPM.cmake:135 (message):
  CPackRPM:Warning: Path
  /home/centos/smoketest/PR-14363/build/plugins/kafka/include/librdkafka/rdkafka.h
  is not on one of the relocatable paths! Package will be partially
  relocatable.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.13/Modules/Internal/CPack/CPackRPM.cmake:1001 (cpack_rpm_prepare_relocation_paths)
  /usr/local/share/cmake-3.13/Modules/Internal/CPack/CPackRPM.cmake:1870 (cpack_rpm_generate_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/local/share/cmake-3.13/Modules/Internal/CPack/CPackRPM.cmake:135 (message):
  CPackRPM:Warning: Path
  /home/centos/smoketest/PR-14363/build/plugins/kafka/include/librdkafka/rdkafka_mock.h
  is not on one of the relocatable paths! Package will be partially
  relocatable.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.13/Modules/Internal/CPack/CPackRPM.cmake:1001 (cpack_rpm_prepare_relocation_paths)
  /usr/local/share/cmake-3.13/Modules/Internal/CPack/CPackRPM.cmake:1870 (cpack_rpm_generate_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by dcamper** [comment]
@AttilaVamos I was not able to duplicate this under Ubuntu.  My CentOS dev env is broken so I was unable to test there.

The source of the problem is likely the new -p argument for cp.  Under Linux, that causes cp to retain a source's mode, ownership, and timestamps.

I've just pushed a commit that separates Apple and non-Apple cp options.  For non-Apple, only mode and timestamp is preserve.  Please test.

**Comment by dcamper** [comment]
Update: I was able to build the plugin under CentOS 8 without problems.

But, my librdkafka submodule is owned by the same user as is building the plugin.  Your submodule is likely owned by root.

**Comment by AttilaVamos** [comment]
@dcamper Can you build and install the platform package as well?
Unfortunately your latest commit has same problem.

**Comment by dcamper** [comment]
What installation command are you using?  My 'sudo make install' is unlikely to show a problem relating to ownership.

**Comment by AttilaVamos** [comment]
@dcamper use "make package"  then  "sudo rpm -i --nodeps <hpccsystems-platform-xxx.rpm>"

**Comment by dcamper** [comment]
add_custom_target() is the culprit.  It is adding the source lib/ and include/ directories to the package (both .rpm and .deb).  I'm trying to find a workaround now.

**Comment by AttilaVamos** [comment]
@dcamper Thanks

**Comment by dcamper** [comment]
@Michael-Gardner @AttilaVamos I've revamped the "figure out if things changed" algorithm; please review this latest commit.

The underlying problem turned out to be the 'make install' target within librdkafka.  That library _always_ performs tests, which in turn makes the libraries dirty, no matter what.  The dirty libraries are seen by cpack during 'make package' so librdkafka was always relinked and cpack included everything recreated by librdkafka whether it really changed or not.  That's where the non-relocatable directories and files came from.

This latest modification explicitly computes and compares md5 checksums for copied source files, then triggers librdkafka's make/make install only when necessary.  I suspect that this explicit checking is required only for librdkafka, not (necessarily) for any other build-in-place submodules we include.

**Review by AttilaVamos — APPROVED** [review]
It seems good to merge.

**Comment by richardkchapman** [comment]
@Michael-Gardner Can you approve?

**Review by Michael-Gardner — APPROVED** [review]
@dcamper This looks good and ready for merge

**Comment by richardkchapman** [comment]
@dcamper Can you squash please. Is 7.8.x still the appropriate target for this or would 7.12.x or master be better?

**Comment by AttilaVamos** [comment]
I think the regression errors are not related to the changes in this PR.

**Comment by dcamper** [comment]
> @dcamper Can you squash please. Is 7.8.x still the appropriate target for this or would 7.12.x or master be better?

I think 7.12.x is more appropriate, but you mentioned on Dec. 2 that 7.8 may be a better target.  Your call:  What should the target be?

**Comment by dcamper** [comment]
Squashed.

**Comment by AttilaVamos** [comment]
I think the workflow_contingency_8 errors are not related to this PR.

**Comment by AttilaVamos** [comment]
@dcamper It seems the base of your PR is still 7.8.x

**Pull request merged**
