### PR TITLE
HPCC-13685 Support whitespace separated JSON objects at file root level

### PR DESCRIPTION
**Pull request by afishbeck**
Signed-off-by: Anthony Fishbeck anthony.fishbeck@lexisnexis.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@jakesmith Please review

**Comment by jakesmith** [comment]
From JIRA : 
> It's somewhat common that JSON files come in the form:
> {}\n{}\n{}
> Which isn't itself valid JSON but contains JSON objects

As this isn't valid JSON, I am wondering if not better handled outside of this JSON parser..

You could for example handle by parsing until error (invalid JSON) character, parsing the foreign format (e.g. '{'), then continuing.. to parse the next JSON stream.

**Comment by jakesmith** [comment]
Back to you @afishbeck

**Comment by afishbeck** [comment]
@jakesmith I think it's convenient to support this universally, but perhaps I could just add a flag?  It's basically supporting the common JSON file format which is a superset of JSON only differing at the root level.  A flag would allow us to distinguish and give errors for invalid JSON object format when we weren't expecting the file format.

**Comment by jakesmith** [comment]
@afishbeck - not sure what the 'common JSON file format' is, but if it's that common in JSON files, then perhaps it's okay as it is..
I'll leave it up to you to decide if flag worthy or not.

**Comment by afishbeck** [comment]
@jakesmith It seems quite common and people have tried to make it a standard.  For example:  http://jsonlines.org/  and https://en.wikipedia.org/wiki/Line_Delimited_JSON.  I don't think I'll add a flag for now, but could add something more like a "strict" flag later so we can generate errors when entries are not comma delimited.

**Comment by jakesmith** [comment]
Ok

**Pull request merged**
