### PR TITLE
HPCC-30143 Fix Capitalization inconsistencies in LR

### PR DESCRIPTION
**Pull request by JamesDeFabia**
## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Review by g-pan — APPROVED** [review]
Approved.

**Comment by ghalliday** [comment]
@JamesDeFabia there are a couple of examples of "output(" as well

**Comment by ghalliday** [comment]
/home/gavin/dev/hpcc/docs/EN_US/ECLReference/ECL_Error.xml
  2949,11:       02: output(MyModule.SmallPersonSet);
/home/gavin/dev/hpcc/docs/EN_US/ECLStandardLibraryReference/SLR-Mods/CountWords.xml
  72,1: output(LENGTH(TRIM(Str1,LEFT,RIGHT)) - LENGTH(TRIM(Str1,ALL)) + 1);
/home/gavin/dev/hpcc/docs/EN_US/ECLStandardLibraryReference/SLR-Mods/WordCount.xml
  64,1: output(LENGTH(TRIM(Str1,LEFT,RIGHT)) - LENGTH(TRIM(Str1,ALL)) + 1);
/home/gavin/dev/hpcc/docs/EN_US/HPCC4J/HPCC4J_Mods/HPCC4J_Use.xml
  35,13:  wu.setECL("output('Hello World');"); // The ECL to execute.
/home/gavin/dev/hpcc/docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
  545,60:               text (including the quotes): <programlisting>output('Hello world'); </programlisting></para>
/home/gavin/dev/hpcc/docs/PT_BR/ECLStandardLibraryReference/SLR-Mods/CountWords.xml
  56,1: output(LENGTH(TRIM(Str1,LEFT,RIGHT)) - LENGTH(TRIM(Str1,ALL)) + 1);
/home/gavin/dev/hpcc/docs/PT_BR/ECLStandardLibraryReference/SLR-Mods/WordCount.xml
  64,1: output(LENGTH(TRIM(Str1,LEFT,RIGHT)) - LENGTH(TRIM(Str1,ALL)) + 1);
/home/gavin/dev/hpcc/docs/PT_BR/HPCC4J/HPCC4J_Mods/HPCC4J_Use.xml
  35,13:  wu.setECL("output('Hello World');"); // The ECL to execute.
/home/gavin/dev/hpcc/docs/PT_BR/HPCCClientTools/CT_Mods/CT_Comm_Line_ECL.xml
  242,1: output(ds, ,'testdata::namesdb');</programlisting>
  259,1: output(ds1);</programlisting>
/home/gavin/dev/hpcc/docs/PT_BR/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
  559,60:               seguir (incluindo as aspas): <programlisting>output('Hello world'); </programlisting></para>

**Review by g-pan — APPROVED** [review]
Reviewed, and Approved.

**Comment by JamesDeFabia** [comment]
> ```
> /home/gavin/dev/hpcc/docs/EN_US/ECLReference/ECL_Error.xml
>   2949,11:       02: output(MyModule.SmallPersonSet);
> /home/gavin/dev/hpcc/docs/EN_US/ECLStandardLibraryReference/SLR-Mods/CountWords.xml
>   72,1: output(LENGTH(TRIM(Str1,LEFT,RIGHT)) - LENGTH(TRIM(Str1,ALL)) + 1);
> /home/gavin/dev/hpcc/docs/EN_US/ECLStandardLibraryReference/SLR-Mods/WordCount.xml
>   64,1: output(LENGTH(TRIM(Str1,LEFT,RIGHT)) - LENGTH(TRIM(Str1,ALL)) + 1);
> /home/gavin/dev/hpcc/docs/EN_US/HPCC4J/HPCC4J_Mods/HPCC4J_Use.xml
>   35,13:  wu.setECL("output('Hello World');"); // The ECL to execute.
> /home/gavin/dev/hpcc/docs/EN_US/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
>   545,60:               text (including the quotes): <programlisting>output('Hello world'); </programlisting></para>
> /home/gavin/dev/hpcc/docs/PT_BR/ECLStandardLibraryReference/SLR-Mods/CountWords.xml
>   56,1: output(LENGTH(TRIM(Str1,LEFT,RIGHT)) - LENGTH(TRIM(Str1,ALL)) + 1);
> /home/gavin/dev/hpcc/docs/PT_BR/ECLStandardLibraryReference/SLR-Mods/WordCount.xml
>   64,1: output(LENGTH(TRIM(Str1,LEFT,RIGHT)) - LENGTH(TRIM(Str1,ALL)) + 1);
> /home/gavin/dev/hpcc/docs/PT_BR/HPCC4J/HPCC4J_Mods/HPCC4J_Use.xml
>   35,13:  wu.setECL("output('Hello World');"); // The ECL to execute.
> /home/gavin/dev/hpcc/docs/PT_BR/HPCCClientTools/CT_Mods/CT_Comm_Line_ECL.xml
>   242,1: output(ds, ,'testdata::namesdb');</programlisting>
>   259,1: output(ds1);</programlisting>
> /home/gavin/dev/hpcc/docs/PT_BR/Installing_and_RunningTheHPCCPlatform/Installing_and_RunningTheHPCCPlatform.xml
>   559,60:               seguir (incluindo as aspas): <programlisting>output('Hello world'); </programlisting></para>
> ```

@ghalliday I made the changed you requested and deleted a very old file that was never used.

**Review by ghalliday — APPROVED** [review]

**Pull request merged**
