### PR TITLE
HPCC-8396 Change default value for localThorPortInc

### PR DESCRIPTION
**Pull request by kenrowland**
Change localThorPortInc default to 20

Signed-off-by: Ken Rowland <kenneth.rowland@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [x] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by kenrowland** [comment]
@jakesmith Please review

**Comment by jakesmith** [comment]
@kenrowland - PR title should be changed as change is not just in configmgr now.

Also there a few other places that should be changed to 20 at the same time, if you search through all sources for localThorPortInc you'll find them.

There should also be a similar PR for the LN repository

**Comment by kenrowland** [comment]
@jakesmith Made a couple of additional updates. Please review. 
Also, should the 20 in the following be changed to use the #define value changed in this commit:
thorlcr/slave/slavmain.cpp:        unsigned localThorPortInc = globals->getPropInt("@localThorPortInc", 20);

**Comment by jakesmith** [comment]
yes, the one in slavemain.cpp should use #define really

There's still a couple more - initfiles/componentfiles/configxml/setvars_linux.xsl and testing/regress/environment.xml.in
@kenrowland

**Comment by kenrowland** [comment]
@richardkchapman Please merge

**Pull request merged**
