### PR TITLE
HPCC-31171 Encrypt on worker threads rather than UDP send thread

### PR DESCRIPTION
**Pull request by richardkchapman**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [x] Performance
  - [x] Security
  - [x] Thread-safety
  - [x] Cloud-compatibility
  - [x] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Using udpsim

### CODE REVIEW

**Review by ghalliday — APPROVED** [review]
Change looks good.
It is hard to know which way to default the option.  I suspect on a lightly loaded system this may reduce performance slightly - because aes encryption will no longer be executed in parallel with the code to walk the indexes.  On a heavily loaded system I suspect it will help because once the udp transport layer becomes the bottleneck, anything that speeds up the rate packets are sent is likely to help.

**Review by mckellyln — APPROVED** [review]
I think it makes sense, looks good to merge.

**Comment by richardkchapman** [comment]
On a lightly loaded system, there will be other worker threads available for walking the indexes when the AES encryption is happening. I would have thought

**Comment by ghalliday** [comment]
I think it is a good idea.  My concern is changing the way it works on a point release.  I wonder about defaulting it to remain the same for 9.4.x, but encourage business units to test enabling the option and look its effect on performance.

@richardkchapman @mckellyln 

What are your votes for merging this?

**Comment by mckellyln** [comment]
We could merge it, but leave default as-is and do some testing and change default in a future release ?
I would learn towards defaulting it on (the new method) and if there is some noticeable diff in the near term then we can disable via config.

**Comment by richardkchapman** [comment]
Feels like a smaller change than many others that have gone into the 9.4 series. I don't really mind either way but if we choose to default off in 9.4.x then we need to also release a change to change the default in master, or else it will become yet another unused option...

(Also, if we change the default at a major release rather than a minor one, it will be much harder for us to spot any negative impact - not that I think a negative impact is likely)

**Pull request merged**
