### PR TITLE
HPCC-13519 Fix crash if keyed denormalize in child query.

### PR DESCRIPTION
**Pull request by jakesmith**
A Keyed Denormalize inside a child query wasn't being initialized
correctly and crashing the slave(s).

Signed-off-by: Jake Smith jake.smith@lexisnexis.com

### CODE REVIEW

**Comment by jakesmith** [comment]
@ghalliday - please review

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by richardkchapman** [comment]
Should there be a regression suite test for this?

**Comment by ghalliday** [comment]
@richardkchapman fix looks good.  We probably should have a regression test.

**Comment by jakesmith** [comment]
Have added some child query denormalize tests to existing keyed_denormalize.ecl regression test.
@richardkchapman

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| key | Pass | Pass | Pass |
| keydiff1 | Excl. | Pass | Excl. |
| keyed_join4 | Pass | Pass | Excl. |
 
HPCC Stop: OK

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| keyed_denormalize | Pass | Pass | Pass |
 
HPCC Stop: OK

**Pull request merged**
