### PR TITLE
HPCC-13280 Fix incomplete foreign LFN for roxie cache and remote lookup

### PR DESCRIPTION
**Pull request by afishbeck**
Signed-off-by: Anthony Fishbeck anthony.fishbeck@lexisnexis.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
Is this a regression?

**Comment by afishbeck** [comment]
Not a regression.. at least it's probably been like that for a few years.

**Comment by richardkchapman** [comment]
Do the changes in 5.2 regarding when foreign is resolved change the impact of this issue in any way?

**Comment by AttilaVamos** [comment]
Automated Smoketest Build success

**Comment by afishbeck** [comment]
Not really, those files look just like files found remotely at publish time now.

But this should fix the caching of those files, and make roxie more "self healing" if an initial bad state causes roxie to try to go directly to the remote roxie to get DFS meta data using "legacy mode". (A file trying to use legacy mode is how I stumbled on this issue.)

**Comment by richardkchapman** [comment]
Ok. I was just trying to check that there was no reason we might need this to go in 5.2

**Pull request merged**
