### PR TITLE
HPCC-17151 Throw exception if Thor group not found for ZAP report

### PR DESCRIPTION
**Pull request by wangkx**
Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [x] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:
Create a WU. Rename a Thor cluster. Select "Include slave logs" when creating ZAP report for that WU.

### CODE REVIEW

**Comment by wangkx** [comment]
@afishbeck please review.

**Comment by afishbeck** [comment]
@wangkx What would cause the group not to be found?

This makes the zap file all or nothing... which I guess means that users will definitely know that something is wrong (and ask operations to fix it?).  Is that better in these cases?  Or would it be better to still return some zap content and also give an error saying couldn't resolve the group and therefore get the thor log file?  Maybe even include the error inside the zap as well?  Depends on whether there would be any value to them that way.

**Comment by wangkx** [comment]
The Group was not found due to incorrect thor process name (thor20_dev01). The environment has thor processes called thor20_dev and thor20_dev02. We believe that the thor process name was changed after the WU was created.

The ZAP report does work if not including thor slave log.

**Comment by afishbeck** [comment]
Ok I guess it's not that valuable without it, and this at least lets users who don't quite understand what should be in it to know that a full report can't be generated.

**Review by afishbeck — APPROVED** [review]
@wangkx looks fine.

**Comment by wangkx** [comment]
@richardkchapman this PR is ready to be merged.

**Pull request merged**
