### PR TITLE
HPCC-13486 Fix memory leaks in wuwebview

### PR DESCRIPTION
**Pull request by wangkx**
The code is added to fix the memory leaks.

Signed-off-by: wangkx kevin.wang@lexisnexis.com

### CODE REVIEW

**Comment by wangkx** [comment]
@afishbeck please review.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by afishbeck** [comment]
@wangkx looks good.

**Comment by wangkx** [comment]
@richardkchapman this pull request is ready to merge.

**Pull request merged**
