### PR TITLE
HPCC-16811 Provide functions to extract values from a typed field

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

### CODE REVIEW

**Comment by ghalliday** [comment]
@shamser please review.  More work from a previous branch in preparation for #14412 changes.

**Review by shamser — COMMENTED** [review]
@ghalliday I can imagine that if getUtf8 and getInt member functions that haven't been implemented (which silently continue at present), could makes it easier for someone making changes in the future to introduce bugs.  Any reason these Unimplemented member functions are silently continuing rather than throwing an exception?

**Comment by ghalliday** [comment]
I am in two minds about those functions.  I opted for silent because of the context they are likely to be used - but could be persuaded otherwise.  The question is whether the caller should need to check the type before calling the function.

I will change RtlUnimplementedTypeInfo, but I think it makes sense for the others to return blank.

**Comment by ghalliday** [comment]
@shamser are you happy with that?

**Comment by shamser** [comment]
@ghalliday Sure. @richardkchapman  Code reviewed Ok.

**Pull request merged**
