### PR TITLE
HPCC-24895 Return session token in VerifyUser response

### PR DESCRIPTION
**Pull request by wangkx**
Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by wangkx** [comment]
@afishbeck please review

**Review by afishbeck — APPROVED** [review]
@wangkx looks fine.

**Comment by richardkchapman** [comment]
@ghalliday Can you comment?

This FEELS like it needs some extra security scrutiny to me...

**Comment by ghalliday** [comment]
I don't completely understand how the sessions work.  Is the problem that the session id is returned in a cookie, but Gordon cannot get at the cookie locally?  Because httpOnly is set?  Is this new functionality more secure than disabling that flag?

My impression is that it isn't generally recommended to provide a session id as a part of the url.  It might be logged, or accessible by someone else.  What is the plan for using this session id once he has it?  Create a cookie to be sent for the child pages?

Definitely not this commit, but I noticed the recommended session id is a 128bits string, rather than 32bits.  The current method of generating session ids could also be improved.  (And there is no check for duplicates.)

**Comment by wangkx** [comment]
The session id is returned in a cookie. But, Gordon cannot get the cookie because he is using a non browser based client application. So, in this fix, I return the session ID in the VerifyUser response. @GordonSmith could you please comment?

I just created https://track.hpccsystems.com/browse/HPCC-25010 for improving the session ID.

**Comment by GordonSmith** [comment]
In this instance I will be setting the session token into a cookie in an embedded web page (which I hope will work).

Sequence of events:
1.  Client app calls verify user and gets a valid token
2.  Client app launched embedded webpage to display ecl watch with session token embedded in cookie

This is so the ECL IDE can display an ECL Watch page without having to login again (having logged into the IDE).

**Comment by GordonSmith** [comment]
(I am not 100% sure this will work, and I may be adding a Jira to allow the session to passed via POST message as well.

**Comment by afishbeck** [comment]
With this current design I don't think it's too far from the IDE just doing what the browser does anyway, although the session token is returned to the client in a different way (in the body rather than a cookie).

If we start sending back the token in an HTTP post we could consider changing the token into a new kind of signed token explicitly for this purpose.  Kind of like an oath token.  Gordon calls ESP to get the auth token, and then passes it through the browser to log the user in.  And that's when the session cookie gets created.

Or, we could do that anyway, even if Gordon doesn't need to use POST.

**Comment by afishbeck** [comment]
I'm thinking we restrict this as much as we can.. and make it a more formal REST/SOAP login mechanism.  I don't think the current function even quite works for what Gordon wanted anyway since it returns an existing session which is the opposite of what we want for the IDE and for security.

Perhaps:
1. Instead of VerifyUser, create a new explicit REST/SOAP login function.. something like ClientLogin.
2. Can only be used from REST clients to do a fresh login.  Cannot be used to get my "current session id" especially from an ESP browser application.
3. As a REST client credentials will be there for the request... not an existing cookie.  Kevin can enforce that.
4. The token should be verifiable that it was created by ESP and has an entry in the DALI session store.
5. Ideally we would only support this over HTTPS.  Is that at all feasible at this point?
--- stage 2 --
6. When the token gets used it should have to come from the same origin IP as the login request.
7. We should never accept the token as a URL parameter.  Ideally the token would be passed in as credentials, not as part of the message.  Like as bearer token or as password.. and should only be accepted by one method...
We could add a another new method like StartClientSession that takes the login token as its credential and basically turns it into a session cookie.  With the same restrictions about IP, etc.  But comes from a browser that isn't logged in and logs it in.

After one time use, the token then is no longer useful for anything else. (session in dali is now in active state)

From Gordon's perspective he would
1. Make a REST/SOAP call to the login function and get a token.
2. Direct the browser to the StartClientSession method with the token as the credential.

**Comment by GordonSmith** [comment]
@afishbeck this sounds plausible - it also sounds similar to some of the bigger oauth type stuff we are looking at for the cloud?  
Given this isn't high priority should we be waiting for the "full" solution, or do you see this as being different enough?

**Comment by afishbeck** [comment]
@GordonSmith if this can wait for our OAUTH solution, and doesn't need to work with non-oauth environments then that would be ideal.  We need to solve OAUTH for command line and other clients as well.

**Comment by GordonSmith** [comment]
@afishbeck I am ok with that.

**Comment by wangkx** [comment]
Based on the latest comments, I am closing this PR.

**Pull request closed without merging**
