### PR TITLE
HPCC-13462 Add ability filter by DFUWUID

### PR DESCRIPTION
**Pull request by wangkx**
Using this fix, in ESP FileSpray.GetDFUWorkunits, a user may filter
DFU Workunits by wuid.

Signed-off-by: wangkx kevin.wang@lexisnexis.com

### CODE REVIEW

**Comment by wangkx** [comment]
@miguelvazq @RussWhitehead please review.

**Comment by wangkx** [comment]
@RussWhitehead I just added the check for '*clusterName'. Please review again.

**Comment by RussWhitehead** [comment]
Looks good

**Comment by richardkchapman** [comment]
@miguelvazq Have you looked at this?

**Comment by miguelvazq** [comment]
I can pull in branch and test. This language I am not familiar with.

**Comment by richardkchapman** [comment]
I was more wondering if it provided the functionality you would need

**Comment by miguelvazq** [comment]
Should be easy to test I already have my code in place. Let cherry-pick this branch.

**Comment by miguelvazq** [comment]
@richardkchapman I have tested this and it provides the functionality I need.

**Pull request merged**
