### PR TITLE
HPCC-25048 Ensure dfu despray wrap option generates multiple file parts

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
@wangkx please review.

**Comment by wangkx** [comment]
@ghalliday the code looks fine. 

I did  a few tests. When the wrap=1, the file name generated by the despray does contain the "._$P$_of_$N$". But, when no wrap=1, no file is created by the despray. I am not sure whether the problem is related or not.
No matter the wrap=1 or not, the despray returns an error: SSH failed to connect 192.168.44.233: /opt/HPCCSystems/bin/run_ftslave 192.168.44.233 13 0 6411 D20210105-104557 /var/log/HPCCSystems/mydfuserver.

**Comment by ghalliday** [comment]
@wangkx did the same command work without this PR?  What command were you using.  Also, what is 192.168.44.233?

**Comment by wangkx** [comment]
I was using the command: sudo dfuplus action=despray server=192.168.44.233:8010 srcname=.::notes1.txt dstip=192.168.44.233 dstfile=/var/lib/HPCCSystems/mydropzone/notes1002.txt
The 192.168.44.233 is the IP of my local test VM.

I haven't tried the command without this PR. I am working on it now.

**Comment by wangkx** [comment]
@ghalliday the same problems happen for the latest candidate-7.12.x (without this PR). Should I create a separate JIRA?

**Comment by ghalliday** [comment]
@wangkx yes, please create a separate jira.  Did it use to work?  If so, maybe one of the recent changes broke it.

**Review by richardkchapman — APPROVED** [review]

**Pull request merged**
