### PR TITLE
HPCC-15775 Optimize count(dataset) and exists(dataset)

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@shamser please review

**Comment by richardkchapman** [comment]
Needs rebasing for a clean merge

**Comment by shamser** [comment]
@ghalliday I don't understand doBuildRowAssignAggregate so am not sure if it's correct .. everything else is fine.

**Comment by ghalliday** [comment]
The only change in doBuildRowAssignAggregate() is moving the call to avoid unnecessary work.

@richardkchapman please review/merge

**Pull request merged**
