### PR TITLE
HPCC-16199 Document Dali File access

### PR DESCRIPTION
**Pull request by g-pan**
Fix HPCC-16199 Document Dali File access
Document changes enabling file scope security in Dali

Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>
@JamesDeFabia please review

### CODE REVIEW

**Review by JamesDeFabia — APPROVED** [review]
Looks good to merge

**Comment by richardkchapman** [comment]
@AttilaVamos What are the 4 errors on the smoketest build?

**Comment by AttilaVamos** [comment]
Those error come from the ECL Watch rebuild result (Gordon asked to me to add that result to smoketest report).

**Comment by richardkchapman** [comment]
So does that mean that ECLWatch is not currently rebuilding correctly on 6.0.x branch?

**Comment by AttilaVamos** [comment]
It seems yes

**Comment by richardkchapman** [comment]
I upmerged 6.0.8 branch into 6.0.x - hopefully that should resolve. Can you rerun the smoketest

**Comment by AttilaVamos** [comment]
Re-scheduled.

**Comment by AttilaVamos** [comment]
@richardkchapman It is clean now.  
The 1 unittest timeout fixed in 6.2.0 (https://github.com/hpcc-systems/HPCC-Platform/pull/9069) as well.

**Pull request merged**
