### PR TITLE
HPCC-22328 WU Analysis store full scope in Exception->scope

### PR DESCRIPTION
**Pull request by shamser**
Signed-off-by: Shamser Ahmed <shamser.ahmed@lexisnexis.co.uk>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by AttilaVamos** [comment]
@shamser this PR generated 20 core files in Dali.
```
Core was generated by `dafilesrv -L /mnt/disk1/home/vamosax/smoketest/PR-12665/hpcc/var/log/HPCCSystem'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f77c6d72533 in CRemoteIndexBaseActivity::CRemoteIndexBaseActivity (this=this@entry=0x7f77b0001440, config=..., fileDesc=fileDesc@entry=0x0) at /mnt/disk1/home/vamosax/smoketest/PR-12665/HPCC-Platform/fs/dafsserver/dafsserver.cpp:2026
2026	        translator.setown(createRecordTranslator(outMeta->queryRecordAccessor(true), *record));
 ```

**Comment by AttilaVamos** [comment]
Some core and trace files are attached to JIRA

**Comment by jakesmith** [comment]
@shamser - that looks like it's to be related to my recent PR merge: https://github.com/hpcc-systems/HPCC-Platform/pull/12617

I'll have a look.

**Comment by jakesmith** [comment]
@AttilaVamos - can you remind me, how many slaves/channels/memory does the Thor setup have for smoketest?  can we put this info in the report in future

**Comment by AttilaVamos** [comment]
@jakesmith 4 slaves, 1 channel/slave, default (enviroment.xml based) memory settings. 
Yes I will add these information to the report.

**Comment by jakesmith** [comment]
@shamser - the cores were due to a regression in https://github.com/hpcc-systems/HPCC-Platform/pull/12617 , and not related to this PR.

Fix pending for my PR is : https://github.com/hpcc-systems/HPCC-Platform/pull/12669

**Pull request merged**
