### PR TITLE
HPCC-23966 Document STD.Crypto Decrypt restriction

### PR DESCRIPTION
**Pull request by JamesDeFabia**
Signed-off-by: Jim DeFabia <jamesdefabia@lexisnexis.com>
@RussWhitehead Please review

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Review by RussWhitehead — APPROVED** [review]

**Comment by RussWhitehead** [comment]
@JamesDeFabia Looks good

**Comment by richardkchapman** [comment]
@RussWhitehead What is it we are storing in the encrypted output that makes this true (and why are we storing it there?)

**Comment by RussWhitehead** [comment]
@richardkchapman The encrypted buffer that I return to the caller is an ECL DATA buffer in the format
    Initialization Vector Length
    Initialization Vector - Needed to decrypt
    Decrypted Data Length - Needed to preallocate return buffer
    Encrypted Data Length - Probably wasn't necessary but there nonetheless
    Encrypted Data

**Comment by richardkchapman** [comment]
I'm a bit dubious that the extra info in there actually reduces the security of the encrypted information... Any cryptologists out there?

**Comment by RussWhitehead** [comment]
@dcamper Has a lot of knowledge in this area.  However, without the passphrase, the extra information is of no real use

**Comment by dcamper** [comment]
@richardkchapman The extra metadata does not introduce less security.  It is possible, in fact, to convert an encrypted blob from Std.Crypto's format to the more general format (and back again) without knowing any secrets.  You do need to know what encryption algorithm was used, but that is not a secret.  Because you can perform that translation, it follows that no additional information is needed, so there is no information leak.  Therefore, the security of the two formats is the same.

**Pull request merged**
