### PR TITLE
HPCC-17179 Add FEW option to LOOP

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [x] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [x] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

Modified looprpn2 in the regression suite to use the new option, and tested.  Currently fails!

### CODE REVIEW

**Comment by ghalliday** [comment]
@jakesmith I added this option but thor fails when I submit a query using it with the following error:

 <Exception><Code>3000</Code><Source>eclagent</Source><Message>System error: 3000: Graph graph1[5], filter[8]: SLAVE #4 [192.168.0.200:20700]: assert(!hasStarted() || hasStopped()) failed - file: thgraphslave.hpp, line 69,  - caused by (3000, assert(!hasStarted() || hasStopped()) failed - file: thgraphslave.hpp, line 69)</Message></Exception>

Can we investigate when you get back.

**Comment by jakesmith** [comment]
@ghalliday - I've tried to reproduce this error with an example query from Gavin, but failed to do so, in debug/release and in various Thor configurations.

**Comment by jakesmith** [comment]
@ghalliday - should a regression suite test be added with this PR?

**Comment by ghalliday** [comment]
@jakesmith added example

**Comment by jakesmith** [comment]
@ghalliday - testing this issue, exposed a few problems (see HPCC-17555).

So you could mark this JIRA blocked by that.

**Comment by ghalliday** [comment]
@shamser example now runs - please review.

**Review by shamser — APPROVED** [review]
@richardkchapman Code reviewed ok.  (Regression checked and looks good too)

**Comment by richardkchapman** [comment]
@ghalliday Is there a Jira for the doc change?

**Comment by ghalliday** [comment]
@richardkchapman HPCC-17593

**Pull request merged**
