### PR TITLE
HPCC-17522 Provide a thread safe singleton helper function and class

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [x] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

Checked compiled.

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman @jakesmith @mckellyln for discussion and potentially merging.  Code samples for comparison:

Current (potentially unsafe) code:
```
static CKeyStore *keyStore = NULL;
static CriticalSection initCrit;
inline CKeyStore *queryKeyStore()
{
    if (keyStore) return keyStore; // avoid crit
    CriticalBlock b(initCrit);
    if (!keyStore) keyStore = new CKeyStore;
    return keyStore;
}

```
Using the function:  (note the use of a lambda function)
```
static std::atomic<CKeyStore *> keyStore;
static CriticalSection initCrit;
inline CKeyStore * queryKeyStore()
{
    return querySingleton(keyStore, initCrit, []{ return new CKeyStore; });
}
```
Using the class:
```
static Singleton<CKeyStore> keyStore;
CKeyStore * queryKeyStore()
{
    return keyStore.query([] { return new CKeyStore; });
}
```

**Comment by ghalliday** [comment]
I haven't double checked the disassembly yet to compare the implementation.  (I'm not sure that queryKeyStore() should be inline as a separate comment).

**Comment by ghalliday** [comment]
I made all functions non inline and compared the assembler.

The function and the original code produce almost identical code - probably identical # of instructions.
Strangely the class generates more efficient code if the pointer is already set up (no pushing registers onto the stack) and similar (or slightly better?) code if it is not set up.

I can email the 3 samples if anyone is interested.

**Comment by mckellyln** [comment]
I think this looks good.  We support lambdas now everywhere, right ?

**Pull request merged**
