### PR TITLE
HPCC-28284 Update defaultSprayParts and numWorkers docs/schema tip

### PR DESCRIPTION
**Pull request by jakesmith**
Update storage.md to relect fact that defaultSprayParts defaults
to the size of the largest Thor.

Update values.schema.json numWorkers description to clarify that
it defines the number of containers, multiple of which may be
in the same pod, depending on value of numWorkersPerPod.
Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Review by ghalliday — APPROVED** [review]

**Review by ghalliday — CHANGES_REQUESTED** [review]
@jakesmith  Actually not sure.  The rest of the code assumes that numWorkers is a multiple of numWorkersPerPod - so I think the code was correct before.

**Comment by jakesmith** [comment]
> @jakesmith Actually not sure. The rest of the code assumes that numWorkers is a multiple of numWorkersPerPod - so I think the code was correct before.

you're right, I was mislead by:
```
        "numWorkers": {
          "type": "integer",
          "description": "The number of worker pods",
          "minimum": 1
        },
```

That should say number worker containers, where by default (when numWorkersPerPod=1) # worker containers = # worker pods.

I'll adjust that schema description.

**Comment by jakesmith** [comment]
```
1) test: MetricFrameworkTests::Test_histogram_metric (E) 
uncaught exception of type std::exception (or derived).
- std::bad_alloc
```

@kenrowland @AttilaVamos @ghalliday - not related to this PR, is this a recently introduced regression?

**Review by ghalliday — APPROVED** [review]

**Comment by ghalliday** [comment]
@kenrowland I can see the problem - I will open a jira.

**Pull request merged**
