### PR TITLE
HPCC-19468 New Defects reported by Coverity Scan

### PR DESCRIPTION
**Pull request by richardkchapman**
Eclrtl related bugs

Signed-off-by: Richard Chapman <rchapman@hpccsystems.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [x] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x ] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by richardkchapman** [comment]
@ghalliday Please review/merge

**Comment by AttilaVamos** [comment]
@richardkchapman   checked all other defects as well.

**Comment by AttilaVamos** [comment]
I have 4 other fixes:
- CID: [1402592](https://scan7.coverity.com/reports.htm#v10043/p10032/fileInstanceId=50780013&defectInstanceId=10587181&mergedDefectId=1402592), [1142337](https://scan7.coverity.com/reports.htm#v10043/p10032/fileInstanceId=50779988&defectInstanceId=10586873&mergedDefectId=595353), [1142338](https://scan7.coverity.com/reports.htm#v10043/p10032/fileInstanceId=50779988&defectInstanceId=10586877&mergedDefectId=595352) and [1366397](https://scan7.coverity.com/reports.htm#v10043/p10032/fileInstanceId=50779989&defectInstanceId=10587188&mergedDefectId=1366397)

2 FP:
- CID: [1142306](https://scan7.coverity.com/reports.htm#v10043/p10032/fileInstanceId=50779993&defectInstanceId=10586865&mergedDefectId=595295), [1143018](https://scan7.coverity.com/reports.htm#v10043/p10032/fileInstanceId=50779993&defectInstanceId=10586895&mergedDefectId=595408)

3 what I presume FP as well but should discuss:
- CID: [1402537](https://scan7.coverity.com/reports.htm#v10043/p10032/fileInstanceId=50779993&defectInstanceId=10586945&mergedDefectId=1402537), [1402538 ](https://scan7.coverity.com/reports.htm#v10043/p10032/fileInstanceId=50779993&defectInstanceId=10586945&mergedDefectId=1402538) and [1402539](https://scan7.coverity.com/reports.htm#v10043/p10032/fileInstanceId=50779993&defectInstanceId=10586947&mergedDefectId=1402539)

and 1 is can be a bug in some special circumstances:
- CID: [1457053](https://scan7.coverity.com/reports.htm#v10043/p10032/fileInstanceId=50779993&defectInstanceId=10587258&mergedDefectId=1457053)

**Comment by richardkchapman** [comment]
Coverity report seems to have become a bit confused - it's re-reported a lot of issues that were previously reported (such as the ones above that were first reported in 2017 or earlier).

Still worth fixing though. Are you planning to submit a separate PR for them?

**Comment by AttilaVamos** [comment]
Yes it is a bit strange. I think they have some internal database issue or improvement in scanner or something.
But yes, I agree worth fixing and I will discus  those 3 (can be FP) + 1 (can be a bug) and create PR for them.

**Comment by richardkchapman** [comment]
@ghalliday

**Comment by AttilaVamos** [comment]
@richardkchapman may I merge your change with mine (where I addressed all other rtl related issues) and create PR for https://track.hpccsystems.com/browse/HPCC-19472 ?

**Comment by richardkchapman** [comment]
@AttilaVamos If you like

**Pull request closed without merging**
