### PR TITLE
HPCC-15197 Generated c++ warns about narrowing conversions

### PR DESCRIPTION
**Pull request by richardkchapman**
Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@ghalliday Please review

**Comment by ghalliday** [comment]
That is not going to work.  You'll remove the warning from the inline definition - but break wherever it is used, since it is assumed to be a char *.

**Comment by richardkchapman** [comment]
@ghalliday Do you have an example of it failing that I can dig into? I'm not sure it is used anywhere except memcpy...

**Comment by richardkchapman** [comment]
(and/or a suggestion of how you think it should be fixed)

**Pull request closed without merging**
