### PR TITLE
HPCC-23507 Move filter pointer when checking thor time filter

### PR DESCRIPTION
**Pull request by wangkx**
This fixes a bug in PR-13137 in cassandrawu's getWorkUnitsSorted().

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by wangkx** [comment]
@AttilaVamos please review.

**Comment by AttilaVamos** [comment]
@wangkx It seems your fix revealed some further problems.

**Comment by wangkx** [comment]
Without my fix, those failed tests may not run. Now, we have to know what those tests for and why they fail.

**Comment by wangkx** [comment]
Does this mean that there is an error in testInit():

Cassandra:1) test: WuTool::testInit (E)

**Comment by AttilaVamos** [comment]
Yes

**Comment by wangkx** [comment]
void testInit()
    {
        Owned<IWorkUnitFactory> factory = getWorkUnitFactory();
        if (globals->getPropBool("entire", false) && globals->getPropBool("repository", false))
        {
            factory->deleteRepository(false);
            factory->createRepository();
            DBGLOG("Repository recreated\n");
        }
    }
Do you where the error comes from?

**Comment by AttilaVamos** [comment]
I don't know, but I tried to reproduce this problem on my local VM and I wasn't able to. It finished without any error.
Let me reschedule this PR in and see what happen.

**Comment by wangkx** [comment]
Ok, thanks.

**Comment by AttilaVamos** [comment]
This test will fail based on a bit old Cassandra installed on Smoketest machine. I updated it and reschedule this PR again.

**Comment by wangkx** [comment]
@AttilaVamos looks like no more smoketest error.

**Review by AttilaVamos — APPROVED** [review]
@wangkx Good to merge.

**Comment by wangkx** [comment]
@richardkchapman please merge this PR.

**Pull request merged**
