### PR TITLE
HPCC-16783 Pass flushing string buffer in a couple of places

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman please review

**Comment by richardkchapman** [comment]
@afishbeck can you check

**Review by afishbeck — APPROVED** [review]
Looks good. 

Note that in these areas writer->rewindTo() would never be called.  In cases where that is needed such as dyanmic_esdl this change would not be allowed.

**Comment by richardkchapman** [comment]
Is this really a 6.2.2 change? @ghalliday

**Comment by ghalliday** [comment]
@richardkchapman retargeted

**Pull request merged**
