### PR TITLE
HPCC-14726 Fixed regression in start_backupnode logging

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner michael.gardner@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@mckellyln Please review

**Comment by mckellyln** [comment]
Looks fine.

**Comment by richardkchapman** [comment]
When was the regression introduced?

**Comment by Michael-Gardner** [comment]
5.4.0 with the logging update to all the init files.

**Pull request merged**
