### PR TITLE
HPCC-31462-LIBXML2 Add option to manually test docs build

### PR DESCRIPTION
**Pull request by GordonSmith**
## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by GordonSmith** [comment]
@Michael-Gardner Same as your solution, but I rolled the version forward and not back.

Also added gh runner test.

**Review by Michael-Gardner — CHANGES_REQUESTED** [review]
@GordonSmith Bumping the version up didn't fix the issue. Just ran a test here ( https://github.com/Michael-Gardner/HPCC-Platform/actions/runs/8393210379/job/22987688765 )

This was the error that caused the build failure. 

2024-03-22T17:20:52.8073217Z CMake Error at ConfiguringHPCC.fo.cmake:6 (message):
2024-03-22T17:20:52.8074717Z   xsltproc build failure: 6
2024-03-22T17:20:52.8075352Z 
2024-03-22T17:20:52.8075363Z 
2024-03-22T17:20:52.8082445Z gmake[2]: *** [docs/EN_US/ConfiguringHPCC/CMakeFiles/ConfiguringHPCC_EN_US-9.6.1-closedown0.pdf.dir/build.make:79: docs/EN_US/ConfiguringHPCC/ConfiguringHPCC.fo] Error 1
2024-03-22T17:20:52.8086454Z gmake[1]: *** [CMakeFiles/Makefile2:6169: docs/EN_US/ConfiguringHPCC/CMakeFiles/ConfiguringHPCC_EN_US-9.6.1-closedown0.pdf.dir/all] Error 2
2024-03-22T17:20:52.8088545Z gmake[1]: *** Waiting for unfinished jobs....

That's from the -xinclude in xsltproc not finding the needed files relative to the documents base xpath.  Still not certain why libxml2 version 2.11.x does this and not 2.10 or 2.9.

The changes you made to the github action workflow files look fine.

**Comment by GordonSmith** [comment]
@Michael-Gardner I merged your PR and rebased mine (removing the overlay stuff).

**Comment by GordonSmith** [comment]
@Michael-Gardner bump

**Pull request closed without merging**
