### PR TITLE
HPCC-16284 ESDL2ECL generate ECL comment regarding array max_count

### PR DESCRIPTION
**Pull request by rpastrana**
Signed-off-by: rpastrana rodrigo.pastrana@lexisnexis.com

### CODE REVIEW

**Comment by rpastrana** [comment]
@g-pan please review.

**Comment by g-pan** [comment]
XSL Looks ok to me.

**Comment by garonsky** [comment]
looks good.

**Comment by rpastrana** [comment]
@richardkchapman please merge

**Pull request merged**
