### PR TITLE
HPCC-14856 Document REFRESH option on PERSIST

### PR DESCRIPTION
**Pull request by JamesDeFabia**
Signed-off-by: Jim DeFabia jamesdefabia@lexisnexis.com
@shamser Please review

### CODE REVIEW

**Comment by richardkchapman** [comment]
@shamser Please review

**Comment by shamser** [comment]
@JamesDeFabia @richardkchapman Should we provide any warnings regarding layout changes when REFRESH(false) is used?

**Comment by richardkchapman** [comment]
In the docs, it's worth mentioning this potential issue.

**Comment by richardkchapman** [comment]
@JamesDeFabia Back to you

**Comment by JamesDeFabia** [comment]
@shamser Please have another look

**Comment by shamser** [comment]
@JamesDeFabia @richardkchapman Looks good.  Ok to merge.

**Pull request merged**
