### PR TITLE
HPCC-31212 Add plane name to RemoteDirectory

### PR DESCRIPTION
**Pull request by wangkx**
The STD.File.RemoteDirectory lists files in one landing zone folder. The existing method can only specify a landing zone using host name. In this PR, a landing zone can be specified by plane name.
 

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by wangkx** [comment]
@jakesmith this PR is based on https://github.com/hpcc-systems/HPCC-Platform/pull/18275 (the first commit). You may review the second commit or wait after https://github.com/hpcc-systems/HPCC-Platform/pull/18275 is merged. 
I haven't found that the failing check is related.

**Review by jakesmith — COMMENTED** [review]
See general comments in dependent PR (https://github.com/hpcc-systems/HPCC-Platform/pull/18275).
Let's revisit this when that review is complete/near complete.

**Comment by wangkx** [comment]
The windows build error seems not related to this PR. The second commit does not need to be reviewed because it is a temporary build fix for the issue in the latest master repo and will be removed before merging.

**Review by jakesmith — COMMENTED** [review]
@wangkx - given the route of other changes to MoveExternalFile/DeleteExternalFile/CreateExternalDirectory (i.e. adding a plane param), and despite RemoteDirectory not being a great name (and despite me suggesting a new method name be introduced), I think for consistency with other changes, this change should take the same route, i.e. a plane option should be added to RemoteDirectory too, and it and/or the hostname if provided should be validated against dropzone planes.

**Comment by wangkx** [comment]
@jakesmith I am not sure I fully understand your requirement. Based on the comment, I will add a fsRemoteDirectory_v2, as I did for MoveExternalFile, etc. Should I keep the new fsListPlaneDirectory in this PR or it is no longer needed?

**Comment by wangkx** [comment]
@jakesmith I made the changes from fsListPlaneDirectory to fsRemoteDirectory_v2. I also modified the PR title and description. Please review.

**Review by jakesmith — APPROVED** [review]
@wangkx - looks good.

**Comment by wangkx** [comment]
@ghalliday please merge this PR.

**Pull request merged**
