### PR TITLE
HPCC-32242 add serviceName for StatefulSet

### PR DESCRIPTION
**Pull request by xwang2713**
"serviceName" is required according to Kubernetes StatefulSet spec:
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
"dali" already has a service with the same name as StatefulSet name. Even though it is a full service not just headless service but it should be fine.  

Not all Kubernetes environments will report an error if this is missing such as my local Helm (v3.9.3) and Docker Desktop Kubernetes (V1.29.1) and Azure Kubernetes Service (AKS) @gfortil using.

The problem originally reported by @bobf2000 in his Docker Desktop environment. He did update Kubernetes to the latest
but still got the error documented in JIRA https://hpccsystems.atlassian.net/browse/HPCC-32242

Signed off by Xiaoming.Wang@lexisnexisrisk.com

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Tested by @bobf2000 on his Docker Desktop environment

### CODE REVIEW

**Review by jakesmith — DISMISSED** [review]
@xwang2713 - looks good.

**Comment by jakesmith** [comment]
@xwang2713 - it looks like this is associated with the wrong JIRA (HPCC-32243 is titled "https://hpccsystems.atlassian.net/browse/HPCC-32243")

**Comment by xwang2713** [comment]
@jakesmith just update the commit message. Hopefully it is not too late for today's RC build.

**Review by jakesmith — APPROVED** [review]
@xwang2713 - looks good.

**Comment by jakesmith** [comment]
> @jakesmith just update the commit message. Hopefully it is not too late for today's RC build.

@xwang2713 - thanks yes, it got in.

**Pull request merged**
