### PR TITLE
HPCC-14717 Update WsWorkunits Interface version for 6.0

### PR DESCRIPTION
**Pull request by wangkx**
The existing 6.0 WsWorkunits Interface is different from 5.4.
But, the version numbers are the same (1.56). This fix changes
the the version number for 6.0 to 1.57.

Also fixed a small bug inside the 6.0 code.

Signed-off-by: wangkx kevin.wang@lexisnexis.com

### CODE REVIEW

**Comment by wangkx** [comment]
@rpastrana please review.

**Comment by rpastrana** [comment]
Reviewed, left some comments.

**Comment by wangkx** [comment]
I made the change based on the comments. Please review again.

**Comment by rpastrana** [comment]
Changes look good.

**Comment by wangkx** [comment]
@richardkchapman this PR is ready to merge.

**Pull request merged**
