### PR TITLE
HPCC-17843 Check DFU queue name correctly in FileSpray web service

### PR DESCRIPTION
**Pull request by wangkx**
The existing FileSpray web service does not read queue names correctly
when a DFU Server has multiple queues.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by wangkx** [comment]
@jakesmith  please review.

**Review by jakesmith — CHANGES_REQUESTED** [review]
@wangkx  - I don't think this is the right location for the fix.
HPCC-16873 introduced getDFUServerQueueNames() specifically for this feature.
I don't think you should another method (and not outside of it's closely related method in workunit.hpp)

I think it (getDFUServerQueueNames) should return all the dfu server queues, without duplicates.

The duplication is a perculiarity of the way DFU server listens to multiple jobs on the same queue.
If we ever wanted a method to return all duplicates across all DFUservers, we could add that, but I'm sure we won't.

**Comment by wangkx** [comment]
@jakesmith I made the changes based on your comment. Please let me know if I miss anything.

**Comment by jakesmith** [comment]
@wangkx - looks fine.
Have you tested with a scenario similar to one that caused problems?

**Comment by wangkx** [comment]
Yes, I tested.

@richardkchapman this PR is ready to be merged.

**Pull request merged**
