### PR TITLE
HPCC-21935 Fix lazy file io crash

### PR DESCRIPTION
**Pull request by jakesmith**
It was possible for requests from the cache to overlap with
previous requests expiring and being removed.
The overlaping request for a previously cached result, that
was about to be destroyed linked the result before the
PSEUDO_COUNT was set, meaning it could be destroyed twice.

Protect by checking isAlive() when looking up and locking
mutex within beforeDispose()

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
@ghalliday - please review

**Comment by ghalliday** [comment]
I'm not sure this is the correct change.  As far as I can see the original code didn't have a call to isAlive() which is required if you have a cache which doesn't link the items.  
The code should be:

        Linked<CLazyFileIO> file = files.find(id);
        if (!file || !file->isAlive())

I suspect your change would actually introduce a race condition.
@jakesmith

**Comment by ghalliday** [comment]
See the comments at the bottom of jiface.hpp on the pattern needed.

**Comment by ghalliday** [comment]
ok, looking at the code again I don't think it introduces a new race condition, but it does mean that each call to Release() enters a critical section.

**Comment by jakesmith** [comment]
Yes, I can't see the potential race with mutex lock in Release(), but beforeDispose() pattern is better , as avoids crit per Release(), so I'll change to that.

**Comment by jakesmith** [comment]
@ghalliday - please see revised commit.

**Pull request merged**
