### PR TITLE
HPCC-17508 Automatically add Ping method to all static ESP services

### PR DESCRIPTION
**Pull request by rpastrana**
- Adds onPing to all static ESP service interface
- Implements onPing automatically. Returns empty response

Signed-off-by: Rodrigo Pastrana <rodrigo.pastrana@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [x] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [x] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by rpastrana** [comment]
@afishbeck please review.

**Comment by afishbeck** [comment]
@rpastrana this would be hard to version, but I guess having a new request, response, and method appear in old versions of our WSDLs won't be likely to break anything.  New fields to existing structures are a different story.

But I would be worried about forcing scapps like services to have this.  Since it affects hidl at a low level it will show up in dynamic ESDL definitions, right?

We should make this optional at the very least from the ESDL command line when generating xml, wsdl, xsd, etc.

**Comment by rpastrana** [comment]
@afishbeck, I see your point... the new hidl could be used to build legacy ESDL defs... but I agree I don't think that's a big deal. I personally don't expect to change the ping() interface, if anybody ever requires new fields, they'll need to create their own method through ESDL...
Hmmm... I suppose we could add a flag to turn off adding the PING.... I do wish we could rely on all services having the ping()

**Comment by afishbeck** [comment]
@rpastrana just not sure how others will react.  Could run it by Jiafu.  Or default to on and have an option to esdl.exe to turn off.

**Comment by rpastrana** [comment]
I'll talk to him, I'll prob add the option anyway.

**Comment by rpastrana** [comment]
@afishbeck please review.

**Review by afishbeck — APPROVED** [review]
@rpastrana looks ok

**Comment by rpastrana** [comment]
@richardkchapman please merge

**Pull request merged**
