### PR TITLE
HPCC-19896 Add XSD test files

### PR DESCRIPTION
**Pull request by kenrowland**
Add XSD test files for config2 manager testing

Signed-off-by: Ken Rowland <kenneth.rowland@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by kenrowland** [comment]
@rpastrana Please review

**Review by rpastrana — COMMENTED** [review]
@kenrowland the files look fine, but can we provide more documentation about what they do? either more descriptive file name, or a comment in the file(s)?
Also, do we intend to fill the Test folder with various xsd/xml files or should they be grouped in subfolders, or prefixed file names?

**Comment by kenrowland** [comment]
The Test folder was to hold all the test data. Perhaps if it grows too large we can separate. For now it doesn't really make sense. In fact, the test xml data may all exist in a single file.

**Comment by rpastrana** [comment]
ok, so the test folder can potentially hold multiple test files (presumably from multiple test cases) at the root level. How are you going to distinguish the multiple test cases?

**Comment by kenrowland** [comment]
This is just the test data. The test cases will be written by Chris, so as he writes them we may decide to reorganize the directory. The organization could even by test area, say testing of types, element insertion and deletion, and others, so I think an organization at this point is premature.

I added comments to the XSDs, please take a look.

**Comment by rpastrana** [comment]
@kenrowland this is the time to set the standard. Even if this test suite never grows, set it up now to grow in an organized manner. (unless there's a technical reason that prevents you from doing this) Create a subfolder for this test case you've created, hopefully we can get more descriptive than "test1".
Also the copyright header date seems outdated.

**Comment by kenrowland** [comment]
Changed to single named set of test data files that does not imply multiple sets. At this time the test data should be able to be contained in one set of test files and one test environment file.

@rpastrana Please review latest changes

**Comment by rpastrana** [comment]
@kenrowland looks reasonable.

**Comment by kenrowland** [comment]
@richardkchapman Please merge

**Pull request merged**
