### PR TITLE
HPCC-17304 Leaking environment iterators and return with an unlinked pointer

### PR DESCRIPTION
**Pull request by AttilaVamos**
Change
- CConstMachineInfoIterator
- CConstDropZoneIteratorByComputer
- CConstDropZoneInfoIterator
implementation.

Fix unlinked return pointer.

Signed-off-by: Attila Vamos <attila.vamos@gmail.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

Manually

### CODE REVIEW

**Comment by AttilaVamos** [comment]
@jakesmith please review?

**Comment by jakesmith** [comment]
@AttilaVamos - looks good, I cannot see any issues.

However, I smoketest failures appear to indicate esp is crashing, which is being investigated. It may be (complete speculation) that your leak fixes have exposed a bug in esp or common code elsewhere that was masked by the leaked objects these iterators were returning.

**Comment by AttilaVamos** [comment]
@jakesmith Thanks for the help to fix this issue. If you wish to take a final look to the code, please do.

**Comment by jakesmith** [comment]
@AttilaVamos - Looks good, but it's worth updating the JIRA + PR commit heading+description, to note the bug fixed here too.

**Comment by AttilaVamos** [comment]
@jakesmith updated.

**Comment by jakesmith** [comment]
@richardkchapman - good to merge.

**Comment by richardkchapman** [comment]
@AttilaVamos Please rebase for a clean merge

**Comment by AttilaVamos** [comment]
@richardkchapman rebased and it is clean now. Please merge.

**Pull request merged**
