### PR TITLE
HPCC-31744 Record time started and time stopped for DFU workunit to higher level of granularity

### PR DESCRIPTION
**Pull request by shamser**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [x] Test my draft Pull Request.

### CODE REVIEW

**Comment by shamser** [comment]
> @shamser is there an equivalent change needed for the elapsed time?

Elapsed time is already being recorded to nanosecond accuracy.  No changes required for elapsed time. @GordonSmith

**Review by jakesmith — APPROVED** [review]
@shamser - looks good.

**Review by ghalliday — COMMENTED** [review]
The change is ok, but better would be to add a setNowTimestamp/setNowAccurate to CDateTime and call that instead.  There are probably several other places that would benefit from a more accurate time, and it could also gain nano second granularity by using

```
        timeNs = std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::system_clock::now().time_since_epoch());
```

**Comment by ghalliday** [comment]
@shamser do you want to merge as-is, or will you add the new function in this PR?

**Comment by shamser** [comment]
> ime_since_epoch());

@ghalliday if there are other places that would benefit from more nano-second accuracy timestamps, I'd prefer to make the the suggested change in a separate PR (https://hpccsystems.atlassian.net/browse/HPCC-31833). As far I can see what the stats use the getTimeStampNowValue, so this change is consistent with that. Would it make sense to update getTimeStampNowValue use the new method?

**Review by ghalliday — COMMENTED** [review]
Merging since a useful improvement.  A fuller/better encapsulated change to follow.

**Pull request merged**
