### PR TITLE
HPCC-30723 Support helm install of esdl application

### PR DESCRIPTION
**Pull request by asselitx**
- Remove default esp.bindings value. Helm templates enforce that a value must be provided.
- Add esdl example to helm/examples that shows two ways of deploying an esdl application service with helm.

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [x] Performance
  - [x] Security
  - [x] Thread-safety
  - [x] Cloud-compatibility
  - [x] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

I have tested helm deployment using both localfile and with the bundle on the image, and ensured that helm rejects an install when the esp.bindings value is not supplied. There was no change to any c++ code so valgrind didn't need to be used.

### CODE REVIEW

**Comment by asselitx** [comment]
@afishbeck I'm looking for your approval of this approach. It didn't require a large change, but I felt an example illustrating two ways of doing it was important.

Since the template change was very small, let me know if you think I should still get review from Jake or Gavin.

**Review by afishbeck — APPROVED** [review]
@asselitx looks great.

**Comment by ghalliday** [comment]
The change looks good.  @asselitx @afishbeck is 9.4.x or 9.6.0 the most suitable target for the change?

**Comment by afishbeck** [comment]
> The change looks good. @asselitx @afishbeck is 9.4.x or 9.6.0 the most suitable target for the change?

@ghalliday this is mostly documentation, examples, and parameter checking.  The only slight risk is the changing of a value default in esp/applications/esdl/esp.yaml.

But I also don't think there is pressure to get this into 9.4.x so I would retarget to master/9.6.x.

@asselitx can you change the target branch and rebase?

**Pull request merged**
