### PR TITLE
HPCC-23063 Fix security manager plugin loading

### PR DESCRIPTION
**Pull request by timothyklemm**
Accept configuration attribute "libName" as an alternative to "LibName".
Existing plugins create configurations with the former and fail to load.

Accept configuration attribute "instanceFactoryName" as an alternative to
"InstanceFactoryName". Existing plugins create configurations with the former
and expect a hard-coded default value.

Signed-off-by: Tim Klemm <tim.klemm@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [x] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by timothyklemm** [comment]
@RussWhitehead this is a small fix to get security manager plugins loading. I tried using the single user plugin to test HPCC-24312, and it wouldn't load because the configurations created for it use the wrong case.

**Review by RussWhitehead — COMMENTED** [review]
Although this looks fine, why is it better than just fixing the offending plugins to do it correctly?

**Comment by timothyklemm** [comment]
I ran into this with my plugin when moving to 7.0. The lower case names worked in 6.x, and stopped working in 7.0. I just updated my plugin. That works for configurations made after the fix, but not for configurations created before. By changing the loader to accept either form, we fix everybody.

**Comment by RussWhitehead** [comment]
Who generates these keynames in the configuration?  Should we open a Jira against the  plugin config files to make them consistent, even if you handle it in this code?  Otherwise, this looks good for merge

**Comment by timothyklemm** [comment]
The plugin defines the names it uses. There is no opportunity for a transform to change the plugin's names to match the names expected by code. We could fix the plugins so new configurations match the first attempt in code, but retain the fallback for older configurations.

**Pull request merged**
