### PR TITLE
HPCC-13912 Return Replicate for files on >2 clusters

### PR DESCRIPTION
**Pull request by wangkx**
Also add BaseDir and ReplicateDir for file on clusters.

Signed-off-by: wangkx kevin.wang@lexisnexis.com

### CODE REVIEW

**Comment by wangkx** [comment]
@jakesmith please review.

**Comment by jakesmith** [comment]
Previous change added a Replicate flag for the whole file (and didn't deal with situation where file was on >1 cluster).
This change adds Replicate + basedir + replicatedir per file *part* by the looks of it..

Why? That would duplicate the same information e.g. 400 times.
It should be returned once per cluster per logical file.
I would have expected at the top of the parts under each cluster, the cluster info (replicate+basedir+repdir) then the parts.

@wangkx

**Comment by wangkx** [comment]
@jakesmith What I have done is the same as your comment. The (replicate+basedir+repdir)  are in the DFUFilePartsOnCluster, not in the 'ESPstruct DFUPart'. After them, the DFUFilePartsOnCluster has parts (DFUFileParts). See below:

ESPStruct [nil_remove] DFUFilePartsOnCluster
{
    string Cluster; //per cluster per logical file
    [min_ver("1.31")] string BaseDir; //per cluster per logical file
    [min_ver("1.31")] string ReplicateDir; //per cluster per logical file
    [min_ver("1.31")] bool Replicate; //per cluster per logical file
     ESParray<ESPstruct DFUPart> DFUFileParts; //the parts per cluster per logical file
};

**Comment by jakesmith** [comment]
Ah ok, I misread, I thought the code was now inside the part iterator.

**Comment by jakesmith** [comment]
I'm curious (saw before but forgot to comment) , what is the '[nil_remove]' ?

**Comment by wangkx** [comment]
The '[nil_remove]' means that an item will not be in the structure if the item is not set. For example, in ESPStruct [nil_remove] DFUFilePartsOnCluster, if the BaseDir and ReplicateDir are not set, ESP will only return "cluster=xx, replicate=xx, DFUFileParts=...".

**Comment by richardkchapman** [comment]
Typo "Replciate" in commit message

**Comment by jakesmith** [comment]
Ok apart from correction of typo in commit message, this is ready to merge.
@wangkx

**Comment by wangkx** [comment]
@richardkchapman The typo has been fixed. Ready to merge.

**Pull request merged**
