### PR TITLE
HPCC-13281 Remove unnecessary defaults

### PR DESCRIPTION
**Pull request by jamienoss**
This also removes the server stats being dumped to the logs and
the turning off of the server verbosity.

Signed-off-by: James Noss james.noss@lexisnexis.com

### CODE REVIEW

**Comment by jamienoss** [comment]
@richardkchapman, @ghalliday please review.

**Comment by AttilaVamos** [comment]
Smoketest Build success

**Comment by ghalliday** [comment]
@jamienoss an you add some details into the jira to describe why the change is being done.

@richardkchapman changes look sensible, but should be double checked - especially if this is going into 5.2 as currently targetted.

**Comment by jamienoss** [comment]
@ghalliday, @richardkchapman jira updated.

**Comment by richardkchapman** [comment]
I merged, but I should probably have requested an improved commit message before I did - the problem being that the top line of the commit (which is what appears when doing a git log --oneline - and thus when getting a summary of what is new between 5.2.0-rc7 and gold) makes no mention of the fact that it is related to the memcached plugin. Please ask yourself "How will this look in the context of a changelog" when creating commit messages and in particular writing the titles for them.

**Pull request merged**
