### PR TITLE
HPCC-18228 Refactor generated ESP code to use unique member var names

### PR DESCRIPTION
**Pull request by rpastrana**
- Adds "request" prefix to userid, password and realm member vars
- Refactors getter setter methods for userid,password and realm

Signed-off-by: Rodrigo Pastrana <rodrigo.pastrana@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by rpastrana** [comment]
@afishbeck please review. I used "request" as a prefix to attain some level of uniqueness, but i wouldn't be surprised if you have a better prefix, just let me know, it'll be simple to change.

**Comment by afishbeck** [comment]
@rpastrana rather than just trying to make the access name unique, this is one place we may want to break our naming scheme all together.. so it is impossible for someone to create a message level variable to match ours.

So for example soap_userid, rather than m_userid.  with a comment to explain why.

And soapGetUserId() rather than getUserId(), again with a comment.

**Comment by rpastrana** [comment]
@afishbeck please take a look

**Review by afishbeck — APPROVED** [review]
@rpastrana looks good.

**Comment by rpastrana** [comment]
@richardkchapman please merge.

**Pull request merged**
