### PR TITLE
HPCC-13201 Fix WsECL form handling of blank fields

### PR DESCRIPTION
**Pull request by afishbeck**
Signed-off-by: Anthony Fishbeck anthony.fishbeck@lexisnexis.com

### CODE REVIEW

**Comment by afishbeck** [comment]
@richardkchapman FYI Krishna requested this be in 5.2.2.

**Comment by afishbeck** [comment]
Looks like a regression starting in 5.0

**Comment by richardkchapman** [comment]
Should really target 5.0.14 then

**Comment by afishbeck** [comment]
Closing to target 5.0.14.

**Pull request closed without merging**
