### PR TITLE
HPCC-13543 Ensure that parent extract for child queries is thread safe

### PR DESCRIPTION
**Pull request by ghalliday**

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman please review

**Comment by ghalliday** [comment]
Some notes:
Commit 1 removes a member that was being generated incorrectly
Commit 2 cleans up some code so that it is posssible to tell if a row is fixed size.
Commit 3 fixes the bug
Commit 4 makes it acceptable by ensuring fixed size extracts are allocated on the heap - avoiding a reallocation for each child query.

Commits 1+2 were separately regression tested to ensure they didn't introduce any issues.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by richardkchapman** [comment]
The comments on the commits don't seem to match your descriptions above....

**Comment by richardkchapman** [comment]
There should be a test in the runtime suite that exercises this - does the one in https://github.com/hpcc-systems/HPCC-Platform/pull/7313 cover it?

**Comment by ghalliday** [comment]
I think the commit order got mixed up - I did rebase to try and get them into order.

**Pull request merged**
