### PR TITLE
HPCC-14643 Add socket keepalive to thor<->eclagent conversation

### PR DESCRIPTION
**Pull request by mckellyln**
Signed-off-by: Mark Kelly mark.kelly@lexisnexis.com

Added keepalive to one place as per the JIRA issue.

@jakesmith please review

### CODE REVIEW

**Comment by richardkchapman** [comment]
Not sure this is a 5.4.8 change? Perhaps 5.6.0?

**Comment by jakesmith** [comment]
Could be a point change, but it's such an old issue and really won't be _that_ helpful until the associated issue is resolved (HPCC-14663), so I recommend 5.6

**Comment by jakesmith** [comment]
changes look good.

But needs rebasing onto candidate-5.6.0 and PR re-issuing.

@mckellyln

**Comment by mckellyln** [comment]
closing and re-issuing for candidate-5.6.0

**Pull request closed without merging**
