### PR TITLE
HPCC-19592 ECL generated by esdl command no longer compiles

### PR DESCRIPTION
**Pull request by mayx**
- Don't generate ECL for empty requests and responses. This way
  the Ping request and response that are causing the problem will
  no longer generate ECL

Signed-off-by: mayx <yanrui.ma@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [x] Performance
  - [x] Security
  - [x] Thread-safety
  - [x] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by mayx** [comment]
@rpastrana please review...

**Comment by rpastrana** [comment]
@mayx help me understand the problem... I see that the auto-generated ping methods are represent as empty EsdlREquests in the esxdl and somehow that breaks the ECL generated. The comments in the change seem to indicate we're skipping the ECL generation of empty reqs/resps? 
If that's correct, I'm concerned we're gong to ignore other empty requests (we have some in wsesdlconfig,etc.) I don't know how often they would appear in transactional ESPs, but we should prob fix the generated ECL instead. Thoughts?

**Comment by mayx** [comment]
@rpastrana You said "fix the generated ECL instead" - what would you suggest to fix the generated ECL? If the struct is empty, the record generated will be empty and it won't compile. We either need to make the record non-empty, which won't match the esdl, or change ECL compiler to allow empty records, right?

**Comment by rpastrana** [comment]
@mayx can you publish here what the generated ECL looks like for an empty req?

**Comment by mayx** [comment]
@rpastrana it simply generates records without any field:

EXPORT t_EsdlExamplePingRequest := RECORD
END;

EXPORT t_EsdlExamplePingResponse := RECORD
END;

**Comment by rpastrana** [comment]
@mayx it prob doesn't make sense to allow the empty ECL rec definition, so... not generating the record is probl reasonable. can we at least generate a comment so the ECL developer understands why there's no request record? @afishbeck what do you think?

**Comment by rpastrana** [comment]
@mayx discussed w/ @afishbeck offline -- we agree on providing comment and comment out the the empty record def

**Comment by mayx** [comment]
@rpastrana Please review again.

**Review by rpastrana — APPROVED** [review]
@mayx looks reasonable.

**Pull request merged**
