### PR TITLE
HPCC-18986 Fix potential stall with csvread with header lines

### PR DESCRIPTION
**Pull request by jakesmith**
Csv read tried to read the header lines on start(), if the file
was sparse and the slave dealt with multiple parts per slave,
the processing might not send a message to the next slave to
indicate how many header lines had been read, until the next or
all parts had been read by that slave.
Consequently, when a csv read like this was being read by an
activity which did not start reading on all slaves, there could
be deadlock. The particular scenario this was seen in was where
as CSV read with a HEADING that was larger than the cluster, was
being read by a JOIN on the RHS.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by jakesmith** [comment]
@richardkchapman @ghalliday - would one of you please review

**Comment by richardkchapman** [comment]
@mckellyln Please review.

**Review by mckellyln — APPROVED** [review]

**Comment by mckellyln** [comment]
@jakesmith changes look fine to merge

**Comment by jakesmith** [comment]
@richardkchapman - please merge

**Pull request merged**
