### PR TITLE
HPCC-22517 Update SSL Steps for ESP

### PR DESCRIPTION
**Pull request by g-pan**
Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>
@JamesDeFabia please review

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Successful build tests: http://10.240.32.243/view/Docs%207.0/job/AnotherDocBuild7/65/

### CODE REVIEW

**Review by JamesDeFabia — CHANGES_REQUESTED** [review]
@g-pan The Jira issue said a screenshot was confusing. Has that been addressed?
Also needs a sentence saying to remove HTTP service instances after testing connectivity via HTTPS

**Review by JamesDeFabia — CHANGES_REQUESTED** [review]
There are steps needed to set proper ownership

sudo cp server.crt /var/lib/HPCCSystems/myesp/server.crt
sudo chown hpcc:hpcc /var/lib/HPCCSystems/myesp/server.crt
sudo chmod 644 /var/lib/HPCCSystems/myesp/server.crt

private key last step would be different permissions:

sudo chmod 600 /var/lib/HPCCSystems/myesp/private.key

@mckellyln will help 

Also bad page break on page 88 
@g-pan

**Comment by g-pan** [comment]
@mckellyln please see  http://10.240.32.243/view/Docs%207.0/job/AnotherDocBuild7/70/CE=ubuntu-18.04-amd64-2/artifact/build-docs/Release/docs/EN_US/Installing_and_RunningTheHPCCPlatform_EN_US-7.4.15-closedown0.pdf#page=84  and confirm if correct

**Comment by mckellyln** [comment]
Hi,

In the second part “and for the private key” the name of the file is wrong, it is server.key and I think it should be private.key

And the comments start with # but these don’t need to be in the darkened part of what you actually type.
Can you make the comments be regular text and only have the darkened part be the sudo cp, sudo chown, sudo chmod ?

thanks,
-mark

**Comment by g-pan** [comment]
@mckellyln sure thing. Please have a look at http://10.240.32.243/view/Docs%207.0/job/AnotherDocBuild7/71/CE=ubuntu-18.04-amd64-2/artifact/build-docs/Release/docs/EN_US/Installing_and_RunningTheHPCCPlatform_EN_US-7.4.15-closedown0.pdf#page=84

**Comment by mckellyln** [comment]
Hi,

The private key file should be called private.key, not server.key – in all 3 locations.

thanks,
-mark

**Comment by g-pan** [comment]
@mckellyln 3rd time's the charm. Made the changes and rebased.

**Comment by mckellyln** [comment]
Hi,

I need to see the pdf ?
There should be a

sudo cp
sudo chown
sudo chmod

for both server.crt
and for private.key

but chmod for private key is 600, not 640.

I didn’t see the chown in the commit text ?

thanks,
-mark

**Pull request merged**
