### PR TITLE
HPCC-19632 WIP open for discussion

### PR DESCRIPTION
**Pull request by rpastrana**
Signed-off-by: Rodrigo Pastrana <rodrigo.pastrana@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by rpastrana** [comment]
@mayx take a look, let me know if this approach works for you

**Comment by rpastrana** [comment]
@AttilaVamos it's unlikely that this change caused the roxie test failure, can we look into what happened?

**Comment by mayx** [comment]
@rpastrana A few comments:
1) A ReadWriteLock should be used instead of critical section. Critical section essentially serializes all methods. We can put a WriteLockBlock inside setAttachedState(), and ReadLockBlock inside other methods. This way all the regular methods can be executed in parallel, and will serialize with setAttachedState().
2) Can we hold off releasing this until after my PR is released to avoid endless merge conflicts. Maybe mark this as 7.2?

**Comment by rpastrana** [comment]
@mayx we can wait until after your pr is merged

**Comment by AttilaVamos** [comment]
I rescheduled this PR to see the problem is persistent or transient. It seems transient, but I will check HPCC logs from previous test.

**Comment by rpastrana** [comment]
@mayx we can wait for pull request to merge, but please review the latest changes to this pr.

**Comment by rpastrana** [comment]
@AttilaVamos  odd error message in smoketest, specially since this commit didn't change that line... I'll investigate

**Comment by rpastrana** [comment]
@AttilaVamos this is building fine on my machine, can we rerun?

**Comment by mayx** [comment]
@rpastrana looks much better. Couple of comments: 1) do we need to do the same for esdl_binding.hpp/cpp? 2) If we're already properly protecting at the binding level, do we really need the locks inside esdl store (up for discussion)?

**Comment by rpastrana** [comment]
@mayx please take a look at these changes again, I think you had reservations regarding if this change was actually needed.

**Comment by rpastrana** [comment]
@afishbeck please take a look as well, it's been a while, but I believe this was an attempt to synchronize wsESDLconfig upon attach/detach

**Comment by afishbeck** [comment]
@mayx what were your reservations again?

**Comment by mayx** [comment]
@afishbeck I was asking Rodrigo to release after my change was merged in. My changes were merged quite a while ago so the reservation is gone now.

**Comment by richardkchapman** [comment]
Going to need rebasing, and commit/PR title fixing...

**Pull request closed without merging**
