### PR TITLE
HPCC-24692 Mask reference to spark controlled offensive terms

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Cloud User <centos@michael-temp-c8.novalocal>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@rpastrana Changed everything on our side that could be changed. Used the manager/worker terminology to mimic what we see in Thor clusters.  There's still some MASTER_ variables in the scripts but they have to stay that way for spark-hadoop externals to pick them up properly as environment variables. Where they show up in our logs, things will say manager/worker.

**Review by rpastrana — APPROVED** [review]
@Michael-Gardner

**Comment by richardkchapman** [comment]
@Michael-Gardner Can you check your local git settings please - the signature on your commit is not right

**Comment by Michael-Gardner** [comment]
> @Michael-Gardner Can you check your local git settings please - the signature on your commit is not right

Sorry thought I had that fixed yesterday. For some reason --amend --reset-author didn't work and I didn't catch that it never actually changed. Had to use rebase -i and reword the commit.  Should be showing up correctly now.

**Pull request merged**
