### PR TITLE
HPCC-16766 ZH Translations

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes HPCC-16766

Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@miguelvazq @xwang2713 Please Review

**Review by xwang2713 — COMMENTED** [review]
line 29 AddToExistingSuperfile: "添加到现有超级文件" should be changed to AddToExistingSuperfile:"添加到现有文件集" for consistency.
The same line 145 Directories: "目录" should be changed to Directories: "文件目录"

**Comment by GordonSmith** [comment]
@xwang2713 Updated.

**Review by xwang2713 — COMMENTED** [review]
Looks good

**Pull request merged**
