### PR TITLE
HPCC-15307 Added libmemcached source build to cmake

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner michael.gardner@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@jamienoss Please take a look when you get a chance.

**Comment by Michael-Gardner** [comment]
@richardkchapman Lorraine informed me that Jamie won't be in for a while to look over this PR.  Any suggestions on who else should take a look at it?  My first thought would be Ming?

**Comment by richardkchapman** [comment]
@xwang2713 Please review

**Comment by xwang2713** [comment]
HPCC libmemcached.so linked to libmemcached.so.11. Should it need link to  libmemcached.so.11.0.0? It does for rpm/deb package install

**Comment by Michael-Gardner** [comment]
@xwang2713 I just installed the package on centos 6 and it has symlinks for libmemcached.so, libmemcached.so.11, which both point to libmemcached.so.11.0.0 under /opt/HPCCSystems/lib/.

I also checked the plugin and it's linking against libmemcached.so.11 which in turn is actually libmemcached.so.11.0.0 so it looks like everything is good.  Is this not how you're seeing it?

**Comment by xwang2713** [comment]
yes. The code looks good

**Comment by Michael-Gardner** [comment]
perfect.  @richardkchapman should be ready for your eyes

**Pull request merged**
