### PR TITLE
HPCC-15314 Filter out duplicated schemas for QueryOutputView

### PR DESCRIPTION
**Pull request by wangkx**
Duplicated schemas cause WsECL QueryOutputView to show duplicated
results. In this fix, duplicated schemas are filtered out before
using them in xslt.

Signed-off-by: wangkx kevin.wang@lexisnexis.com

### CODE REVIEW

**Comment by wangkx** [comment]
@afishbeck please review.

**Comment by afishbeck** [comment]
Hmmmm.  You may just be covering up the symptom.  I'd like to know what is duplicating the schemas in the first place.  Looks like ECL may be generating duplicates?

**Comment by wangkx** [comment]
The duplicated schema is read from the "MANIFEST" of workunit dll. To my knowledge, it should be  generated by ECL. I am not sure whether it is by mistake or not.

**Comment by afishbeck** [comment]
Is the multiple schema problem easy to reproduce?

**Comment by wangkx** [comment]
I only reproduced the duplicated display by using original libW....so.

**Comment by wangkx** [comment]
This may be for a separate JIRA.

**Pull request closed without merging**
