### PR TITLE
HPCC-20441 Return special exception for invalid session ID or IP

### PR DESCRIPTION
**Pull request by wangkx**
ESP client (ECLWatch) may choose a predefined action based on the
exception. If the session ID is invalid, ESP also cleans session
related cookies. If the session ID is valid, but, it is from an
IP not same as the IP when session is created, ESP does not
clean the cookies because the new IP may be from an un-authencated
user and the authencated user from the original IP may still use
the session.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by wangkx** [comment]
@RussWhitehead please review.
@miguelvazq please check if this is what you need for https://track.hpccsystems.com/browse/HPCC-20660.

**Comment by RussWhitehead** [comment]
@wangkx Looks good

**Comment by richardkchapman** [comment]
@miguelvazq

**Comment by wangkx** [comment]
@miguelvazq as we discussed, I also clear the cookie when the session is received from a wrong IP.

**Comment by miguelvazq** [comment]
Just to be clear if the user is disconnected and comes back in with a different IP you will clear a the session cookie for the user? So it is the intent to send them back to the login page to re-authenticate? If so, they will lose their place unless we add a path mechanism within ECLWatch that we keep around as a "last couple of places you visited internal browsing history". Keep in mind VPN of any kind can be spotty at times.

**Comment by wangkx** [comment]
Yes, the intent is to let the user to re-authenticate. To do that, as we discussed yesterday, I need to clear the session cookies. If you can let the user to keep their places, that will be great.

**Comment by miguelvazq** [comment]
Currently, there is no way of keeping track of where the was user was last. @GordonSmith thoughts?

**Comment by GordonSmith** [comment]
@wangkx is there a corresponding ECL Watch issue for this?  
Also we would need a test server with this code on it, to implement our end...

**Pull request merged**
