### PR TITLE
HPCC-13581 Fix problem projecting index read with ONFAIL LIMIT

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman should this target 5.2.4?  It is the fix for David's issue.
@jamienoss please review.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by richardkchapman** [comment]
Leave on 5.4.0 for now - see if we need another 5.2.4 build

**Comment by jamienoss** [comment]
@ghalliday is there any coverage of this in the regression suite?
@richardkchapman other than the possible lack of a regression test, this looks good to merge.

**Comment by ghalliday** [comment]
dbayliss43.eclxml in the private regression suite shows the problem.  I could try and isolate an example if necessary.

**Pull request merged**
