### PR TITLE
HPCC-14790 Overwrite Cmake supplied RelDebWithInfo w Release cxx flags

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner michael.gardner@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@mckellyln please review

**Comment by mckellyln** [comment]
Since -O3 can eliminate some more debug info than -O2 and this changes the default CMake RelWithDebInfo, I would consider an alternative approach where we do not strip the exes if a new build variable is added, something like -DSTRIPEXE=OFF, that can be used with Release.

But otherwise this looks fine.

**Comment by Michael-Gardner** [comment]
@richardkchapman Ready for your eyes.  The way I have it set up right now we should have exactly the same c++ flags used regardless of a Release or RelWithDebInfo build.  The only difference is that for a Release build we use set(CPACK_STRIP_FILES TRUE).

**Comment by richardkchapman** [comment]
To Mark's concern, the way we use RelWithDebInfo is to assist in tracking down an issue that only appears in release builds (otherwise we will use a Debug build). A "don't strip" option would work too but then you would overwrite the builds each time you wanted to switch from a genuine Release build to one with DebInfo. That may or may not be a concern.

@GordonSmith @ghalliday Any opinions?

**Comment by ghalliday** [comment]
I would prefer the code to match the release code, than to have better debug information.

I run RelWithDebInfo by default - it is helpful that I can get a useful stacktrack out when it codes/crashes, but matching the code that is running on production systems is more valuable.

**Comment by ghalliday** [comment]
(I would not mind if there was a different option to configure whether release builds are stripped.  If so I would switch to Release and disable stripping.)

**Comment by GordonSmith** [comment]
I am not sure I would want two RelWithDebInfos
From the IDE / Windows point of view this change will not affect them...

**Pull request merged**
