### PR TITLE
HPCC-13832 Add description and owner to LDAP Group creation

### PR DESCRIPTION
**Pull request by RussWhitehead**
As requested by InfoSec in preparation to the RISK Migration, we need to add
group "description" and "owner" to group entries. This PR adds those fields
to the GroupAdd interface, and also retrieves them via the GroupInfo struct
(where needed)

Signed-off-by: Russ Whitehead william.whitehead@lexisnexis.com

### CODE REVIEW

**Comment by RussWhitehead** [comment]
@wangkx Please review

**Comment by wangkx** [comment]
@RussWhitehead two comments.

**Comment by RussWhitehead** [comment]
@wangkx Please rereview

**Comment by wangkx** [comment]
@RussWhitehead looks good.

**Pull request merged**
