### PR TITLE
HPCC-14978 ConfigMgr - Fix hardware copy across files

### PR DESCRIPTION
**Pull request by garonsky**
Signed-off-by: Gleb Aronsky gleb.aronsky@lexisnexis.com

### CODE REVIEW

**Comment by garonsky** [comment]
@wangkx please review

**Comment by wangkx** [comment]
@garonsky some questions - back to you.

**Comment by wangkx** [comment]
@garonsky looks fine now.

**Comment by garonsky** [comment]
@richardkchapman this is ready to merge

**Pull request merged**
