### PR TITLE
HPCC-25892 Update standard log columns in container mode

### PR DESCRIPTION
**Pull request by rpastrana**
- Removes "prefix" field and adds log "class" field to standard log

Signed-off-by: Rodrigo Pastrana <rodrigo.pastrana@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by rpastrana** [comment]
sample log output:
kubectl logs eclwatch-5b484f9c84-wzplx
00000044 USR PRO 2021-05-14 03:18:19.390     1     1 "binding ws_store_binding, on 0.0.0.0:8888"
00000045 USR PRO 2021-05-14 03:18:19.390     1     1 "binding ws_codesign_binding, on 0.0.0.0:8888"
00000046 USR PRO 2021-05-14 03:18:19.390     1     1 "binding ws_resources_binding, on 0.0.0.0:8888"
00000047 USR PRO 2021-05-14 03:18:19.390     1     1 "binding WSDali_binding, on 0.0.0.0:8888"
00000048 USR PRO 2021-05-14 03:18:19.390     1     1 "Metrics initializing..."
00000049 PRG INF 2021-05-14 03:18:19.391     1     1 "Creating sentinel file /tmp/eclwatch.sentinel for rerun from script"
0000004A PRG INF 2021-05-14 03:18:19.391     1     1 "ESP server started."
0000004B OPR MET 2021-05-14 03:19:19.391     1    23 "name=requests,value=2"
0000004C USR PRO 2021-05-14 03:20:19.266     1    19 "CInfoCacheReaderThread Activity Reader: InfoCache collected (0 seconds)."
0000004D OPR MET 2021-05-14 03:20:19.391     1    23 "name=requests,value=3"

Third column contains log entry class type:
disaster(DIS), error(ERR), warning(WRN),information(INF),progress(PRO),metric(MET)

MET type log entries only via Kibana:
image

**Comment by rpastrana** [comment]
@ghalliday please review.
A couple of notes:
- This change assumes _WIN32 and _CONTAINERIZED are mutually exclusive. In its current state they are, but its conceivable a win32 based container could be created in the future.
- The "prefix" is removed in favor of the class column in container mode only, partly to reduce overhead, but mostly to reduce redundancy since programmatic filtering will be based on the class column and won't need the prefix in the message.

**Review by ghalliday — DISMISSED** [review]
@richardkchapman only comment is wondering whether this should also be the default for bare-metal.

**Comment by rpastrana** [comment]
@ghalliday I agree we should avoid diverging from bare-metal if possible, but removing the "prefix" from bare metal is potentially detrimental, and I didn't see much gain in adding the class column...

Keeping the prefix and adding the class column for both modes would be nice and simple, but not optimal imho.

**Comment by rpastrana** [comment]
@ghalliday I just realized I needed to update a readme which discusses the default log columns and the class types, and squashed the change.

**Review by richardkchapman — APPROVED** [review]

**Pull request merged**
