### PR TITLE
HPCC-26093 Move metrics config from values.yml into example files

### PR DESCRIPTION
**Pull request by kenrowland**
Removed metrics config from values.yml. Created new examples
directory for metrics and added README and example yml files
for existing sinks.

Signed-off-by: Ken Rowland kenneth.rowland@lexisnexisrisk.com

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by kenrowland** [comment]
@ghalliday @rpastrana Please do a final review. I had to abandon the original PR to retarget candidate-8.2.x (would not let me merge cleanly for some reason).

I addressed the issue with the accidental change in the original values.yml.

I noted that the logging sink writes to the component log.

As far as what metrics are available from components, I don't think this the the appropriate place to address it.

**Comment by rpastrana** [comment]
> 
> 
> @ghalliday @rpastrana Please do a final review. I had to abandon the original PR to retarget candidate-8.2.x (would not let me merge cleanly for some reason).
> 
> I addressed the issue with the accidental change in the original values.yml.
> 
> I noted that the logging sink writes to the component log.
> 
> As far as what metrics are available from components, I don't think this the the appropriate place to address it.

Depending on how/if available metrics are exposed, the examples/README is a great place to document it. Also, the main point was to get you thinking about that feature. @kenrowland

**Review by ghalliday — COMMENTED** [review]
@kenrowland  Looks good.  Only comment is we have been using .yaml for the file extension, rather than .yml, so these should be changed to be consistent.

**Comment by kenrowland** [comment]
@ghalliday Changed filenames to .yaml and squished. Please approve for merge. Thanks.

**Review by ghalliday — APPROVED** [review]
Looks ok to me.  It raises various questions in my mind about Prometheus will work - but they're independent of this PR.

**Comment by kenrowland** [comment]
@richardkchapman Please merge. Windows compile failure is not related to the changes in this PR. 

Thanks.

**Pull request merged**
