### PR TITLE
HPCC-18705 Spraying/copying between different size cluster appears to be mangling the size in the target file

### PR DESCRIPTION
**Pull request by AttilaVamos**
Fix target parts/file size and compressed size calculation.

Signed-off-by: Attila Vamos <attila.vamos@gmail.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Tested manually with copy between two local system where source has 2 and the target has 4 slaves.
- Spray a file into source system with and without compression.
- Copy uncompressed 2 parts file to uncompresssed 4 parts
- Copy uncompressed 2 parts file to compresssed 4 parts
- Copy compressed 2 parts file to uncompresssed 4 parts
- Copy compressed 2 parts file to compresssed 4 parts

All target files checked with ELWatch:
- part number, sizes
- content from the first record and the last

All target file metadata checked with daliadmin
- file and parts size real and compressed (if applicable)

### CODE REVIEW

**Comment by AttilaVamos** [comment]
@jakesmith please review.

**Comment by jakesmith** [comment]
@AttilaVamos  Re. testing above, how about the other way around, copies from a larger cluster to smaller cluster? Which was the problematic case reported in HPCC-18708
Does this PR fix that case too?

**Comment by AttilaVamos** [comment]
@jakesmith 
I set up a source system with 8 slaves, spray file with and without compression to it, then remote copied those files into a 4 slaves system.
- Copy uncompressed 8 parts file to uncompressed 4 parts
- Copy uncompressed 8 parts file to compressed 4 parts
- Copy compressed 8 parts file to uncompressed 4 parts
- Copy compressed 8 parts file to compressed 4 parts

All target files checked with ECLWatch:
- part number, sizes
- content from the first record and the last

All target file metadata checked with daliadmin

All target physical (part-) file as well as compressed sizes are correct. Both compressed and uncompressed target file shows same and correct content.

**Comment by jakesmith** [comment]
@AttilaVamos - ok, the PR + JIRA titles need changing to reflect not just a small->large cluster spray fix.

**Comment by jakesmith** [comment]
@AttilaVamos - also PR check boxes need doing.

**Comment by AttilaVamos** [comment]
@jakesmith check boxes are done. PR title changed, but I can't change the original JIRA title.

**Comment by jakesmith** [comment]
@AttilaVamos  Thanks, looks good as far as I can tell.

@richardkchapman - ready to merge.

**Pull request merged**
