### PR TITLE
HPCC-32121 Compare and update the PT containerized HPCC to match the EN

### PR DESCRIPTION
**Pull request by vfumene**
## Type of change:
- [x ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Review by g-pan — APPROVED** [review]
Tested and Approved.

**Comment by g-pan** [comment]
Unit Test results :  https://github.com/g-pan/github-action-dev-build/actions/runs/10150067836
Artifacts Approved by SME

**Comment by g-pan** [comment]
Perhaps this should not be approved. No Conflict was detected in testing. 
@vfumene can you please look at this conflict and reply here if it is a duplicate or probably rightfully removed.

**Comment by g-pan** [comment]
Unapproving pending further investigagtions

**Comment by g-pan** [comment]
TESTING - HERE and ON https://github.com/g-pan/github-action-dev-build/actions

**Comment by g-pan** [comment]
[100%] Built target docs

Uploaded bytes 60678586
Finished uploading artifact content to blob storage!
SHA256 hash of uploaded artifact zip is b038c4cacf72bc1615d35ff8b2971c228eed17e5b9714a61c46f437521690049
Finalizing artifact upload

UNIT TEST\S of CONFLICT RESOLVED ALL PASSED> This should be good now.

**Review by g-pan — APPROVED** [review]
APPROVED modified PR

**Comment by ghalliday** [comment]
@g-pan that second commit does not look correct.  The correct solution is to use git rebase to base this commit on the most recent version

**Comment by g-pan** [comment]
I believe only @vfumene  can rebase this as it is his branch. 

Here are the suggested steps:
Use this technique to resolve a CONFLICT (in this Pull Request):

From Git Command Line:
(go to your branch portuguese_lang_update_)
Issue command:
$ git rebase

Hopefully that is ALL required... then you can commit and push and that should be good, ELSE, 
If returns "unable to "Auto-Merge" CONFLICT (Content) error: <message> "

(this case the "conflict" only consisted of some text around lines 1019 - 1100 -which it was showing as the conflict. Only verify that this text needs to be deleted - see my commit https://github.com/hpcc-systems/HPCC-Platform/pull/18846/files  )

Open the offending file (use any text editor) : ConfigureValues.xml and goto line 1019 and if there remove that text from the source -- but ONLY do this if it complains about the CONFLICT - if there is no conflict do NOTHING) 
Also be sure to remove conflict markers (<<<<<, =====, and >>>>>) 
Save the file - 
Then you may need to issue :
$ git add filename.xml
to add the modified file back into your branch

Issue command:
$ git rebase --continue

This may open a commit msg file - edit that file - if necessary - close and should return to command prompt.

Issue command:
$ git push -f origin branchname

After push completes Verify changes here in GitHub - then request my review again.

**Comment by g-pan** [comment]
too many issues. Closing to reissue a new clean Pull Request

**Pull request closed without merging**
