### PR TITLE
HPCC-17105 Default created superfiles in PromoteSuperFile to interleaved

### PR DESCRIPTION
**Pull request by jakesmith**
To match elsewhere.
To not be interleaved meant superfiles would split parts sequentially,
therefore instead of reading all part 1's on node 1, it would read
part 1-M on node 1, part M+1-N on node 2 etc. And consequently where
the cluster was local to the logical files, do a lot of unnecessary
remote reading.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

Full regression suite, that includes some uses of promoteSuperfile, and verified that super files produced were interleaved.

### CODE REVIEW

**Comment by jakesmith** [comment]
@AttilaVamos - please review

**Comment by AttilaVamos** [comment]
@richardkchapman - looks good to merge.

**Comment by richardkchapman** [comment]
Is there any time where non-interleaved is what was desired? Do we need to tell people about this change (redbook)?

@jakesmith One question

**Comment by jakesmith** [comment]
@richardkchapman - I don't really know why non-interleaved was an option - it is an option on manually created superfiles via fileservices (sequential flag).

It _might_ be desirable I suppose on hthor/roxie to have had supers that were read sequentially, but I suspect it should have been a runtime read option, not a publish option.

In cases where the files are being read by a remote cluster or of a different size, it doesn't really matter either way.

**Comment by jakesmith** [comment]
>Do we need to tell people about this change (redbook)?

Not sure, it's quite confusing, the net result is probably to speed up the reads of supers read on Thor created this way.
It also would fix the issue reported in HPCC-17036, but that is also now fixed by handling non-interleaved keys.

**Pull request merged**
