### PR TITLE
HPCC-16386 Improve hoisting of no_dataset_from_transform subgraphs

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@shamser fyi.  It changes various examples in the private regression suite.  The one I looked at looked like a good change.

bip2.eclxml
bip3.eclxml
bizlinka.eclxml
bizlink.eclxml
bug81212.eclxml
cdyho.eclxml
cmandan1.eclxml
cmandan2.eclxml
dabittan.eclxml
dbayliss42.eclxml
dlingle12.eclxml
dlingle13.eclxml
dlingle16.eclxml
giantcpp.eclxml
issue16052.eclxml
klogemann40.eclxml
klogemann43.eclxml
klogemann48.eclxml
klogermann27.eclxml
kturlapathi5.eclxml
madquery1.eclxml
mrhodes10.eclxml
mrhodes11.eclxml
mrhodes12.eclxml
mrhodes14.eclxml
mrhodes4.eclxml
mrhodes7.eclxml
mrhodes9.eclxml
salini4.eclxml
srao2b.eclxml
srao2.eclxml
tina2.eclxml
wfid.eclxml
xbdl2.eclxml
xbdl.eclxml

Please take a look and see what you think.

**Comment by ghalliday** [comment]
The key change in those examples is count(ds) or da[1] being moved out of an inline child query - which generates more code, but reduces the amount of data sent to the activities containing those queries (especially if they are executed remotely).

**Comment by shamser** [comment]
@ghalliday I've looked at a few regression programs and from what I can tell it looks good.  I've also tested the fix with the count(a+b) changes and it's improved the optimization when used with inline ds.

**Comment by ghalliday** [comment]
@richardkchapman

**Pull request merged**
