### PR TITLE
HPCC-16778 Syntax check the contents of macros

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman please review

**Comment by richardkchapman** [comment]
Missing a word 'check'  in the commit message title

**Comment by richardkchapman** [comment]
@ghalliday Change looks fine but commit text needs fixing

**Comment by ghalliday** [comment]
@richardkchapman fixed

**Pull request merged**
