### PR TITLE
HPCC-17060 Changes to ecl standard library not included in package

### PR DESCRIPTION
**Pull request by richardkchapman**
Signed-off-by: Richard Chapman <rchapman@hpccsystems.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately

## Testing:
Built a package, modified standard library, built again, observed the change was taken.

### CODE REVIEW

**Comment by richardkchapman** [comment]
@Michael-Gardner Please review

**Comment by Michael-Gardner** [comment]
@richardkchapman There is a small bug with this (at least on my 16.04 environment).  

The gpg command won't overwrite the ${CMAKE_CURRENT_BINARY_DIR}/${module} file when it goes to update the file, which causes a failure.  If you add the line...

`COMMAND bash "-c" "rm -f ${CMAKE_CURRENT_BINARY_DIR}/${module}"`

add_custom_command just before the GPG_COMMAND_STRING, it should take care of the issue.

**Comment by richardkchapman** [comment]
@Michael-Gardner That sounds like a separate bug rather than a problem with this fix...

Will that work if the commands get run in parallel as I think was discovered recently?

**Comment by richardkchapman** [comment]
A bit of googling suggests adding --batch --yes to the gpg command might help

**Comment by Michael-Gardner** [comment]
I'll test the batch --yes option now

**Comment by Michael-Gardner** [comment]
@richardkchapman  adding --yes after the --batch in the gpg command will work

**Comment by richardkchapman** [comment]
@Michael-Gardner Is that everywhere that --batch is used, or just in this macro?

**Comment by Michael-Gardner** [comment]
We really should only need it in the Macro.  Looking at the code for the 'gpg signing check' that happens on our cmake call, I don't think we'd gain anything by adding it there.  If I was to re-write that section to use an existing file as our target for checking whether or not we could do --clearsign, then having the --yes option would cut down on some code.

**Comment by richardkchapman** [comment]
@Michael-Gardner Repushed to include the extra --yes

**Comment by Michael-Gardner** [comment]
@richardkchapman Tested and works on Ubuntu 16.04.  Looks good.

**Pull request merged**
