### PR TITLE
HPCC-13759 Logical Files names missing

### PR DESCRIPTION
**Pull request by miguelvazq**
Logical files tab was missing its logical file names within the list. Super files now show the relationship between the two and the logical file tabs shows the logical files individually.

Signed-off by: Miguel Vazquez miguel.vazquez@lexisnexis.com

### CODE REVIEW

**Comment by miguelvazq** [comment]
@GordonSmith  Please review.

**Comment by miguelvazq** [comment]
@wangkx Please review.

**Comment by miguelvazq** [comment]
Added a missing variable during our discussion.

**Comment by wangkx** [comment]
Ok, I will continue my review tomorrow.

**Comment by wangkx** [comment]
@miguelvazq looks good now.

**Pull request merged**
