### PR TITLE
HPCC-19258 Remove noroxie from regression files

### PR DESCRIPTION
**Pull request by mckellyln**
Signed-off-by: Mark Kelly <mark.kelly@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by richardkchapman** [comment]
Most of these could be cleared up by suppressing the warning - you see it on Roxie only because joins are implicitly LOOKUP joins by default (@ghalliday can comment on whether adding implicit limits is appropriate on joins that were not specified LOOKUP by the coder).

keydiff is not likley to be supported - put the noroxie back on the test.

Some others have differences related to whether an empty XML result gets reported for a result that is written to disk - these are generally handled by creating a roxie-specific key file for the test in question.

childcondnway, wuread3 and wuread4 and maybe loop10 look like they are highlighting genuine Roxie issues that should be looked at.

**Comment by ghalliday** [comment]
The warnings on the joins are because only roxie defaults to generating them.  They can be suppressed with #onwarning, or by setting #option('warnOnImplicitJoinLimit', false);  same for the index reads ('warnOnImplicitReadLimit').

**Comment by ghalliday** [comment]
@mckellyln

**Comment by mckellyln** [comment]
Added //norixie back in for keydifff and keydiff1 and added \#option() for the joins and index reads.

**Comment by richardkchapman** [comment]
Looks like it needs a rebase

**Comment by mckellyln** [comment]
imgkey.ecl produces error:
Untranslatable record layout mismatch detected for file regress::single::imgfile

**Comment by richardkchapman** [comment]
I opened a Jira for the imgkey issue - PR to follow shortly

**Comment by mckellyln** [comment]
Errors are:

     89. Test: childcondnway.ecl
    <Exception><Code>1413</Code><Source>Roxie</Source><Message>STATE: activity 11 reset without stop (in Iterate 4)</Message></Exception>

    431. Test: loop10.ecl
    <Exception><Source>Roxie</Source><Message>Dataset too large to output to workunit (limit 1 megabytes), in result (name=spill1)</Message></Exception>

    656. Test: splitter-partialstart.ecl
    +<Dataset name='Result 4'>
    +</Dataset>

    826. Test: update.ecl
    +<Dataset name='Result 9'>
    +</Dataset>

    845. Test: wuread3.ecl
    <Exception><Code>1409</Code><Source>Roxie</Source><Message>Failed to retrieve data value Names</Message></Exception>

    846. Test: wuread4.ecl
    <Exception><Code>1409</Code><Source>Roxie</Source><Message>Failed to retrieve data value names</Message></Exception>

**Comment by richardkchapman** [comment]
splitter-partialstart and update will probably require special key files for roxie.

I will raise separate jiras for the others.

**Comment by richardkchapman** [comment]
Created:

HPCC-19711 - childcondnway test fails on Roxie
HPCC-19712 - loop10.ecl fails in roxie
HPCC-19710 wuread3 and wuread4 tests fail in roxie

**Comment by mckellyln** [comment]
@richardkchapman should I update this but leave the 5 as //noroxie so we merge in the other changes ?

**Comment by richardkchapman** [comment]
@mckellyln Yes please

**Comment by richardkchapman** [comment]
@mckellyln Please squash

**Comment by mckellyln** [comment]
ok sure. I was thinking of adding the two new key files for update and splitter-partialstart to this.
Should I do that as part of this or squash as is and add separately.

**Comment by mckellyln** [comment]
squashed

**Pull request merged**
