### PR TITLE
HPCC-13898 Use no_attr_expr in more places

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@AttilaVamos can you investigate which dependencies are missing from the build system which cause the smoketest to fail?

**Comment by AttilaVamos** [comment]
Yes, I'm on.

**Comment by ghalliday** [comment]
Thanks

**Comment by AttilaVamos** [comment]
That was a second run without any changes only reschedule this PR. This problem is a little bit tricky,

**Comment by richardkchapman** [comment]
@jamienoss please review

**Comment by jamienoss** [comment]
@AttilaVamos did you get to the bottom of the build issue? I see that the latter smoketest succeeded but I can't tell that you didn't build serially. There has been no new commit as perhaps expected to fix the build issue.

**Comment by AttilaVamos** [comment]
@jamienoss Not yet, but I'm close. The second run was same parallel build but in other time, other unconscious state of a complex digital system called multi core build machine.

**Comment by jamienoss** [comment]
@richardkchapman this is good to merge.

**Pull request merged**
