### PR TITLE
HPCC-13913 Document FromStringToDate

### PR DESCRIPTION
**Pull request by JamesDeFabia**
Signed-off-by: Jim DeFabia jamesdefabia@lexisnexis.com
@dcamper Please review

### CODE REVIEW

**Comment by dcamper** [comment]
Technically, the function will return zero if either there is a match failure (as documented now) or if the date components match but the result is an invalid date, as in the second example.  Otherwise, looks great.

Note that the internal documentation for the function should probably also be updated.

**Comment by richardkchapman** [comment]
@JamesDeFabia back to you

**Comment by JamesDeFabia** [comment]
@dcamper Edits made, please review again.

**Comment by dcamper** [comment]
Edits look good.  Thanks!

**Pull request merged**
