### PR TITLE
HPCC-11599 Move remainder of the old regression suite over to new suite

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman moves all the old regression suite over to the new structure.  A couple of files will be moved to the performance suite (see separate pull request).  This pull request does introduce some failures which require fixes elsewhere:
- warnings that shoud be ignored (https://track.hpccsystems.com/browse/HPCC-12314)
- tests run on thor that should be (https://track.hpccsystems.com/browse/HPCC-12862)
- no option to supply stored parameters to a query (https://track.hpccsystems.com/browse/HPCC-12863)

@AttilaVamos please review.

**Comment by AttilaVamos** [comment]
@ghalliday 
To solve the "tests run on thor that should be (https://track.hpccsystems.com/browse/HPCC-12862)" issue you can put

//nothor

tag into the relevant test cases.

**Comment by ghalliday** [comment]
@AttilaVamos for some reason this is still on my attention list.  Mentioning you again..

**Comment by AttilaVamos** [comment]
Regression test result is:
Hthor: Total:658 passed:632 failed:26
Thor:  Total:615 passed:529 failed:86
Roxie: Total:659 passed:617 failed:38
@richardkchapman I think the decision is in your hand to merge it now or wait for Regression Engine improvement.

**Pull request merged**
