### PR TITLE
HPCC-12355 Allow configuration of nice value per component

### PR DESCRIPTION
**Pull request by mckellyln**
It has been shown that systems can respond better to pre-flight, ssh'ing in, etc. when running Thor jobs if the Thor processes are re-niced to a slightly lower priority.  This pull request adds the ability to define a nice increment in the HPCC config for several components.

Signed-off-by: Mark Kelly <mark.kelly@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Full QA suite works as expected and Configmgr was used to try nice values for each supported component.

### CODE REVIEW

**Comment by mckellyln** [comment]
@jakesmith please review.  @BrianB644 fyi.

**Comment by mckellyln** [comment]
See https://github.com/hpcc-systems/HPCC-Platform/pull/11072 for the other global method PR

**Comment by BrianB644** [comment]
Hmm … The primary use case for the request feature is to provide an way to configure Thor Slave work to run at a lower priority.

There may be a use case where we want to adjust all of HPCC relative to the rest of the system, but what we ABSOLUTELY NEED … and what this ticket was written to facilitate … is “priority separation” between the highly-threaded compute-bound processing and the processes that support them.

Without priority separation the OS doesn’t know which processes are important and there can be so many compute-bound threads available to run that only a tiny bit of the available CPUs will be used for other tasks. (I should work up a sample calculation)

With priority separation in place most work on a heavily loaded Thor will run at a lower priority. This will allow all the other user-level process on the system to have low-latency first dibs on the available CPUs … meaning they will complete all their work quickly … servicing interrupts, responding to watchdog timers, managing any work the Thor has created, and allowing prospective work, like read-aheads, to function as designed.

If we have a use case for adjusting the whole of HPCC up/down … perhaps it should be a written up separately.

Brian

**Comment by jakesmith** [comment]
Other components are highly thread and highly compute bound, e.g. roxie or hthor.
Others are highly threaded and i/o bound - and we believe it is the intense I/O (network) not high CPU which caused similar issues in some of clusters that were running Lustre.

In the vast majority of setups this has not been an issue at all - standard priority hasn't caused any mp link closed issues.

@BrianB644 - is there any particular disadvantage *if* priority is set because it's causing cpu/network/io contention with other processes/drivers - to not adjust for all? HPCC often co-exist on same now, so lowering priority of just Thor effectively increases priority of dafilesrv for example.

Both a simple global niceness level [default] setting and a per component override can be added if useful.

**Comment by BrianB644** [comment]
From my specific experience, I would disagree that standard priority hasn’t caused any MP-link closed issues. When I worked on the Private Cloud HPCC systems we saw issues … and every AWS system I’ve managed … has been engineered tightly … and they all show the issue when stressed (if the renice script hadn’t been set up or had failed). At my current, when I arrived, both groups I worked with saw these errors daily-ish … but restarting with crossed fingers usually worked … if it didn’t work then they twiddled their jobs (or perhaps relaxed their configurations) until it happened to work. The users had been conditioned to accept it as normal.

I don’t have much experience pushing either Roxie or hThor to it limits … so I can’t really speak to the configuration in question. In retrospect though, I think it is likely that the file system under the Private Cloud (Gluster perhaps) was likely to have been affected. I asked for permission to nice the thor slaves under that system, but I didn’t have admin rights and the admin team wasn’t interested at the time.

I’m not sure I understand the question about “there being any disadvantage if priority is set?” … but I would always recommend adjusting priorities in systems where one is trying to optimize throughput. It is all about priority separation … for HPCC, dafilesrv qualifies as deserving a higher relative priority compared to thor slaves. If everything runs at the same priority than the OS can’t distinguish between different types of work. It seems obvious that any work that benefits from quick access to CPU and that does small bits of specific work especially if it is providing a service to the “business parts” of the system should run at a higher priority (think dafilesrv … it doesn’t create its own work). It doesn’t have to be a higher priority, it just needs to be relatively higher than the work it supports. If there is nothing to denote priority, a form of Priority Inversion will take place if the business parts of the system (think thor slaves) go compute bound which interferes with low-latency access to the CPU for those bits that have low-touch, low-latency support roles (think ssh, dafilesrv, and FUSE filesystems).

Anyway, I liked the original change with the original defaults. Adjusting the nice priority for the whole suite of applications is OK too and I see reasons why to have it as a feature.

Cheers,

Brian

**Comment by mckellyln** [comment]
Closing and will re-open against a new JIRA issue.

**Pull request closed without merging**
