### PR TITLE
HPCC-18377 Add the audience field to the logging

### PR DESCRIPTION
**Pull request by shamser**
Signed-off-by: Shamser Ahmed <shamser.ahmed@lexisnexis.co.uk>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by shamser** [comment]
TODO: Where should this change be documented?

**Comment by shamser** [comment]
@ghalliday Please can you review.

**Comment by ghalliday** [comment]
@richardkchapman should this target 7.4.x or 7.6.0?
@shamser I think jmisc.cpp openLogFile also needs changing.  Should that be using MSGFIELD_STANDARD?

**Comment by shamser** [comment]
@ghalliday @richardkchapman  Shall I re-target to 7.6.0?

**Comment by shamser** [comment]
@ghalliday ECL Watch is not display the log files correctly. There are ECLWatch code that is hard-coded to expect the log files to be in the old format.  Please see WsWuInfo::parseLogLine in ws_workunitHelpers.cpp.  The problem is the old format is assumed for displaying log files in ECL Watch and for search for log for particular workunits.

So, the options I can think of are:
1) Make use of the format specified in environment.conf.   However, if we do that then it won't display/search older older log files correctly.
2) Create a function that "guesses" what fTIM+DAT+MLT+MID+PID+TID+COD+QUO+PFXormat has been written out by examine a few lines of the log file.  This should be easy enough when it's just to determine whether or not the audience has been included.  However, it would be hard to guess every column correctly. (columns such as process id, thread id  and node id are all numbers).
3) Create a header line in every new log file with the format (when missing, assume the format is in the old format).  For example, add something like:
#TIM+DAT+MLT+MID+PID+TID+COD+QUO+PFX

**Comment by shamser** [comment]
A header line is added to record the log format.

**Pull request closed without merging**
