### PR TITLE
Hpcc 12702 add logging manager

### PR DESCRIPTION
**Pull request by rpastrana**
Dynamic ESP services attempt to utilize logging manager if present.

### CODE REVIEW

**Comment by rpastrana** [comment]
@wangkx please review.

**Comment by wangkx** [comment]
Two minors. Looks fine.

**Comment by rpastrana** [comment]
@wangkx please review latest commit

**Comment by wangkx** [comment]
Looks fine.

**Comment by rpastrana** [comment]
@richardkchapman please merge.

**Pull request merged**
