### PR TITLE
HPCC-15721 Dojo version 1.10.5

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes HPCC-15721

Signed-off-by: Gordon Smith gordonjsmith@gmail.com

### CODE REVIEW

**Comment by GordonSmith** [comment]
@richardkchapman This resolved the deprecation warning, but I am not convinced this is the actual issue.  Also these commits are against 1.10.5 tags, so we will need to create branches to match those for the submodule stuff.

**Comment by richardkchapman** [comment]
Why are you targetting 5.6.4 (which is closed...)

**Comment by GordonSmith** [comment]
If this _is_ an issue we will need to fix it for the 5.x code base and this was the closest branch I could find (easier to rebase to actual branch when you create it).

**Comment by richardkchapman** [comment]
Closing as it turns out the warning was a red herring,

**Pull request closed without merging**
