### PR TITLE
HPCC-17646 Memcached dependency added to esphttp and soaplib

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner <michael.gardner@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
I have tested this against a test branch of Kevin's code that requires libmemcached for esphttp and soaplib.  Fixed issue with multiple FindLIBMEMCACHED.cmake calls.  According to the documentation we really shouldn't be using a 'guard header' on our Find modules.  Cmake caches the information internally and will automatically skip find_package, find_path, or find_library if they've already been called with the same parameters, and then insures that the variables that would normally be passed out from the find_package call will be available in the callers scope.

For any additional projects that require libmemcached we should use a template like this ...

{code}
# directly after project() call
find_package(LIBMEMCACHED ${LIBMEMCACHED_MINVERSION})
if(LIBMEMCACHED_FOUND)
    add_definitions(-DUSE_LIBMEMCACHED)
    include_directories(${LIBMEMCACHED_INCLUDE_DIR})
endif()

#at end of cmake project file
if(LIBMEMCACHED_FOUND)
    if(MEMCACHED_USE_EXTERNAL_LIBRARY)
        target_link_libraries(soaplib libmemcached libmemcachedutil)
        add_dependencies(soaplib generate-libmemcached)
        install(CODE "set(ENV{LD_LIBRARY_PATH} \"\$ENV{LD_LIBRARY_PATH}:${PROJECT_BINARY_DIR}:${CMAKE_BINARY_DIR}/build-libmemcached/libmemcached/.libs\")")
    else()
        target_link_libraries(soaplib ${LIBMEMCACHED_LIBRARIES})
    endif()
endif()
{code}

@wangkx Please review

**Comment by wangkx** [comment]
In my limited knowledge, I haven't found any problem here. The code has been tested in my test environment. And the memcached lib was linked to ESP and the function does work for me. @xwang2713 could you please take a second look?

**Review by xwang2713 — COMMENTED** [review]
Looks good

**Comment by Michael-Gardner** [comment]
@richardkchapman Ready for you to look at.

**Pull request merged**
