### PR TITLE
HPCC-16317 Results fail to display

### PR DESCRIPTION
**Pull request by GordonSmith**
Regression in nested dataset code preventing results with a nested numeric to
display.

Signed-off-by: Gordon Smith gordonjsmith@gmail.com

### CODE REVIEW

**Comment by GordonSmith** [comment]
@miguelvazq Please Review

**Comment by richardkchapman** [comment]
This did not affect 6.0 series?

**Comment by GordonSmith** [comment]
No its a regression caused by:  https://github.com/hpcc-systems/HPCC-Platform/pull/9004 (which was issued against master)?

**Comment by miguelvazq** [comment]
Looks good.

**Pull request merged**
