### PR TITLE
HPCC-19615 Return a login error if ESP session is not unlocked

### PR DESCRIPTION
**Pull request by wangkx**
When a user locks an ESP session, an ESPClientLocked cookie will
be created. When the session is unlocked, the cookie will be
removed. When ESP receives a login request, ESP will return a
login error if the cookie exists.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by wangkx** [comment]
@RussWhitehead please review.

**Review by RussWhitehead — COMMENTED** [review]
The code looks fine, but I am concerned that if, say the machine reboots, leaving the cookie, a user will never be able to login/unlock without clearing the cookie cache

**Comment by richardkchapman** [comment]
We can't be the first people ever to encounter this problem, and I've never seen a login page that had a "ignore the cookie" option. There must be a better way!

@GordonSmith

**Comment by GordonSmith** [comment]
I am not sure what the "expected" behavior should even be - but IMO for 7.0.0 I would go with whatever the simplest/default behavior is.

Since we are using cookie based server sessions, you can only have 1 session active across all tabs - this being the case we should probably just keep our expectations simple "you can only ever be logged in as 1 user" - if/when we switch to POST/GET session management (passing the session ID in with each request as an additional param), then this can change.

Assuming the above is acceptable the issue now becomes "what to do with User1 on Tab1 when User2 logs in on Tab2"?  Since every request includes the UserID + SessionID it should be an easy test to check if the combination is valid, if not the server can now boot the user to the logout or login page on Tab 1.  This does imply that the server managing the sessions needs to associate each session with a user ID (which should be a many->one relationship).

I suspect if you go down the road of trying to "hack" a multi user solution into a single user paradigm, you will end up chasing down corner issues forever, which is why a lot of web sites pass the sessionID around as an additional param in the POST/GET calls.

**Comment by wangkx** [comment]
@RussWhitehead please correct me if I am wrong: When a user locks a page, ECLWatch UI keeps the page behind a Unlock page and ESP kills the session. If the user unlocks the page, ESP creates a new session. Then, ECLWatch UI removes the Unlock page and displays the page which was locked. If a user logs into the ECLWatch from another tab when a page is locked, this PR may warning the user that 'Some session information about previous locked page(s) is found. If you login to ECLWatch from this tab, you may have to manually navigate to that page'.

**Comment by RussWhitehead** [comment]
@wangkx That sound like what we discussed. A question, if they try to log into the same ESP from a different tab, could the locked pages be unlocked using the new cookie/session?  Or could we report to the user "You are already logged into this ESP, please switch to the locked tab and unlock?"    My goal is to keep the user from loosing the screens they have already navigated to

**Comment by wangkx** [comment]
To unlock the page in another tab, we need to support the communication between tabs. @miguelvazq could you please confirm that?

**Comment by miguelvazq** [comment]
The cross tab communication (currently implementing) when you unlock in one tab it will broadcast an unlock any tab matching that Host/IP in the browser window instance.

**Comment by wangkx** [comment]
I am closing this PR because the design may change after the cross tab communication is implemented. For example, the ESPClientLocked cookie may not be needed if the tab for new login page may find the locked tab....

**Pull request closed without merging**
