### PR TITLE
HPCC-22059 Dfsclient-7.2.8 release update for spark plugin

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
Includes bug fixes for common-hpcc and dfsclient.  @jpmcmu Please review

**Comment by jpmcmu** [comment]
@Michael-Gardner looks good

**Comment by Michael-Gardner** [comment]
@richardkchapman Ready for merge.

**Comment by richardkchapman** [comment]
Should this be targeting 7.2.x ? Is this something that should be automatically updated every time we tag?

**Comment by richardkchapman** [comment]
@Michael-Gardner

**Comment by Michael-Gardner** [comment]
@richardkchapman It shouldn't be automatically updated every time we tag because it's not always guaranteed that we'll be generated new jars if there aren't bug fixes that need to go into a new release.

**Comment by richardkchapman** [comment]
@Michael-Gardner I suspect we should generate new ones per point-release of platform anyway.

**Comment by Michael-Gardner** [comment]
@richardkchapman Talked to the other Java project members and we'll start to release a new dfsclient and spark-hpcc each release, regardless of bug fixes that we have available.  I can get the major.minor.point out of the version.cmake file and set the DFSCLIENT_VERSION and SPARK_HPCC_VERSION to match.  Should make it so we don't have to touch this file in the future.

I'll update this PR to include those changes.

**Comment by richardkchapman** [comment]
@Michael-Gardner I think this is waiting for something from you?

**Pull request closed without merging**
