### PR TITLE
HPCC-13869 ESP Exception not echoed correctly.

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes HPCC-13869

Signed-off-by: Gordon Smith gordon.smith@lexisnexis.com

### CODE REVIEW

**Comment by GordonSmith** [comment]
@miguelvazq Please Review

**Comment by richardkchapman** [comment]
Should this target 5.2.6?

**Comment by GordonSmith** [comment]
I will re-target it.  FWIW the bug is that it is hiding an underlying ESP Exception - from ECL Watches point of view this bug has always been there, I suspect the ESP Exception is new or the regression test which highlighted this is new.

**Comment by GordonSmith** [comment]
Re-issuing against 5.2.6:  https://github.com/hpcc-systems/HPCC-Platform/pull/7526

**Pull request closed without merging**
