### PR TITLE
HPCC-15637 envgen - set thor master option

### PR DESCRIPTION
**Pull request by garonsky**
- set_ips thor <IPs> will use first IP as thor master

Signed-off-by: Gleb Aronsky gleb.aronsky@lexisnexis.com

### CODE REVIEW

**Comment by garonsky** [comment]
@Michael-Gardner please review

**Comment by Michael-Gardner** [comment]
@garonsky Works well.  Only comment I have is that the error output on line wizardInputs.cpp:341 is a bit confusing.

-env ~/my.xml -ip 10.176.32.23-29 -supportnodes 1 -thornodes 2 -assign_ips thor 10.176.32.25-26

Exception: -1:
Total nodes: 7 (1 Support Nodes + 6 Non-support Nodes)
Error: Cannot assign 2 number of nodes for Thor Slaves due to insufficient non-support nodes available. Please enter different values

The exception makes it seem like we aren't giving it enough nodes in total, but in reality the issue is how many nodes we're giving the thorcluster explicitly with the assign_ips range.

**Comment by richardkchapman** [comment]
@garonsky This PR seems to have stalled?

**Comment by garonsky** [comment]
@Michael-Gardner update error message based comments.  Please review again.

**Comment by richardkchapman** [comment]
@Michael-Gardner This is waiting for you...

**Comment by Michael-Gardner** [comment]
@richardkchapman Looks good.

**Pull request merged**
