### PR TITLE
HPCC-18556 Ensure url /c$ (and similar) are translated.

### PR DESCRIPTION
**Pull request by jakesmith**
Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Simple hand-crafted tests, e.g.
```
Owned<IFile> iFile = createIFile("//192.168.1.115/c$/tmp2/testwrite");
Owned<IFileIO> iFileIO = iFile->open(IFOcreate);
```

involving a Linux - >Win dafilesrv.

Validated that fix hit correct directory

### CODE REVIEW

**Comment by jakesmith** [comment]
@richardkchapman - please review 

NB: I am running regression suite, will report back that passed, but unlikely to hit code.

**Comment by jakesmith** [comment]
@richardkchapman - regression suite passed.

**Comment by richardkchapman** [comment]
Is this still needed once other changes have been made (by Kevin/Attila)?

**Comment by jakesmith** [comment]
Yes.
Kevin/Attila's changes are to ensure that sprays/desprays aren't rejected due to mismatching the path when lookup a dropzone (due to casing or posix mismatch).

Once it passes that though and a posix path like /c$/path/ is used on a windows dropzone, it succeeds, but writes to the wrong directory, i.e. C:\c$\path\ instead of C:\path\

**Comment by jakesmith** [comment]
Closing for now

**Pull request closed without merging**
