### PR TITLE
HPCC-27486 Allow symbols to be stripped from release builds

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
For discussion.  I think it reduced my local image size from 2.5GB to 1.85GB.  It would be worthwhile investigating where the rest of the size is coming from - that still seems rather large.

Having a quick look:

sha256:988ef21d07b4df46bbbe383d3a697d95a6aedc40386e76432b6056db34a6d07b   33 minutes ago   /bin/sh -c apt-get install -y   default-jdk   g++   git   git-lfs   openssh-client   libapr1   libnuma1   libboost-regex1.71.0   libpython3.8   libmemcached11   libmemcachedutil2   libmysqlclient21   libxslt1.1   locales   python   psmisc   r-base-core   zip   libarchive13   libatlas3-base   curl   1.3GB     

is the bulk of the size.  It might be worth investigating how that can be reduced...

**Comment by jakesmith** [comment]
Changes look fine, but isn't this going to hamper our post-mortem efforts when there's a problem?
Should this only be applied when !Debug and !RelWithDebInfo ?

**Review by jakesmith — COMMENTED** [review]
see questions

**Comment by ghalliday** [comment]
Merged as part of HPCC-27805

**Pull request closed without merging**
