### PR TITLE
HPCC-13246 Constant rows are now legal to link count

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@jamienoss please review

**Comment by ghalliday** [comment]
With the changes in the memory manager for 5.0/5.2 it is now legal to link/release constant rows.

This change on its own only has an effect on a few examples (lnpoc, reil1), its main effect is in combination with HPCC-13245 - not yet released.

**Comment by jamienoss** [comment]
@ghalliday Looks ok to me.
Is It ok to merge without HPCC-13245 then? You say that it only has an affect on a few examples but is that effect ok?

**Comment by ghalliday** [comment]
Have a look at the differences in generated code, and see what you think!

Even with HPCC-13245 It doesn't seem to be making many changes (regression still running) - it may require another change which won't be released for a while to show a significant difference.

**Comment by ghalliday** [comment]
@richardkchapman please review/merge

**Pull request merged**
