### PR TITLE
HPCC-24202 Fix htpasswd memory leak in error handling

### PR DESCRIPTION
**Pull request by timothyklemm**
Capture file loading exceptions so they may either be re-thrown or released. Any
exception message starting with "htpasswd" will be re-thrown. All others will be
repackaged and released.

Signed-off-by: Tim Klemm <tim.klemm@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by timothyklemm** [comment]
@RussWhitehead please review.

**Review by RussWhitehead — CHANGES_REQUESTED** [review]
Code look good but formatting is incorrect (view file)

**Comment by timothyklemm** [comment]
Serious question: If the formatting discrepancy is because the file is filled with tab characters, we're not supposed commit tabs, and we're not supposed to combine tab replacement with other code changes, which formatting rule takes precedence? I honestly don't know, and opted for the "mine is correct and the rest can be fixed later" solution.

**Comment by RussWhitehead** [comment]
Yes, I feel your pain.  I recommend you line up the entire CATCH block to be consistent with the matching TRY. I think it's a worthy improvement

**Comment by richardkchapman** [comment]
In general, the rule "match the style of the surrounding code" tends to take precedence over "match the style guide of the project".

Tabs are particularly awkward though (which is why we prefer not to let them in in the first place).

I'm fine with merging this as is

**Pull request merged**
