### PR TITLE
HPCC-16367 Add more date/time functions to Std Lib Ref 

### PR DESCRIPTION
**Pull request by JamesDeFabia**
Signed-off-by: Jim DeFabia jamesdefabia@lexisnexis.com
@dcamper Please review (pdf sent)

### CODE REVIEW

**Comment by dcamper** [comment]
IsValidTime() has an incorrect return value description and general description.

CurrentDate() has an incorrect return value description.

Everything else looks good.

@JamesDeFabia Back to you.

**Comment by JamesDeFabia** [comment]
@dcamper Edits made, please review again

**Comment by dcamper** [comment]
For consistency, please make some changes to IsValidTime(); suggestions, which obviously you can modify:

time argument description:  "A time value in the Time_t format."
General description:  "The IsValidTime function returns TRUE if the time is valid, by validating each of the individual components (hours, minutes and seconds)."

These were cribbed from IsValidDate().  Striving for consistency.

CurrentDate() looks good.

**Comment by JamesDeFabia** [comment]
@dcamper Edits made, please have another look. (pdf sent)

**Comment by dcamper** [comment]
@JamesDeFabia Everything looks great.  Thanks, Jim!

**Pull request merged**
