### PR TITLE
HPCC-18771 Refactor (Docs) Directory Structure

### PR DESCRIPTION
**Pull request by g-pan**
Fix HPCC-18771 Refactor (Docs) Directory Structure
Part of Internationalization effort needed to refactor 
the Docs directory structure. 
This is an extensive change, please review thoroughly. 

Testing results can be viewed at: 
http://10.240.32.243/job/DocDevII/

@xwang2713 please review
@JamesDeFabia please review

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [x] This change is a POTENTIALLY breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [x] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Testing and Test results can be viewed on 
      http://10.240.32.243/job/DocDevII/

### CODE REVIEW

**Comment by JamesDeFabia** [comment]
Looks ok from my point of view. 
@xwang2713 should have the last word.

**Comment by xwang2713** [comment]
These changes are only related to docs build (under docs/ directory). The build run OK and the contents are reviewed by Greg and Jim. It looks good for me.

**Comment by richardkchapman** [comment]
I merged this, then noticed that the commits seem a bit messed up so reverted. May need to reopen the PR after commits are sorted out

**Comment by richardkchapman** [comment]
@g-pan

**Pull request merged**
