### PR TITLE
HPCC-15030 Recursively expand modules inside the plugin directory

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman I think this is the code needed to fix the ML library visability, but I haven't managed to test it at all.

**Comment by richardkchapman** [comment]
@cloLN Is this something you could test?

**Comment by cloLN** [comment]
hmmm.  @ghalliday - is this something I can see in configmgr or is this elsewhere?

**Comment by richardkchapman** [comment]
You would see it in eclide if connected to an eclserver that had additional source installed

**Comment by cloLN** [comment]
Is there a separate pull request for the esp changes required?

**Comment by richardkchapman** [comment]
@ghalliday ? I think esp may use this code...

**Comment by ghalliday** [comment]
@cloLN esp uses this code, but there are no required changes in esp to get it to work.  It calls utility functions which generate the xml that it requires.

**Comment by cloLN** [comment]
Finally able to get this to work.  was able to copy the ML library into /opt/HPCCSystems/plugins and IDE recognized it instantly and was able to see nested folders.

**Pull request merged**
