### PR TITLE
HPCC-14653 STORED-FORMAT-SELECT to create drop down on generated form

### PR DESCRIPTION
**Pull request by afishbeck**
Support new select attribute to STORED(FORMAT(...)) to create a drop down selection input
on the generated WsECL form.

string ch1 := 'none' : stored('ch1', format(select('apple,banana,pear')));

Will create a drop down on the generated form with choices "apple",
"banana", and "pear".

Signed-off-by: Anthony Fishbeck anthony.fishbeck@lexisnexis.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@wangkx please review

**Comment by afishbeck** [comment]
I'll update the regression test result key.

**Comment by afishbeck** [comment]
@wangkx updated with a few enhancements, and updated the test key.

You can now specify display text and specify the default:

    unsigned8 u8 := 0 : stored('u8', format(fieldwidth(8), sequence(18), select('one=1,two=2,three=3,*four=4')));

    string ch1 := 'ban' : stored('ch1', format(select('apple=app,pear,*banana=ban,orange'))); //banana is default
    string ch2 := '' : stored('ch2', format(select(',apple=app,pear,banana=ban,orange'))); //start with empty, no specified default
    string ch3 := '' : stored('ch3', format(select('apple=app,pear,*,banana=ban,orange'))); //empty in middle, is default

**Comment by wangkx** [comment]
@afishbeck looks fine.

**Pull request merged**
