### PR TITLE
HPCC-23640 Force failure if Python development libs not found

### PR DESCRIPTION
**Pull request by Michael-Gardner**
- Removes deprecated PythonLibs and replaces with FindPython2 and FindPython3
- Removes add_plugin logic so builds will fail if development python/python3 libs aren't located
- Using HPCC_ADD_SUBDIRECTORY and USE_PYTHON2/USE_PYTHON3 are set ON by default in commonSetup.cmake

Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 Please review

**Comment by Michael-Gardner** [comment]
@xwang2713 Please review if you can find the time.  Small changes to move  from the deprecated PythonLibs module to FindPython2 & FindPython3 modules (cmake 3.12+). Removed Add_plugin logic and added REQUIRED to the find_package call.  Control to include pyembed & py3embed is done with HPCC_ADD_SUBDIRECTORY( USE_PYTHON2/3).

**Review by xwang2713 — COMMENTED** [review]
Looks good

**Comment by xwang2713** [comment]
Do we need require mini cmake to 3.12?

**Comment by Michael-Gardner** [comment]
Think we already do require 3.13.0 or greater
@richardkchapman ready for merge

**Comment by richardkchapman** [comment]
This feels more like a 7.8/master level change to me

**Comment by richardkchapman** [comment]
@Michael-Gardner

**Comment by Michael-Gardner** [comment]
This is a bug fix that exists in 7.6.x.  @xwang2713 I believe that 7.6. is where we went to forcing python to always be present?  We went away from thinking about python2 and 3 as plugins and expecting them in normal CE builds.

**Comment by richardkchapman** [comment]
It's a bigger change than I am willing to put in 7.6.x at this late stage, if all it gives us is detection of a misconfigured build system

**Comment by Michael-Gardner** [comment]
Ok I'll rebase and set it up to target master then

**Comment by Michael-Gardner** [comment]
Rebased to master, Doing a quick test to ensure the functionality remains the same after changing target branches.

**Comment by Michael-Gardner** [comment]
@richardkchapman ready for merge

**Pull request merged**
