### PR TITLE
HPCC-16611 Ignore SIGPIPE after ldap_bind() calls

### PR DESCRIPTION
**Pull request by mckellyln**
Updated PR with a more complete and better fix.

Signed-off-by: Mark Kelly <mark.kelly@lexisnexis.com>

### CODE REVIEW

**Comment by mckellyln** [comment]
This still does not resolve issue.

**Comment by mckellyln** [comment]
@richardkchapman this PR is cleaner, more simple and correct code for ignoring SIGPIPE after ldap_bind() calls AND also it does not reset handler to SIG_DFL but to what it was before in dtor of LinuxPipeProcess.

**Comment by richardkchapman** [comment]
The title of the commit (and the pull-request) is now somewhat misleading, as it's not really related to LDAP at all...

**Comment by richardkchapman** [comment]
But since it's referring back to the prior attempts to fix (which WERE believed to be ldap related)  it's probably clearest to leave it

**Pull request merged**
