### PR TITLE
HPCC-15635 - Memcached tests fail with undefined symbols

### PR DESCRIPTION
**Pull request by richardkchapman**
Rename our memcached plugin to avoid name clash with the memcached API dll.

Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@cloLN FYI
@jamienoss FYI
@ghalliday Please review/merge

**Comment by richardkchapman** [comment]
@Michael-Gardner Can you review too please

**Comment by cloLN** [comment]
clo@ubuntu1404:~/regress/regress6001/regress$ ./ecl-test query memcache*.ecl
[Action] Suite: hthor
[Action] Queries: 2
[Action]   1. Test: memcachederrortests.ecl
[Pass]   1. Pass W20160527-101522 (9 sec)
[Pass]   1. URL http://10.176.152.200:8010/?Widget=WUDetailsWidget&Wuid=W20160527-101522
[Action]   2. Test: memcachedtest.ecl
[Pass]   2. Pass W20160527-101532 (15 sec)
[Pass]   2. URL http://10.176.152.200:8010/?Widget=WUDetailsWidget&Wuid=W20160527-101532
[Action]
    -------------------------------------------------
    Result:
    Passing: 2
    Failure: 0
    -------------------------------------------------
    Log: /home/clo/regress/regress6001/log/hthor.16-05-27-10-15-21.log
    -------------------------------------------------
    Elapsed time: 27 sec  (00:00:27)
    -------------------------------------------------

[Action] Suite: thor
[Action] Queries: 1
[Action]   1. Test: memcachedtest.ecl
[Pass]   1. Pass W20160527-101550 (15 sec)
[Pass]   1. URL http://10.176.152.200:8010/?Widget=WUDetailsWidget&Wuid=W20160527-101550
[Action]
    -------------------------------------------------
    Result:
    Passing: 1
    Failure: 0
    -------------------------------------------------
    Log: /home/clo/regress/regress6001/log/thor.16-05-27-10-15-48.log
    -------------------------------------------------
    Elapsed time: 17 sec  (00:00:17)
    -------------------------------------------------

[Action] Suite: roxie
[Action] Queries: 2
[Action]   1. Test: memcachederrortests.ecl
[Pass]   1. Pass W20160527-101608 (10 sec)
[Pass]   1. URL http://10.176.152.200:8010/?Widget=WUDetailsWidget&Wuid=W20160527-101608
[Action]   2. Test: memcachedtest.ecl
[Pass]   2. Pass W20160527-101618 (16 sec)
[Pass]   2. URL http://10.176.152.200:8010/?Widget=WUDetailsWidget&Wuid=W20160527-101618
[Action]
    -------------------------------------------------
    Result:
    Passing: 2
    Failure: 0
    -------------------------------------------------
    Log: /home/clo/regress/regress6001/log/roxie.16-05-27-10-16-06.log
    -------------------------------------------------
    Elapsed time: 28 sec  (00:00:28)
    -------------------------------------------------

**Comment by Michael-Gardner** [comment]
Built and installed on a centos 6 box.  Everything is linking correctly.  Looks good.

**Pull request merged**
