### PR TITLE
HPCC-16897 FIX OSX client tools "libsecuresocket.so missing"

### PR DESCRIPTION
**Pull request by afishbeck**
OSX version of client tools should be looking for libsecuresocket.dylib.

Signed-off-by: Anthony Fishbeck <anthony.fishbeck@lexisnexis.com>

### CODE REVIEW

**Comment by afishbeck** [comment]
@richardkchapman can you test this on OSX?

**Comment by afishbeck** [comment]
Also improved error message.

**Comment by richardkchapman** [comment]
Well it worked in the sense that it now tries to load the correct library (and succeeds, provided it can find it via DYLD_LIBRARY_PATH). But it then seems to hang indefinitely...

It may well be that the ESP I am hitting does not have ssl configured.

**Comment by afishbeck** [comment]
@richardkchapman if the previous version failed with this error, and after this fix it hangs, then most likely this exact problem was successfully fixed.  Making sure SSL actually works properly on OSX would require a properly configured ESP.

**Pull request merged**
