### PR TITLE
HPCC-23556 GlobalThis undefined in Edge

### PR DESCRIPTION
**Pull request by miguelvazq**
When trying to view ECL Watch in Edge there is a console error that
GlobalThis is undefined. GlobalThis is unsupported in IE.

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by miguelvazq** [comment]
@kunalaswani Can you test?

**Review by GordonSmith — APPROVED** [review]
Code Looks good, but should probably target 7.6?

**Review by kunalaswani — APPROVED** [review]
Tested, looks to have resolved the object error.

**Comment by GordonSmith** [comment]
@richardkchapman ready to pull.

**Comment by richardkchapman** [comment]
@GordonSmith Did you want to target 7.6?

**Comment by GordonSmith** [comment]
@richardkchapman good question - 7.4 if possible...

**Comment by richardkchapman** [comment]
We can merge to 7.4 but we won't be doing a 7.4 build unless there is a compelling reason (does this count?)

**Comment by GordonSmith** [comment]
Maybe - its an IE11 breaker, but given no one noticed its probably just time to deprecate IE11 support now with a view to dropping it in 8.x (especially now IDE has no IE dependency).

**Comment by richardkchapman** [comment]
Then I say merge to 7.4 but don't tag it until other changes force us to

**Comment by GordonSmith** [comment]
@miguelvazq can you rebase for 7.4?

**Comment by miguelvazq** [comment]
> @miguelvazq can you rebase for 7.4?

Will do when I get into office first thing.

**Comment by miguelvazq** [comment]
@GordonSmith Rebased.

**Comment by GordonSmith** [comment]
@miguelvazq can you re-target 7.4?

**Comment by miguelvazq** [comment]
@GordonSmith Should be good now.

**Comment by GordonSmith** [comment]
@richardkchapman ready to be pulled (and up merged).

**Comment by richardkchapman** [comment]
@migNow it's targetting 7.4.0 (not 7.4.x) and has a stray commit in it.

git rebase --onto candidate-7.4.x HEAD^ && git push origin -f

**Comment by GordonSmith** [comment]
@richardkchapman I tidied that up...

**Pull request merged**
