### PR TITLE
HPCC-17993 Fix prefix to correct installation target

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 and @rpastrana Please take a look at this PR.
Jenkins build: http://10.240.32.243/view/custom/job/MG-CE-64/

**Comment by Michael-Gardner** [comment]
I think we are assuming the wrong location.  a 64 bit package should be installed under "Program Files" on a 64 bit machine, a 32 bit package should be installed under "Program Files" on a 32 bit machine, the only time we need the (x86) is if we are installing a 32 bit package on a 64 bit machine, which we don't do anymore.

I think the x86 is leftover from when we just did 32 bit clienttools builds and nothing else.  If you could comment on this I would appreciate it Ming.  I know you know a lot about the windows builds.

**Comment by richardkchapman** [comment]
Is the env being looked up at make time (as opposed to install time) ? If so, not sure there is any point carefully lookup up the settings in the environment since there's no reason to suppose they will match on the install machine - especially as there is much confusion about whether 32-bit windows programs even get to see the program files environment settings (so behaviour is likely to depend on whether cmake is 64-bit or 32-bit program...). 

If my reading is correct and these settings are dependent on the environment as seen by CMake, then may as well hard-wire them and be done with it.

**Comment by richardkchapman** [comment]
I'm not sure it's correct to say we don't install 32-bit packages on 64-bit machines - that's up to the user to decide which package they want, and for most purposes 32-bit is likely to be preferred even on 64-bit hardware.

**Comment by richardkchapman** [comment]
I would also argue that the 32-bit OS case is now vanishingly rare, so this change feels like it's moving in the wrong direction.

What was the symptom that caused this issue to be opened in the first place??

**Comment by Michael-Gardner** [comment]
They are done by cmake, you are correct.  I was trying to find a registry key or something last night that would help with the problem, but I don't know as much on windows environments as Ming does.  

It originally was found due to the esdl.bat filling in this variable at build time, and then on a 64 bit machine, it would appear that we were expecting to be installed in the x86 folder, when in fact our 64 bit package was properly installed in the Program Files folder where it belonged.  That's why I think this might have been leftover from before we were building 64 bit windows clienttools.

**Comment by Michael-Gardner** [comment]
@richardkchapman Rodrigo and I have been talking and think we should probably set this to 6.4.2 so we can test it a bit more.

**Comment by rpastrana** [comment]
@Michael-Gardner so the original issue has to do w/ a path in the ESDL.bat which we generate at build-time, which could end up being wrong depending on where the clienttools actually gets installed?

**Comment by rpastrana** [comment]
@richardkchapman we can defer this to 6.4.x
@Michael-Gardner is it worthwhile drafting up a known limitation for this?

**Comment by Michael-Gardner** [comment]
Yes that is correct.

**Comment by Michael-Gardner** [comment]
Yeah it wouldn't be a long writeup.

**Comment by richardkchapman** [comment]
Pushing back to 6.4.2 and closing for more analysis

**Comment by xwang2713** [comment]
The x64 build installed OK. I am build ing x86 and will double check the install.  CPack variable CPACK_INSTALL_PREFIX is little mis-leading. For x64 build it still point to "Program Files (x86)"

**Pull request closed without merging**
