### PR TITLE
HPCC-17038 Report and return POLLERR errors

### PR DESCRIPTION
**Pull request by mckellyln**
## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [x] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [x] Performance
  - [x] Security
  - [x] Thread-safety
  - [x] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

Full QA suite passed

### CODE REVIEW

**Comment by mckellyln** [comment]
@jakesmith re-targeted PR.  If we do check for data available and there is an error, not sure how to best dump that data and still throw/fail ?

**Comment by jakesmith** [comment]
> If we do check for data available and there is an error, not sure how to best dump that data and still throw/fail ?

From the poll() man page, it doesn't sound possible to have both..:

```
The field revents is an output parameter, filled by the kernel with
the events that actually occurred.  The bits returned in revents can
include any of those specified in events, or one of the values
POLLERR, POLLHUP, or POLLNVAL.  (These three bits are meaningless in
the events field, and will be set in the revents field whenever the
corresponding condition is true.)
```

So implies you cannot have POLLIN + (POLLERR | POLLHUP | POLLNVAL)
In which case the order of checking POLLIN vs POLLERR etc. is irrelevant ..

And this change is good to go.

**Comment by jakesmith** [comment]
@richardkchapman - as far as I can tell, change is good, ready to merge.

**Comment by richardkchapman** [comment]
Are we sure this is not going to lead to excessive tracing?

**Comment by jakesmith** [comment]
I am not sure, @mckellyln ?
Perhaps need a environment.con setting to enable it (though we really only want on for Thor).

**Comment by mckellyln** [comment]
We only log if we find errors so I do not think it should lead to extra logging.
QA suite passes with no additional tracing reported that I can see.

**Comment by richardkchapman** [comment]
Ok, just wanted to make sure we had thought about it

**Comment by richardkchapman** [comment]
@mckellyln Can you squash to one commit please

**Comment by mckellyln** [comment]
Something did not go coeectly with the squash and I am missing one commit.
I will re-issue PR with correct code changes.

**Comment by mckellyln** [comment]
New PR is: https://github.com/hpcc-systems/HPCC-Platform/pull/9670

**Pull request closed without merging**
