### PR TITLE
HPCC-13503 Use "jobtemp::" as a prefix for temp files with job duration

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@jamienoss please review

**Comment by jamienoss** [comment]
@ghalliday are you sure these are all cases covered?

For example hqlresource.cpp:~2016
```
IHqlExpression * CResourceOptions::createDiskSpillName()
{
    StringBuffer s;
    s.append("~spill::");
    appendUniqueId(s, spillSequence.next());
    return createConstant(s.str());
}
```
is unchanged, and the jira suggests that this may also need altering though the function name, perhaps, the opposite? As you can see I am unsure of which are which, job temporaries vs spills between subgraphs.

**Comment by ghalliday** [comment]
@jamienoss that is the case that needs to stay the same because it is a spill within a single graph.  hqlresource takes a single graph and splits it into subgraphs, creating spills.

**Comment by jamienoss** [comment]
@richardkchapman good to merge.

**Pull request merged**
