### PR TITLE
HPCC-23232 Eclagent's use of QueryTerminationCleanup wrong.

### PR DESCRIPTION
**Pull request by jakesmith**
QueryTerminationCleanup at the end process, must clearup
before the query dll is unloaded.
If it waits until atexit, any hooks installed by the query
dll of dependent dlls, will be called to late and could crash.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
@ghalliday - please review

**Comment by ghalliday** [comment]
@richardkchapman @jakesmith this change looks reasonable.

As a summary it is trying to fix the problems with gcc < 2.18 where thread termination functions can be called after dlls are unloaded.  If the change is needed for hthor then I suspect thor, roxie (and anything else?) should also be explicitly calling the hook destructors on the main thread before exiting.

**Comment by jakesmith** [comment]
I think you're right, but have only seen this being hit on eclagent so far.
Shall we merge this one, which bit us, and open a separate JIRA for otehrs?
@ghalliday @richardkchapman

**Comment by mckellyln** [comment]
Perhaps not seen in thor, roxie because eclagent/hthor is started/stopped much more often.

**Comment by richardkchapman** [comment]
Roxie is never stopped other than via a kill... and it's main thread never calls any of the plugins that might add a hook.

Thor may also not ever use its main thread to call plugins?

**Pull request merged**
