### PR TITLE
HPCC-16754 Python embedded languages integrated into platform

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 This moves py2embed and py3embed into the platform.  Please review.  The plugins/py(x)embed/CMakeLists.txt files simply have the `if(PYEMBED)` condition removed, the rest is fixed indentation.

@johnholt I doubt I'll be able to make dependencies on packages installed by pip.  That will  most likely need to be a change in documentation.  I can talk with @g-pan about whatever we decide to do.

This PR will most likely need to be modified once we merge https://github.com/hpcc-systems/HPCC-Platform/pull/10587

**Comment by xwang2713** [comment]
Do we need add python3 to cmake_modules/dependencies/?

**Comment by xwang2713** [comment]
I take a back. python2 will still available in future Ubuntu release

**Comment by xwang2713** [comment]
Looks good

**Comment by Michael-Gardner** [comment]
@richardkchapman I have rebased this against master and fixed the conflicts in the pyembed/py3embed CMakeLists.txt.  It's ready to be merged if you want to take a look at it.

**Comment by richardkchapman** [comment]
If I'm reading the diff correctly, this is basically removing the IF() tests around the building of the python plugins. 

It would be better if the conditions were retained for use by developers that want to build on systems where python libraries are not installed, and we just adjusted when they are set (and potentially what they are called).

@Michael-Gardner

**Comment by Michael-Gardner** [comment]
Ok I'll make those changes.

**Comment by Michael-Gardner** [comment]
@AttilaVamos What exactly happened with the smoketest here?  Was there an issue with the smoketest as a whole, or is something actually wrong with my branch?

**Comment by AttilaVamos** [comment]
There was some strange thing around. I think it would be better if I reschedule this PR and let us see what happen.

**Comment by Michael-Gardner** [comment]
Thanks Attila!

**Comment by AttilaVamos** [comment]
It is very likely your result won't be clean based on something wrong with unittests, but this isn't related to this PR.

**Comment by Michael-Gardner** [comment]
@richardkchapman I tested it this way against LN and CE builds, and with Ubuntu 17.04 and Centos 7.  Instead of the changes to the Plugin CMakeLists.txt files, I just enabled the INCLUDE_PYxEMBED variable by default for both 2 and 3.

**Pull request merged**
