### PR TITLE
HPCC-29573 Fix sasha service not found in WS-FS

### PR DESCRIPTION
**Pull request by wangkx**
When I archive a DFU workunit in a cloud environment, I got the 'Service 'sasha-wu-archiver' not found' error. It is because incorrect service type is used to find out sasha service. For ECL WU, the service type for sasha should be 'wu-archiver'. For DFU WU, the service type for sasha should be 'dfuwu-archiver'.

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Review by jakesmith — APPROVED** [review]
Look fine.
I think given this hasn't been working and it's a simple fix, it would be better if this was rebased/retargeted to 8.12.x

**Comment by wangkx** [comment]
@ghalliday this PR has been retargeted to 8.12.x. Please merge.

**Comment by AttilaVamos** [comment]
The On-Demand Smoketest (AWS) found a core file related to ESP server after Regression Testing. 
Unfortunately the GDB crashed during trace file generated, so I can provide only this information:
```[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `esp snmpid=16928'.
Program terminated with signal SIGSEGV, Segmentation fault.
../../gdb/psymtab.c:316: internal-error: sect_index_text not initialized
A problem internal to GDB has been detected,
further debugging may prove unreliable.
```
I can't find any more information in esp.log, Perhaps it happened at clean up.

**Comment by wangkx** [comment]
I haven't found any relation between the core and the changes in this PR.

**Comment by ghalliday** [comment]
Change looks good.  Waiting for tests to run.  I agree the core is unlikely to be related to this issue.

**Pull request merged**
