### PR TITLE
HPCC-28651 Disable multicast by default in bare-metal

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman @mckellyln pushed to provoke a discussion....

**Review by mckellyln — APPROVED** [review]
Looks good.

Just an fyi, there are a few places such as:
in ccdmain:
```
            IWARNLOG("multicastTTL value (%d) invalid, must be >=0, resetting to %u", ttlTmp, multicastTTL);
```
and in ccdqueue is:
```
            DBGLOG("Roxie: multicastTTL: %u", multicastTTL);
```
these should not log or not log "multicast" at least if it is disabled.

**Comment by richardkchapman** [comment]
This change will have the documented effect, but what the impact will be on bare metal performance is hard to predict. I suspect most bare metal systems will actually be unaffected unless you rename the option, since the setting is likely burned in to existing environment.xml files

**Review by richardkchapman — APPROVED** [review]

**Comment by richardkchapman** [comment]
This change will have the documented effect, but what the impact will be on bare metal performance is hard to predict. I suspect most bare metal systems will actually be unaffected unless you rename the option, since the setting is likely burned in to existing environment.xml files

**Comment by richardkchapman** [comment]
Also should be noted that multicast isn't just used for the outbound message from server to agent - it's also used for IBYTI and potentially sniffer flow control (though I think the latter may have been removed)

**Comment by ghalliday** [comment]
@richardkchapman I think I did rename it.   I may need to check all the xsl files etc copy it across correctly

**Comment by ghalliday** [comment]
@richardkchapman pushed a commit to update the other configuration files.  The main question is do we think this is a good idea?

**Comment by richardkchapman** [comment]
Changing bare metal to be closer to cloud means the cloud setup is less of an unknown, but also means that we risk breaking our "fallback" bare metal config.

In this instance operation with multicast off is well-enough known that I don't think it's a big deal either way. On that basis I'd be inclined not to bother, but it's up to you.

**Comment by ghalliday** [comment]
Needs testing and probably shouldn't change the option name.  Closing for now.

**Pull request closed without merging**
