### PR TITLE
HPCC-23036 Distribute PKI keys using admin user

### PR DESCRIPTION
**Pull request by Michael-Gardner**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@mayx Please review one last time so we can get this merged.  Rebased with master to fix the history where I cherry-picked your HPCC-23035 commit.

**Review by mayx — COMMENTED** [review]
Overall looks good. Couple of minor suggestions:
1) generate-hpccsystems-target.in only change is one extra new line, probably not intended?
2) in pik_setup.cmake, can we change to:
message(STATUS \"Running setup of environment for a local dev build\")
if(EXISTS ${INSTALL_DIR}/etc/init.d/setupPKI)
  execute_process(COMMAND ${INSTALL_DIR}/etc/init.d/setupPKI)
endif()

Reason is for developers who have DESTDIR defined, if they run make package, they'll get the warning and it's kind of confusing...

**Comment by mayx** [comment]
Or even:
if(EXISTS ${INSTALL_DIR}/etc/init.d/setupPKI)
message(STATUS "Running setup of environment for a local dev build")
execute_process(COMMAND ${INSTALL_DIR}/etc/init.d/setupPKI)
endif()

**Comment by mayx** [comment]
Also the wording can be a bit more specific:

if(EXISTS ${INSTALL_DIR}/etc/init.d/setupPKI)
message(STATUS "Running pki setup for a local dev build")
execute_process(COMMAND ${INSTALL_DIR}/etc/init.d/setupPKI)
endif()

**Comment by Michael-Gardner** [comment]
@mayx made the changes you requested.  Removed that added line from the systemd generate target file.  Here's what I ended up with for the pki setup install code

install(CODE "
if(EXISTS ${INSTALL_DIR}/etc/init.d/setupPKI)
  message(STATUS \"Running pki setup for a local dev build\")
  execute_process(COMMAND ${INSTALL_DIR}/etc/init.d/setupPKI)
endif()
")

**Review by mayx — APPROVED** [review]
@Michael-Gardner looks good.

**Comment by Michael-Gardner** [comment]
@richardkchapman ready for merge

**Pull request merged**
