### PR TITLE
HPCC-12670 Allow user provide non-default path for required development ...

### PR DESCRIPTION
**Pull request by xwang2713**
Allow HPCC build search both user provided libraries path and native path

Previously HPCC only allow user use either "EXTERNALS_DIRECTORY"  or native libraries (IF USE_NATIVE_LIBRARIES is not set to OFF native libraries will overwrite ""EXTERNALS_DIRECTORY" settings) .  With this change user can use both. "EXTERNALS_DIRECTORY" will be searched first if provided. If libraries file or header files not found and "USE_NATIVE_LIBRARIES" is  "ON".  navie libraries path will be tried.

@mckellyln @Michael-Gardner please help review.

### CODE REVIEW

**Comment by richardkchapman** [comment]
Calling FIND_PATH a second time for a given variable will not do anything if the variable was already set by a previous FIND_PATH. This is standard CMake behaviour. As such I'm not sure that this change is actually doing anything?

**Comment by xwang2713** [comment]
It only re-run if nothing found.
From CMake documentation for FIND_PATH: "If nothing is found, the result will be <VAR>-NOTFOUND, and the search will be attempted again the next time find_path is invoked with the same variable".
Also I can add "unset" before re-try FIND_PATH.

But not sure if we still want this pull-request. For official platform/clienttools build  we always use native libraries.

**Comment by richardkchapman** [comment]
Unless I'm misunderstanding your code, it's suppressing the second find_path if the first one found something - but this is not needed because of the cmake semantics as described above.

**Comment by mckellyln** [comment]
I will reexamine, I thought it was common to:

find_library(<VAR> NAMES name PATHS paths... NO_DEFAULT_PATH)
find_library(<VAR> NAMES name)

to try and find a lib in a custom path before looking in the default place.

**Comment by xwang2713** [comment]
Talked with Mark. We think it probably is better to move this to 5.4.0 or later.
We don't want to have any impact on 5.2.0 RC1 which is coming very soon.

**Comment by richardkchapman** [comment]
It's already targetting master (i.e. 6.0)

**Comment by xwang2713** [comment]
Mark thinks it is un-necessary to keep this ticket. I will close this pull-request as well as the JIRA HPCC-12670

**Pull request closed without merging**
