### PR TITLE
Hpcc 15726 fix 6.0.2

### PR DESCRIPTION
**Pull request by AttilaVamos**
MoveExternalFile() unable to move file if the source or target name contains any character that's invalid to a logical file path

### CODE REVIEW

**Comment by AttilaVamos** [comment]
@jakesmith please review.

**Comment by jakesmith** [comment]
@AttilaVamos - looks like commits need squashing and message/description corrected.

**Comment by jakesmith** [comment]
@AttilaVamos - see comments in JIRA.

**Comment by richardkchapman** [comment]
Please rebase/reopen for 6.0.4

**Pull request closed without merging**
