### PR TITLE
HPCC-21395: Repair and rationalize client tools build on macOS Mojave

### PR DESCRIPTION
**Pull request by dcamper**
Signed-off-by: Dan S. Camper <dan.camper@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Projects built with these changes include a release version of macOS client tools and an Ubuntu 18.04 platform version. Client tools testing has been confined to a non-thorough manual test of the compiler and some features of the ecl binary. The Ubuntu 18.04 platform compiles (after a manual modification to some downloaded libmemcached code) but an exhaustive test has not been completed.

### CODE REVIEW

**Comment by dcamper** [comment]
Previous PR (https://github.com/hpcc-systems/HPCC-Platform/pull/12120#event-2121151770) had been closed.  This is a replacement.

**Comment by dcamper** [comment]
@xwang2713 Ming, please recheck a build from this branch.  It incorporate Ken's Boost fix.  Thanks!

**Comment by xwang2713** [comment]
Build run successfully: http://10.240.32.243/job/CE-clienttools-osx-JIRA-21395/CE=mac_osx_x86_64/5/console

**Comment by dcamper** [comment]
@xwang2713 Thanks, Ming!

I modified an endif() within cmake_modules/FindCBLAS.cmake to avoid a cmake warning (mismatched arguments).

@richardkchapman Please re-review when you get a chance.  Thanks

**Comment by dcamper** [comment]
Rebased to current 7.2.0 branch.

@richardkchapman Please review.  Thanks!

**Comment by richardkchapman** [comment]
@dcamper I think there may be another change needed following recent upmerges to 7.2.0

**Comment by dcamper** [comment]
@richardkchapman Updated a new instance of a U_ICU_VERSION_MAJOR_NUM check.  Please re-review.  Thanks!

**Pull request merged**
