### PR TITLE
HPCC-28213 Remove libmysql from vcpkg dependencies

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by AttilaVamos** [comment]
It seems, this change doesn't fix the problem, because we have same core after hthor finished:
```
[New LWP 10162]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `hthor --workunit=W20220920-135608-1 --daliServers=10.22.254.38:7070'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007efdd05f30f8 in ?? () from /lib64/libgcc_s.so.1

Backtrace for all threads
==========================
Thread 1 (Thread 0x7efdce7aa140 (LWP 10162)):
#0  0x00007efdd05f30f8 in ?? () from /lib64/libgcc_s.so.1
#1  0x00007efdd05f3ff9 in _Unwind_Backtrace () from /lib64/libgcc_s.so.1
#2  0x00007efdd010ecd6 in backtrace () from /lib64/libc.so.6
#3  0x00007efdd161f675 in printStackReport (startIP=139628264575936) at /home/centos/smoketest/PR-16537/HPCC-Platform/system/jlib/jexcept.cpp:1545
#4  0x00007efdd161fc3d in excsighandler (signum=11, info=0x7ffc877f0f30, extra=0x7ffc877f0e00) at /home/centos/smoketest/PR-16537/HPCC-Platform/system/jlib/jexcept.cpp:1158
#5  <signal handler called>
#6  0x00007efdbd1c53c0 in ?? ()
#7  0x00007efdd1dcecd2 in i18n_cleanup() () from /opt/HPCCSystems/lib/libeclrtl.so
#8  0x00007efdd1e1247c in ucln_cleanupOne_69 () from /opt/HPCCSystems/lib/libeclrtl.so
#9  0x00007efdd1e1251a in ucln_lib_cleanup_69 () from /opt/HPCCSystems/lib/libeclrtl.so
#10 0x00007efdd1e12577 in u_cleanup_69 () from /opt/HPCCSystems/lib/libeclrtl.so
#11 0x00007efdd1643ed5 in InitTable::exit (this=this@entry=0xd01030, ctx=ctx@entry=0x0) at /home/centos/smoketest/PR-16537/HPCC-Platform/system/jlib/jlib.cpp:110
#12 0x00007efdd1643fc5 in ExitModuleObjects (ctx=<optimized out>) at /home/centos/smoketest/PR-16537/HPCC-Platform/system/jlib/jlib.cpp:40
#13 0x0000000000402309 in main ()
```
and the WUID is created for :
```
egrep 'W20220920-135608-1' RelWithDebInfo_Regress_Hthor_2022-09-20_13-13-13.log
[Pass] 978. Pass xmlread.ecl ( version: multiPart=true ) - W20220920-135608-1 (2 sec)
[Pass] 978. URL http://127.0.0.1:8010/?Widget=WUDetailsWidget&Wuid=W20220920-135608-1
```

**Comment by ghalliday** [comment]
> It seems, this change doesn't fix the problem, because we have same core after hthor finished:

I don't think this crash is related to mySQL - it is because the icu library is linked into multiple dlls as an archive.  Did this target the correct issue number?

**Review by ghalliday — CHANGES_REQUESTED** [review]
Was this meant to target HPCC-28211?

**Comment by mckellyln** [comment]
I agree, this PR is a suggested fix to HPCC-28211 (https://track.hpccsystems.com/browse/HPCC-28211)

**Pull request closed without merging**
