### PR TITLE
HPCC-14140 Potential thread and socket leak from cacheFileConnect

### PR DESCRIPTION
**Pull request by richardkchapman**
Remove weirdly-coded workaround for (since fixed) inability to set timeout
when connecting to remote files.

Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@jakesmith Please review

**Comment by jakesmith** [comment]
@richardkchapman - looks a good change to me.

**Comment by ghalliday** [comment]
Looks like a good change.

@richardkchapman what about dafilesrcLookupTimeout - should that be deleted?  Should the control message "control:dafilesrvLookupTimeout" be updated/deleted?

**Comment by richardkchapman** [comment]
@ghalliday I changed it so that dafilesrvLookupTimeout retains its original meaning.

**Pull request merged**
