### PR TITLE
HPCC-23258 Improve resourcing of expressions evaluated once

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
@shamser please review.
Some examples that change:
spillread1 xyan1 kel351c
They all get smaller, generally because results that are already calculated are saved as temporary results and then used instead of being recalculated.

**Review by shamser — COMMENTED** [review]
@ghalliday xyan1 is failing to compile:
ut.hasField(13,10): error C2215: stringtouppercase does not have FOLD specified, can't constant fold it
ut.hasField(17,9): error C2215: While expanding macro <param>
ut.hasField(18,8): error C2215: While expanding macro <param>
IDLExternalLinking.mac_xLinking_on_thor_Boca(14,46): error C2215: While expanding macro hasfield
DID_Add.MAC_Match_Flex(742,72): error C2215: While expanding macro mac_xlinking_on_thor_boca
Ingenix_NatlProf.Sanctions_Code_DID(20,21): error C2215: While expanding macro mac_match_flex
ut.hasField(13,10): error C2071: Constant expression expected
ut.hasField(13,130): error C3001: Too many errors (max = 5); Aborting...
ut.hasField(17,9): error C2071: While expanding macro <param>
ut.hasField(18,8): error C2071: While expanding macro <param>
IDLExternalLinking.mac_xLinking_on_thor_Boca(14,46): error C2071: While expanding macro hasfield
DID_Add.MAC_Match_Flex(742,72): error C2071: While expanding macro mac_xlinking_on_thor_boca
Ingenix_NatlProf.Sanctions_Code_DID(20,21): error C2071: While expanding macro mac_match_flex
13 errors, 1 warning

**Comment by shamser** [comment]
@ghalliday spillread1 has also reported 10 errors

**Comment by ghalliday** [comment]
@shamser that error isn't connected to this PR.  You need to run the regression suite so that plugins are picked up by eclcc (and used in place of the definitions in the archive).

**Review by shamser — APPROVED** [review]
@richardkchapman Reviewed

**Pull request merged**
