### PR TITLE
HPCC-22657 Fix unittest issues using uncontactable IPs

### PR DESCRIPTION
**Pull request by jakesmith**
HPCC-22627 meant the IP's in a file being published, might
be contacted if the meta size info was missing.

In the case of some unit test logical files, the IPs
were made up, and no part size meta info was added.
That causes a hang trying to contact the made up IPs.

Fix by publilshing with size meta data for the purposes
of these unit tests.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jakesmith** [comment]
@AttilaVamos - can you review/test this on OBT?

**Comment by richardkchapman** [comment]
Better still would be if trying to fetch meta from an uncontactable IP did not hang up...

**Comment by jakesmith** [comment]
Agree, Mark is looking at general jsocket change to try to avoid lengthy connects if IP is unreachable.

**Comment by AttilaVamos** [comment]
@jakesmith I can confirm, with this fix both tests are pass in OBT environment. (Log files are attached to the JIRA)

**Comment by jakesmith** [comment]
@richardkchapman - please merge

**Pull request merged**
