### PR TITLE
HPCC-17340 Include libRInside.so and check for Rcpp version at build

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner <michael.gardner@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 Please review this.  Richard wanted libRInside.so added to the rembed package.  I've gone ahead and fixed the build boxes so they all have appropriate versions of R, Rcpp, Rinside, and inline.  This also checks at build time to make sure the Rcpp version is equal or greater than 0.12.1.

**Comment by Michael-Gardner** [comment]
@richardkchapman Here are the changes you requested in https://github.com/hpcc-systems/HPCC-Platform/pull/9755 for the build/packaging process.

**Comment by Michael-Gardner** [comment]
@richardkchapman I've gotten rinside included into the package, but in testing I found that r-base-core wasn't being added as a dependency even when using dpkg-shlibdeps.  I've gone ahead and appended it to the dependency list within the Rembed project.

In testing on a 16.04 machine with no dependencies met, `apt-get install -f` now pulls in libr.so.  Our copy of libRinside.so under /opt/HPCCSystems/lib is getting linked to correctly.  But when run eclcc against testing/regress/embedR.ecl, the output executable gives this error when ran.

> Error: function 'dataptr' not provided by package 'Rcpp'
> In addition: Warning message:
> In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
>  there is no package called 'Rcpp'
> Segmentation fault (core dumped)

I checked with the rembed.cpp and it does appear that RCPP_HEADER_ONLY is defined properly.  If I look at the symbol table of libRembed.so I see HIDE_RCPP_dataptr defined in text.  And no symbols that are just dataptr.  Also all the symbols in libRembed.so that are in the Rcpp namespace appear to be defined in text, and there are none that are undefined (which is expected bc we aren't linking to a libRcpp.so).

**Comment by richardkchapman** [comment]
@Michael-Gardner R versioning and Rcpp is a mess.

You could try adding r-cran-rcpp to the dependencies as well as r-cran-core. But I am concerned that may interfere with people that want to install R/Rcpp manually in order to get newer versions?

**Comment by Michael-Gardner** [comment]
It looks like we might be good post 16.04 if we include r-cran-rcpp.  14.04 and 12.04 are both going to have issues with rcpp versioning but if those are really the only two hard cases, we can probably get away with adding something to the redbook about them.  It will make the downstream installation of the Rembed plugin easier for the majority of users.

el6 and el7 look like the epel repositories will provide sufficient versions of rcpp. el5 might not have a sufficient version but we're just about out of the support window for that version of centos.

I'll also test against installing Rcpp through the package manager, and then a higher version through a manual install.

**Comment by Michael-Gardner** [comment]
@richardkchapman Ready for you to look at.  Rembed now appends its dependencies.  It also includes libRInside.so in  the package.  

Ubuntu 12.04 was the only platform I was having any issues with.  Mainly due to the fact that the version of R on it was so old and we had to use a custom repository to pull in the dependencies.  But since that won't be a supported version for 6.4.0, there no longer is a problem.

**Pull request merged**
