### PR TITLE
HPCC-13897 Spray ignoring replication=false and creating logical files flagged as replicated

### PR DESCRIPTION
**Pull request by AttilaVamos**
Set defaultCopies = DFD_NoCopies if not replicate a file.

Signed-off-by: Attila Vamos attila.vamos@gmail.com

### CODE REVIEW

**Comment by AttilaVamos** [comment]
@jakesmith please review.

**Comment by jakesmith** [comment]
@AttilaVamos - there is similar code in CFileSprayEx::onCopy(), which I think needs the same change.

**Comment by AttilaVamos** [comment]
@jakesmith it seems this changes not enough. I should recheck my previous attempt.

**Comment by AttilaVamos** [comment]
@jakesmith CFileSprayEx::onCopy() updated, ECLWatch 'Is Replicated:' issue clarified. Please re-review.

**Comment by jakesmith** [comment]
@richardkchapman - good to merge.

**Pull request merged**
