### PR TITLE
HPCC-18947 Libbase58 linking for jlib in plugins builds

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner <michael.gardner@lexisnexisrisk.net>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 Please review and test this.  Should fix the linking issue you were seeing in the nightly builds with jlib not finding libbase58 when making plugins.

**Comment by mckellyln** [comment]
When did libbase58 get added ?
Should it be a sub-module ??

**Comment by Michael-Gardner** [comment]
@mckellyln It got added early in December.  It is setup just like lzma and lz4 as a static module. It's likely fine the way it is.  I think @afishbeck would have more information for you on that.

**Comment by mckellyln** [comment]
ok, thanks.  I was just asking, as it seems to me stuff like this is often brought in as a sub-module.
Just for accuracy, lz4 is a sub-module.
@afishbeck fyi.

**Comment by AttilaVamos** [comment]
@Michael-Gardner The error is:
CMake Error at cmake_modules/commonSetup.cmake:516 (add_subdirectory):
  The binary directory

    /mnt/disk1/home/vamosax/smoketest/PR-10766/build/system/libbase58

  is already used to build a source directory.  It cannot be used to build
  source directory

    /mnt/disk1/home/vamosax/smoketest/PR-10766/HPCC-Platform/system/libbase58

  Specify a unique binary directory name.
Call Stack (most recent call first):
  system/CMakeLists.txt:22 (HPCC_ADD_SUBDIRECTORY)

**Comment by xwang2713** [comment]
Looks good

**Comment by Michael-Gardner** [comment]
we certainly could set it up that way Mark.  It appears that there is a github for the project here https://github.com/bitcoin/libbase58.  @afishbeck is this something you would want done?

**Comment by Michael-Gardner** [comment]
@AttilaVamos Think I figured out why that was an issue.  Pushed a new commit for the smoke test to check.

**Comment by AttilaVamos** [comment]
@Michael-Gardner build & test session started.

**Comment by Michael-Gardner** [comment]
@richardkchapman ready for merge

**Comment by afishbeck** [comment]
@Michael-Gardner @mckellyln I think I need to change the library a bit to compile properly in windows.  Let's keep it local for now.  Once I make the changes I'll consider submitting them to the source project, then if they accept the changes we can consider making it a sub-module.  They may not care about windows.

**Comment by richardkchapman** [comment]
@afishbeck You happy with this change?

**Comment by Michael-Gardner** [comment]
@richardkchapman want me to squash these commits?  The way it gets handled here now should be identical to how lz4 and lzma get handled in cmake, when added as a dependency to jlib.

**Comment by Michael-Gardner** [comment]
@richardkchapman ready for merge

**Comment by afishbeck** [comment]
@richardkchapman I think the change is fine.

**Pull request merged**
