### PR TITLE
HPCC-13573 Improve throttling and diagnostic statistics

### PR DESCRIPTION
**Pull request by jakesmith**
- Split throttling into 2 categories (slow/fast).
- Allow throttle items to queue rather than block
- Improve error reporting/feedback to client
- Improve configurability over limits
- Improve statistics, # clients, # reqeusts, throttling and allow
  to be requested via dafscontrol

Signed-off-by: Jake Smith jake.smith@lexisnexis.com

### CODE REVIEW

**Comment by jakesmith** [comment]
@mckellyln @ghalliday - please review

**Comment by ghalliday** [comment]
I haven't looked at sockfile.cpp yet, but the rest looks ok.

Only comment so far is that some of the code (possibly especially in sockfile?) might be simpler if you used an array indexed by the throttle type instead of 2 distinct classes.  It would also make it easier to add extra classes later.  Not worth changing retrospectively though.

**Comment by ghalliday** [comment]
CAsyncCommandManager::wait() - shouldn't that be calling threadsem.wait?

**Comment by ghalliday** [comment]
throwErr() could be more clearly renamed to appendErr()

**Comment by ghalliday** [comment]
cmStats should have dimension of RFCmax

**Comment by ghalliday** [comment]
minor:         cmdStats[cmd] = cmdStats[cmd]+1;
could be         cmdStats[cmd]++;

**Comment by ghalliday** [comment]
It is also probably worth sorting the list for all clients in getInfo()

**Comment by ghalliday** [comment]
It looks like currentCmd may be uninitialised when it gets to line 3657

**Comment by jakesmith** [comment]
>CAsyncCommandManager::wait() - shouldn't that be calling threadsem.wait?

whoops!
Yes it should, correcting.

**Comment by jakesmith** [comment]
>throwErr() could be more clearly renamed to appendErr()

agree, although not new, but I'll change.

**Comment by ghalliday** [comment]
Actually I misread - it is ok.

**Comment by jakesmith** [comment]
>cmStats should have dimension of RFCmax

actually because of the RFCunknown and:
```
        memset(&cmdStats[0], 0, sizeof(cmdStats));
```
it would have to be of RFCmax+1 or RFCunknown.

Instead I'll make the memsets:
```
        memset(&cmdStats[0], 0, sizeof(unsigned)*(RFCmax-1));
```

**Comment by jakesmith** [comment]
>minor: cmdStats[cmd] = cmdStats[cmd]+1;
could be cmdStats[cmd]++;

agreed, will change

**Comment by ghalliday** [comment]
Second pass:

                if (0 == avail)
                    avail = 0;

is a bit redundant.

**Comment by jakesmith** [comment]
>It is also probably worth sorting the list for all clients in getInfo()

ok, changed.

**Comment by jakesmith** [comment]
>is a bit redundant.

remnant of something I was debugging, there are a couple of others too, the "cmd too high .." sections, which I haven now removed.

**Comment by ghalliday** [comment]
{
                    CriticalBlock b(crit);
                    totalThrottleDelay += ms;
                }

It is a shame that we need to use a critical block.  This would really benefit from the c++11 atomic operations.  Alternatively it could probably use an atomic_t since it is unlikely to wrap.

**Comment by ghalliday** [comment]
not so bad  - that is only executed when a command is throttled.  I had thought it was all commands.

**Comment by ghalliday** [comment]
GetInfo no longer returns a value

        reply.append(retcode).append(retstr.str());

is now

        reply.append(0).append(retstr.str());

was that intended?

**Comment by ghalliday** [comment]
@richardkchapman with the second commit the changes look ok.  (Just one question about getInfo outstanding).  It would be worth trying to review it carefully.

**Comment by jakesmith** [comment]
>was that intended?
> And will it cause issues in the caller?

It was intentional.
It unconditionally returned 0 before and only used in psuedo code cmdFirewall

**Comment by mckellyln** [comment]
Why doesn't sockfile.cpp show up with changes ?  Is it because there are too many ?

**Comment by richardkchapman** [comment]
I assume so - mostly moved code. I downloaded the branch and compared locally

**Pull request merged**
