### PR TITLE
Build json trim flag

### PR DESCRIPTION
**Pull request by linuxsc**
@afishbeck

### CODE REVIEW

**Comment by richardkchapman** [comment]
Tony is on vacation at the moment - he should review when he returns.

I think you have some tabs in this file (expanding to 8 chars in github). Can you change to use spaces with our standard 4 character indent please.

**Comment by afishbeck** [comment]
@linuxsc Sorry I hadn't reviewed this already.  Since we are building the JSON string ourselves I think it would be more efficient to modify the function buildJsonAppendValue adding a feature to trim the value if the flag is set, rather than post processing the resulting JSON after its built.  Trimming while appending should also be a much smaller change.

**Comment by richardkchapman** [comment]
@afishbeck This appears to have stalled - anything we can do to move it forward?

**Comment by afishbeck** [comment]
@richardkchapman This is the wrong approach and doesn't do quite what I thought anyway.  Can be closed for now until a simpler solution is submitted.

**Pull request closed without merging**
