### PR TITLE
HPCC-14474 Improve testing of sorts

### PR DESCRIPTION
**Pull request by ghalliday**
Add random, sorted, reverse sorted tests, and check results
are sorted, and sorting is stable.

Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
See also https://github.com/hpcc-systems/ecl-bundles/pull/39

**Comment by ghalliday** [comment]
@richardkchapman please review

**Comment by ghalliday** [comment]
Note: The PR for the merge sort changes includes the new tbbsort implementation.

**Comment by ghalliday** [comment]
@AttilaVamos the error has been associated with the wrong test

**Comment by AttilaVamos** [comment]
@ghalliday I'm working on the error report fix.

**Comment by ghalliday** [comment]
@AttilaVamos that is better.
@richardkchapman please review

**Comment by richardkchapman** [comment]
What if anything are we planning to do about those warnings?

**Comment by richardkchapman** [comment]
@ghalliday One question

**Comment by ghalliday** [comment]
When my sort change (https://github.com/hpcc-systems/HPCC-Platform/pull/7922) is merged in they will go away.

**Comment by ghalliday** [comment]
@richardkchapman replied

**Pull request merged**
