### PR TITLE
HPCC-25220 Fix workunit library clearAliases() causing ESP to core

### PR DESCRIPTION
**Pull request by afishbeck**
Iterating over ptree elements while removing them corrupted the iterator,
will remove properties until none remain instead.

Signed-off-by: Anthony Fishbeck <anthony.fishbeck@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by afishbeck** [comment]
Although @jakesmith this use of the iterator hasn't changed in over 10 years.  Any change it was exposed by the PTree auto qualifier maps changes?  or something else changing in ptree?

**Review by jakesmith — APPROVED** [review]
@afishbeck - change looks good.

The old code was inherently unsafe, I've seen crashes with similar code before.
I don't know why it has only shown up a bug now, but it is possible that the auto qualifier maps have something to do with it...
and I see CMapQualifierIterator is in the stack, so it's involved. So more than likely this old bug has been exposed by those changes.

**Comment by richardkchapman** [comment]
Is 7.12.x the right target for this? Should it be earlier?

**Comment by AttilaVamos** [comment]
@afishbeck I am sure the schedule1.ecl error is not related to this PR

**Comment by afishbeck** [comment]
@richardkchapman I think the change that exposed this was introduced in 7.12.0 but we could target this fix much earlier if you’d like.

**Pull request merged**
