### PR TITLE
HPCC-15001 SecManager restructure to support per-binding secmanager p…

### PR DESCRIPTION
**Pull request by RussWhitehead**
…lugins

Refactor dynamic load of security manager plugins to support new and improved
description in esp.xml configuration that can vary by service binding.

Signed-off-by: Russ Whitehead william.whitehead@lexisnexis.com

### CODE REVIEW

**Comment by RussWhitehead** [comment]
@rpastrana Please review

**Comment by rpastrana** [comment]
@RussWhitehead minor comment, otherwise looks fine.

**Comment by RussWhitehead** [comment]
@richardkchapman Please merge and close

**Comment by richardkchapman** [comment]
Is this for 6.0 ? If so please target the candidate-6.0.0 branch

**Comment by richardkchapman** [comment]
@RussWhitehead One question

**Comment by RussWhitehead** [comment]
Closing PR and replacing with https://github.com/hpcc-systems/HPCC-Platform/pull/8276

**Pull request closed without merging**
