### PR TITLE
HPCC-14457 Split R plugin to its own package

### PR DESCRIPTION
**Pull request by richardkchapman**
Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@cloLN @Michael-Gardner @fvillanustre Please review/comment

**Comment by Michael-Gardner** [comment]
The following change should also allow us to create a better 'requires' list for centos installations.  We might also want to think about not sourcing the dependency file if we are doing an MAKE_R_ONLY build.

```
        set ( CPACK_RPM_SPEC_MORE_DEFINE
"%define _use_internal_dependency_generator 0
%define __getdeps() while read file; do /usr/lib/rpm/rpmdeps -%{1} ${file} | %{__grep} -v libRInside.so | %{__grep} -v libRcpp.so ; done | /bin/sort -u
%define __find_provides /bin/sh -c '%{__getdeps P}'
%define __find_requires /bin/sh -c '%{__getdeps R}'" )
```

That code will allow for removal of libRInside.so and libRcpp.so.  It will keep libR.so in the requires list.

**Comment by richardkchapman** [comment]
@Michael-Gardner I'm not 100% sure what you mean - perhaps you can create a PR based on this branch including the fix you want?

I need to close this to retarget 5.4.6 anyway

**Comment by Michael-Gardner** [comment]
@richardkchapman I've rebased it to 5.4.6 and I'll be submitting a PR after I test it.  Close this if you would please.

**Comment by richardkchapman** [comment]
Needs to target 6.0.0 not 5.4.6

**Pull request closed without merging**
