### PR TITLE
HPCC-15765 Document LIKELY/ UNLIKELY

### PR DESCRIPTION
**Pull request by JamesDeFabia**
Signed-off-by: Jim DeFabia <jamesdefabia@lexisnexis.com>
@shamser Please review. 

Compiled PDF version is avail here: http://10.176.32.6:8080/view/Docs/job/JimsRepoBuilder/CE-DOCS=Ubuntu-14.04-amd64-2/lastSuccessfulBuild/artifact/build-docs/Release/docs/ECLLanguageReference-6.2.0-rc5.pdf#page=108

### CODE REVIEW

**Comment by shamser** [comment]
@JamesDeFabia May be a short note to state value of 0 or 1 for LIKELY will not be accepted (0 implies that the condition would be always false and 1 implies it would be always true.) .  By the way,  I couldn't find reference to the LIKELY/UNLIKELY in the  compiled PDF.

**Comment by JamesDeFabia** [comment]
@shamser Edits made

**Comment by JamesDeFabia** [comment]
@shamser Can you re-review this?

**Comment by ghalliday** [comment]
Looks good

**Pull request merged**
