### PR TITLE
HPCC-15855 ESP cores in LDAP cache code

### PR DESCRIPTION
**Pull request by richardkchapman**
Rolling back changes made in HPCC-15482.

Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@RussWhitehead FYI
@ghalliday Please review

**Comment by ghalliday** [comment]
Those changes look good

**Comment by ghalliday** [comment]
There are various pieces of code that could be improved:

- use a map to a CachedUser instead of a CachedUser *
- avoid some appending to temporary buffers - e.g., use the version of md5_string that starts form a string.
- Examine why clone() is called on the user instead of LINK().  ` m_userCache[username] = new CachedUser(sec_user.clone()); `

**Comment by ghalliday** [comment]
Russ if you're happy I'll merge it.

**Comment by RussWhitehead** [comment]
Go ahead @ghalliday

**Pull request merged**
