### PR TITLE
HPCC-17185 Display explicit messages for errors like missing lib

### PR DESCRIPTION
**Pull request by mayx**
- Add a map to store the original exception when a class is loaded
- Display the stored error message when trying to use the class

Signed-off-by: mayx <yanrui.ma@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by mayx** [comment]
@afishbeck Please review the change.

**Review by afishbeck — COMMENTED** [review]
The change looks good.

But @rpastrana can you verify this covers the case you were having when you opened HPCC-17185?

**Comment by rpastrana** [comment]
@afishbeck @mayx 
The reason this issue was raised was because we found that the situation where DESDL fails to load/access libJavaEmbeded is not gracefully handled. We need to be explicit about the actual error (Cannot find javaembedded library).

**Comment by afishbeck** [comment]
@rpastrana Right, well the plugin should be loaded dynamically during the first call to ensureJavaEmbeded() and exceptions should be caught, and now the proper error reported.

But @mayx can you test and verify what happens if the embedded java library is not there?

**Comment by rpastrana** [comment]
@afishbeck I believe the issue was that javaembedded was missing, and the esp log didn't give a clear indication of what the problem was.

**Comment by afishbeck** [comment]
Well if everything still runs, then this change will respond with an appropriate message whenever the javabased method is called.

But @mayx can you also add a trace log statement when ensureJavaEmbeded() fails to load the library?

**Comment by mayx** [comment]
@afishbeck ensureJavaEmbeded() is already logging the error when it fails the load the library, which happens at start time. Should I log the error every time the method is called (same error that gets sent in the response)?

**Comment by afishbeck** [comment]
@mayx No, so I guess we're good.

**Pull request merged**
