### PR TITLE
HPCC-16816 Copy original password to cached secuser

### PR DESCRIPTION
**Pull request by wangkx**
Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

### CODE REVIEW

**Comment by wangkx** [comment]
@afishbeck please review.

**Review by afishbeck — APPROVED** [review]
Looks good.  The new variable name is helpful too.

**Comment by wangkx** [comment]
@richardkchapman this PR is ready to be merged.

**Comment by RussWhitehead** [comment]
@wangkx @afishbeck  Looks good, and I tested to confirm

**Pull request merged**
