### PR TITLE
HPCC-14934  Add code to detect amazon linux

### PR DESCRIPTION
**Pull request by xwang2713**
Amazon Linux is rpm system and rpm package pattern is amzn1.<arch>.rpm

Signed-off-by: Xiaoming Wang xiaoming.wang@lexisnexi.com 

@Michael-Gardner please help reviewing.

### CODE REVIEW

**Comment by richardkchapman** [comment]
Typo in commit message title?

**Comment by xwang2713** [comment]
Corrected it.

**Comment by richardkchapman** [comment]
You corrected the pull request title - need to correct in the commit (via git commit --amend) then force-push it

**Comment by xwang2713** [comment]
Done.

**Comment by Michael-Gardner** [comment]
@xwang2713 looks good

**Pull request merged**
