### PR TITLE
HPCC-22927 File service functions that can point to an external Esp should optionally take credentials

### PR DESCRIPTION
**Pull request by AttilaVamos**
Update functions with username and password:

- fSprayFixed
- SprayFixed
- fSprayVariable
- SprayVariable
- fSprayDelimited
- SprayDelimited
- fSprayXml
- SprayXml
- fDespray
- Despray
- fCopy
- Copy
- fReplicate
- Replicate
- fMonitorLogicalFileName
- MonitorLogicalFileName
- fMonitorFile
- MonitorFile
- WaitDfuWorkunit
- AbortDfuWorkunit

Set username and password token for SOAP call.

Signed-off-by: Attila Vamos <attila.vamos@gmail.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [x] Test my draft Pull Request.

### CODE REVIEW

**Comment by AttilaVamos** [comment]
@jakesmith please review. I will change/update the description soon.

**Comment by AttilaVamos** [comment]
@jakesmith some part was missing in my previous commit. Now it is complete, please review this version.

**Comment by jakesmith** [comment]
I know many fileservice calls *can* take an espserver, e.g. *spray calls, but not sure they should..
RemotePull seems the exception, where it is explicit that you _need_ to reference another esp.

I think this PR should limit itself to the minimal change needed/requested, i.e. just RemotePull.

I suspect for most of the rest, if not all the rest, they should not have the ability to point to an esp in a foreign environment (but that can be a discussion/change in another JIRA/PR).

@AttilaVamos.

**Comment by jakesmith** [comment]
@AttilaVamos - Should also re-target this to master as too late for 7.8

**Comment by AttilaVamos** [comment]
Close this PR based on the aim of the related JIRA issue has been changed. 
The necessary subset of this changes implemented in https://github.com/hpcc-systems/HPCC-Platform/pull/13849

**Pull request closed without merging**
