### PR TITLE
HPCC-29604 Bump H3 version to 4.1.0

### PR DESCRIPTION
**Pull request by GordonSmith**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by GordonSmith** [comment]
@ghalliday I have rebased this onto:  https://github.com/hpcc-systems/HPCC-Platform/pull/17437 and it will need to be rebased once that has been pulled (simplifies the vcpkg submodule changes).

**Comment by ghalliday** [comment]
@GordonSmith this still looks like is failing to build.

**Review by ghalliday — CHANGES_REQUESTED** [review]
Build currently failing

**Comment by GordonSmith** [comment]
@ghalliday - Rebased on latest master which should resolve the previous issue(s)

**Comment by ghalliday** [comment]
@GordonSmith this is still failing....

**Comment by GordonSmith** [comment]
@ghalliday that issue is because the smoketest is using a prebuilt base image, which won't have the h3 library version bump.
I will run the regression test here locally for a sanity check.

**Comment by GordonSmith** [comment]
@ghalliday that issue is because the smoketest is using an "old" base image, which won't get these changes until they are pulled.

**Review by ghalliday — APPROVED** [review]

**Comment by GordonSmith** [comment]
@ghalliday it is passing regression OMM:
```
[Action] Suite: hthor
[Action] Queries: 1
[Action]   1. Test: h3.ecl
[Pass]   1. Pass h3.ecl - W20230905-171700 (1 sec)
[Pass]   1. URL http://127.0.0.1:8010/?Widget=WUDetailsWidget&Wuid=W20230905-171700
[Action] 
    -------------------------------------------------
    Result:
    Passing: 1
    Failure: 0
    -------------------------------------------------
    Log: /home/gordon/HPCCSystems-regression/log/hthor.23-09-05-17-16-59.log
    -------------------------------------------------
    Elapsed time: 3 sec  (00:00:03) 
    -------------------------------------------------

```

**Pull request merged**
