### PR TITLE
HPCC-23824 Containerized logging configuration changes

### PR DESCRIPTION
**Pull request by richardkchapman**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [x] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:
Manual testing and inspection of generated helm charts

### CODE REVIEW

**Comment by richardkchapman** [comment]
@rpastrana based on your PR, what do you think?

**Comment by richardkchapman** [comment]
@ghalliday @jakesmith for comment

**Comment by jakesmith** [comment]
Looks like a sensible change to me.
It's good to have a global default, 1 place to change it, and for components to individually be able to override.

One question I have, if a component does override (e.g. detail:) in it's defaultYaml - then it's default will be now be overridden by the global default.
Saying that, I don't think the defaultYaml's should be setting these properties, there are currently two places that do, but set them to the standard internal default anyway, so could be deleted.

**Comment by rpastrana** [comment]
@richardkchapman this change seems to follow the standard.
jLog does seem to set defaults for detail in code, perhaps we do not need to set the global default in the values yaml. In fact some of the default yaml entries @jakesmith mentioned above seem to superfluously set details as well, I'll clean that up.

**Comment by jakesmith** [comment]
@rpastrana - worth deleting the overrides in the component defaults that don't change the base default.
I think I'd leave the global setting in, you could comment it out and change comment to say override to change default, but it's probably clearer as it is.

**Comment by rpastrana** [comment]
@richardkchapman back to you

**Comment by richardkchapman** [comment]
@ghalliday Please review/merge

**Pull request merged**
