### PR TITLE
HPCC-13532 Set reschedule flag based on WU state

### PR DESCRIPTION
**Pull request by wangkx**
The EventSchedule flag in ECL WUInfo response is used to
decide whether a Reschedule button should be shown on the
ECL WU Details page or not. Since the schedule is not
allowed for WUStateFailed, WUStateArchived, WUStateAborting,
WUStateAborted, and WUStateScheduled, the EventSchedule flag
should be set based on WU state.

Signed-off-by: wangkx kevin.wang@lexisnexis.com

### CODE REVIEW

**Comment by wangkx** [comment]
@miguelvazq please check whether this works for you or not.
@afishbeck please review.

**Comment by wangkx** [comment]
@afishbeck I just removed the code inside the getWorkflow() since it is duplicated.

**Comment by miguelvazq** [comment]
I pulled this in and now I do not get the ability to reschedule if workunit state was failed or aborted (correct). But, you are not showing the de-schedule button if the status of the workunit is in "waiting". We must show this de-schedule button in this case.

**Comment by wangkx** [comment]
There is still an extra line of duplicate, which causes the de-schedule button not showing.

**Comment by miguelvazq** [comment]
Let me re-test.

**Comment by miguelvazq** [comment]
This works as expected now after I tested the second time.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Pull request merged**
