### PR TITLE
HPCC-14310 Add Envgen (wizard) cmd line pararms to specifiy comp IPs

### PR DESCRIPTION
**Pull request by garonsky**
- Allow for a IP(s) to be specified for specific component types.

Signed-off-by: Gleb Aronsky gleb.aronsky@lexisnexis.com

### CODE REVIEW

**Comment by garonsky** [comment]
@wangkx please review

**Comment by wangkx** [comment]
@garonsky just several small ...

**Comment by garonsky** [comment]
@wangkx made changes based on comments.  Please review.

**Comment by wangkx** [comment]
@garonsky looks fine.

**Comment by garonsky** [comment]
@richardkchapman this is ready to merge

**Pull request merged**
