### PR TITLE
HPCC-15123 Reimplement WorkunitServices.WorkunitTimeStamps

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman should this also be added to 5.6.2?  It theoretically changes the behaviour of ECL programmes - previously they always returned an empty list, now it works.  The format is slightly different from before though.

It requires some minor work to reserve a merge conflict if so.

**Comment by richardkchapman** [comment]
It's borderline. In the interests of good relations with the users (who view this as a regression) it might be smart to put into 5.6.2

**Comment by ghalliday** [comment]
I'll create a separate PR for 5.6.2.  You will probably need to merge both anyway, it won't be automatic.

**Comment by ghalliday** [comment]
See https://github.com/hpcc-systems/HPCC-Platform/pull/8374 for 5.6.2 PR.

**Pull request merged**
