### PR TITLE
HPCC-12939 Added include file for sync_file_region call to be more efficient

### PR DESCRIPTION
**Pull request by mckellyln**
Removed duplicate unistd.h and added syscall.h include files
@ghalliday please review
Signed-off-by: Mark Kelly mark.kelly@lexisnexis.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
Have you checked this compiles on windows?

**Comment by richardkchapman** [comment]
I'm intrigued why this needed to change - if it was causing compile errors before, it's critical. If it was not, then why do we need to add the line?

**Comment by mckellyln** [comment]
The include defines __NR_sync_file_range constant which can be used later on in the file.
Changes are within existing __linux__ sections.

**Comment by richardkchapman** [comment]
The Jira (and the commit) should really say "Due to missing include, sync_file_region may be inefficient"

**Comment by mckellyln** [comment]
ok, will change

**Comment by ghalliday** [comment]
Should sync_file_region call sync_file_range rather than directly using the system call?  I think it is present in centos 5 and following.

**Comment by mckellyln** [comment]
I seem to recall that some older platform did not have this call in its glibc or proto in its headers or some such and this was how we chose to get around that.

**Pull request merged**
