### PR TITLE
HPCC-16237 Support OR filter in getWorkUnitsSorted()

### PR DESCRIPTION
**Pull request by wangkx**
Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by richardkchapman** [comment]
Will this work with workunits stored in Cassandra?

**Comment by wangkx** [comment]
This will not work with workunits stored in Cassandra. Does Cassandra support OR query? Should different algorithm be implemented for workunits stored in Cassandra?

**Comment by wangkx** [comment]
@jakesmith please review.

**Comment by richardkchapman** [comment]
We would have to implement it separately (it would probably be realtively simple).

You should extend the workunit selftests in wutool.cpp to include coverage of this case - I can then implement the equivalent in cassandra (or you can, if you prefer).

**Comment by richardkchapman** [comment]
I may have misunderstood as I looked at fairly quickly, but I think this is going to implement the OR conditions as a post-filter - meaning a full scan of every workunit in the system if that's the only thing being filtered on. Efficiency would be horrendous.

Better would be to fetch wus in state a and wus in state b and merge the lists, I suspect

**Comment by wangkx** [comment]
If I understand correctly, what you suggest is to fetch wus in state a (and wus in state b separately) using conn->getElements(xPath(state a)). And merge the lists. Should I merge the lists inside the getWorkUnitsSorted() or after the getWorkUnitsSorted()? If after the getWorkUnitsSorted(), you may not need to change cassandrawu.
Also we need to support > 2 states and other OR conditions (Clusters, Owners, etc.).

**Comment by wangkx** [comment]
I guess that the lists have to be merged inside the getWorkUnitsSorted() because they should be merged before sorting.

**Comment by richardkchapman** [comment]
There's a danger in assuming "we need to support all possible options" - I would prefer to support only ones that we can implement efficiently.

**Comment by jakesmith** [comment]
I agree, post filtering should be avoided wherever possible.
In this case, the original request is to return all running workunits, by returning workunits that are in a set of possible workunit states.

>I guess that the lists have to be merged inside the getWorkUnitsSorted() because they should be merged before sorting.

Yes, or rather in CWorkUnitsPager in the Dali implementation Ithink, which pulls the workunits from Dali. It could request workunits in state A, B, C... and merge them.

**Comment by wangkx** [comment]
I will add some code to retrieve and merge the lists inside the CWorkUnitsPager. For now, I may only support the OR options for states, clusters, and owners. And the OR options combinations will not be  supported for now.

**Comment by wangkx** [comment]
This PR is replaced by https://github.com/hpcc-systems/HPCC-Platform/pull/9739.

**Pull request closed without merging**
