### PR TITLE
HPCC-23915 ESP can fail to restart after startup exception

### PR DESCRIPTION
**Pull request by mckellyln**
Signed-off-by: Mark Kelly <mark.kelly@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [x] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by mckellyln** [comment]
NOTE this code change helps the situation some but there are many code paths at startup that could thorw an exception and thus where to retry connections or throw and restart is open for discussion.
I think there seems to be multiple connect()s occuring near the same time concurrently, such as in CSessionCleaner::run() and initDali() that have xpaths "/Sessions" that might be worth looking into also.

**Comment by mckellyln** [comment]
@jakesmith @Michael-Gardner please review.
@stuartort fyi

**Comment by jakesmith** [comment]
I think we intentionally want to create the sentinel after a component is 'setup',
or rather we intentionally want to exit and not restart if it can't pass the initial stages.

I'm not sure the exception that caused this incident (the reason for the JIRA being opened) - should have happened in the early setup stage, i.e. I think should have been later and hence after the sentinel creation.

I'll add some more notes to JIRA.

**Comment by mckellyln** [comment]
The multiple connect()s are probably fine as they do not have identical xpaths.
The code change in this PR moves the creation of the sentinel file earlier in the ESP startup, but there are still code paths that can throw before the sentinel file is written. Perhaps https://track.hpccsystems.com/browse/HPCC-23880 will provide a more complete solution.

**Comment by mckellyln** [comment]
@jakesmith should we still do this PR or is this resolved at a different level now ?

**Comment by jakesmith** [comment]
@mckellyln - I think this PR should be closed. The point at which the sentinel file is created at the moment seems about right, in that it is after initialization.
Now that the issue of the session related exceptions has moved beyond the initialization phase, I think it's okay as it is.

**Comment by mckellyln** [comment]
ok, closing.

**Pull request closed without merging**
