### PR TITLE
HPCC-15012 Redis Plugin - correct cmake package names

### PR DESCRIPTION
**Pull request by jamienoss**
Signed-off-by: James Noss james.noss@lexisnexis.com

### CODE REVIEW

**Comment by jamienoss** [comment]
@richardkchapman please review

**Comment by richardkchapman** [comment]
@Michael-Gardner Please review. I'm not sure that the lib prefix should be present?

**Comment by jamienoss** [comment]
@richardkchapman yeah I wasn't sure about the 'lib' either, but it was already there, just not complete on everything else that needed it to be. I'll remove it to just hiredis.

**Comment by Michael-Gardner** [comment]
@jamienoss Changes look good.  The 'lib' prefix isn't important, just so long as you're consistent in the Findxxx.cmake file.

**Pull request merged**
