### PR TITLE
HPCC-30393 Add new event class and monitor audience

### PR DESCRIPTION
**Pull request by ghalliday**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
@rpastrana the aim is to add these to 8.12.x for backward compatibility (in case there are any issues), but only generate them in 9.4.x and later.

**Review by rpastrana — APPROVED** [review]
@ghalliday looks reasonable.
These changes do affect related docs:
https://github.com/hpcc-systems/HPCC-Platform/blob/7b8fa077e457b5890740cc905fa9811a8079b054/helm/examples/logging/README.md#target-audience-filtering
https://github.com/hpcc-systems/HPCC-Platform/blob/7b8fa077e457b5890740cc905fa9811a8079b054/helm/examples/logging/README.md#target-category-filtering
and logAccess ESP interface:
ESPenum LogEventClass : string
https://github.com/hpcc-systems/HPCC-Platform/blob/7b8fa077e457b5890740cc905fa9811a8079b054/esp/scm/ws_logaccess.ecm#L103
* valid values at time of writing are:
https://github.com/hpcc-systems/HPCC-Platform/blob/7b8fa077e457b5890740cc905fa9811a8079b054/esp/scm/ws_logaccess.ecm#L129
* valid values at time of writing are:
https://github.com/hpcc-systems/HPCC-Platform/blob/7b8fa077e457b5890740cc905fa9811a8079b054/esp/scm/ws_logaccess.ecm#L137

This change is important, but for future, I want to shift focus to providing OTel exporter based trace streams for standard back-end trace monitoring/processing

**Review by rpastrana — APPROVED** [review]
@ghalliday looks good.
There is an ecm enum 'LogEventClass' which first appears in 9.2.x which will need to be updated w/ the new event class "EVT - Event". Since this PR targets an earlier base branch we might need to handle it through another jira.

**Comment by rpastrana** [comment]
@g-pan I believe the changes to the README file in this PR need to be reflected in our of your docs. @JamesDeFabia

**Pull request merged**
