### PR TITLE
HPCC-14245 Changed variable named java to JNI_PATH

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner Michael.Gardner@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@richardkchapman @rpastrana really simple change.  java becomes JNI_PATH.  Tested on centos6

**Comment by rpastrana** [comment]
The change looks reasonable, and the new name is self-documenting.
Is there a doc change associated with this?

**Comment by Michael-Gardner** [comment]
I asked Jim and Greg.  They don't have to change anything in the docs for this.

**Comment by rpastrana** [comment]
@JamesDeFabia @g-pan If we're documenting the embedded java feature, we might want to document this feature Michael added.

**Comment by rpastrana** [comment]
@JamesDeFabia this should be documented.

**Pull request merged**
