### PR TITLE
HPCC-16668 Virtualize ESDL related destructors

### PR DESCRIPTION
**Pull request by rpastrana**
- Declared several destructors as virtual

Signed-off-by: Rodrigo Pastrana <rodrigo.pastrana@lexisnexis.com>

### CODE REVIEW

**Comment by rpastrana** [comment]
@RussWhitehead please review.

**Review by RussWhitehead — APPROVED** [review]
Looks good

**Comment by rpastrana** [comment]
@richardkchapman please merge

**Comment by rpastrana** [comment]
@richardkchapman please merge

**Pull request merged**
