### PR TITLE
HPCC-13447 Give user ability to filter by ID

### PR DESCRIPTION
**Pull request by miguelvazq**
Add to the front end the ability to filter by DFUID.

Signed-off by: Miguel Vazquez miguel.vazquez@lexisnexis.com

### CODE REVIEW

**Comment by miguelvazq** [comment]
@GordonSmith Please review.

**Comment by GordonSmith** [comment]
Looks fine - Does ESP support this field now?

**Comment by miguelvazq** [comment]
Yes, it was added by @wangkx

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Pull request merged**
