### PR TITLE
HPCC-14153 Modified ESP machineService to use CFRunSSH

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Gardner Michael.Gardner@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@wangkx Please review.

**Comment by Michael-Gardner** [comment]
Yes.  We capture all the reply text from the command we executed regardless of the return code.  If there is any text to return, we then store the return code and throw an exception containing the code and the reply text.  The only way I think we could run into a problem here is if the preflight command somehow returned nothing on stderr or stdout at all.  Then an exception would never get thrown.

**Comment by wangkx** [comment]
Will the connection->exec() be timed out if  the preflight command returns nothing on stderr or stdout?

**Comment by Michael-Gardner** [comment]
No it won't time out.  But res.length() will equal 0 and the exception will not be thrown to pass any data out.  So in Cws_machineEx::runCommand we will return -1 (which is what the exitCode gets initialized to) and &response will be empty.

**Comment by wangkx** [comment]
The Cws_machineEx::runCommand does handle the "res.length() = 0" as long as the connection->exec() returns. Will the connection->exec() return (timed out) even if the preflight command (for some reason) is hanging?

**Comment by Michael-Gardner** [comment]
yes.  The connection->init() call sets a timeout for the connection, which we get from the m_SSHConnectTimeoutSeconds (which is how we sourced it before in the original code as well.)

**Comment by wangkx** [comment]
@Michael-Gardner no more question. Code looks good for me.

**Comment by Michael-Gardner** [comment]
@richardkchapman Ready for a final look when you have time.

**Pull request merged**
