### PR TITLE
HPCC-13444 Add Ubuntu 15.04 amd64 support

### PR DESCRIPTION
**Pull request by xwang2713**
Add dependencies list for Ubuntu 15.04.
@Michael-Gardner Please review.
Signed-off-by: Xiaoming Wang xiaoming.wang@lexisnexis.com

### CODE REVIEW

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by Michael-Gardner** [comment]
Tested it this morning.  Works well @xwang2713

**Comment by richardkchapman** [comment]
Should this target 5.2.4 ?

**Comment by xwang2713** [comment]
Better for HPCC 5.4.0.  Traditional start with Linux service will not work. User can directly call "/etc/init.d/hpcc-init <action>". I wrote a simple system script but it still has some problem. Maybe I should open another JIRA ticket for this.

**Comment by richardkchapman** [comment]
@xwang2713 Did you open the extra Jira you mentioned?

**Comment by xwang2713** [comment]
Yes, HPCC-13583 "Add systemd script".  This pull-request can be merged. We can use HPCC-13583 to address the HPCC-init start/stop issues.

**Pull request merged**
