### PR TITLE
HPCC-22181 Mismatched size table in hidl

### PR DESCRIPTION
**Pull request by richardkchapman**
Picked up by sanitize checks, because was reading off the end of the table
when kind was ESP_ENUM.

No idea what it any impact it had in reality.

Signed-off-by: Richard Chapman <rchapman@hpccsystems.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [x] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:
Compiled system using -fsanitize-trap=undefined, which revealed the problem. Whether the new table is right I cannot tell.

### CODE REVIEW

**Comment by richardkchapman** [comment]
@afishbeck Please review

**Review by afishbeck — COMMENTED** [review]
@richardkchapman I believe this only affects generation of code that we no longer use.  For example generated binary scm component interfaces and clarion interfaces.  Although that ancient code is a bit in the weeds so hard to be 100% certain.

**Review by afishbeck — COMMENTED** [review]
Aside from any potential weeds, change looks right.

**Comment by richardkchapman** [comment]
I found the problem because hidl gives an error while building the system if I set -fsanitize-trap, so the code that is affected IS executed. 

However I suspect that other checks within the tests in question probably mean that the incorrect/random answers do not ever impact the generated code.

@ghalliday Please review/merge

**Comment by ghalliday** [comment]
@afishbeck there are the following changes in the generated code:

```
diff -r generated/esp.int generated/esp.int
40c40
< getProcAddress   PROCEDURE(CONST *CSTRING name),*BYTE,PROC
---
> getProcAddress   PROCEDURE(CONST *CSTRING name),*CSTRING,PROC
244c244
< putFile          PROCEDURE(*cppEspContext context, CONST *CSTRING path, *BYTE data, ULONG len),CBOOL,PROC
---
> putFile          PROCEDURE(*cppEspContext context, CONST *CSTRING path, *CSTRING data, ULONG len),CBOOL,PROC
diff -r generated/esp.ipp generated/esp.ipp
1925c1925
< 	bool _stdcall putFile(IEspContext & context, const char * path, void * data, unsigned len)
---
> 	bool _stdcall putFile(IEspContext & context, const char * path, int, void * data, unsigned len)
diff -r generated/soapesp.int generated/soapesp.int
127,128c127,128
< setEventSink     PROCEDURE(*BYTE val),PROC
< getEventSink     PROCEDURE(),*BYTE,PROC
---
> setEventSink     PROCEDURE(*CSTRING val),PROC
> getEventSink     PROCEDURE(),*CSTRING,PROC
131,132c131,132
< setThunkHandle   PROCEDURE(*BYTE val),PROC
< getThunkHandle   PROCEDURE(),*BYTE,PROC
---
> setThunkHandle   PROCEDURE(*CSTRING val),PROC
> getThunkHandle   PROCEDURE(),*CSTRING,PROC
diff -r generated/soapesp.ipp generated/soapesp.ipp
1146c1146
< 	void _stdcall setEventSink(void * val)
---
> 	void _stdcall setEventSink(int, void * val)
1196c1196
< 	void _stdcall setThunkHandle(void * val)
---
> 	void _stdcall setThunkHandle(int, void * val)

```
Are any of them significant?

**Comment by afishbeck** [comment]
@ghalliday all of those files are Clarion related.  .int are the Clarion headers.  Those .ipp files are the c++ stubs for interfacing with Clarion.

**Comment by richardkchapman** [comment]
Perhaps we should remove the Clarion file generation from hidl

**Comment by afishbeck** [comment]
Agreed.  https://track.hpccsystems.com/browse/HPCC-22216

**Pull request merged**
