### PR TITLE
HPCC-22205 Note which node to run config scripts on

### PR DESCRIPTION
**Pull request by g-pan**
Signed-off-by: G-Pan <greg.panagiotatos@lexisnexis.com>

@JamesDeFabia please review.  
  Note: Review of Sys. Admin doc did not reveal any others

http://10.240.32.243/view/Docs%207.0/job/AnotherDocBuild7/62/CE=ubuntu-18.04-amd64-2/artifact/build-docs/Release/docs/EN_US/HPCCSystemAdministratorsGuide_EN_US-7.2.17-closedown0.pdf#page=68

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

## Testing:

Successful Build Test: http://10.240.32.243/view/Docs%207.0/job/AnotherDocBuild7/

### CODE REVIEW

**Review by JamesDeFabia — COMMENTED** [review]
@g-pan 
What about 
 /opt/HPCCSystems/bin/initldap and addScopes? Does it matter from which node these are run?

**Comment by g-pan** [comment]
> @g-pan
> What about
> /opt/HPCCSystems/bin/initldap and addScopes? Does it matter from which node these are run?

On a multi-node system you could run addScopes an any node where
 you can access the daliconf.xml file.

**Comment by g-pan** [comment]
re: initldap is in the config section where we state: &lt;configmgr_IP_Address&gt; is the IP address of the node running Configuration Manager

**Review by JamesDeFabia — APPROVED** [review]
@richardkchapman This is good to merge

**Comment by richardkchapman** [comment]
@jakesmith is this still accurate after whitelist changes?

**Comment by jakesmith** [comment]
hm, not familiar with addScopes.. 
It seems to interact directly with LDAP in one mode (to add)  (security?)

And in other mode (clear) to try to talk to Dali's session manager.. 
Afaics it would have always failed to do so though, as there is no initClientProcess call, and it's attempt to use the session manager would therefore fail.

It doesn't seem right that it gets it's config info from daliconf.xml.

Is this program actually used? I suspect it needs revisiting.
@RussWhitehead - can you comment?

**Comment by RussWhitehead** [comment]
@jakesmith @g-pan addScopes is meant to enumerate all the LDAP users and ensure their hpccinternal::<username> file scope exists with the default permissions. To find the correct LDAP Server and binding information, it needs to extract it from the ldapSecurity block of the daliconf.xml.

**Comment by jakesmith** [comment]
> To find the correct LDAP Server and binding information, it needs to extract it from the ldapSecurity block of the daliconf.xml.

which necessitates it having to run on the same node as Dali?

If it has to connect to Dali.. (?).. that needs testing (since initClientProcess appears to be missing), and if it connects to Dali, why does it need to read daliconf.xml? It could read the info. it needs from the environment , and therefore could be run on any node.

**Comment by RussWhitehead** [comment]
It needs to run on a node that has a copy of the current daliconf.xml.  The only reason it connects to Dali (that I am aware of) is to clear the permissions cache. This code could probably be removed

**Comment by g-pan** [comment]
@jakesmith  would the white list invalidate any of these changes to the text? 
It does not seem to.  Would this then be OK to merge?

**Comment by jakesmith** [comment]
Well, no because addscopes didn't work if it tried to connect to Dali anyway (as I say above, there's no initClientProcess or mp connect).
Afaics it will fail (crash or assert) if it tries to access Dali.
@RussWhitehead  - can you take a look, check that and open a JIRA if confirmed? 

>On a multi-node system you could run addScopes an any node where
>you can access the daliconf.xml file. By default the daliconf.xml file
>can be found on the node where your Dali is.

@g-pan That's a bit misleading - daliconf.xml cannot be anywhere else, but the Dali node.
(it's odd that addRoles uses daliconf.xml at all and not the environment, but that's another matter)

**Comment by g-pan** [comment]
@jakesmith would this change suffice?

**Review by JamesDeFabia — CHANGES_REQUESTED** [review]

**Comment by g-pan** [comment]
@JamesDeFabia @jakesmith please review latest changes. Thanks.

**Review by JamesDeFabia — APPROVED** [review]
Looks good to me

**Comment by richardkchapman** [comment]
@RussWhitehead @jakesmith Can you confirm?

**Comment by RussWhitehead** [comment]
@richardkchapman  THis is correct as written

**Pull request merged**
