### PR TITLE
HPCC-27630 Make CORS handling configurable

### PR DESCRIPTION
**Pull request by afishbeck**
Add ESP application support for a "corsAllow:" section which will
allow explicit control of allowed CORS origins.

Default behavior will no longer simply reflect the origin asking
for access.

```
esp:
- name: eclwatch
  application: eclwatch
  auth: ldap
  replicas: 1
  # The following 'corsAllowed' section is used to configure CORS support
  #   origin - the origin to support CORS requests from
  #   headers - the headers to allow for the given origin via CORS
  #   methods - the HTTP methods to allow for the given origin via CORS
  #
  corsAllowed:
  # origin starting with https will only allow https CORS
  - origin: https://*.my.com
    headers:
    - "X-X"
    methods:
    - "GET"
  # origin starting with http will allow http or https CORS
  - origin: http://www.example.com
    headers:
    - "*"
    methods:
    - "GET"
    - "POST"
```

Signed-off-by: Anthony Fishbeck <anthony.fishbeck@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [x] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by afishbeck** [comment]
@GordonSmith FYI

**Comment by afishbeck** [comment]
@marksr FYI.  Feel free to comment on changes if you have a chance.

**Comment by GordonSmith** [comment]
@afishbeck - what behavior will it have by default?

**Comment by afishbeck** [comment]
@GordonSmith It used to basically allow any origin.. which isn't great and security scans don't like that.  You would now have to configure add any origin you want to allow.  You can probably emulate the old behavior with a configured origin of "*" but it's not advisable.

**Comment by afishbeck** [comment]
@GordonSmith Can you describe the scenarios where you require CORS?  What the origins would be?

**Comment by GordonSmith** [comment]
@afishbeck my scenarios can be summed up here:
ECLIDE (c++):
* SOAP generated stubs (gsoap) on top of the Win32 WinInet network stack
* Chromium v76 embedded web browser, renders WU Details Web Pages (should be fine).

ECL Extension for VSCode:
* @hpcc-js/comms + NodeJS - I should be able to spoof the required headers so not concerned

External Web Sites:
* @hpcc-js/comms + Web Browser - This is the one which may be impacted the most, once CORs is defaulted on.

**Comment by marksr** [comment]
> @marksr FYI. Feel free to comment on changes if you have a chance.

Looks good! I've just merged to an older HPCC version used by our client and it worked just fine. Thanks!

**Review by wangkx — APPROVED** [review]
Looks fine for me.

**Comment by stuartort** [comment]
@afishbeck, in bare metal setups how are users going to be able to make configuration changes?  Does configmgr support this or will changes be needed in envmod @kenrowland.

**Comment by afishbeck** [comment]
@stuartort Ken will create a envmod template outside of this PR.  The environment setup for Gordon to test should use default config, at least initially.

**Review by GordonSmith — APPROVED** [review]
@afishbeck looks ok to me.

**Pull request merged**
