### PR TITLE
HPCC-18692 Ensure per job temp workunit directory removed

### PR DESCRIPTION
**Pull request by jakesmith**
Remove the job specific temp workunit directory at the end of
the job.

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Testing:

Observationally tested

### CODE REVIEW

**Comment by jakesmith** [comment]
@richardkchapman - please review

**Comment by richardkchapman** [comment]
Did you check that the sort spill files had been removed before this point? Not sure exactly when/how that happens.

**Comment by jakesmith** [comment]
>Did you check that the sort spill files had been removed before this point? Not sure exactly when/how that happens.

Yes.
Verified with a sorting spill example and some other examples that used temp files.

**Comment by jakesmith** [comment]
I'll review those hthor failures in the morning.

**Comment by richardkchapman** [comment]
@jakesmith Back to you

**Comment by jakesmith** [comment]
So from the error in the gist, e.g. for action1a
{noformat}
<Exception><Code>39</Code><Source>eclagent</Source><Message>System error: 39: CFile::remove /var/lib/HPCCSystems/myeclagent/temp/W20171107-151703-14, Directory not empty</Message></Exception>
{noformat}

.. it looks like:
a) something was left behind in the temp directory
b) that caused remove() to throw an exception which wasn't handled gracefully.

I will fix (b) in case for whatever reason it hits this.
But I am unable to reproduce it at the moment, perhaps because I am using a make install setup and not an installed package - though I am not sure what difference that would make - I will find out soon.

**Comment by jakesmith** [comment]
Not able to reproduce it on a package install version of this branch either.

**Comment by jakesmith** [comment]
Problem identified/fix pushed.
NB: it should always have hit failures, but for some reason the regression suite 'Pass'ed them sometimes, @AttilaVamos is investigating with a ./ecl-test run with --loglevel debug output from such an event.

In the meantime, this PR is now ready.

**Pull request merged**
