### PR TITLE
HPCC-14209 Add missing member function rtlRowAttr::set()

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman please review

**Comment by richardkchapman** [comment]
Fix looks reasonable I think, but when/where/how was this broken?

**Comment by ghalliday** [comment]
I can binchop to find the extact change if you like.  (If so please ask me.)  It was a change which forced a row into a temporary - probably to fix a problem with rows being accessed after they had gone out of scope, or optimizing copying a row.
Before:

		memcpy(bL3RD.row() + 0U,*(vN3RD.queryrows()) + 0U,vO3RD + 8U);
		rK3RD.setown(bL3RD.finalizeRowClear(vO3RD + 8U));

after

		r4HQD.setown(rtlCloneRow(alloc6HQD,v5HQD + 8U,*(v3HQD.queryrows())));
		r2HQD.set(r4HQD);

**Comment by richardkchapman** [comment]
I don't really care about the exact change, just so long as we understand how it might have happened.

**Pull request merged**
