### PR TITLE
HPCC-13013 Expand Query ID column

### PR DESCRIPTION
**Pull request by miguelvazq**
Expand query id column to make longer id's version number visible and cleanup some other widths.

Signed-off by: Miguel Vazquez miguel.vazquez@lexisnexis.com

### CODE REVIEW

**Comment by miguelvazq** [comment]
@GordonSmith Please review.

**Comment by GordonSmith** [comment]
Did you leave 1 column with no width value, so that it auto expands as the page resizes?

**Comment by richardkchapman** [comment]
@miguelvazq Back to you

**Comment by miguelvazq** [comment]
@GordonSmith I removed the width from Name

**Comment by GordonSmith** [comment]
Looks good so!

**Comment by miguelvazq** [comment]
You sure the columns should have at least one without a width? After looking at this with column width missing it clips the four row icons Suspended, ErrorCount, MixedNodeStates, Activated. Where as before with widths it was looking more appropriate.

**Comment by GordonSmith** [comment]
@miguelvazq - I am pretty sure its what we do for the other lists?  I will need to test locally.

**Comment by miguelvazq** [comment]
OK, I'll await your test. A couple of columns get skewed when I remove one of the widths.

**Comment by miguelvazq** [comment]
Opened https://github.com/hpcc-systems/HPCC-Platform/pull/8187

**Pull request closed without merging**
