### PR TITLE
HPCC-25694 Default file/workunit access problems with new deployment

### PR DESCRIPTION
**Pull request by RussWhitehead**
Create LDAP Workunit/Files features with user permissions, so they can be
applied to "default" permissions when no workunit/file scope exists

Signed-off-by: Russ Whitehead <william.whitehead@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [x] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by RussWhitehead** [comment]
@wangkx Kevin please review

**Review by wangkx — COMMENTED** [review]
This fix does not tight security. I am wondering if there is a better fix. For example, default to no access and allow it being modified. @afishbeck any comment?

**Comment by afishbeck** [comment]
Working on other security features and using other platforms I would try and make it so the system would never accidentally be insecure.  That is, it's best if we error on the side of defaulting to something restrictive but provide an easy way of overriding it if the user wants to.  Not sure exactly what that would mean here.  @RussWhitehead can you comment on what that would mean?

**Comment by RussWhitehead** [comment]
@afishbeck @wangkx This Jira is meant to fix legacy behavior that has presumably worked this way since LDAP was implemented, and is documented in the HPCC manuals.  I believe this Jira should be merged to restore that broken feature.
Separately, I agree that the default should be to lock down access and force admins to open it up, but this will take more thought. 
1) We should do the same for file scopes as well as workunit scopes. Perhaps more?
2) We need to provide guidance on how to open the access. It is very frustrating to a new user when the "nothing works" out of the box. Perhaps a wizard tool that walks the admin through initial security configuration
3) Perhaps some of this could be done at initial configuration. A new "Install Securely" VS "Install Permissively"  LDAP option?
4) Documentation will need to be reevaluated and rewritten once we agree on the behaviour

**Comment by afishbeck** [comment]
@RussWhitehead I'll approve with the idea that this fixes the break, but can you open JIRA(s) for implementing "least privileged access control"?

**Review by afishbeck — APPROVED** [review]
@RussWhitehead approved with the caveat that we will implement a more least privilege approach when we implement the new green field ldap.

**Comment by RussWhitehead** [comment]
@afishbeck Opened https://track.hpccsystems.com/browse/HPCC-25795
@richardkchapman Please merge

**Pull request merged**
