### PR TITLE
HPCC-15169 LRM #option optimizelevel has incorrect default listed

### PR DESCRIPTION
**Pull request by jamienoss**
Signed-off-by: James Noss james.noss@lexisnexis.com

### CODE REVIEW

**Comment by jamienoss** [comment]
@ghalliday & @JamesDeFabia please review, cheers.

**Comment by JamesDeFabia** [comment]
Looks fine from a grammatical and  DocBook XML point of view (and it does make the info clearer) 

@ghalliday should have the last word from a technical point of view

**Comment by jamienoss** [comment]
@JamesDeFabia cool, cheers Jim.

**Comment by richardkchapman** [comment]
@ghalliday please review

**Pull request merged**
