### PR TITLE
HPCC-13723 Update Datastax Cassandra library to version 2.0

### PR DESCRIPTION
**Pull request by richardkchapman**
Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by AttilaVamos** [comment]
There are build errors (smoketest failed to add comment, based on some GitHub interface problem of parsing the message.. I'm working on it.)

The errors:
Build failed
Error(s): 32
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:138:64: error: too many arguments to function ‘CassString cass_future_error_message(CassFuture*)’
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:494:52: error: cannot convert ‘const cass_byte_t** {aka const unsigned char**}’ to ‘CassBytes* {aka CassBytes_*}’ for argument ‘2’ to ‘CassError cass_value_get_bytes(const CassValue*, CassBytes*)’
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:582:60: error: cannot convert ‘const char**’ to ‘CassString* {aka CassString_*}’ for argument ‘2’ to ‘CassError cass_value_get_string(const CassValue*, CassString*)’
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:591:60: error: cannot convert ‘const char**’ to ‘CassString* {aka CassString_*}’ for argument ‘2’ to ‘CassError cass_value_get_string(const CassValue*, CassString*)’
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:615:60: error: cannot convert ‘const char**’ to ‘CassString* {aka CassString_*}’ for argument ‘2’ to ‘CassError cass_value_get_string(const CassValue*, CassString*)’
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:624:60: error: cannot convert ‘const char**’ to ‘CassString* {aka CassString_*}’ for argument ‘2’ to ‘CassError cass_value_get_string(const CassValue*, CassString*)’
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:648:60: error: cannot convert ‘const char**’ to ‘CassString* {aka CassString_*}’ for argument ‘2’ to ‘CassError cass_value_get_string(const CassValue*, CassString*)’
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:657:60: error: cannot convert ‘const char**’ to ‘CassString* {aka CassString_*}’ for argument ‘2’ to ‘CassError cass_value_get_string(const CassValue*, CassString*)’
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:845:126: error: ‘cass_collection_append_string_n’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:850:108: error: ‘cass_statement_bind_string_n’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:863:96: error: could not convert ‘(const cass_byte_t*)value’ from ‘const cass_byte_t* {aka const unsigned char*}’ to ‘CassBytes’
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:865:131: error: could not convert ‘(const cass_byte_t*)value’ from ‘const cass_byte_t* {aka const unsigned char*}’ to ‘CassBytes’
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:924:126: error: ‘cass_collection_append_string_n’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:929:110: error: ‘cass_statement_bind_string_n’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:942:100: error: ‘cass_collection_append_string_n’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:944:135: error: ‘cass_statement_bind_string_n’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:1229:76: error: ‘cass_cluster_set_latency_aware_routing’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:1242:155: error: ‘cass_cluster_set_latency_aware_routing_settings’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:1486:124: error: could not convert ‘(const cass_byte_t*)val’ from ‘const cass_byte_t* {aka const unsigned char*}’ to ‘CassBytes’
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:1522:104: error: ‘cass_statement_bind_string_n’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:1531:126: error: ‘cass_statement_bind_string_n’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:1540:108: error: ‘cass_statement_bind_string_n’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:1607:124: error: ‘cass_collection_append_string_n’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:1620:124: error: ‘cass_collection_append_string_n’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:1644:93: error: ‘cass_collection_append_string_n’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:1653:97: error: ‘cass_collection_append_string_n’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:1662:100: error: could not convert ‘inData’ from ‘const cass_byte_t* {aka const unsigned char*}’ to ‘CassBytes’
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:1694:95: error: ‘cass_statement_new_n’ was not declared in this scope
/home/ati/smoketest/smoketest-7436/HPCC-Platform/plugins/cassandra/cassandraembed.cpp:1703:73: error: could not convert ‘script’ from ‘const char*’ to ‘CassString’
make[2]: *** [plugins/cassandra/CMakeFiles/cassandraembed.dir/cassandraembed.cpp.o] Error 1
make[1]: *** [plugins/cassandra/CMakeFiles/cassandraembed.dir/all] Error 2
make: *** [all] Error 2

**Comment by richardkchapman** [comment]
The build errors suggest you did not do a git submodule update after checking out...

**Comment by richardkchapman** [comment]
@ghalliday Please review

**Comment by AttilaVamos** [comment]
Yes, that is right. Smoketest system updated.

**Pull request merged**
