### PR TITLE
HPCC-28478 Lower default containerized log level

### PR DESCRIPTION
**Pull request by rpastrana**
- Lowers default containerized log level to 60 (info)

Signed-off-by: Rodrigo Pastrana <rodrigo.pastrana@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by rpastrana** [comment]
@ghalliday there's a few ways to accomplish this depending on how intrusive we care to be, immediate impact and how much we want to avoid the log detail

- set logging.detail down to 60 from 80 (filters out programmer info, but relies on detail/level)
- Adjust DefaultDetail #define accordingly in code (can be overwritten in config, but again relies on log detail/level )
- set logging.classes: "ALL-INF" and logging.audiences: "ALL-PRO" (filters out user/operator info, not exactly what is being called for)
- Adjust defaultLogMsgFilter accordingly in code (can be overwritten in config, will affect bare metal)

Is one of these what you had in mind for this task?

**Comment by ghalliday** [comment]
The plan is to completely remove detail from the system, so filtering on the detail will not help.   (E.g. see https://github.com/hpcc-systems/HPCC-Platform/pull/16650 which is currently stalled.  Before that is merged the few cases that do rely on the detail level need to switch to using feature flags.)

I suspect the idea in mind when the jira was created would be to set default log msg filter to match audiences "MSGAUD_all & ~MSGAUD_programmer".  The call from eclcc would need to change to stay the same as it currently is i.e. include programmer.

We also might need to do a careful search of all debugging lines to check the audience before this is enabled - otherwise key tracing information will not be available in the logs.

**Comment by rpastrana** [comment]
Are we ok losing the ability to control log output on a escalating manner? Without the log level feature, we'll be able to filter out entire audiences, and or entire log types.

For example, if we filter out audience programmer and class info we will lose all programmer errors/warnings, and also user/operator info...

**Comment by rpastrana** [comment]
If the end-goal is to implement a industry standard log control mechanism, we should control log output based on graduated levels such as:    Emergency, Alert, Critical, Error, Warning, Notice, Informational, Debug (https://sematext.com/blog/logging-levels/), each of those essentially map to various thresholds of the existing log level/detail.
The log message audience/class can remain more of an annotation for each log message.

**Comment by rpastrana** [comment]
@ghalliday I still contend this would have lowered costs without significant debug information sacrifice.

**Pull request closed without merging**
