### PR TITLE
HPCC-30687 Ensure JTrace sets spanprocessor

### PR DESCRIPTION
**Pull request by rpastrana**
- Defaults Jtrace spanprocessor to simple

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Review by ghalliday — APPROVED** [review]

**Comment by ghalliday** [comment]
@rpastrana do you know why this wasn't caught by the unit tests?

**Comment by ghalliday** [comment]
This should be pulled to 9.4.x and included in an rc2 of 9.4.6

**Comment by rpastrana** [comment]
> @rpastrana do you know why this wasn't caught by the unit tests?

Most likely, TRACECONFIGDEBUG was enabled when executed locally.

As far as unittests check on the PR, I don't see relevant output: https://github.com/hpcc-systems/HPCC-Platform/actions/runs/6200534833/job/16842788047?pr=17759

Are the jlibtests not ran by default?

**Comment by rpastrana** [comment]
Also worth mentioning I've been executing the jtrace tests like this:

```
./bin/unittests -e JlibTraceTest -v
```
which initializes the jlib objects, and prevents the tests from initializing the tracemanager with custom configurations in order to provide wider coverage. 
Is there a pre-existing mechanism to prevent early initialization?

**Comment by ghalliday** [comment]
> > @rpastrana do you know why this wasn't caught by the unit tests?
> 
> Most likely, TRACECONFIGDEBUG was enabled when executed locally.
> 
> As far as unittests check on the PR, I don't see relevant output: https://github.com/hpcc-systems/HPCC-Platform/actions/runs/6200534833/job/16842788047?pr=17759
> 
> Are the jlibtests not ran by default?

@GordonSmith are they run?  If not we should run them - at least the non-stress tests.

**Pull request merged**
