### PR TITLE
HPCC-19423 Refresh of Topology Tab remains on selected service

### PR DESCRIPTION
**Pull request by kunalaswani**
In Operations > Topology, users are now able to refresh Services without it resetting to Targets.

Signed-off-by: Aswani, Kunal <kunal.aswani@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly, or...
  - [x] I have created a JIRA ticket to update the documentation.
  - [x] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [x] I have tested my changes in multiple modern browsers
  - [x] The component(s) render as expected

### CODE REVIEW

**Comment by kunalaswani** [comment]
@GordonSmith please review, there was a case for "Debug" that I'm not sure is still a valid case, can you comment on that as well?

**Comment by GordonSmith** [comment]
Code looks fine - I am not sure what "Debug" your referring to though?

**Comment by kunalaswani** [comment]
In the TopologyWidget file: 

this.viewModeDebug = new ToggleButton({
                    showLabel: true,
                    checked: false,
                    style: { display: "none" },
                    onChange: function (val) {
                        if (val) {
                            context.viewModeMachines.set("checked", false);
                            context.viewModeServices.set("checked", false);
                            context.viewModeTargets.set("checked", false);
                            context.refreshGrid("Debug");
                            context.resetFilter();
                        }
                    },
                    label: "Debug"
                }).placeAt(this.openButton.domNode, "after");

**Comment by GordonSmith** [comment]
Ahh (from memory) that was a special mode I used to debug the tree - I think it just displayed everything.

**Comment by kunalaswani** [comment]
Oh, ok, should i add that parameter into the refresh section as well?

**Comment by GordonSmith** [comment]
@kunalaswani No need.

**Pull request merged**
