### PR TITLE
HPCC-13429 Better error for scalar output inside child query

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@jakesmith @richardkchapman @jamienoss 

This fixes the immediate error, but highilights some other problems, so probably not ready for pulling:

Thor fails with an error:
Internal Error at /home/gavin/dev/hpcc/thorlcr/graph/thgraphslave.cpp(935),
which isn't very helpful.  I could probably improve that.

Roxie and hthor appear to succeed when run as dali workunits, but fail when run as standalone.

There are two issues - outputing a scalar result from a child query, and outputting a scalar result more than once.

So the question is should it fail or succeed?  It is currently inconsistent.

Also, @AttilaVamos the regression suite says they pass even though the test is marked as failing.  I think I have opened a jira for that already.

**Comment by richardkchapman** [comment]
Shouldn't you catch this at compile time?

**Comment by ghalliday** [comment]
I give a warning.  If we decide outputting a scalar from a child query is a bug then yes.  If only outputting more than once is a bug then I don't think so.

**Comment by richardkchapman** [comment]
Is there any plausible scenario where it makes sense to allow (but only once) that could not equally well be handled with an output that was not in the child query?

**Comment by AttilaVamos** [comment]
@ghalliday PR created for "HPCC-13320 Regression tests marked with //fail shouldn't pass if they succeed".

**Comment by ghalliday** [comment]
I'm not sure if there is a plausible scenario.  I could add some code to trap it and see what happens on my regression suite examples.  That might be a good fix especially if I made it a configurable warning that defaulted to reporting an error.

**Comment by ghalliday** [comment]
@richardkchapman how about the consistency question?  Do we categorise it as undefined behaviour, and therefore not care if it succeeds or not.

**Comment by richardkchapman** [comment]
We could:

1. Define that it's an error if output more than once
2. Allow it to be output multiple times - retaining the last value output if going to a workunit, outputting them all if outputting directly to screen - though this might mean we sometimes output invalid XML
3. State that the behaviour is undefined

If we pick 1 or 2 we need a new Jira but it can be low priority. I'm happy with 3 if we have a warning that defaults to error.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by richardkchapman** [comment]
@ghalliday I think this is your court at the moment

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| scalarchild | Fail | Pass | Fail |
 
HPCC Stop: OK

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| scalarchild | Fail | Pass | Fail |
 
HPCC Stop: OK

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| scalarchild | Fail | Pass | Fail |
 
HPCC Stop: OK

**Comment by ghalliday** [comment]
@richardkchapman I'm not sure what to do.
This pull request improves the error messages, and catches some instances at compile time.
I can't think of an easy way to catch all the instances at compile time.
And the scalarchild test isn't caught, and succeeds on some, but not others!

I think I would recommend removing the scalarchild test (move it to ecl/regress), and then taking the rest as-is.  Are you happy with that?

**Comment by richardkchapman** [comment]
@ghalliday Yes

**Comment by ghalliday** [comment]
@richardkchapman test moved

**Pull request merged**
