### PR TITLE
HPCC-13588 Fix bug in generated code for index containing datasets inside rows

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Comment by ghalliday** [comment]
@jamienoss please review
eblood1.eclxml is the original example.  I have also added a runtime test.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| issue13588 | Pass | Pass | Pass |
 
HPCC Stop: OK

**Comment by jamienoss** [comment]
https://track.hpccsystems.com/browse/HPCC-13588

**Comment by jamienoss** [comment]
@richardkchapman this looks good to merge.

**Pull request merged**
