### PR TITLE
HPCC-14924 Fixes for dpkg-shlibdeps conflicting with imported libraries

### PR DESCRIPTION
**Pull request by Michael-Gardner**
Signed-off-by: Michael Jon Gardner michael.gardner@lexisnexis.com

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 Please review when you get a chance.

- Removed symlink
- Removed imported library targets, now they are built using cmake (fixes one of the reasons the symlink was necessary)
- Modified the cassandra (cpp-driver) cmake code to remove the soversion and version from the generated library.  The symlinks created by these target properties were the other reason the original symlink under /opt/HPCCSystems/lib was necessary
- Removed OPTION variable from ADD_PLUGIN.  ADD_PLUGIN macro now generates a ${name}_FOUND variable, similar to how Findxxx.cmake includes work.
- Added r8embed to the list of plugins built with the TEST_PLUGINS option.

**Comment by xwang2713** [comment]
Looks good

**Comment by Michael-Gardner** [comment]
@richardkchapman ready for you to take a look at this when you get a chance.

**Comment by richardkchapman** [comment]
I'm still not happy with the idea that we are modifying (in the cassandra case) or bypassing (in the libuv case) the make files supplied with those libraries. Why do we need to?

**Comment by Michael-Gardner** [comment]
@richardkchapman Sorry for smoke test spam.  So I've gone ahead and figured out a way to fix the shlibdeps issue without having to touch the makefiles of our 3 imported shared objects (libuv, libcassandra, libkafka.)  I included an install(CODE) call in the kafka and cassandra plugin cmake files that append to the LD_LIBRARY_PATH environment variable when packaging.  This gets picked up by dpkg-shlibdeps and it now is able to find our private libraries for dependency generation.

**Comment by richardkchapman** [comment]
Excellent, thank you. @xwang2713 can you re-review please

**Comment by richardkchapman** [comment]
Needs rebasing for a clean merge

**Comment by Michael-Gardner** [comment]
@richardkchapman Rebased and ready for merge

**Pull request merged**
