### PR TITLE
HPCC-14630 Speed up group sort by only checking option once

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@jakesmith please review.
Note, when sorting groups of size 1 (admittedly pathological) this change reduced the time for my test case from 170s to 30s.  It would be well worth checking that there are no other calls to getOptXXX() in code that is likely to be called several times in a query.

**Comment by jakesmith** [comment]
Nice find, big saving for small groups!
@ghalliday - looks good.

**Comment by richardkchapman** [comment]
Needs rebasing for a clean merge

**Comment by ghalliday** [comment]
@richardkchapman rebased

**Comment by richardkchapman** [comment]
Cherry-picked into 5.6.0

**Pull request merged**
