### PR TITLE
HPCC-17102 The redissynctest fails if parallel queries used in regression suite.

### PR DESCRIPTION
**Pull request by AttilaVamos**
Fix the bug where multiple Redis test cases use same database. This caused
failure when those test cases were executing parallel and modify/remove
data with same name used by other test(s).

Signed-off-by: HPCCSmoketest <hpccsmoketest@gmail.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [x] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [x] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [ x The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [x] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

Tested manually with PQ enabled and it will be part of next OBT.

### CODE REVIEW

**Comment by AttilaVamos** [comment]
Unfortunately it is a false positive result.

**Comment by richardkchapman** [comment]
@AttilaVamos Do you know why thor smoketest failed?

**Comment by AttilaVamos** [comment]
@richardkchapman I do know what happens (Thor slave and/or thor generates core and reports <Exception><Code>4</Code><Source>eclagent</Source><Message>System error: 4: MP link closed (10.241.40.11:20100)</Message></Exception>
), but I still can't find out (yet) why. 

Unfortunately it seems similar complex problem again (like as Python2, 3 plugins). Those tests pass on CentOS 6 and Ubuntu 16.04, but fail on CentOS 7 (Smoketest machine).

**Comment by jakesmith** [comment]
@AttilaVamos - could you email me the slave log for this crash?

**Comment by jakesmith** [comment]
@AttilaVamos - thanks received log.

So as you mention, the stack in core is in TBB (and dumped in slave log):
```
00001A11 2017-03-01 14:25:40.374 21817 21817 "================================================"
00001A12 2017-03-01 14:25:40.374 21817 21817 "Signal:    11 Segmentation fault"
00001A13 2017-03-01 14:25:40.374 21817 21817 "Fault IP:  00007FEF80C1599A"
00001A14 2017-03-01 14:25:40.374 21817 21817 "Accessing: 00000000025A4068"
00001A15 2017-03-01 14:25:40.374 21817 21817 "Backtrace:"
00001A16 2017-03-01 14:25:40.374 21817 21817 "  /lib64/libtbbmalloc.so.2(safer_scalable_free+0x9a) [0x7fef80c1599a]"
00001A17 2017-03-01 14:25:40.374 21817 21817 "  /lib64/libtbbmalloc_proxy.so.2(free+0x9) [0x7fef838ad179]"
00001A18 2017-03-01 14:25:40.374 21817 21817 "  /lib64/ld-linux-x86-64.so.2(+0x120b3) [0x7fef88f390b3]"
00001A19 2017-03-01 14:25:40.374 21817 21817 "  /lib64/ld-linux-x86-64.so.2(+0x1126) [0x7fef88f28126]"
00001A1A 2017-03-01 14:25:40.374 21817 21817 "  /opt/HPCCSystems/plugins/libredis.so(+0x341d) [0x7fdfbb37b41d]"
00001A1B 2017-03-01 14:25:40.374 21817 21817 "  /lib64/libc.so.6(__cxa_finalize+0x9a) [0x7fef817df1da]"
00001A1C 2017-03-01 14:25:40.375 21817 21817 "  /opt/HPCCSystems/plugins/libredis.so(+0x33b3) [0x7fdfbb37b3b3]"
00001A1D 2017-03-01 14:25:40.375 21817 21817 "Registers:"
00001A1E 2017-03-01 14:25:40.375 21817 21817 "EAX:0000000000000000  EBX:00000000025A5010  ECX:0000000000000008  EDX:00007FEF89121A10  ESI:00007FEF81826620  EDI:00000000025A5010"
00001A1F 2017-03-01 14:25:40.375 21817 21817 "CS:EIP:0033:00007FEF80C1599A"
00001A20 2017-03-01 14:25:40.375 21817 21817 "   ESP:00007FFF2A4FE210  EBP:00000000025A4000"
00001A21 2017-03-01 14:25:40.375 21817 21817 "Stack[00007FFF2A4FE210]: 0000000000000009 2A4FE76000000000 00007FFF2A4FE760 2A4FE6E000007FFF 00007FFF2A4FE6E0 0000000200007FFF 0000000000000002 831B594500000000"
00001A22 2017-03-01 14:25:40.375 21817 21817 "Stack[00007FFF2A4FE230]: 00007FEF831B5945 0000000200007FEF 0000000000000002 0000000100000000 0000000000000001 9C9D720000000000 C56360099C9D7200 00000290C5636009"
00001A23 2017-03-01 14:25:40.375 21817 21817 "Stack[00007FFF2A4FE250]: 0000000000000290 8912209000000000 00007FEF89122090 0000000800007FEF 0000000000000008 0000000400000000 0000000000000004 89121A1000000000"
00001A24 2017-03-01 14:25:40.375 21817 21817 "Stack[00007FFF2A4FE270]: 00007FEF89121A10 A103720000007FEF 00007FDFA1037200 89121A9000007FDF 00007FEF89121A90 838AD17900007FEF 00007FEF838AD179 0001000100007FEF"
00001A25 2017-03-01 14:25:40.375 21817 21817 "Stack[00007FFF2A4FE290]: 0001000100010001 88F390B300010001 00007FEF88F390B3 8912200000007FEF 00007FEF89122000 0000000000007FEF 0000000000000000 0000000800000000"
00001A26 2017-03-01 14:25:40.375 21817 21817 "Stack[00007FFF2A4FE2B0]: 0000000000000008 0000000800000000 0000000000000008 0001000100000000 0001000100010001 76EDDFF000010001 FFFF801076EDDFF0 00000000FFFF8010"
00001A27 2017-03-01 14:25:40.375 21817 21817 "Stack[00007FFF2A4FE2D0]: 0000000000000000 BB58FF9500000000 00007FDFBB58FF95 0001000100007FDF 0001000100010001 BB584FA800010001 00007FDFBB584FA8 BB584A2000007FDF"
00001A28 2017-03-01 14:25:40.375 21817 21817 "Stack[00007FFF2A4FE2F0]: 00007FDFBB584A20 7FADB91000007FDF 00007FEF7FADB910 0000000000007FEF 0000000000000000 7FADB90000000000 00007FEF7FADB900 0000043800007FEF"

```

**Comment by jakesmith** [comment]
I looks like it's probably unloading the redis plugin at this point at the end of the job.

**Comment by jakesmith** [comment]
Attila mentioned it is possibly related to: https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/516491 which is in TBB 4.1 that's default for CentOS7

**Comment by AttilaVamos** [comment]
If I build the package with -DUSE_TBBMALLOC=OFF (TBB4.1) then all redis related tests pass on Thor (with --PQ as well).  
I will try it with TBB 44.

**Comment by AttilaVamos** [comment]
It works well with TBB44, so I will upgrade smoketest machine soon and reschedule this PR.

**Comment by AttilaVamos** [comment]
@richardkchapman It is clean now. (Thanks for TBB44 malloc).

**Pull request merged**
