### PR TITLE
HPCC-13940 Correctly determine the scope to evalue graph results

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@jamienoss please review

**Comment by jamienoss** [comment]
@ghalliday & @richardkchapman this looks good to merge.

**Comment by jamienoss** [comment]
[~ghalliday] I was wondering if this might have affected Anshu whilst working on the child query changes? Do you have the line number of the assert/internal error? That given in the description on the jira ticket doesn't seem to match up with anything in the current master.

**Comment by richardkchapman** [comment]
@ghalliday Back to you

**Comment by ghalliday** [comment]
You need a more complicated query with at least 2 levels of child queries, and multiple grandchildren to trigger this.  I doubt that Anshu would have hit it.
The original report was from 4.2.4 (see the path in the jira)

@jamienoss you haven't commented on whether the code is ok.

**Comment by jamienoss** [comment]
@ghalliday ok. No I haven't, whilst the code looks good to me, without knowing the actual issue I have no idea of it's relation as an actual fix. Unfortunately the jira doesn't give a snippet of the actual code that throws the internal exception and the line count no longer matches anything in master.

**Comment by ghalliday** [comment]
I should have said, vlad17.eclxml in the private regression suite is the example.

**Comment by jamienoss** [comment]
@richardkchapman good to merge.

**Pull request merged**
