### PR TITLE
HPCC-15995 Implementation of scanning heaplets

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
jira: https://track.hpccsystems.com/browse/HPCC-15995 contains more details

**Comment by ghalliday** [comment]
@jakesmith please review the second commit (thor changes)
@mckellyln please review, especially the 1st commit

**Comment by ghalliday** [comment]
Repushed to remove the unshared allocator which didn't show any benefits.

**Comment by richardkchapman** [comment]
@mckellyln This PR seems to be stalled awaiting your review

**Comment by mckellyln** [comment]
Looks very good, but how do we set new heap flag for jobs ?

**Comment by ghalliday** [comment]
@mckellyln please mention @ghalliday in your comments so I know you've looked at it.

Currently you can set them via a hint on the activity, or via a #option to set them globally.  There is a separate JIRA for changing the platform to use the new allocator

**Comment by richardkchapman** [comment]
@ghalliday Needs rebasing for a clean merge

**Comment by ghalliday** [comment]
@richardkchapman now rebased

**Comment by mckellyln** [comment]
@ghalliday @richardkchapman ok to merge from me

**Pull request merged**
