### PR TITLE
HPCC-20369 Fix Roxie SSL connection logs assertion after timeout

### PR DESCRIPTION
**Pull request by afishbeck**
Persistent SSL connections return zero bytes read when the connection
times out.  We should not have an assertion against this case.

Signed-off-by: Anthony Fishbeck <anthony.fishbeck@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by afishbeck** [comment]
@mckellyln can you test?
@mayx please review... will this change have affects beyond my use?  Is this way of testing for graceful timeout ok?

**Comment by mayx** [comment]
@afishbeck the change by itself is fine. There was some discussion between Jake, Mark and I before and we decided on using avail_read as the way to check graceful close and it works well for the flow of ESP persistence implementation. But here using read returning 0 is the proper choice for this scenario.

However, the added check won't help with coring if there's actually a core, it only prevents an exception from throwing in certain condition (I haven't looked closely if that condition will happen, or if the graceful close would've been handled before this).

BUT, here is the interesting part. I don't see any coring in my tests, with or without your change. I used the same soapplus parameters and input as @mckellyln but don't see any core on Roxie. You also mentioned you couldn't reproduce. Maybe you can test with soapplus, and I'll test with testsocket (I have a feeling -a1 option shouldn't be necessary). To test with soapplus, you need to cherry-pick   https://github.com/hpcc-systems/HPCC-Platform/pull/11553

**Comment by mayx** [comment]
I tested with testsocket. The testsocket program won't finish with -r 3 and -persist, unless -a1 is also present. But -a1 option is cheating and won't read all content if response is large. So the testsocket program may need some changes to make it work with persistence (I'll open a Jira). So can't reproduce core with either testsocket or soapplus...

**Comment by mckellyln** [comment]
@mayx I do not think there is any core with testsocket, just a stack print and an exception.
The check for 0 and return should fix that.

**Comment by mayx** [comment]
@mckellyln @afishbeck I made the assumption the stack trace was from a core. In this case the change is good. I did a quick test and the assertion is gone.

**Comment by mayx** [comment]
@mckellyln @afishbeck I just realized I didn't enable the change, but still there's no Backtrace, so my tests doesn't count. Mark did some test I believe with soapplus and things look good. @mckellyln please confirm.

**Pull request merged**
