### PR TITLE
HPCC-20970 Update OpenSSL library names

### PR DESCRIPTION
**Pull request by xwang2713**
Previous OpenSSL (<1.1) the library names are libeay32 and ssleay. From OpenSSL 1.1 the names are libcrypto and libssl which are consistent with the ones on Linux.

Signed-off-by: Xiaoming Wang <xiaoming.wang@lexisnexi.com> 

@Michael-Gardner please review

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [ ] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.

## Testing:

http://10.240.32.243/job/WCT-20970/

### CODE REVIEW

**Comment by Michael-Gardner** [comment]
@xwang2713 This looks good.

**Comment by richardkchapman** [comment]
Can anyone tell me how we managed to build 7.0.0 clienttools without this change?

**Comment by xwang2713** [comment]
@richardkchapman Yes, this is not needed for build Clienttools on Windows.  Clienttool 7.0.0-rc1 can be built successfully with OpenSSL 1.0.2.  The reason I open this JIRA is @gaojx tried HPCC Platform with OpenSSL 1.1 on Windows but failed. Later he think it is better to use OpenSSL 1.0.2 for his work. I will close this PR and add comment in JIRA HPCC-20970. We may close the JIRA with not-fix.

**Comment by gaojx** [comment]
Yes, I can only build the HPCC on Windows with OpenSSL 1.0.2.  Some functions are removed in OpenSSL 1.2, which are used (e.g., in socketsocket), so unless someone familiar with the securesocket code to change the calls for OpenSSL, we need to stay at 1.0.2 for now.

**Comment by xwang2713** [comment]
Seems this should be on hold unless @gaojx comfortable uses OpenSSL 1.1 on Windows for his work.

**Comment by richardkchapman** [comment]
I changed the target to 7.2.0

**Comment by xwang2713** [comment]
Discussed with @gaojx. He agree to enable this in HPCC 7.2.0 and later.

**Pull request merged**
