### PR TITLE
HPCC-16051 A couple of problems in prev. commit spotted/fixed

### PR DESCRIPTION
**Pull request by jakesmith**
NB: This is mostly tidying up, removing a couple of unused methods
and unecssary member variables (involve onStart())

Signed-off-by: Jake Smith jake.smith@lexisnexis.com

### CODE REVIEW

**Comment by jakesmith** [comment]
@ghalliday - I had wanted to make these changes before PR-9027 was merged:

> Gavin: Is it worth taking the changes you have done in that PR?  If it is only used for slave->master serialization that removes lots of my concerns/confusion
>...
> Jake: There were some changes I wanted to make to this PR, but I think it will be mergeable / an improvement over and fix the issue that provoked it.
> And then I will open another JIRA to change the way child queries initialize etc.

I've also now issued that other JIRA: https://track.hpccsystems.com/browse/HPCC-16212

@ghalliday - please review

**Comment by ghalliday** [comment]
@jakesmith I think onStartCalled/ isOnStarted() can also be deleted.

**Comment by ghalliday** [comment]
otherwise it looks like good cleaning up the code.

**Comment by jakesmith** [comment]
> I think onStartCalled/ isOnStarted() can also be deleted.

Yes, I've remove and squashed change.

@ghalliday - please merge

**Pull request merged**
