### PR TITLE
HPCC-20779 Configure dafilersv file access with default keys

### PR DESCRIPTION
**Pull request by jakesmith**
The dafilesrv external file access service will only accept
signed requests, but the stock environment did not ship with a
suitable configuration.

Use the default generated keys in the stock environment for
dafilesrv cluster keys.
But also remove the default passphrase that these auto-generated
keys used to use since:
a) it is not helpful to keep poorly encoded passphrases in
widely distributed configuration files (environment.xml)
b) The dafilesrv signature configuration doesn't allow
passphrases to be configured in the environment (because of (a))

If passphrases are to be used, they should not be
stored/distributed in config files, but should be secured
elsewhere, e.g. using ssh-agent

Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

### CODE REVIEW

**Comment by jakesmith** [comment]
@richardkchapman  @Michael-Gardner - please review

**Comment by mckellyln** [comment]
@jakesmith I think the env.conf also has this info (commented out) in it - which should be updated also ?

**Comment by jakesmith** [comment]
@mckellyln - yes, now removed.
There is also another change (in CSecureHttpProtocol) to remove the mandatory requirement for there to be a configured pass phrase.

**Comment by RussWhitehead** [comment]
@jakesmith Looks reasonable, but you will need to rebase since my changes for HPCC-20776 will conflict with yours

**Comment by richardkchapman** [comment]
@RussWhitehead Can you comment

**Comment by jakesmith** [comment]
I've rebased/pushed. Bit odd that message history makes it look I pushed before comment, when in fact it was after.

**Comment by RussWhitehead** [comment]
@jakesmith Looks good

**Comment by jakesmith** [comment]
Hold off merging until Godji has checked a previous 'file not found' type error he saw.

**Comment by jakesmith** [comment]
Ok, problem was found, wrong group in env xml config (for hthor).
Have pushed the fix.

@jpmcmu has tested/confirmed fix

@richardkchapman - please merge.

**Pull request merged**
