### PR TITLE
HPCC-16547 Allow an activity to be associated with an error

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

### CODE REVIEW

**Comment by ghalliday** [comment]
@GordonSmith @jakesmith FYI
@afishbeck please can you review, especially the esp changes

**Review by afishbeck — APPROVED** [review]
@ghalliday looks good

**Comment by ghalliday** [comment]
@richardkchapman please merge - but version number of the interface assumed this would be merged after https://github.com/hpcc-systems/HPCC-Platform/pull/9290

**Comment by ghalliday** [comment]
@richardkchapman now rebased

**Pull request merged**
