### PR TITLE
HPCC-25894 Report 413 Request Entity Too Large error in ESP

### PR DESCRIPTION
**Pull request by wangkx**
Current ESP shows the 400 error when the length of a request is
larger than the predefined limit.

Signed-off-by: wangkx <kevin.wang@lexisnexis.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by AttilaVamos** [comment]
@wangkx I am sure the regression is not related to this PR. I will reschedule it to get a clean result.

**Comment by afishbeck** [comment]
@wangkx the change looks fine... but the JIRA says "ESP is currently cutting connection".. did you verify that the exception is caught by a "catch(IEspHttpException* e)" and an HTTP 413 is actually being sent out?  I know in the past there were some errors that were too soon in processing after the socket connection that they weren't returned as HTTP error messages.

**Comment by wangkx** [comment]
Yes, it is caught by the IEspHttpException:
    try
    {
        if (m_request->receive(NULL)==-1) // MORE - pass in IMultiException if we want to see exceptions (which are not fatal)
            return -1;
    }
    catch(IEspHttpException* e)
    {
        m_response->sendException(e);
        ctx->addTraceSummaryValue(LogMin, "msg", e->errorMessage(errMessage).str(), TXSUMMARY_GRP_ENTERPRISE);
        e->Release();
        return 0;
    }
 
And:
 "Sending out HTTP headers:
HTTP/1.1 413 Request Entity Too Large
Content-Type: text/plain
Content-Length: 53
Connection: close"
 "Sending out HTTP content:
CEspHttpException: (The request length was too long.)"

**Review by afishbeck — APPROVED** [review]

**Comment by wangkx** [comment]
@richardkchapman this PR is ready to be merged.

**Comment by afishbeck** [comment]
Added Rodrigo in case he wants to verify.

**Review by rpastrana — APPROVED** [review]
@wangkx looks reasonable.

**Comment by wangkx** [comment]
@richardkchapman please merge this PR.

**Pull request merged**
