### PR TITLE
HPCC-16611 Ignore SIGPIPE before ldap_unbind

### PR DESCRIPTION
**Pull request by mckellyln**
@RussWhitehead please review. / test.

Signed-off-by: Mark Kelly <mark.kelly@lexisnexis.com>

### CODE REVIEW

**Comment by RussWhitehead** [comment]
@mckellyln I feel this is too intrusive.  LDAP_UNBIND is called from many short-lived places in the LDAP code, but there is only one place that it's called on a stale connection.  It would be better to only call it in the CLdapConnection::validate() method

**Comment by mckellyln** [comment]
ok, will change to just in front of validate()

**Comment by mckellyln** [comment]
@RussWhitehead here is the change.  Are we sure this is the only place an unbund will cause the SIGPIPE ?

**Comment by RussWhitehead** [comment]
@mckellyln After reviewing all of the other unbinds, the only one that possibly could is CLdapConnection::~CLdapConnection. All the others are contained in local "ldapinit/ldapbind/ldapDoSomething/ldapUnbind" fragments

**Comment by mckellyln** [comment]
@RussWhitehead should we also add it to the dtor then ?

**Comment by RussWhitehead** [comment]
@mckellyln Looks good

**Comment by mckellyln** [comment]
@RussWhitehead see new comment in JIRA.  Perhaps we should change where we reset handler to ignore SIGPIPE to after connect()/LdapBind() ?

**Comment by RussWhitehead** [comment]
@mckellyln Looks good

**Comment by mckellyln** [comment]
@richardkchapman updated

**Pull request merged**
