### PR TITLE
Adding GSOC child query tests

### PR DESCRIPTION
**Pull request by aranjan1002**
Referring to Issue:

https://track.hpccsystems.com/browse/HPCC-13427

### CODE REVIEW

**Comment by ghalliday** [comment]
The title of the commit should contain HPCC-XXXX as the first item.  (See all the other pull requests for examples.)

**Comment by ghalliday** [comment]
If tests are added to the run time regression suite, then you also need to check in key files (in testing/regress/ecl/key) - otherwise they will be marked as failing.

The keys from the previous run are found in ~/HPCCSystems-regression/results.

If those are correct then they can be copied across, and checked in.

**Comment by ghalliday** [comment]
Pull requests should really be done from a different branch than master.  When you start making changes you should create a new branch.  Commit changes to that branch, and push it when ready.  That has several advantages
- You can work on another independent change while this change is being reviewed
- you can switch back and forward between different work items
- it is very confusing if your master branch is not a subset of the main master branch.

It is worth reading the git book to discover how branches are used - they are a key element in git.

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK

| setup | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| setup | Pass | Pass | Pass |
| setup_fetch | Pass | Pass | Pass |
| setupdict | Pass | Pass | Pass |
| setupsearchindex | Pass | Pass | Pass |
| setupsq | Pass | Pass | Pass |
| setupwordindex | Pass | Pass | Pass |
| setupxml | Pass | Pass | Pass |
 

| test | hthor | thor | roxie |
| ----- | ----- | ----- | ---- |
| gsoc1 | Fail | Fail | Fail |
| gsoc2 | Fail | Fail | Fail |
| gsoc3 | Fail | Fail | Fail |
| gsoc4 | Fail | Fail | Fail |
| gsoc5 | Fail | Fail | Fail |
| gsoc6 | Fail | Fail | Fail |
 
HPCC Stop: OK

**Comment by aranjan1002** [comment]
Quick Question, what should be the number of title? Should it be HPCC-13427 which is the number in URL of the jira issue.

**Comment by AttilaVamos** [comment]
It would be good for this form: 

**HPCC-13427 Release some example queries**

**Description of changes...**

**Signed-off-by: <your sign added by the git commit  with -s parameter>**

**Comment by AttilaVamos** [comment]
Automated Smoketest Build: success
HPCC Start: OK
HPCC Stop: OK

**Pull request closed without merging**
