### PR TITLE
HPCC-23652 Add additional query filters

### PR DESCRIPTION
**Pull request by miguelvazq**
Adding the following suspended status options to QuerySetQuery

- All Queries
- Not Suspended
- Suspended
- Suspended By User
- Suspended By First Node
- Suspended By Any Node

Signed-off by: Miguel Vazquez <miguel.vazquez@lexisnexisrisk.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [ ] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [x] I have tested my changes in multiple modern browsers
  - [x] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by miguelvazq** [comment]
@kunalaswani Please review

**Review by kunalaswani — APPROVED** [review]

**Comment by miguelvazq** [comment]
@richardkchapman ready for merge.

**Comment by richardkchapman** [comment]
Is this supposed to target 7.10.x ?

**Comment by miguelvazq** [comment]
> Is this supposed to target 7.10.x ?

It's a new feature so, I was thinking 7.10.2. I can change base to that.

**Comment by richardkchapman** [comment]
It looked like it was adding the UI for something that is already implemented server-side?

If so, and if the server support is already in 7.10.x, then targetting 7.10.x seems reasonable. But if the server side is not there until master, then master is fine.

**Comment by miguelvazq** [comment]
> It looked like it was adding the UI for something that is already implemented server-side?
> 
> If so, and if the server support is already in 7.10.x, then targetting 7.10.x seems reasonable. But if the server side is not there until master, then master is fine.

Server support was added 7.10.x and it is a U/I addition to support that addition. So, I will change to 7.10.x

**Comment by miguelvazq** [comment]
@richardkchapman rebased.

**Comment by richardkchapman** [comment]
@kunalaswani Can we get new translations?

**Comment by kunalaswani** [comment]
@richardkchapman I will generate and send a translations email.

**Pull request merged**
