### PR TITLE
HPCC-12314 Add OnWarning section to the workunit to configure warnings

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman please review.  This will need to be merged by hand into master because of the Cassandra changes.

**Comment by richardkchapman** [comment]
Code looks ok I think, but I have a question about how it would be used - you don't really want to be going to the workunit to check a warning severity all the time when someone has set that warning to ignore because they know their code would generate it a billion times...

**Comment by ghalliday** [comment]
No, anything that should be tested a lot should be set to cache it.  This was primarily added to disable the FEW warning on index builds which are unlikely to occur often.

Should the addExceptionToWorkUnit() function also use these mappings to automatically map?  Quite a few places add the exception directly instead though.

**Comment by richardkchapman** [comment]
I suspect since you want people to cache it it's best NOT to have addExceptionToWorkunit process it (that's generally called too late anyway - after  you have aborted the operation).

**Comment by ghalliday** [comment]
@richardkchapman added code to allow the default severity to be supplied.

**Pull request merged**
