### PR TITLE
HPCC-17028 Fix invalid bitfield range comparison

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [x] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [x] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [x] Existing deployed queries will not be broken
  - [x] This change fixes the problem, not just the symptom
  - [x] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately

## Testing:
Modified test xmlout2 to trigger an invalid warning on a bitfield comparison.
Ran regression suite on xmlout2 to check new output was correct.
Run compiler regression suites to check code change to xmlout2 was correct, and no other queries affected.

### CODE REVIEW

**Comment by ghalliday** [comment]
@shamser please review.

**Review by shamser — COMMENTED** [review]
@ghalliday Should a test be added for bitfield size 64? Everything else looks good.

**Comment by ghalliday** [comment]
@shamser  You're right, but I don't think bitfield size 64 should be legal.  It should either fail, or be treated as an unsigned8.  Can you open a separate jira?

**Comment by shamser** [comment]
@richardkchapman Code reviewed ok.

**Pull request merged**
