### PR TITLE
HPCC-15805 - Update to latest (2.4.1) Cassandra driver

### PR DESCRIPTION
**Pull request by richardkchapman**
Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@sukhong Please test this as a cleaner fix for your clang build issues.
@ghalliday Please review/merge. Updates the cpp-driver submodule to use the latest stable upstream version (2.4.1)

**Comment by richardkchapman** [comment]
@AttilaVamos That smoketest failure may be related to a submodule update?

**Comment by sukhong** [comment]
@richardkchapman I've tested it locally (merged on the lastest master), and clang builds it fine without any failure.

**Comment by AttilaVamos** [comment]
@sukhong What kind of OS/environment did you use?

**Comment by sukhong** [comment]
@AttilaVamos I use Ubuntu 15.10, with clang 3.8.0.

**Comment by AttilaVamos** [comment]
@richardkchapman This smoketest failure based on the package generation problem on master branch under CentOS

**Comment by richardkchapman** [comment]
@ghalliday Please merge

**Pull request merged**
