### PR TITLE
HPCC-32273 Ensure all secret categories are present in the values schema

### PR DESCRIPTION
**Pull request by ghalliday**
## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
I reordered the lists to make them consistent, and added the missing entries in the schema.
The "system" category needs some thought and may have other implications.  I think it cannot currently come from a vault (because it may be used to configure a vault), but that means that jtrace cannot use the "system" category for its configuration.  @afishbeckln is that understanding correct?

**Review by rpastrana — APPROVED** [review]
@ghalliday approved. Changes seem to achieve the stated goal, and in-line comment provides context for missing vault category.

**Review by jakesmith — APPROVED** [review]
@ghalliday - looks good.

**Comment by afishbeckln** [comment]
> I reordered the lists to make them consistent, and added the missing entries in the schema. The "system" category needs some thought and may have other implications. I think it cannot currently come from a vault (because it may be used to configure a vault), but that means that jtrace cannot use the "system" category for its configuration. @afishbeckln is that understanding correct?

@ghalliday I haven't taken a fresh look at the code.  But if we don't already I would think we should be able to support a mixed system category.  The vault secret obviously has to come from kubernetes (disk mount).  I would think other secrets in the same category should be able to be in vault.  Asking for a secret that is in the vault would mean the vault manager was inited with it's secret from disk and then the rest should work.  Maybe I'm overlooking some issue, or there is currently a bug?

**Pull request merged**
