### PR TITLE
HPCC-28348 Optimize IF(cond) when cond already true/false

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [x] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
Quite a few significant improvements.  E.g. bug86867 reduced by 80%.  A couple of very minor increases I still need to investgate, but would merge as is if I don't discover anything.

**Comment by richardkchapman** [comment]
Surprised that this has ot already been removed by constant folder...

**Comment by ghalliday** [comment]
It isn't removed by the constant folder because it is often non-obvious.  For instance

```
x := IF(cond, a, b)
y := PROJECT(x, transform());
z := IF(cond, y, z);
```

In the context of evaluating z, this can be optimized to

```
x := a;
y := PROJECT(x, transform());
z := IF(cond, y, z);
```

because x is only evaluated on the true branch.  However if you apply that optimization generally, and y is used from somewhere else you will end up evaluating both  PROJECT(a, transform()) and PROJECT(IF(cond, a,b), transform) - increasing the amount of work.
One of the optimizers tries to take that into account, but it is very hard to accurate count for child queries, so it tends to be concervative.

**Comment by ghalliday** [comment]
Wrong jira used in commit message - should be 28352.  I will fix.

It isn't removed by the constant folder because it is often non-obvious.  For instance


```
x := IF(cond, a, b)
y := PROJECT(x, transform());
z := IF(cond, y, z);
```

In the context of evaluating z, this can be optimized to

```
x := a;
y := PROJECT(x, transform());
z := IF(cond, y, z);
```

because x is only evaluated on the true branch.  However if you apply that optimization generally, and y is used from somewhere else you will end up evaluating both  PROJECT(a, transform()) and PROJECT(IF(cond, a,b), transform) - increasing the amount of work.
One of the optimizers tries to take that into account, but it is very hard to accurate count for child queries, so it tends to be conservative.

**Review by richardkchapman — APPROVED** [review]

**Comment by ghalliday** [comment]
@richardkchapman rerun the regression suite.  no queries got larger.   I have another similar change which I will push as an extra commit.

**Review by richardkchapman — APPROVED** [review]

**Pull request merged**
