### PR TITLE
HPCC-31573 Add Github Action for ESP Regression Suite

### PR DESCRIPTION
**Pull request by jpmcmu**
- Added HPCC4j ESP regression suite to K8s regression suite

Signed-off-by: James McMullan James.McMullan@lexisnexis.com

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [X] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [X] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [X] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [X] I have read the CONTRIBUTORS document.
- [X] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [X] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [X] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jpmcmu** [comment]
@rpastrana please review

**Comment by jpmcmu** [comment]
# Example Test Output:

# ESP Regression Suite Test Failures:
The following tests failed; checkout a copy of the HPCC4j project with the following command and run the individual test commands below to debug the failures.
```
git clone https://github.com/BrokenTests.git hpcc4j
cd hpcc4j && git checkout BrokenTests
```
## org.hpccsystems.ws.client.WsDFUClientTest.testGetFiles Failed
**Error:** ```Example error```
**Test Command:** ```mvn -B -Dhpccconn=https://eclwatch.default:8010 -Dtest=org.hpccsystems.ws.client.WsDFUClientTest#testGetFiles test```
## org.hpccsystems.ws.client.WsDFUClientTest.testGetFileContent Failed
**Error:** ```Example error```
**Test Command:** ```mvn -B -Dhpccconn=https://eclwatch.default:8010 -Dtest=org.hpccsystems.ws.client.WsDFUClientTest#testGetFileContent test```
## org.hpccsystems.ws.client.WUQueryTest.testGetWorkunitByAppName Failed
**Error:** ```Example error```
**Test Command:** ```mvn -B -Dhpccconn=https://eclwatch.default:8010 -Dtest=org.hpccsystems.ws.client.WUQueryTest#testGetWorkunitByAppName test```
## org.hpccsystems.ws.client.WSWorkunitsTest.testMultipleWsWUInits Failed
**Error:** ```Example error```
**Test Command:** ```mvn -B -Dhpccconn=https://eclwatch.default:8010 -Dtest=org.hpccsystems.ws.client.WSWorkunitsTest#testMultipleWsWUInits test```

**Review by rpastrana — APPROVED** [review]
@jpmcmu looks good from my end, let's have @GordonSmith and @ghalliday take a peek

**Review by GordonSmith — APPROVED** [review]
Yaml looks fine - didn't review the python...

**Review by ghalliday — APPROVED** [review]
Looks reasaonable

**Pull request merged**
