### PR TITLE
HPCC-31052 ECL Watch metrics timeline darkmode issue

### PR DESCRIPTION
**Pull request by GordonSmith**
Background is stuck on white.
Tweaked grid highlighting and border for darkmode.

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [x] I have raised JIRA issues to address them separately
- [x] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [x] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by jeclrsg** [comment]
@GordonSmith The only one issue I see is that those button styles in HolyGrail.tsx would need a rule or two added perhaps in DojoGrid.css? The Hotspots (or any disabled button I guess) has the light theme's hover color.

image

**Comment by jeclrsg** [comment]
I think there might've just been an issue when branches were getting split up into separate / smaller PRs, eg the issue in my previous comment & screenshot doesn't exist when I checked out (and installed dependencies for) the PR for HPCC-31052.

**Comment by jeclrsg** [comment]
@GordonSmith I rebased this branch onto the latest 9.2.x, and that light blue hover was still there for the dark theme. I think it's coming from this CSS rule (https://github.com/hpcc-systems/HPCC-Platform/blame/master/esp/src/eclwatch/css/hpcc.css#L30). I deleted that entire `button:hover { ... }` rule and nothing that I could see changed in either the v9 or v5 UIs.

**Comment by GordonSmith** [comment]
I also see this - but on latest 9.2.x, not specific to this PR - can you open a new Jira ticket and we can fix in separate PR.

Note:  Looking at the history this style was added as part of an old Graph view, so should be safe to remove.

**Review by jeclrsg — APPROVED** [review]

**Pull request merged**
