### PR TITLE
HPCC-16117 UDP messaging threads should run at elevated priority

### PR DESCRIPTION
**Pull request by richardkchapman**
Signed-off-by: Richard Chapman rchapman@hpccsystems.com

### CODE REVIEW

**Comment by richardkchapman** [comment]
@ghalliday Please review

**Comment by richardkchapman** [comment]
@mckellyln Perhaps you should review this one...

**Comment by mckellyln** [comment]
Changes look good.

**Comment by richardkchapman** [comment]
@ghalliday Please review/merge

**Pull request merged**
