### PR TITLE
HPCC-31306 Add support for non-string span attributes

### PR DESCRIPTION
**Pull request by ghalliday**
## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [ ] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [x] Test my draft Pull Request.

### CODE REVIEW

**Comment by ghalliday** [comment]
@rpastrana compare ignoring changes in whitespace.
The single attribute added is a test case.  Is stats.time_elapsed a good naming convention?  I think it matches the standard. There will be a further PR which will add more attributes.

**Review by rpastrana — APPROVED** [review]
@ghalliday looks good to go

**Comment by rpastrana** [comment]
> @rpastrana compare ignoring changes in whitespace. The single attribute added is a test case. Is stats.time_elapsed a good naming convention? I think it matches the standard. There will be a further PR which will add more attributes.

The name seems perfectly fine, and I like the thought of qualifying these values as "stats". 

If we want to scrutinize and set the long term convention, I wonder if we could be more explicit about the meaning of the stat(s). For instance does this stat refer to a span's elapsed time, or the total query elapsed time?

Some options to consider:

> stats.total_time
> query.stats.time_elapsed
> query.total.time_elapsed
> stats.total.time_elapsed
> stats.query_elapsed_time
> stats.elapased_time_ms



The only other attributes I see in our code base are:
"hpcc.wuid" and  "hpcc.graph"

I suppose those two were "hpcc" prefixed to avoid potential name clashes

**Comment by ghalliday** [comment]
> > @rpastrana compare ignoring changes in whitespace. The single attribute added is a test case. Is stats.time_elapsed a good naming convention? I think it matches the standard. There will be a further PR which will add more attributes.
> 
> The name seems perfectly fine, and I like the thought of qualifying these values as "stats".
> 
> If we want to scrutinize and set the long term convention, I wonder if we could be more explicit about the meaning of the stat(s). For instance does this stat refer to a span's elapsed time, or the total query elapsed time?
> 
> Some options to consider:
> 
> > stats.total_time
> > query.stats.time_elapsed
> > query.total.time_elapsed
> > stats.total.time_elapsed
> > stats.query_elapsed_time
> > stats.elapased_time_ms
> 
> The only other attributes I see in our code base are: "hpcc.wuid" and "hpcc.graph"
> 
> I suppose those two were "hpcc" prefixed to avoid potential name clashes

We use time_total_execute to represent the time actually spent running, which may be different from the elapsed time (smaller if there are gaps waiting for something else, longer if multiple things executing at the same time).
query.xxx  I think it is more consistent to always have stats. as the prefix for all stats.  Possibly stats.query.time_elapsed, or Possibly stats.time_query_elapsed, but query is a bit redundant.

I named it to be consistent with the naming convention used for all out stats, so there is a clear 1:1 mapping from the values displayed in eclwatch and the values reported in the trace.
yes "hpcc." was used as a prefix to prevent them clashing.  I think stats. is a reasonable prefix.

Actually I wonder if "stat" would be better - but we can discuss that in the follow on PR.

**Comment by ghalliday** [comment]
BTW in this case the span elapsed time is identical to the query elapsed time.

**Pull request merged**
