### PR TITLE
HPCC-30743 ElasticSearch LogAccess PodName suport

### PR DESCRIPTION
**Pull request by rpastrana**
- Adds pod.name log mapping to sample values yaml
- Adds pod.name as default field in logaccess plugin
- Adds pod name based filter support

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [ ] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Cloud-compatibility
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browsers
  - [ ] The component(s) render as expected

## Smoketest:
- [ ] Send notifications about my Pull Request position in Smoketest queue.
- [ ] Test my draft Pull Request.

### CODE REVIEW

**Comment by rpastrana** [comment]
@jeclrsg I've added kubernetes.pod.name support to the Elastic Search logaccess plugin. This is what you can expect to get back when calling getlogs:

```json
<GetLogsResponse>
<LogLines>
{
	"lines": [
		{
			"fields": [
				{
					"timestamp": "2023-11-06T20:52:19.265Z",
					"hpcc.log.threadid": "232",
					"hpcc.log.timestamp": "2023-11-06 20:52:19.265",
					"kubernetes.container.name": "myeclccserver",
					"hpcc.log.jobid": "W20231106-205213",
					"hpcc.log.audience": "USR",
					"hpcc.log.message": "Agent request 'W20231106-205213' enqueued on 'hthor.agent'",
					"kubernetes.pod.name": "myeclccserver-f86b798c6-nlw5n",
					"hpcc.log.sequence": "0000001D",
					"hpcc.log.class": "PRO",
					"hpcc.log.procid": "8"
				}
			]
		},
		{
			"fields": [
				{
					"timestamp": "2023-11-06T20:52:23.232Z",
					"hpcc.log.threadid": "9",
					"hpcc.log.timestamp": "2023-11-06 20:52:23.232",
					"kubernetes.container.name": "hthor-job-w20231106-205213",
					"hpcc.log.jobid": "W20231106-205213",
					"hpcc.log.audience": "OPR",
					"hpcc.log.message": "hthor build community_9.4.9-closedown0Debug[heads/HPCC-30401-JTrace-optional-traceid-support-0-gc85263-dirty]",
					"kubernetes.pod.name": "hthor-job-w20231106-205213-jdcss",
					"hpcc.log.sequence": "00000003",
					"hpcc.log.class": "INF",
					"hpcc.log.procid": "9"
				}
			]
		}
	]
}
</LogLines>
<LogLineCount>2</LogLineCount>
<TotalLogLinesAvailable>91</TotalLogLinesAvailable>
</GetLogsResponse>
```

**Comment by rpastrana** [comment]
Also changed the "instance" column to map to container.id:
image

**Review by jeclrsg — APPROVED** [review]

**Review by jakesmith — APPROVED** [review]
@rpastrana - looks good.

**Comment by rpastrana** [comment]
@ghalliday ready for merge

**Pull request merged**
