### PR TITLE
HPCC-16322 A test of parallel child queries that request results

### PR DESCRIPTION
**Pull request by jakesmith**
Signed-off-by: Jake Smith <jake.smith@lexisnexis.com>

### CODE REVIEW

**Comment by jakesmith** [comment]
@ghalliday - adding test you created from JIRA. Please review.

**Comment by ghalliday** [comment]
Looks fine - should it go in 6.2?

**Comment by richardkchapman** [comment]
I'm happy to merge to 6.2 if you retarget it @jakesmith

**Comment by jakesmith** [comment]
Closing to rebase onto 6.2.0

**Pull request closed without merging**
