### PR TITLE
HPCC-17430 Avoid rsync if localThor=true

### PR DESCRIPTION
**Pull request by jakesmith**
Signed-off-by: Jake Smith <jake.smith@lexisnexisrisk.com>

## Type of change:
- [x] This change is a bug fix (non-breaking change which fixes an issue).
- [ ] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [ ] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [ ] The commit message title makes sense in a changelog, by itself.
  - [ ] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [x] I have read the CONTRIBUTORS document.
- [ ] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [ ] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.
- [x] I have given due consideration to all of the following potential concerns:
  - [ ] Scalability
  - [ ] Performance
  - [ ] Security
  - [ ] Thread-safety
  - [ ] Premature optimization
  - [ ] Existing deployed queries will not be broken
  - [ ] This change fixes the problem, not just the symptom
  - [ ] The target branch of this pull request is appropriate for such a change.
- [x] There are no similar instances of the same problem that should be addressed
  - [ ] I have addressed them here
  - [ ] I have raised JIRA issues to address them separately
- [ ] This is a user interface / front-end modification
  - [ ] I have tested my changes in multiple modern browers
  - [ ] The component(s) render as expected

## Testing:

Tested locally. (with localThor set to true and to false)

### CODE REVIEW

**Comment by richardkchapman** [comment]
Missing checklist

**Comment by jakesmith** [comment]
>Missing checklist

I always create the PR, then complete the checklist.
And consider it incomplete until I ask someone for review.

**Comment by jakesmith** [comment]
@ghalliday - please review/check in your WSL env.

**Comment by richardkchapman** [comment]
I think there's a race condition in your algorithm for creating pull requests... I create mine in a single atomic operation.

**Comment by jakesmith** [comment]
:) Well - if it gets reviewed (or commented on) in the few seconds before I've asked for it to be .. yes.

If there's a way to use the tick boxes (and not hand-edit the block of text) - the former being a lot more friendly and less error prone, then I'll do it that way.

I also thought it had been suggested to take this approach, precisely so tick boxes can be used.

**Comment by richardkchapman** [comment]
I don't really mind how you do it, so long as you don't complain about me being too quick ... I don't find the hand-editing error-prone

**Comment by ghalliday** [comment]
It fixes my problems with bash on windows.
@jakesmith did you retest with localThor set to false?

**Comment by jakesmith** [comment]
@ghalliday - yes test with localThor=false.

**Pull request merged**
