### PR TITLE
HPCC-14570 Allow get_cycles_now() to be inlined as getTSC()

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman please review

**Comment by richardkchapman** [comment]
@ghalliday As discussed, need to (a) make it easy to disable in CMake file and (b) check that this call is never used for anything but gathering stats, i.e. that the only downside of the new code run on old hardware is that stats will be inaccurate.

**Comment by ghalliday** [comment]
@richardkchapman see changes, and comment in the jira.

**Comment by richardkchapman** [comment]
I'm still nervous. What about the idea of a get_fast_cycles_now() that we call from the places that are (a) speed critical and (b) not accuracy-critical ?

Alternatively, what about defaulting the setting differently on EE/LN vs CE builds?

**Comment by ghalliday** [comment]
The problem with (a) is that the same bases classes are used in critical and non-critical places.

We could default the option off, and then default it on for LN builds.

**Comment by ghalliday** [comment]
What in particular makes you nervous?  I think 64bit was introduced at a very similar time.  We could default it on only for 64bit.
@mckellyln do you have an opinion?

**Comment by richardkchapman** [comment]
What happens on VMs ?

**Comment by mckellyln** [comment]
I do not think it is as accurate on VMs.

**Comment by richardkchapman** [comment]
@ghalliday Ok in the interests of moving this forward let's default it on for 64-bit and off for 32-bit

**Comment by ghalliday** [comment]
@richardkchapman

**Comment by mckellyln** [comment]
I get
jdebug.cpp:303:13: error: ‘use_gettimeofday’ defined but not used [-Werror=unused-variable]
error when trying to build now, unless I add __attribute__((unused)) to use_gettimeofday declaration.

**Pull request merged**
