### PR TITLE
HPCC-14712 Build failure from array bounds jlib warning

### PR DESCRIPTION
**Pull request by mckellyln**
Signed-off-by: Mark Kelly mark.kelly@lexisnexis.com

### CODE REVIEW

**Comment by mckellyln** [comment]
@xwang2713 please review and test

**Comment by richardkchapman** [comment]
I thought it had been determined that his array bounds error happens because of a compiler bug in loop unrolling that is fixed in gcc 5.0.0

Do you have evidence to the contrary. And if so do we have an alternative explanation for the array bounds error?

**Comment by xwang2713** [comment]
Ubuntu 15.10  has g++ version 5.2.1 and shows error: 
jlzw.cpp:209:40: error: array subscript is above array bounds [-Werror=array-bounds]
    ShiftInfo & cur = ShiftArray[copyBits][shift];             \
                                        ^
 /var/lib/jenkins/workspace/CE-Candidate-clienttools-6.0.0-test/CE/ubuntu-15.10-amd64/HPCC-Platform/system/jlib/jlzw.cpp:504:17: note: in expansion of macro ‘GETCODE’                GETCODE(oldcode);

**Comment by mckellyln** [comment]
It seems jencrypt compile error happens with g++ < 5.0 but jlzw compile error happens with g++ >= 4.9.?

**Comment by richardkchapman** [comment]
Then perhaps we need to look more closely at the jlzw error to make sure it really is a false positive from a compiler bug...

**Comment by mckellyln** [comment]
Hard to say.  The types used allow for array bounds to be exceeded, but it only happens at opt level -O2 and above and not if the macro is changed to a function.

**Comment by mckellyln** [comment]
-ftree-vrp is the specific optimization (in -O2 and above) that finds the error.

**Comment by richardkchapman** [comment]
Well I stared at the code some more and as far as I can see the values of both copyBits and shift can be determined by static anaylsis on line 504, and both are in range. So it must be a compiler bug.

**Pull request merged**
