### PR TITLE
HPCC-13828 Generate key comparison functions for sorts

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday gavin.halliday@lexisnexis.com

### CODE REVIEW

**Comment by ghalliday** [comment]
@jakesmith please test/review.  Does this give you what you need?

**Comment by ghalliday** [comment]
Having run the regression suite this fails on some examples, so I need to fix it.  It may allow you to test your code though.

**Comment by ghalliday** [comment]
@jakesmith I think this is now fixed (including a few pre-existing bugs for merge)

**Comment by jakesmith** [comment]
I'm going to need some other ICompare's.
In particular a compare for left key to right row, for co-sorting, e.g. in global join/denormalize case.

There is also ICompare's for the sliding join cases that Id need where ISortKeySerializer's are generated
@ghalliday

**Comment by jakesmith** [comment]
Also - I'm currently serializing the keys, by converting rows to keys using ISortKeySerializer::recordToKey, then serializing them using the ISortKeySerializer IOutputMeta serializer, which works, but would it makes sense for you to specifically generate a IOutputRowSerializer that serialized from row to key?

**Comment by ghalliday** [comment]
Yes it would make sense - it is linked to https://track.hpccsystems.com/browse/HPCC-12955 and https://track.hpccsystems.com/browse/HPCC-11676.

**Comment by ghalliday** [comment]
(But well beyond the scope of this jira)

**Comment by ghalliday** [comment]
Closing until ready

**Pull request closed without merging**
