### PR TITLE
HPCC-17408 Add Clienttools bin to Windows PATH variable

### PR DESCRIPTION
**Pull request by xwang2713**
Set CPACK_NSIS_MODIFY_PATH to "ON" to add <INSTALL DIR>/bin to PATH
Add ECLCmd.bat to start menu

Signed-off-by: Xiaoming Wang <xiaoming.wang@lexisnexi.com> 
@Michael-Gardner please review

@JamesDeFabia not sure if any clienttools installation documentation need update or not.
I briefly discussed with @g-pan 

## Type of change:
- [ ] This change is a bug fix (non-breaking change which fixes an issue).
- [x] This change is a new feature (non-breaking change which adds functionality).
- [ ] This change improves the code (refactor or other change that does not change the functionality)
- [ ] This change fixes warnings (the fix does not alter the functionality or the generated code)
- [ ] This change is a breaking change (fix or feature that will cause existing behavior to change).
- [ ] This change alters the query API (existing queries will have to be recompiled)

## Checklist:
- [x] My code follows the code style of this project.
  - [x] My code does not create any new warnings from compiler, build system, or lint.
- [x] The commit message is properly formatted and free of typos.
  - [x] The commit message title makes sense in a changelog, by itself.
  - [x] The commit is signed.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly, or...
  - [ ] I have created a JIRA ticket to update the documentation.
  - [ ] Any new interfaces or exported functions are appropriately commented.
- [ ] I have read the CONTRIBUTORS document.
- [x] The change has been fully tested:
  - [ ] I have added tests to cover my changes.
  - [x] All new and existing tests passed.
  - [ ] I have checked that this change does not introduce memory leaks.
  - [ ] I have used Valgrind or similar tools to check for potential issues.

## Testing:

http://10.240.32.243/view/custom/job/CE-CT-W32-PATH/

Godji tested normal case and tested negative case (PATH too long).

### CODE REVIEW

**Comment by xwang2713** [comment]
Change "ECL CMD" to "ECL Command Prompt" in start menu.

**Comment by Michael-Gardner** [comment]
@xwang2713 Looks good.

**Comment by richardkchapman** [comment]
Please squash

**Comment by xwang2713** [comment]
Squash done.

**Pull request merged**
